force-app/main/default/objects/Location/fields/Common_Name__c.field-meta.xml
<CustomField>
    <fullName>Common_Name__c</fullName>
    <description>This field contains a summary of the details of this facility Location. The structure of this field is as such: Facility Id, Facility Location, Facility Name. This field is being used by Provider Connect.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Common Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VCR/VCR_LocationRepo.cls
/**
 * @description Location Repository class implementing the v pattern
 * Created by riadhmankai on 5/23/24.
 */

public inherited sharing class VCR_LocationRepo extends VTC_BaseRepo {
    /**
     * @description Default constructor
     */
    public VCR_LocationRepo() {
        super(Schema.Location.SObjectType);
    }

    /**
     * @description Fetch the locations that are located inside of the locationExternalIds for display later on
     * @param locationExternalIds External Facility (Location) IDs
     * @return Locations matching the external IDs passed in parameter
     */
    public List<Schema.Location> fetchLocationsByExternalId(Set<String> locationExternalIds) {
        return (List<Schema.Location>) fetch(
            'SELECT Id, Name, Common_Name__c, VAF_Facility_ID__c ' +
                'FROM Location ' +
                'WHERE VAF_Facility_ID__c IN :locationExternalIds',
            new Map<String, Object>{ 'locationExternalIds' => locationExternalIds }
        );
    }
}