sfdx-source/main/default/objects/VCC_Endpoint_Status_Code__mdt/VCC_Endpoint_Status_Code__mdt.object-meta.xml
<CustomObject>
    <description>Represents a list of potential Response Status codes and their related descriptions.</description>
    <label>Endpoint Status Code</label>
    <pluralLabel>Endpoint Status Codes</pluralLabel>
</CustomObject>

force-app/main/default/objects/VCC_Endpoint_Status_Code__mdt/fields/VCC_App_Name__c.field-meta.xml
<CustomField>
    <fullName>VCC_App_Name__c</fullName>
    <label>App Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Endpoint_Status_Code__mdt/fields/VCC_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>VCC_Endpoint__c</fullName>
    <label>Endpoint</label>
    <referenceTo>vccEndpoint__mdt</referenceTo>
    <relationshipLabel>Endpoint Status Codes</relationshipLabel>
    <relationshipName>VCC_Endpoint_Status_Codes</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Endpoint_Status_Code__mdt/fields/VCC_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>VCC_Status_Code__c</fullName>
    <label>Status Code</label>
    <referenceTo>VCC_Status_Code__mdt</referenceTo>
    <relationshipLabel>Endpoint Status Codes</relationshipLabel>
    <relationshipName>VCC_Endpoint_Status_Codes</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/VCC_Status_Code__mdt/VCC_Status_Code__mdt.object-meta.xml
<CustomObject>
    <label>Status Code</label>
    <pluralLabel>Status Codes</pluralLabel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Status_Code__mdt/fields/VCC_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>VCC_Status_Code__c</fullName>
    <label>Status Code</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/main/default/classes/VCC/VCC_EndpointStatusCodeSelectorTest.cls
@IsTest
public with sharing class VCC_EndpointStatusCodeSelectorTest {
    @IsTest
    public static void instantiationTest() {
        Test.startTest();
        VCC_EndpointStatusCodeSelector escs = new VCC_EndpointStatusCodeSelector();
        Test.stopTest();

        System.assert(escs != null, 'Did not instantiate as expected.');
    }

    @IsTest
    public static void addSObjectFieldsTest() {
        VCC_EndpointStatusCodeSelector escs = new VCC_EndpointStatusCodeSelector();

        System.assert(!escs.getSObjectFieldList().contains(CodeSet.IsActive), 'Selector already contains the field to test.');

        Test.startTest();
        escs.addSObjectFields(new List<SObjectField>{ CodeSet.IsActive });
        Test.stopTest();

        System.assert(escs.getSObjectFieldList().contains(CodeSet.IsActive), 'Selector did not add SObject field correctly.');
    }

    @IsTest
    public static void selectByCodeAndEndpointTest() {
        VCC_EndpointStatusCodeSelector escs = new VCC_EndpointStatusCodeSelector();
        Integer statusCode = 400;
        String endpointName = 'vccVdifIsValidEsig';
        List<VCC_Endpoint_Status_Code__mdt> controlList = [
            SELECT Id
            FROM VCC_Endpoint_Status_Code__mdt
            WHERE VCC_Endpoint__c = :endpointName AND VCC_App_Name__c = NULL AND VCC_Status_Code__r.VCC_Status_Code__c = :statusCode
        ];
        List<VCC_Endpoint_Status_Code__mdt> esccList = escs.selectByCodeAndEndpoint(statusCode, endpointName);

        System.assert(controlList.size() == esccList.size(), 'Size mismatch.');
    }

    @IsTest
    public static void selectByCodeAndAppTest() {
        VCC_EndpointStatusCodeSelector escs = new VCC_EndpointStatusCodeSelector();
        Integer statusCode = 400;
        String appName = 'Vdif';
        List<VCC_Endpoint_Status_Code__mdt> controlList = [
            SELECT Id
            FROM VCC_Endpoint_Status_Code__mdt
            WHERE VCC_Endpoint__c = NULL AND VCC_App_Name__c = :appName AND VCC_Status_Code__r.VCC_Status_Code__c = :statusCode
        ];
        List<VCC_Endpoint_Status_Code__mdt> esccList = escs.selectByCodeAndApp(statusCode, appName);

        System.assert(controlList.size() == esccList.size(), 'Size mismatch.');
    }

    @IsTest
    public static void selectGlobalByCodeTest() {
        VCC_EndpointStatusCodeSelector escs = new VCC_EndpointStatusCodeSelector();
        Integer statusCode = 400;
        List<VCC_Endpoint_Status_Code__mdt> controlList = [
            SELECT Id
            FROM VCC_Endpoint_Status_Code__mdt
            WHERE VCC_Endpoint__c = NULL AND VCC_App_Name__c = NULL AND VCC_Status_Code__r.VCC_Status_Code__c = :statusCode
        ];
        List<VCC_Endpoint_Status_Code__mdt> esccList = escs.selectGlobalByCode(statusCode);

        System.assert(controlList.size() == esccList.size(), 'Size mismatch.');
    }

    @IsTest
    public static void selectEndpointNameTest() {
        VCC_EndpointStatusCodeSelector escs = new VCC_EndpointStatusCodeSelector();
        String endpointName = 'vccVdifIsValidEsig';
        List<VCC_Endpoint_Status_Code__mdt> controlList = [
            SELECT Id
            FROM VCC_Endpoint_Status_Code__mdt
            WHERE VCC_Endpoint__c = :endpointName
        ];
        List<VCC_Endpoint_Status_Code__mdt> esccList = escs.selectByEndpointName(endpointName);
        System.assert(controlList.size() == esccList.size(), 'Size mismatch.');
    }
}