force-app/main/default/objects/Case/fields/Case_Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Case_Record_Type_Name__c</fullName>
    <formula>RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Record Type Name</label>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/Case/fields/TUC_Assigned_VISN__c.field-meta.xml
<CustomField>
    <fullName>TUC_Assigned_VISN__c</fullName>
    <description>Pulls the VISN from the Assigned Facility record</description>
    <formula>TUC_Assigned_Facility__r.VAF_VISN__c</formula>
    <label>VISN</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/main/default/objects/Case/fields/TUC_Wait_Time__c.field-meta.xml
<CustomField>
    <fullName>TUC_Wait_Time__c</fullName>
    <description>Used in tucTeleECCaseNotifyBatchHelper apex class. Field used in Available Cases queue to indicate time patient has been waiting to be seen.</description>
    <formula
    >IF ( ISPICKVAL(Status,&quot;New&quot;) , IF( NOW() - CreatedDate &gt; 0 , If (FLOOR( (NOW() - CreatedDate ) * 24 ) &lt; 10 , &apos;0&apos;, &apos;&apos;) + TEXT( FLOOR(
        (NOW() - CreatedDate ) * 24 ) ) &amp; &quot;:&quot; &amp; If (ROUND( MOD( (NOW() - CreatedDate ) * 24 * 60, 60 ), 0 ) &lt; 10, &apos;0&apos;, &apos;&apos;) + TEXT( ROUND(
        MOD( (NOW() - CreatedDate ) * 24 * 60, 60 ), 0) ), &quot;&quot; ), If (FLOOR( (NOW() - TUC_Status_Change_Time_Holder__c ) * 24 ) &lt; 10 , &apos;0&apos;, &apos;&apos;) +
        TEXT( FLOOR( (NOW() - TUC_Status_Change_Time_Holder__c ) * 24 ) ) &amp; &quot;:&quot; &amp; If (ROUND( MOD( (NOW() - TUC_Status_Change_Time_Holder__c ) * 24 * 60, 60 ), 0 )
        &lt; 10, &apos;0&apos;, &apos;&apos;) + TEXT( ROUND( MOD( (NOW() - TUC_Status_Change_Time_Holder__c ) * 24 * 60, 60 ), 0) ) ) /*with seconds IF (
        ISPICKVAL(Status,&quot;New&quot;) , IF( NOW() - CreatedDate &gt; 0 , If (FLOOR( (NOW() - CreatedDate ) * 24 ) &lt; 10 , &apos;0&apos;, &apos;&apos;) + TEXT( FLOOR( (NOW() -
        CreatedDate ) * 24 ) ) &amp; &quot;:&quot; &amp; If (ROUND( MOD( (NOW() - CreatedDate ) * 24 * 60, 60 ), 0 ) &lt; 10, &apos;0&apos;, &apos;&apos;) + TEXT( ROUND( MOD(
        (NOW() - CreatedDate ) * 24 * 60, 60 ), 0 ) ) &amp; &quot;:&quot; &amp; If (ROUND( MOD( (NOW() - CreatedDate ) * 24 * 60 * 60, 60 ), 0 ) &lt; 10, &apos;0&apos;,
        &apos;&apos;) + TEXT( ROUND( MOD( (NOW() - CreatedDate ) * 24 * 60 * 60, 60 ), 0 ) ), &quot;&quot; ), &quot;&quot;) */ /* Original IF ( ISPICKVAL(Status,&quot;New&quot;) ,
        IF( NOW() - CreatedDate &gt; 0 , TEXT( FLOOR( NOW() - CreatedDate ) ) &amp; &quot; : &quot; &amp; TEXT( FLOOR( MOD( (NOW() - CreatedDate ) * 24, 24 ) ) ) &amp; &quot; :
        &quot; &amp; TEXT( ROUND( MOD( (NOW() - CreatedDate ) * 24 * 60, 60 ), 0 ) ), &quot;&quot; ), &quot;&quot;) */</formula>
    <label>Wait Time ( Hr : Min )</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/VCC_Owner_Queue_type__c.field-meta.xml
<CustomField>
    <fullName>VCC_Owner_Queue_type__c</fullName>
    <description
    >Displays the end of the queue name to determine the type of queue the case is for. Used in VISN Queue Formula formula field. VISN 99 is a Mock/Test VISN</description>
    <formula>IF(CONTAINS(Owner:Queue.DeveloperName,&apos;10&apos;) || CONTAINS(Owner:Queue.DeveloperName,&apos;11&apos;) || CONTAINS(Owner:Queue.DeveloperName,&apos;12&apos;) ||
        CONTAINS(Owner:Queue.DeveloperName,&apos;13&apos;) || CONTAINS(Owner:Queue.DeveloperName,&apos;14&apos;) || CONTAINS(Owner:Queue.DeveloperName,&apos;15&apos;) ||
        CONTAINS(Owner:Queue.DeveloperName,&apos;16&apos;) || CONTAINS(Owner:Queue.DeveloperName,&apos;17&apos;) || CONTAINS(Owner:Queue.DeveloperName,&apos;18&apos;) ||
        CONTAINS(Owner:Queue.DeveloperName,&apos;19&apos;) || CONTAINS(Owner:Queue.DeveloperName,&apos;20&apos;) || CONTAINS(Owner:Queue.DeveloperName,&apos;21&apos;) ||
        CONTAINS(Owner:Queue.DeveloperName,&apos;22&apos;) || CONTAINS(Owner:Queue.DeveloperName,&apos;23&apos;) || CONTAINS(Owner:Queue.DeveloperName,&apos;99&apos;) ,
        MID(Owner:Queue.DeveloperName, 8,30), MID(Owner:Queue.DeveloperName, 7,30) )</formula>
    <label>Owner Queue Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TUC/tucTeleECCaseNotifyBatch.cls
/**
 * Tele EC Case Notifier
 *
 * This Scheduled Batch class retrives all urgent cases via SOQL
 * and will create platform event(s) if those cases are assigned
 * to the queue for longer than 5 minutes. This class reschedules
 * itself upon completion
 *
 * @param - intervalInMinutes: integer value that determines when
 * 							   the next run of this batch class
 * 							   will occur in minutes after completion
 * @param - continueBatch: boolean value that will enable/disable
 * 						   the job to reschedule itself
 * @return - void
 */
global with sharing class tucTeleECCaseNotifyBatch implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.stateful {
    @TestVisible
    Integer intervalInMinutes = 1;
    @TestVisible
    Boolean continueBatch = true;

    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'Select id, CaseNumber, TUC_Assigned_VISN__c, Status, TUC_Wait_Time__c from case where Case_Record_Type_Name__c like \'Tele_Urgent%\' and VCC_Owner_Queue_type__c = \'le_Emergency_Care_0_2_Hours\'';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Case> cases) {
        tucTeleECCaseNotifyBatchHelper.checkCasesToNotify(cases);
    }

    global void finish(Database.BatchableContext BC) {
        if (continueBatch) {
            system.scheduleBatch(new tucTeleECCaseNotifyBatch(), 'TeleECCaseMonitor' + Datetime.now(), intervalInMinutes);
        }
    }
}