force-app/main/default/objects/Case/fields/PC_Specialty__c.field-meta.xml
<CustomField>
    <fullName>PC_Specialty__c</fullName>
    <label>Specialty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PC_Specialties</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PC_Case__c/PC_Case__c.object-meta.xml
<CustomObject>
    <description>Object to hold Provider Connect cases</description>
    <label>PrC Case</label>
    <nameField>
        <displayFormat>PCC-{0000000000}</displayFormat>
        <label>Provider Connect Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrC Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/PC_Case__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Teams</fullName>
                <label>Teams Video</label>
            </value>
            <value>
                <fullName>Phone</fullName>
                <label>Phone Callback</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PC_Case__c/fields/Closed__c.field-meta.xml
<CustomField>
    <fullName>Closed__c</fullName>
    <formula>IF(ISBLANK(Closed_Date__c),FALSE,TRUE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PC_Case__c/fields/Closed_Date__c.field-meta.xml
<CustomField>
    <fullName>Closed_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date/Time Closed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/PC_Case__c/fields/Specialty__c.field-meta.xml
<CustomField>
    <fullName>Specialty__c</fullName>
    <label>Specialty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PC_Specialties</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/PC_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Note</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed Resolved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/PC_Case__c/recordTypes/Provider_Connect_Case.recordType-meta.xml
<RecordType>
    <fullName>Provider_Connect_Case</fullName>
    <active>true</active>
    <label>Provider Connect Case</label>
</RecordType>

sfdx-source/main/default/objects/UserServicePresence/fields/PC_Chat_Channel__c.field-meta.xml
<CustomField>
    <fullName>PC_Chat_Channel__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PC Chat Channel</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UserServicePresence/fields/PC_Phone_Channel__c.field-meta.xml
<CustomField>
    <fullName>PC_Phone_Channel__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PC Phone Channel</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UserServicePresence/fields/PC_Specialty__c.field-meta.xml
<CustomField>
    <fullName>PC_Specialty__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Specialty</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/UserServicePresence/fields/PC_Teams_Channel__c.field-meta.xml
<CustomField>
    <fullName>PC_Teams_Channel__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PC Teams Channel</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/PC_Specialties.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Addiction Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>Allergy/Immunology</fullName>
    </customValue>
    <customValue>
        <fullName>Amputation Clinic</fullName>
    </customValue>
    <customValue>
        <fullName>Anesthesiology</fullName>
    </customValue>
    <customValue>
        <fullName>Anti-Coagulation Clinic</fullName>
    </customValue>
    <customValue>
        <fullName>Audiology</fullName>
    </customValue>
    <customValue>
        <fullName>Blood Pressure Evaluation</fullName>
    </customValue>
    <customValue>
        <fullName>Brain Injury</fullName>
    </customValue>
    <customValue>
        <fullName>Bros (Blind Rehab O/P Spec)</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiac Catheterization</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiac Implantable Electronic Devices (Cied)</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiac Surgery</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiology</fullName>
    </customValue>
    <customValue>
        <fullName>Chart Consult</fullName>
    </customValue>
    <customValue>
        <fullName>Clinical Pharmacy</fullName>
    </customValue>
    <customValue>
        <fullName>Community Care Consult</fullName>
    </customValue>
    <customValue>
        <fullName>Community Nursing Home (Cnh) Follow-Up</fullName>
    </customValue>
    <customValue>
        <fullName>Computerized Tomography (Ct)</fullName>
    </customValue>
    <customValue>
        <fullName>Cysto Room Unit For Outpatient</fullName>
    </customValue>
    <customValue>
        <fullName>Dental</fullName>
    </customValue>
    <customValue>
        <fullName>Dermatology</fullName>
    </customValue>
    <customValue>
        <fullName>Diabetes</fullName>
    </customValue>
    <customValue>
        <fullName>Eeg</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>Endocrinology</fullName>
    </customValue>
    <customValue>
        <fullName>Epilepsy</fullName>
    </customValue>
    <customValue>
        <fullName>Eye Telehealth Screening</fullName>
    </customValue>
    <customValue>
        <fullName>Gastroenterology</fullName>
    </customValue>
    <customValue>
        <fullName>General Internal Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>General Surgery</fullName>
    </customValue>
    <description>DO NOT CHANGE API NAME OF PICKLIST VALUES</description>
    <masterLabel>PC Specialties</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/PC/PC_ManagerController.cls
/**
 * @description       : Class used as a controller for pcOmniChannelSupervisor LWC
 * @author            : George Elias
 * @group             : Booze Allen Hamilton
 * @last modified on  : 07-06-2022
 * @last modified by  : George Elias
 * Modifications Log
 * Ver   Date         Author                               Modification
 * 1.0   07-06-2022   George Elias                          Initial Version
 **/
public with sharing class PC_ManagerController {
    /**
     * @description       : Wrapper class used to return data to LWC
     * @author            : George Elias
     * */
    @TestVisible
    public class AgentHistory {
        @AuraEnabled
        public String agentName;
        @AuraEnabled
        public String agentId;
        @AuraEnabled
        public String agentImage;
        @AuraEnabled
        public String currentStatus = 'Offline';
        @AuraEnabled
        public Decimal currentCapacity = 0;
        @AuraEnabled
        public List<UserServicePresence> historicStatuses = new List<UserServicePresence>();
        @AuraEnabled
        public List<PC_Case__c> openCases = new List<PC_Case__c>();
        @AuraEnabled
        public List<PC_Case__c> allCases = new List<PC_Case__c>();
    }

    /**
     * @description Method to fetch historical case and presence data of PC specialist
     * @author George Elias | 07-06-2022
     * @return  List<AgentHistory> - List of AgenHistory wrapper class
     **/
    @AuraEnabled
    public static List<AgentHistory> getAgentHistory() {
        try {
            List<AgentHistory> returnList = new List<AgentHistory>();
            Id pcRtId = Schema.SObjectType.ServiceResource.getRecordTypeInfosByName()
                .get('Provider Connect Resource')
                .getRecordTypeId();
            List<String> lsUserIds = new List<String>();
            for (ServiceResource sr : [
                SELECT RelatedRecordId
                FROM ServiceResource
                WHERE RecordTypeId = :pcRtId
                WITH SECURITY_ENFORCED
            ]) {
                lsUserIds.add(sr.RelatedRecordId);
            }

            if (lsUserIds.size() == 0) {
                throw new PC_CustomException('No Provider Connect specialists found.');
            }

            Map<Id, User> mpUsers = new Map<Id, User>(
                [SELECT Id, Name, MediumPhotoUrl FROM User WHERE Id IN :lsUserIds WITH SECURITY_ENFORCED ORDER BY Name]
            );
            Map<String, List<UserServicePresence>> mpUserPresence = new Map<String, List<UserServicePresence>>();
            for (UserServicePresence usp : [
                SELECT
                    UserId,
                    User.Name,
                    ServicePresenceStatus.MasterLabel,
                    StatusStartDate,
                    ConfiguredCapacity,
                    StatusEndDate,
                    IsAway,
                    IdleDuration,
                    AtCapacityDuration,
                    AverageCapacity,
                    IsCurrentState,
                    StatusDuration,
                    PC_Specialty__c,
                    PC_Teams_Channel__c,
                    PC_Chat_Channel__c,
                    PC_Phone_Channel__c
                FROM UserServicePresence
                WHERE UserId IN :lsUserIds AND StatusStartDate = LAST_N_DAYS:30
                WITH SECURITY_ENFORCED
                ORDER BY IsCurrentState DESC, CreatedDate DESC
            ]) {
                if (mpUserPresence.containsKey(usp.UserId)) {
                    mpUserPresence.get(usp.UserId).add(usp);
                } else {
                    mpUserPresence.put(usp.UserId, new List<UserServicePresence>{ usp });
                }
            }

            Map<String, List<PC_Case__c>> mpOpenCases = new Map<String, List<PC_Case__c>>();
            Map<String, List<PC_Case__c>> mpAllCases = new Map<String, List<PC_Case__c>>();
            for (PC_Case__c c : [
                SELECT Id, Name, CreatedDate, Specialty__c, Channel__c, Status__c, OwnerId, Closed__c, Closed_Date__c
                FROM PC_Case__c
                WHERE RecordType.DeveloperName = 'Provider_Connect_Case' AND CreatedDate = LAST_N_DAYS:30
                ORDER BY Name DESC
            ]) {
                if (c.Closed__c == false) {
                    if (mpOpenCases.containsKey(c.OwnerId)) {
                        mpOpenCases.get(c.OwnerId).add(c);
                    } else {
                        mpOpenCases.put(c.OwnerId, new List<PC_Case__c>{ c });
                    }
                }
                if (mpAllCases.containsKey(c.OwnerId)) {
                    mpAllCases.get(c.OwnerId).add(c);
                } else {
                    mpAllCases.put(c.OwnerId, new List<PC_Case__c>{ c });
                }
            }

            List<AgentWork> lsAW = [
                SELECT UserId, Status, CapacityWeight
                FROM AgentWork
                WHERE Status = 'Opened'
                WITH SECURITY_ENFORCED
            ];

            if (Test.isRunningTest()) {
                User specialist = [
                    SELECT Id
                    FROM User
                    WHERE LastName = 'Test PC Manager'
                    WITH SECURITY_ENFORCED
                    LIMIT 1
                ];

                ServiceChannel sc = [
                    SELECT Id
                    FROM ServiceChannel
                    WHERE DeveloperName = 'PC_Chat_Service'
                    WITH SECURITY_ENFORCED
                    LIMIT 1
                ];

                PC_Case__c c = [SELECT Id FROM PC_Case__c WITH SECURITY_ENFORCED LIMIT 1];
                lsAW.add(
                    new AgentWork(
                        UserID = specialist.Id,
                        WorkItemId = c.Id,
                        ServiceChannelId = sc.Id,
                        CapacityWeight = 5
                    )
                );
            }

            Map<String, Decimal> mpAgentCapacity = new Map<String, Decimal>();
            for (AgentWork aw : lsAW) {
                if (mpAgentCapacity.containsKey(aw.UserId)) {
                    mpAgentCapacity.put(aw.UserId, mpAgentCapacity.get(aw.UserId) + aw.CapacityWeight);
                } else {
                    mpAgentCapacity.put(aw.UserId, aw.CapacityWeight);
                }
            }

            for (String userId : mpUsers.keySet()) {
                AgentHistory ag = new AgentHistory();
                ag.agentId = userId;
                ag.agentName = mpUsers.get(userId).Name;
                ag.agentImage = mpUsers.get(userId).MediumPhotoUrl;

                if (mpUserPresence.containsKey(userId)) {
                    ag.currentStatus = mpUserPresence.get(userId)[0].IsCurrentState == true
                        ? mpUserPresence.get(userId)[0].ServicePresenceStatus.MasterLabel.split(' - ')[0]
                        : 'Offline';
                    ag.historicStatuses = mpUserPresence.get(userId);
                }
                if (mpAllCases.containsKey(userId)) {
                    ag.allCases = mpAllCases.get(userId);
                }
                if (mpOpenCases.containsKey(userId)) {
                    ag.openCases = mpOpenCases.get(userId);
                }

                if (mpAgentCapacity.containsKey(userId)) {
                    ag.currentCapacity = (mpAgentCapacity.get(userId) / 20) * 100;
                }
                returnList.add(ag);
            }

            return returnList;
        } catch (Exception e) {
            log_LogService.log('PC_ManagerController.getAgentHistory Exception', log_LogService.LogType.ERROR, e);
            log_LogService.publish();
            throw new AuraHandledException(e.getMessage());
        }
    }
}