force-app/main/default/objects/Case/fields/PC_Specialty__c.field-meta.xml
<CustomField>
    <fullName>PC_Specialty__c</fullName>
    <label>Specialty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PC_Specialties</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PC_AWPushEvent__c/PC_AWPushEvent__c.object-meta.xml
<CustomObject>
    <description>Used to trigger a Push Topic when a PC_Case__c status changes, a Specialist logs on or off. The key objects this pushtopic reacts on is UserPresence and
        AgentWork.</description>
    <label>PrC AWPushEvent</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>PC AWPushEvent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PrC AWPushEvents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/PC_AWPushEvent__c/fields/CaseClosedByName__c.field-meta.xml
<CustomField>
    <fullName>CaseClosedByName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CaseClosedByName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/PC_AWPushEvent__c/fields/CaseClosedJSON__c.field-meta.xml
<CustomField>
    <fullName>CaseClosedJSON__c</fullName>
    <description>Holds the JSON for cases closed in bulk.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>CaseClosedJSON</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PC_AWPushEvent__c/fields/CaseClosedStatus__c.field-meta.xml
<CustomField>
    <fullName>CaseClosedStatus__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CaseClosedStatus</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/PC_AWPushEvent__c/fields/ConsultantsOnline__c.field-meta.xml
<CustomField>
    <fullName>ConsultantsOnline__c</fullName>
    <label>ConsultantsOnline</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/main/default/objects/PC_AWPushEvent__c/fields/GeneralDisabled__c.field-meta.xml
<CustomField>
    <fullName>GeneralDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox that denotes if the General PrC Case button should be active. Utilized in Push Events to set button disabled or enabled</description>
    <label>GeneralDisabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PC_AWPushEvent__c/fields/HasPresence__c.field-meta.xml
<CustomField>
    <fullName>HasPresence__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HasPresence</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/PC_AWPushEvent__c/fields/MinCapacity__c.field-meta.xml
<CustomField>
    <fullName>MinCapacity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>MinCapacity</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

sfdx-source/main/default/objects/PC_AWPushEvent__c/fields/NewCaseOwner__c.field-meta.xml
<CustomField>
    <fullName>NewCaseOwner__c</fullName>
    <description>Holds the new case owner if the case owner was changed</description>
    <encryptionScheme>None</encryptionScheme>
    <label>NewCaseOwner</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/PC_AWPushEvent__c/fields/NewOwnerCity__c.field-meta.xml
<CustomField>
    <fullName>NewOwnerCity__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>NewOwnerCity</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/PC_AWPushEvent__c/fields/NewOwnerDepartment__c.field-meta.xml
<CustomField>
    <fullName>NewOwnerDepartment__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>NewOwnerDepartment</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PC_AWPushEvent__c/fields/NewOwnerEmail__c.field-meta.xml
<CustomField>
    <fullName>NewOwnerEmail__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>NewOwnerEmail</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PC_AWPushEvent__c/fields/NewOwnerMediumPhotoUrl__c.field-meta.xml
<CustomField>
    <fullName>NewOwnerMediumPhotoUrl__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>NewOwnerMediumPhotoUrl</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PC_AWPushEvent__c/fields/NewOwnerState__c.field-meta.xml
<CustomField>
    <fullName>NewOwnerState__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>NewOwnerState</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/PC_AWPushEvent__c/fields/NewOwnerTitle__c.field-meta.xml
<CustomField>
    <fullName>NewOwnerTitle__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>NewOwnerTitle</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PC_AWPushEvent__c/fields/PatientSpecificDisabled__c.field-meta.xml
<CustomField>
    <fullName>PatientSpecificDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox that denotes if the Patient Specific PrC Case button should be active. Utilized in Push Events to set button disabled or enabled</description>
    <label>PatientSpecificDisabled</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/PC_AWPushEvent__c/fields/SkillName__c.field-meta.xml
<CustomField>
    <fullName>SkillName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SkillName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PC_Case__c/PC_Case__c.object-meta.xml
<CustomObject>
    <description>Object to hold Provider Connect cases</description>
    <label>PrC Case</label>
    <nameField>
        <displayFormat>PCC-{0000000000}</displayFormat>
        <label>Provider Connect Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrC Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PC_Case__c/fields/Closed__c.field-meta.xml
<CustomField>
    <fullName>Closed__c</fullName>
    <formula>IF(ISBLANK(Closed_Date__c),FALSE,TRUE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PC_Case__c/fields/Specialty__c.field-meta.xml
<CustomField>
    <fullName>Specialty__c</fullName>
    <label>Specialty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PC_Specialties</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/PC_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Note</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed Resolved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UserServicePresence/fields/PC_Specialty__c.field-meta.xml
<CustomField>
    <fullName>PC_Specialty__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Specialty</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/PC_Specialties.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Addiction Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>Allergy/Immunology</fullName>
    </customValue>
    <customValue>
        <fullName>Amputation Clinic</fullName>
    </customValue>
    <customValue>
        <fullName>Anesthesiology</fullName>
    </customValue>
    <customValue>
        <fullName>Anti-Coagulation Clinic</fullName>
    </customValue>
    <customValue>
        <fullName>Audiology</fullName>
    </customValue>
    <customValue>
        <fullName>Blood Pressure Evaluation</fullName>
    </customValue>
    <customValue>
        <fullName>Brain Injury</fullName>
    </customValue>
    <customValue>
        <fullName>Bros (Blind Rehab O/P Spec)</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiac Catheterization</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiac Implantable Electronic Devices (Cied)</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiac Surgery</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiology</fullName>
    </customValue>
    <customValue>
        <fullName>Chart Consult</fullName>
    </customValue>
    <customValue>
        <fullName>Clinical Pharmacy</fullName>
    </customValue>
    <customValue>
        <fullName>Community Care Consult</fullName>
    </customValue>
    <customValue>
        <fullName>Community Nursing Home (Cnh) Follow-Up</fullName>
    </customValue>
    <customValue>
        <fullName>Computerized Tomography (Ct)</fullName>
    </customValue>
    <customValue>
        <fullName>Cysto Room Unit For Outpatient</fullName>
    </customValue>
    <customValue>
        <fullName>Dental</fullName>
    </customValue>
    <customValue>
        <fullName>Dermatology</fullName>
    </customValue>
    <customValue>
        <fullName>Diabetes</fullName>
    </customValue>
    <customValue>
        <fullName>Eeg</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>Endocrinology</fullName>
    </customValue>
    <customValue>
        <fullName>Epilepsy</fullName>
    </customValue>
    <customValue>
        <fullName>Eye Telehealth Screening</fullName>
    </customValue>
    <customValue>
        <fullName>Gastroenterology</fullName>
    </customValue>
    <customValue>
        <fullName>General Internal Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>General Surgery</fullName>
    </customValue>
    <description>DO NOT CHANGE API NAME OF PICKLIST VALUES</description>
    <masterLabel>PC Specialties</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/PC/PC_SuperScreenPushEvent.cls
/**
 * @description Class used by PC_ChatStreamController to track new/changed data from Agent Work and User Service Presence records from their respective record-triggered flows (Trigger_Pushtopic_from_AgentWork & PC_Set_Presence_Channel)
 *              The AW Push Event created from the flow input is used to invoke the PC Super Screen Push Topic in order to refresh the Availability Matrix table on the FLP Homepage
 * @author      Booz Allen Hamilton
 * @see         PC_ChatStreamController
 */
public inherited sharing class PC_SuperScreenPushEvent {
    private AgentWork agentWork;
    private PC_Case__c pcCase;
    private UserServicePresence userServicePresence;

    /**
     * @description AW Push Event to refresh PC Super Screen (Availability Matrix)
     */
    public PC_AWPushEvent__c pushEvent {
        public get {
            return this.pushEvent = this.pushEvent ?? new PC_AWPushEvent__c();
        }
        private set;
    }

    /**
     * @description Specialty for the event
     */
    public String specialty {
        public get {
            return this.userServicePresence?.PC_Specialty__c ?? this.pcCase?.Specialty__c;
        }
        private set;
    }

    /**
     * @description constructor for Agent Work record-triggered flows that want to invoke the PC Super Screen Push Topic
     * @param agentWork
     * @param pcCase
     * @param pushEvent
     */
    public PC_SuperScreenPushEvent(AgentWork agentWork, PC_Case__c pcCase, PC_AWPushEvent__c pushEvent) {
        this.agentWork = agentWork;
        this.pcCase = pcCase;
        this.pushEvent = pushEvent;
        this.pushEvent.OwnerId = agentWork?.UserId;
    }

    /**
     * @description constructor for User Service Presence record-triggered flows that want to invoke the PC Super Screen Push Topic
     * @param userServicePresence
     * @param pushEvent
     */
    public PC_SuperScreenPushEvent(UserServicePresence userServicePresence, PC_AWPushEvent__c pushEvent) {
        this.userServicePresence = userServicePresence;
        this.pushEvent = pushEvent;
        this.pushEvent.OwnerId = userServicePresence?.UserId;
    }

    /**
     * @description resets all fields on the push event to default values
     */
    public void resetPushEventFields() {
        this.pushEvent.CaseClosedJSON__c = '';
        this.pushEvent.CaseClosedByName__c = '';
        this.pushEvent.CaseClosedStatus__c = '';
        this.pushEvent.NewCaseOwner__c = '';
        this.pushEvent.NewOwnerTitle__c = '';
        this.pushEvent.NewOwnerCity__c = '';
        this.pushEvent.NewOwnerState__c = '';
        this.pushEvent.NewOwnerEmail__c = '';
        this.pushEvent.NewOwnerMediumPhotoUrl__c = '';
        this.pushEvent.NewOwnerDepartment__c = '';
        this.pushEvent.SkillName__c = '';
        this.pushEvent.HasPresence__c = false;
        this.pushEvent.ConsultantsOnline__c = 0;
        this.pushEvent.MinCapacity__c = 0.0;
        this.pushEvent.PatientSpecificDisabled__c = false;
        this.pushEvent.GeneralDisabled__c = false;
    }

    /**
     * @description sets New Owner fields on push event when an Agent Work record is Canceled and/or PrC Case is Closed
     * @param pcCaseOwner
     */
    public void setNewOwnerFields(User pcCaseOwner) {
        if (pcCaseOwner == null || this.agentWork?.Status != 'Canceled' || this.pcCase?.Closed__c) {
            return;
        }

        this.pushEvent.NewCaseOwner__c = pcCaseOwner?.Name;
        this.pushEvent.NewOwnerTitle__c = pcCaseOwner?.Title;
        this.pushEvent.NewOwnerCity__c = pcCaseOwner?.City;
        this.pushEvent.NewOwnerState__c = pcCaseOwner?.State;
        this.pushEvent.NewOwnerEmail__c = pcCaseOwner?.Email;
        this.pushEvent.NewOwnerMediumPhotoUrl__c = pcCaseOwner?.MediumPhotoUrl;
        this.pushEvent.NewOwnerDepartment__c = pcCaseOwner?.Department;
    }

    /**
     * @description sets Case Closed fields on push event when a PrC Case is Closed or Cancelled
     * @param pcCaseLastModifiedUser
     */
    public void setCaseClosedFields(User pcCaseLastModifiedUser) {
        if (pcCaseLastModifiedUser == null || !(this.pcCase?.Closed__c || this.pcCase?.Status__c == 'Cancelled')) {
            return;
        }

        this.pushEvent.CaseClosedByName__c = pcCaseLastModifiedUser?.Name ?? '';
        this.pushEvent.CaseClosedStatus__c = pcCase?.Status__c;
        this.pushEvent.CaseClosedJSON__c = JSON.serialize(new Map<String, String>{ pcCase?.Id => pcCase?.Name });
    }

    /**
     * @description sets Specialty Availability fields on push event so Specialty table on the Availability Matrix (PC SuperScreen) can the provided skill's row info is updated for conditional displays
     * @param skillStatus
     */
    public void setSpecialtyAvailabilityFields(PC_ProviderConnectController.SkillStatus skillStatus) {
        if (skillStatus == null || !this.specialty.equalsIgnoreCase(skillStatus?.skillName)) {
            return;
        }

        this.pushEvent.SkillName__c = skillStatus.skillName;
        this.pushEvent.HasPresence__c = skillStatus.hasPresence;
        this.pushEvent.ConsultantsOnline__c = skillStatus.consultantsOnline;
        this.pushEvent.MinCapacity__c = skillStatus.minCapacity;
        this.pushEvent.PatientSpecificDisabled__c = skillStatus.patientSpecificDisabled;
        this.pushEvent.GeneralDisabled__c = skillStatus.generalDisabled;
    }
}