force-app/main/default/objects/Case/fields/VCC_Case_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case_Sub_Type__c</fullName>
    <description>Categorize the Case for reporting purposes.</description>
    <inlineHelpText>Categorize the Case for reporting purposes.</inlineHelpText>
    <label>Case Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>VCC_Case_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrative</fullName>
            </value>
            <value>
                <fullName>Community Care</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Emergent</fullName>
            </value>
            <value>
                <fullName>Medication Status</fullName>
            </value>
            <value>
                <fullName>Non-Emergent</fullName>
            </value>
            <value>
                <fullName>Telephone Virtual Visit</fullName>
                <label>Phone</label>
            </value>
            <value>
                <fullName>Refill Medication</fullName>
            </value>
            <value>
                <fullName>Renew Medication</fullName>
            </value>
            <value>
                <fullName>Scheduling</fullName>
            </value>
            <value>
                <fullName>Triage</fullName>
            </value>
            <value>
                <fullName>Urgent</fullName>
            </value>
            <value>
                <fullName>Urgent First Fill</fullName>
            </value>
            <value>
                <fullName>Video Virtual Visit</fullName>
                <label>Video</label>
            </value>
            <value>
                <fullName>PHR VCV</fullName>
            </value>
            <value>
                <fullName>Administrative and Scheduling</fullName>
                <label>Scheduling and Administrative</label>
            </value>
            <value>
                <fullName>Pharmacy</fullName>
            </value>
            <value>
                <fullName>Pharmacy Quality Assurance Issue</fullName>
            </value>
            <value>
                <fullName>Medication Error</fullName>
                <isActive>false</isActive>
                <label>Medication Error</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/VCC_Case_Type__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case_Type__c</fullName>
    <description>Type of Case the caller is calling about</description>
    <inlineHelpText>Type of Case the caller is calling about</inlineHelpText>
    <label>Case Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrative</fullName>
            </value>
            <value>
                <fullName>Pharmacy</fullName>
            </value>
            <value>
                <fullName>Symptom</fullName>
            </value>
            <value>
                <fullName>VCV</fullName>
            </value>
            <value>
                <fullName>Tele-Emergency Care</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/VCC_Follow_Up_Appt_Needed__c.field-meta.xml
<CustomField>
    <fullName>VCC_Follow_Up_Appt_Needed__c</fullName>
    <description>Utilized Medical Provider when a follow up appointment is needed after a virtual visit appointment</description>
    <inlineHelpText>Select when an appointment is needed for the Veteran. A related case will automatically be created and placed in the MSA Queue for scheduling the
        appointment.</inlineHelpText>
    <label>Follow-Up Appt Needed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Within 24 Hrs</fullName>
            </value>
            <value>
                <fullName>Within 24-72 Hrs</fullName>
            </value>
            <value>
                <fullName>Within 8 hours</fullName>
            </value>
            <value>
                <fullName>Within 24 hours</fullName>
            </value>
            <value>
                <fullName>Within 3 days</fullName>
            </value>
            <value>
                <fullName>Within 2 weeks</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/Case/fields/VCC_Follow_Up_Appt_Needed_Hours__c.field-meta.xml
<CustomField>
    <fullName>VCC_Follow_Up_Appt_Needed_Hours__c</fullName>
    <description>Calculate hours / Render hours based on VCC_Follow_Up_Appt_Needed__c - Returned values are hours example 8,24,72 CCCM-18442</description>
    <formula>IF( TEXT(VCC_Follow_Up_Appt_Needed__c) = &apos;Within 8 hours&apos;, 8, IF( TEXT(VCC_Follow_Up_Appt_Needed__c) = &apos;Within 24 hours&apos;, 24, IF(
        TEXT(VCC_Follow_Up_Appt_Needed__c) = &apos;Within 24 Hrs&apos;, 24, IF( TEXT(VCC_Follow_Up_Appt_Needed__c) = &apos;Within 3 days&apos;, 72, IF(
        TEXT(VCC_Follow_Up_Appt_Needed__c) = &apos;Within 24-72 Hrs&apos;, 54, IF( TEXT(VCC_Follow_Up_Appt_Needed__c) = &apos;Within 2 weeks&apos;, 336, 1000000 ) ) ) ) )
        )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>VCC Follow Up Appt Needed Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/main/default/objects/Case/fields/VCC_Queue_type__c.field-meta.xml
<CustomField>
    <fullName>VCC_Queue_type__c</fullName>
    <description>field to identify the Queue&apos;s service that is associated with the case.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Queue Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/Case/fields/VCC_VISN_to_Queue_Formula__c.field-meta.xml
<CustomField>
    <fullName>VCC_VISN_to_Queue_Formula__c</fullName>
    <description>Compares the User.Division with the Queue Name to determine cases to show in &quot;My VISN&quot; Case list views on Home Page.</description>
    <formula
    >IF ( (&quot;CCC_V&quot; + mid($User.Division,6,2) + VCC_Queue_type__c) = Owner:Queue.DeveloperName || (&quot;VCC_V&quot; + mid($User.Division,6,2) + VCC_Queue_type__c) =
        Owner:Queue.DeveloperName, true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>VISN to Queue Formula</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/VCC/VCC_SchedulingCasesListController.cls
/**
 * @author VAHC
 * @since 4/20/2023
 * @description Class that holds apex methods to be used in LWC/Aura components
 */

public with sharing class VCC_SchedulingCasesListController {
    /**
     * @description class that gets a list of cases in the MSA queue
     * @return List of VCC_CaseModal
     */
    @AuraEnabled
    public static List<VCC_CaseModal> getCaseList() {
        List<Case> caseList = [
            SELECT
                Id,
                CaseNumber,
                ContactId,
                Contact.Name,
                Status,
                RecordTypeId,
                RecordType.Name,
                VCC_Case_Type__c,
                VCC_Case_Sub_Type__c,
                Subject,
                CreatedDate,
                Owner.Name,
                VCC_Follow_Up_Appt_Needed__c,
                VCC_Follow_Up_Appt_Needed_Hours__c
            FROM Case
            WHERE
                VCC_Queue_type__c = '_MSA'
                AND VCC_VISN_to_Queue_Formula__c = TRUE
                AND (Status = 'New'
                OR Status = 'Open'
                OR Status = 'Patient Call Back'
                OR Status = 'Ready for MP'
                OR Status = 'Nurse Encounter'
                OR Status = 'MP Encounter')
            WITH SECURITY_ENFORCED
            ORDER BY VCC_Follow_Up_Appt_Needed_Hours__c ASC NULLS LAST, CreatedDate ASC
            LIMIT 10000
        ];

        if (Test.isRunningTest()) {
            caseList = [
                SELECT
                    Id,
                    CaseNumber,
                    ContactId,
                    Contact.Name,
                    Status,
                    RecordTypeId,
                    RecordType.Name,
                    VCC_Case_Type__c,
                    VCC_Case_Sub_Type__c,
                    Subject,
                    CreatedDate,
                    Owner.Name,
                    VCC_Follow_Up_Appt_Needed__c,
                    VCC_Follow_Up_Appt_Needed_Hours__c
                FROM Case
                WITH SECURITY_ENFORCED
                LIMIT 10000
            ];
        }
        List<VCC_CaseModal> caseModalList = new List<VCC_CaseModal>();
        for (Case caseObj : caseList) {
            VCC_CaseModal caseModalObj = new VCC_CaseModal();
            caseModalObj.caseId = caseObj.Id;
            caseModalObj.caseNumber = caseObj.CaseNumber;
            caseModalObj.caseURL = '/lightning/r/Case/' + caseObj.Id + '/view';
            caseModalObj.contactId = caseObj.ContactId;
            caseModalObj.contactName = caseObj.Contact.Name;
            caseModalObj.contactURL = '/lightning/r/Contact/' + caseObj.contactId + '/view';
            caseModalObj.recordType = caseObj.RecordType.Name;
            caseModalObj.caseType = caseObj.VCC_Case_Type__c;
            caseModalObj.caseSubType = caseObj.VCC_Case_Sub_Type__c;
            caseModalObj.subject = caseObj.Subject;
            caseModalObj.subjectURL = String.isNotBlank(caseObj.Subject)
                ? '/lightning/r/Case/' + caseObj.Id + '/view'
                : '';
            caseModalObj.status = caseObj.Status;
            caseModalObj.dateTimeOpened = caseObj.CreatedDate;
            caseModalObj.dateTimeOpenedStr = caseObj.CreatedDate.format();
            caseModalObj.caseOwnerAlias = caseObj.Owner.Name;
            caseModalObj.followUpAppt = caseObj.VCC_Follow_Up_Appt_Needed__c;
            caseModalObj.followUpApptHours = caseObj.VCC_Follow_Up_Appt_Needed_Hours__c;
            caseModalList.add(caseModalObj);
        }
        return caseModalList;
    }
}