force-app/main/default/objects/Case/fields/VCC_Case_Type__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case_Type__c</fullName>
    <description>Type of Case the caller is calling about</description>
    <inlineHelpText>Type of Case the caller is calling about</inlineHelpText>
    <label>Case Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrative</fullName>
            </value>
            <value>
                <fullName>Pharmacy</fullName>
            </value>
            <value>
                <fullName>Symptom</fullName>
            </value>
            <value>
                <fullName>VCV</fullName>
            </value>
            <value>
                <fullName>Tele-Emergency Care</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/Case/fields/VCC_Progress_Note__c.field-meta.xml
<CustomField>
    <fullName>VCC_Progress_Note__c</fullName>
    <description>Check true if there are any Progress Notes, related to the case.</description>
    <formula>IF( VCC_Progress_Notes_Count__c &gt; 0, TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Check true if there are any Progress Notes, related to the case.</inlineHelpText>
    <label>Progress Note</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/VCC_Vitrual_Clinic_Visit.recordType-meta.xml
<RecordType>
    <fullName>VCC_Vitrual_Clinic_Visit</fullName>
    <active>true</active>
    <businessProcess>VCC Support Process</businessProcess>
    <description>--VA Health Connect virtual visits with medical providers</description>
    <label>Virtual Clinic Visit Case</label>
</RecordType>

sfdx-source/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

sfdx-source/main/default/objects/VCC_Call_Tracking__c/VCC_Call_Tracking__c.object-meta.xml
<CustomObject>
    <description>The Call Tracking object is used to track unsuccessful outbound phone call attempts to a patient or caregiver at or after their scheduled appointment time, so that the CCC has documented date/timestamps of those attempts.</description>
    <label>Call Tracking</label>
    <nameField>
        <displayFormat>CALL-{00000}</displayFormat>
        <label>Call Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Tracking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VCC_Call_Tracking__c/fields/VCC_Call_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>VCC_Call_Date_Time__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>The date/time that the call has occurred</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Call Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/VCC_Call_Tracking__c/fields/VCC_Progress_Note__c.field-meta.xml
<CustomField>
    <fullName>VCC_Progress_Note__c</fullName>
    <label>Progress Note</label>
    <referenceTo>VCC_Progress_Note__c</referenceTo>
    <relationshipLabel>Call Tracking</relationshipLabel>
    <relationshipName>Call_Tracking</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/VCC_Progress_Note__c.object-meta.xml
<CustomObject>
    <description>Progress Notes</description>
    <label>Progress Note</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>Progress Note</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Additional_Comments__c.field-meta.xml
<CustomField>
    <fullName>VCC_Additional_Comments__c</fullName>
    <description>Used to add any additional comments about lost medication</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter any additional comments about lost medication</inlineHelpText>
    <label>Additional Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Caregiver_Name__c.field-meta.xml
<CustomField>
    <fullName>VCC_Caregiver_Name__c</fullName>
    <description>Name of caregiver speaking on behalf of the patient</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Name of caregiver speaking on behalf of the patient</inlineHelpText>
    <label>Caller/Recipient Name</label>
    <type>TextArea</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Case__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case__c</fullName>
    <description>Parent Case for Progress Note</description>
    <inlineHelpText>Case related to Progress Note on the patient record.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Progress Notes</relationshipLabel>
    <relationshipName>Progress_Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Relative_Type__c.field-meta.xml
<CustomField>
    <fullName>VCC_Relative_Type__c</fullName>
    <description>Relationship of Caller to Veteran. Populated from the Phone Call/Case via a Flow.</description>
    <inlineHelpText>Relationship of the Caller to the Veteran. This is populated from the Phone Call/Case, if captured.</inlineHelpText>
    <label>Caller/Recipient Relation to Patient</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Self</fullName>
            </value>
            <value>
                <fullName>Caregiver</fullName>
            </value>
            <value>
                <fullName>Power of Attorney</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Anonymous</fullName>
                <isActive>false</isActive>
                <label>Anonymous</label>
            </value>
            <value>
                <fullName>Aunt</fullName>
                <isActive>false</isActive>
                <label>Aunt</label>
            </value>
            <value>
                <fullName>Daughter</fullName>
                <isActive>false</isActive>
                <label>Daughter</label>
            </value>
            <value>
                <fullName>Father</fullName>
                <isActive>false</isActive>
                <label>Father</label>
            </value>
            <value>
                <fullName>Home Health</fullName>
                <isActive>false</isActive>
                <label>Home Health</label>
            </value>
            <value>
                <fullName>Mother</fullName>
                <isActive>false</isActive>
                <label>Mother</label>
            </value>
            <value>
                <fullName>Neighbor</fullName>
                <isActive>false</isActive>
                <label>Neighbor</label>
            </value>
            <value>
                <fullName>Sibling</fullName>
                <isActive>false</isActive>
                <label>Sibling</label>
            </value>
            <value>
                <fullName>Son</fullName>
                <isActive>false</isActive>
                <label>Son</label>
            </value>
            <value>
                <fullName>Spouse</fullName>
                <isActive>false</isActive>
                <label>Spouse</label>
            </value>
            <value>
                <fullName>Uncle</fullName>
                <isActive>false</isActive>
                <label>Uncle</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/classes/VCR/Tests/VCR_CallTrackingRepoTest.cls
/**
 * @author Booz Allen Hamilton
 * @description Tests for VCR_CallTrackingRepo class.
 * @see VCR_CallTrackingRepo
 */
@IsTest
public with sharing class VCR_CallTrackingRepoTest {
    private static final String VAVET_BASE_PROFILE = 'VAVET Base Profile';
    private static final String VCC_MEDICAL_PROVIDER = 'VCC_Medical_Provider';
    private static final String VCC_INT_TEST = 'VCC Integration Test Utility User';
    private static final String VCC_MP_VIEWER = 'VAHC VCV Appointment Viewer Medical Provider';
    private static final String USER_FIRST_NAME = 'CallTrackingTest';

    /**@description Create Test User for CallTrackingRepoTests
     */
    @TestSetup
    static void makeData() {
        new VATEST_UserBuilder()
            .withUserProfile(VAVET_BASE_PROFILE)
            .withStandardData()
            .setFields(User.TimeZoneSidKey, UserInfo.getTimeZone().getID())
            .setFields(User.FirstName, USER_FIRST_NAME)
            .withPermissionSet(VCC_MEDICAL_PROVIDER)
            .withPermissionSet(VCC_INT_TEST)
            .withPermissionSet(VCC_MP_VIEWER)
            .build(true);
    }
    /**
     * @description Create Test Data for CallTrackingRepoTests
     * @param insertCallTrackingRecords Boolean for positive and negative tests
     * @return Id of Progress Note
     */
    public static Id createTestData(Boolean insertCallTrackingRecords) {
        VATEST_SObjectFactory.createSObject(
            new Account(
                FirstName = 'Testly',
                LastName = 'Person Accounted',
                RecordTypeId = new VCR_AccountRepo().recordTypeConstant.fromDeveloperName('PersonAccount').Id
            ),
            true
        );

        Contact testContact = [SELECT Id FROM Contact LIMIT 1];
        update testContact;

        Id caseRecTypeId = new VCR_CaseRepo().recordTypeConstant.fromDeveloperName('VCC_Vitrual_Clinic_Visit').Id;

        Case testCase = (Case) VATEST_SObjectFactory.createSObject(
            new Case(RecordTypeId = caseRecTypeId, VCC_Case_Type__c = 'VCV', ContactId = testContact.Id),
            true
        );

        VCC_Progress_Note__c testProgressNote = (VCC_Progress_Note__c) VATEST_SObjectFactory.createSObject(
            new VCC_Progress_Note__c(
                VCC_Case__c = testCase.id,
                VCC_Caregiver_Name__c = 'Care Giver',
                VCC_Additional_Comments__c = 'Note1',
                VCC_Relative_Type__c = 'Self'
            ),
            true
        );

        if (insertCallTrackingRecords) {
            VATEST_SObjectFactory.createSObject(
                new VCC_Call_Tracking__c(
                    VCC_Progress_Note__c = testProgressNote.Id,
                    VCC_Call_Date_Time__c = Datetime.now(),
                    CreatedDate = Datetime.now()
                ),
                true
            );
        }

        return testProgressNote.Id;
    }

    /**
     * @description Test fetchById() for success path
     */
    @IsTest
    static void unitTestConstructorPositive() {
        User testUser = [SELECT Id FROM User WHERE FirstName = :USER_FIRST_NAME LIMIT 1];
        System.runAs(testUser) {
            Test.startTest();
            VCR_CallTrackingRepo repo = new VCR_CallTrackingRepo();
            Assert.isNotNull(repo, 'Expected constructor to properly instantiate a VCR_CallTrackingRepo');
            Test.stopTest();
        }
    }

    /**
     * @description Test retrieving contact when given a list of ICNs positive
     */
    @IsTest
    static void funcGetCallTrackingListPositive() {
        User testUser = [SELECT Id FROM User WHERE FirstName = :USER_FIRST_NAME LIMIT 1];
        System.runAs(testUser) {
            Id testProgressNoteId = createTestData(true);
            Test.startTest();
            VCR_CallTrackingRepo callTrackingRepo = new VCR_CallTrackingRepo();
            List<VCC_Call_Tracking__c> results = callTrackingRepo.fetchCallTrackingList(testProgressNoteId);
            Assert.areEqual(1, results.size(), 'Expected to receive one record but returned: ' + results.size());
            Test.stopTest();
        }
    }

    /**
     * @description Test retrieving contact when given a list of ICNs positive
     */
    @IsTest
    static void funcGetCallTrackingListNegative() {
        User testUser = [SELECT Id FROM User WHERE FirstName = :USER_FIRST_NAME LIMIT 1];
        System.runAs(testUser) {
            Id testProgressNoteId = createTestData(false);
            Test.startTest();
            VCR_CallTrackingRepo callTrackingRepo = new VCR_CallTrackingRepo();
            List<VCC_Call_Tracking__c> results = callTrackingRepo.fetchCallTrackingList(testProgressNoteId);
            Assert.areEqual(0, results.size(), 'Expected to receive no records but observed: ' + results.size());
            Test.stopTest();
        }
    }
}