force-app/main/default/objects/Case/fields/VCC_Caller_Name__c.field-meta.xml
<CustomField>
    <fullName>VCC_Caller_Name__c</fullName>
    <description>The name of the caller if the the Caller Relation to Veteran is not &quot;Self&quot;. Populated via the Verify Caller process.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The name of the caller if the the Caller Relation to Veteran is not &quot;Self&quot;. Populated via the Verify Caller process.</inlineHelpText>
    <label>Caller Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/Case/fields/VCC_Caller_Relation__c.field-meta.xml
<CustomField>
    <fullName>VCC_Caller_Relation__c</fullName>
    <description>Identifies the relationship of the Caller to the Patient</description>
    <inlineHelpText>Identifies the relationship of the Caller to the Patient. Populated via the Verify Patient process.</inlineHelpText>
    <label>Caller/Recipient Relation to Patient</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Self</fullName>
            </value>
            <value>
                <fullName>Caregiver</fullName>
            </value>
            <value>
                <fullName>Power of Attorney</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Anonymous</fullName>
                <isActive>false</isActive>
                <label>Anonymous</label>
            </value>
            <value>
                <fullName>Aunt</fullName>
                <isActive>false</isActive>
                <label>Aunt</label>
            </value>
            <value>
                <fullName>Daughter</fullName>
                <isActive>false</isActive>
                <label>Daughter</label>
            </value>
            <value>
                <fullName>Father</fullName>
                <isActive>false</isActive>
                <label>Father</label>
            </value>
            <value>
                <fullName>Home Health</fullName>
                <isActive>false</isActive>
                <label>Home Health</label>
            </value>
            <value>
                <fullName>Internal Review Only</fullName>
                <isActive>false</isActive>
                <label>Internal Review Only</label>
            </value>
            <value>
                <fullName>Mother</fullName>
                <isActive>false</isActive>
                <label>Mother</label>
            </value>
            <value>
                <fullName>Neighbor</fullName>
                <isActive>false</isActive>
                <label>Neighbor</label>
            </value>
            <value>
                <fullName>Psychiatrist</fullName>
                <isActive>false</isActive>
                <label>Psychiatrist</label>
            </value>
            <value>
                <fullName>Relative</fullName>
                <isActive>false</isActive>
                <label>Relative</label>
            </value>
            <value>
                <fullName>Sibling</fullName>
                <isActive>false</isActive>
                <label>Sibling</label>
            </value>
            <value>
                <fullName>Son</fullName>
                <isActive>false</isActive>
                <label>Son</label>
            </value>
            <value>
                <fullName>Spouse</fullName>
                <isActive>false</isActive>
                <label>Spouse</label>
            </value>
            <value>
                <fullName>Uncle</fullName>
                <isActive>false</isActive>
                <label>Uncle</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/Case/fields/VCC_Patient_Stated_Symptoms__c.field-meta.xml
<CustomField>
    <fullName>VCC_Patient_Stated_Symptoms__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Patient Stated Symptoms</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/main/default/objects/Case/fields/VCC_Progress_Note__c.field-meta.xml
<CustomField>
    <fullName>VCC_Progress_Note__c</fullName>
    <description>Check true if there are any Progress Notes, related to the case.</description>
    <formula>IF( VCC_Progress_Notes_Count__c &gt; 0, TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Check true if there are any Progress Notes, related to the case.</inlineHelpText>
    <label>Progress Note</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/Case/fields/VCC_Relation_Type_Other__c.field-meta.xml
<CustomField>
    <fullName>VCC_Relation_Type_Other__c</fullName>
    <description>Identifies the relationship type of Caller, if not listed in the Caller Relation to Veteran. Populated via the Verify Caller flow.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>If Caller Relation to Veteran is Other, describe caller relation to Veteran. Populated via the Verify Caller process.</inlineHelpText>
    <label>Relation Type (if Other)</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/VCC_Progress_Note__c.object-meta.xml
<CustomObject>
    <description>Progress Notes</description>
    <label>Progress Note</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>Progress Note</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Additional_Comments__c.field-meta.xml
<CustomField>
    <fullName>VCC_Additional_Comments__c</fullName>
    <description>Used to add any additional comments about lost medication</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter any additional comments about lost medication</inlineHelpText>
    <label>Additional Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Caller_Name__c.field-meta.xml
<CustomField>
    <fullName>VCC_Caller_Name__c</fullName>
    <description>If caller is not veteran, name of caller, populated from case.</description>
    <formula>VCC_Case__r.VCC_Caller_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>If caller is not veteran, name of caller, populated from case.</inlineHelpText>
    <label>Caller Name</label>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Case__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case__c</fullName>
    <description>Parent Case for Progress Note</description>
    <inlineHelpText>Case related to Progress Note on the patient record.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Progress Notes</relationshipLabel>
    <relationshipName>Progress_Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Chief_Complaint__c.field-meta.xml
<CustomField>
    <fullName>VCC_Chief_Complaint__c</fullName>
    <description>Primary reason for patient’s call.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Primary reason for patient’s call.</inlineHelpText>
    <label>Chief Complaint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note__c/fields/VCC_Comments_patient_in_crisis__c.field-meta.xml
<CustomField>
    <fullName>VCC_Comments_patient_in_crisis__c</fullName>
    <description>Enter comments related to the patient that is in crisis</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter comments related to the patient in crisis</inlineHelpText>
    <label>Comments - Patient in crisis</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note__c/fields/VCC_Patient_Stated_Symptoms__c.field-meta.xml
<CustomField>
    <fullName>VCC_Patient_Stated_Symptoms__c</fullName>
    <description>Description of what the patient&apos;s symptoms are, according to the patient</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Patient Stated Symptoms</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note__c/recordTypes/VCC_Clinical_Triage_Note_Progress_Note.recordType-meta.xml
<RecordType>
    <fullName>VCC_Clinical_Triage_Note_Progress_Note</fullName>
    <active>true</active>
    <description>Holds the fields for the Clinical Triage Progress Note</description>
    <label>Clinical Triage Progress Note</label>
</RecordType>

sfdx-source/main/default/classes/VCC/VCC_ProgressNoteDomainTest.cls
@isTest
public with sharing class VCC_ProgressNoteDomainTest {
    @TestSetup
    static void makeData() {
        VCC_TestDataFactory.insertUser('System Administrator');

        User testUser = TestUtility.buildTestUserByFirstAndLastName('firstName', 'lastName');
        insert testUser;

        Account testAcct = TestUtility.createAccount('Account A');
        insert testAcct;

        Contact cont = TestUtility.createContact(testUser.Id, 'lastName', testAcct.Id);
        insert cont;

        Case testCase = new Case(
            RecordTypeId = Case.SObjectType.getDescribe(SObjectDescribeOptions.FULL).getRecordTypeInfosByName().get('Clinical Triage Case').getRecordTypeId(),
            VCC_Caller_Relation__c = 'Self'
        );
        if (Case.SObjectType.getDescribe(SObjectDescribeOptions.FULL).isCreateable()) {
            insert testCase;
        }

        insert new VCC_Progress_Note__c(
            VCC_Additional_Comments__c = 'Some additional comment.',
            VCC_Comments_patient_in_crisis__c = 'some long string that will be longer than 80 characters long to demonstrate the line breaking',
            VCC_Case__c = testCase.Id,
            RecordTypeId = Schema.SObjectType.VCC_Progress_Note__c.getRecordTypeInfosByDeveloperName().get('VCC_Clinical_Triage_Note_Progress_Note').getRecordTypeId()
        );
    }
    /**
     * @description create a test user for running tests
     * @return A test user
     **/
    public static User getTestUser() {
        return [SELECT Id FROM User WHERE LastName = 'Testing' LIMIT 1];
    }

    @IsTest
    static void charLimitErrorTest() {
        System.runAs(getTestUser()) {
            VCC_Progress_Note__c progNote = [SELECT Id FROM VCC_Progress_Note__c LIMIT 1];
            String str250 = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium.';

            progNote.VCC_Chief_Complaint__c = str250 + 'abcde';
            progNote.VCC_Patient_Stated_Symptoms__c = str250 + str250 + str250 + str250;

            Test.startTest();
            try {
                update progNote;
            } catch (Exception e) {
                Assert.isTrue(e.getMessage().contains('Chief_Complaint'), 'Expected Error to be thrown');
            }
            Test.stopTest();
        }
    }

    @IsTest
    static void newProgressNoteTest() {
        System.runAs(getTestUser()) {
            Case caseSample = [SELECT Id, VCC_Caller_Relation__c, VCC_Relation_Type_Other__c, VCC_Caller_Name__c FROM Case LIMIT 1];
            Test.startTest();
            VCC_ProgressNoteDomain progNoteDomain = new VCC_ProgressNoteDomain();
            VCC_Progress_Note__c progNote = progNoteDomain.newProgressNote(
                'progNoteString',
                true,
                false,
                caseSample,
                VCC_Progress_Note__c.SObjectType.getDescribe(SObjectDescribeOptions.DEFERRED)
                    .getRecordTypeInfosByDeveloperName()
                    .get('VCC_Clinical_Triage_Note_Progress_Note')
                    .getRecordTypeId(),
                'a test facility'
            );
            Test.stopTest();
            Assert.isNotNull(progNote, 'Expected Clinical Triage Progress Note to be created');
        }
    }
}