force-app/main/default/objects/Case/fields/VCC_Caller_Name__c.field-meta.xml
<CustomField>
    <fullName>VCC_Caller_Name__c</fullName>
    <description>The name of the caller if the the Caller Relation to Veteran is not &quot;Self&quot;. Populated via the Verify Caller process.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The name of the caller if the the Caller Relation to Veteran is not &quot;Self&quot;. Populated via the Verify Caller process.</inlineHelpText>
    <label>Caller Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/Case/fields/VCC_Caller_Relation__c.field-meta.xml
<CustomField>
    <fullName>VCC_Caller_Relation__c</fullName>
    <description>Identifies the relationship of the Caller to the Patient</description>
    <inlineHelpText>Identifies the relationship of the Caller to the Patient. Populated via the Verify Patient process.</inlineHelpText>
    <label>Caller/Recipient Relation to Patient</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Self</fullName>
            </value>
            <value>
                <fullName>Caregiver</fullName>
            </value>
            <value>
                <fullName>Power of Attorney</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Anonymous</fullName>
                <isActive>false</isActive>
                <label>Anonymous</label>
            </value>
            <value>
                <fullName>Aunt</fullName>
                <isActive>false</isActive>
                <label>Aunt</label>
            </value>
            <value>
                <fullName>Daughter</fullName>
                <isActive>false</isActive>
                <label>Daughter</label>
            </value>
            <value>
                <fullName>Father</fullName>
                <isActive>false</isActive>
                <label>Father</label>
            </value>
            <value>
                <fullName>Home Health</fullName>
                <isActive>false</isActive>
                <label>Home Health</label>
            </value>
            <value>
                <fullName>Internal Review Only</fullName>
                <isActive>false</isActive>
                <label>Internal Review Only</label>
            </value>
            <value>
                <fullName>Mother</fullName>
                <isActive>false</isActive>
                <label>Mother</label>
            </value>
            <value>
                <fullName>Neighbor</fullName>
                <isActive>false</isActive>
                <label>Neighbor</label>
            </value>
            <value>
                <fullName>Psychiatrist</fullName>
                <isActive>false</isActive>
                <label>Psychiatrist</label>
            </value>
            <value>
                <fullName>Relative</fullName>
                <isActive>false</isActive>
                <label>Relative</label>
            </value>
            <value>
                <fullName>Sibling</fullName>
                <isActive>false</isActive>
                <label>Sibling</label>
            </value>
            <value>
                <fullName>Son</fullName>
                <isActive>false</isActive>
                <label>Son</label>
            </value>
            <value>
                <fullName>Spouse</fullName>
                <isActive>false</isActive>
                <label>Spouse</label>
            </value>
            <value>
                <fullName>Uncle</fullName>
                <isActive>false</isActive>
                <label>Uncle</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/Case/fields/VCC_Case_Outcome_Multi__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case_Outcome_Multi__c</fullName>
    <description>Case outcome field used on the Administrative and Scheduling Case that allows MSAs to select multiple outcomes for why the case was created</description>
    <inlineHelpText>Action Completed for the Veteran</inlineHelpText>
    <label>Case Outcome</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processed Medication Refill</fullName>
            </value>
            <value>
                <fullName>Entered Progress Note</fullName>
            </value>
            <value>
                <fullName>Entered Unsigned Order</fullName>
            </value>
            <value>
                <fullName>Provided Medication Extension</fullName>
            </value>
            <value>
                <fullName>Provided Status of Rx</fullName>
            </value>
            <value>
                <fullName>Provided Medication Counseling</fullName>
            </value>
            <value>
                <fullName>Provided Requested Information</fullName>
            </value>
            <value>
                <fullName>Provided Bridge Supply</fullName>
            </value>
            <value>
                <fullName>Provider Care Coordination</fullName>
            </value>
            <value>
                <fullName>Adjudicated Retail Billing</fullName>
            </value>
            <value>
                <fullName>Processed Pending Order</fullName>
            </value>
            <value>
                <fullName>Processed Early Fill</fullName>
            </value>
            <value>
                <fullName>Notified Local Site</fullName>
            </value>
            <value>
                <fullName>Transferred to CCC Nurse</fullName>
            </value>
            <value>
                <fullName>Transferred to CCC Scheduling</fullName>
            </value>
            <value>
                <fullName>Transferred to Veterans Crisis Line</fullName>
            </value>
            <value>
                <fullName>Contacted Emergency Services</fullName>
            </value>
            <value>
                <fullName>Call Dropped - Could not Reconnect</fullName>
            </value>
            <value>
                <fullName>Caller Terminated</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Cannot Complete Scheduling Action</fullName>
            </value>
            <value>
                <fullName>Completed Scheduling Action</fullName>
            </value>
            <value>
                <fullName>Progress Note to PACT</fullName>
            </value>
            <value>
                <fullName>Refilled Medication</fullName>
            </value>
            <value>
                <fullName>Requested Medication Renewal</fullName>
            </value>
            <value>
                <fullName>Transferred Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/VCC_Case_Reason_Multi__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case_Reason_Multi__c</fullName>
    <description>Reason why patient is calling-Multiselect</description>
    <inlineHelpText>Reason why patient is calling</inlineHelpText>
    <label>Case Reason</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>VCC_Case_Sub_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Schedule Appointment</fullName>
            </value>
            <value>
                <fullName>Cancel Appointment</fullName>
            </value>
            <value>
                <fullName>Verify Appointment</fullName>
            </value>
            <value>
                <fullName>Request Call Back</fullName>
            </value>
            <value>
                <fullName>Benefits &amp; Enrollment</fullName>
            </value>
            <value>
                <fullName>Community Care/ Mission Act</fullName>
            </value>
            <value>
                <fullName>Consult Request</fullName>
            </value>
            <value>
                <fullName>Death Notification</fullName>
            </value>
            <value>
                <fullName>Home Health/Nursing Home</fullName>
            </value>
            <value>
                <fullName>Lab/ Imaging Result</fullName>
            </value>
            <value>
                <fullName>Medical Equipment Request</fullName>
            </value>
            <value>
                <fullName>Medication Refill/Renewal</fullName>
            </value>
            <value>
                <fullName>Outside Care Performed</fullName>
            </value>
            <value>
                <fullName>Paperwork Request</fullName>
            </value>
            <value>
                <fullName>Update Demographic</fullName>
            </value>
            <value>
                <fullName>Dropped Call</fullName>
            </value>
            <value>
                <fullName>Returned Call</fullName>
            </value>
            <value>
                <fullName>Medication Refill</fullName>
            </value>
            <value>
                <fullName>Medication Renewal</fullName>
            </value>
            <value>
                <fullName>Prescription Status</fullName>
            </value>
            <value>
                <fullName>Prescription Tracking</fullName>
            </value>
            <value>
                <fullName>Facility Information</fullName>
            </value>
            <value>
                <fullName>Community Care Information</fullName>
            </value>
            <value>
                <fullName>Urgent First Fill Issues</fullName>
            </value>
            <value>
                <fullName>Med List Reconciliation</fullName>
            </value>
            <value>
                <fullName>Mission Act Information</fullName>
            </value>
            <value>
                <fullName>Clinical Question(s)</fullName>
            </value>
            <value>
                <fullName>Medication Recall</fullName>
            </value>
            <value>
                <fullName>Side Effect/ADR</fullName>
            </value>
            <value>
                <fullName>Crisis Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/VCC_Pharmacy.recordType-meta.xml
<RecordType>
    <fullName>VCC_Pharmacy</fullName>
    <active>true</active>
    <businessProcess>VCC Support Process</businessProcess>
    <description>--VA Health Connect medication and prescription cases</description>
    <label>Pharmacy Case</label>
</RecordType>

sfdx-source/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

sfdx-source/main/default/classes/VCC/VCC_CaseDomainTest.cls
/**
 * @description       : Test class for VCC_CaseDomain
 * @author            : Booz Allen Hamilton
 * @date              : 12/2024
 **/
@IsTest
private with sharing class VCC_CaseDomainTest {
    /**
     * @description creates test Pharm user
     */
    @TestSetup
    static void makeData() {
        new VATEST_UserBuilder()
            .withUserProfile('VAVET Base Profile')
            .withPermissionSets(new Set<String>{ 'VAHC_Standard_VCC_User', 'VCC_Pharmacy_I', 'HealthCloudFoundation' })
            .withStandardData()
            .build(true);
    }

    /**
     * @description gets test pharm user
     * @return A test pharm user
     */
    public static User getTestPharmUser() {
        return [
            SELECT Id, Title
            FROM User
            WHERE Email LIKE 'Testuser@test.example.com%'
            LIMIT 1
        ];
    }

    /**
     * @description test run of constructor positive
     */
    @IsTest
    private static void unitConstructPositive() {
        System.runAs(getTestPharmUser()) {
            Test.startTest();
            VCC_CaseDomain casedomain = new VCC_CaseDomain();
            Test.stopTest();

            Assert.isNotNull(casedomain, 'Expected the class to be initialized.');
        }
    }

    /**
     * @description tests the init of refill description layout positive
     */
    @IsTest
    private static void unitRefillDescriptionLayoutPositive() {
        System.runAs(getTestPharmUser()) {
            Test.startTest();
            VCC_CaseDomain.RefillDescriptionLayout refillDescriptionLayout = new VCC_CaseDomain.RefillDescriptionLayout();
            Test.stopTest();

            Assert.isNotNull(refillDescriptionLayout, 'Expected class to be initialized.');
            Assert.isTrue(refillDescriptionLayout.success, 'Expected property to be initialized.');
        }
    }

    /**
     * @description test for creating medication refill case to have Pharm user values positive
     */
    @IsTest
    private static void funcCreateMedicationRefillCaseAsPharmUserPositive() {
        Case testCase;
        System.runAs(getTestPharmUser()) {
            Account testAccount = (Account) VATEST_SObjectFactory.createSObject(
                new Account(
                    RecordTypeId = new VCR_AccountRepo().recordTypeConstant.fromDeveloperName('PersonAccount').Id
                ),
                true
            );
            Test.startTest();
            testCase = new VCC_CaseDomain().createMedicationRefillCase(testAccount, 1, true);
            Test.stopTest();
        }

        Assert.isNotNull(testCase, 'Expected a new case to be created.');
        Assert.areEqual(
            'Pharmacy',
            testCase.Type,
            'Expected a new case to be an Admin type but was not: ' + testCase.Type
        );
        Assert.areEqual(
            'Medication Refill',
            testCase.VCC_Case_Reason_Multi__c,
            'Expected case reason to be Medication Refill but was not: ' + testCase.VCC_Case_Reason_Multi__c
        );
        Assert.areEqual(
            'Processed Medication Refill',
            testCase.VCC_Case_Outcome_Multi__c,
            'Expected case outcome to be Processed Medication Refill but was not: ' + testCase.VCC_Case_Outcome_Multi__c
        );
    }

    /**
     * @description test for creating medication refill case to have MSA user values positive
     */
    @IsTest
    private static void funcCreateMedicationRefillCaseAsMSAUserPositive() {
        User testUser = new VATEST_UserBuilder()
            .withUserProfile('VAVET Base Profile')
            .withPermissionSets(new Set<String>{ 'VCC_Advanced_Medical_Support_Assistant', 'HealthCloudFoundation' })
            .withStandardData()
            .build(true);
        Case testCase;
        System.runAs(testUser) {
            Account testAccount = (Account) VATEST_SObjectFactory.createSObject(
                new Account(
                    RecordTypeId = new VCR_AccountRepo().recordTypeConstant.fromDeveloperName('PersonAccount').Id
                ),
                true
            );
            Test.startTest();
            testCase = new VCC_CaseDomain().createMedicationRefillCase(testAccount, 1, true);
            Test.stopTest();
        }
        Assert.isNotNull(testCase, 'Expected a new case to be created.');
        Assert.areEqual(
            'Administrative',
            testCase.Type,
            'Expected a new case to be a Admin type but was not: ' + testCase.Type
        );
        Assert.areEqual(
            'Medication Refill/Renewal',
            testCase.VCC_Case_Reason_Multi__c,
            'Expected case reason to be Medication Refill/Renewal but was not: ' + testCase.VCC_Case_Reason_Multi__c
        );
        Assert.areEqual(
            'Refilled Medication',
            testCase.VCC_Case_Outcome_Multi__c,
            'Expected case outcome to be Refill Medication but was not: ' + testCase.VCC_Case_Outcome_Multi__c
        );
    }

    /**
     * @description Tests the setting of case description when the response is of a failure, negative
     */
    @IsTest
    private static void unitSetMedicationRefillDescriptionNegative() {
        Account testAccount = (Account) VATEST_SObjectFactory.createSObject(
            new Account(RecordTypeId = new VCR_AccountRepo().recordTypeConstant.fromDeveloperName('PersonAccount').Id),
            true
        );
        Case testCase = (Case) VATEST_SObjectFactory.createSObject(
            new Case(
                RecordTypeId = new VCR_CaseRepo().recordTypeConstant.fromDeveloperName('VCC_Pharmacy').Id,
                Subject = 'VCC_CaseDomainTestTest',
                AccountId = testAccount.Id,
                VCC_Caller_Relation__c = 'Self',
                VCC_Caller_Name__c = 'Unit Test'
            ),
            true
        );

        VCC_DivaClient.ResponseJSON responseJSON = new VCC_DivaClient.ResponseJSON();
        responseJSON.prescriptionId = 'fakeId';
        responseJSON.success = false;
        responseJSON.message = 'Fail response';
        List<VCC_DivaClient.ResponseJSON> responseJSONs = new List<VCC_DivaClient.ResponseJSON>{ responseJSON };

        VCC_MedsService.MedRefillRequest medRefillRequest = new VCC_MedsService.MedRefillRequest();
        medRefillRequest.prescriptionId = 'fakeId';
        List<VCC_MedsService.MedRefillRequest> medRefillRequests = new List<VCC_MedsService.MedRefillRequest>{
            medRefillRequest
        };
        System.runAs(getTestPharmUser()) {
            Test.startTest();
            new VCC_CaseDomain().setMedicationRefillDescription(testCase, responseJSONs, medRefillRequests);
            Test.stopTest();
        }

        Assert.isTrue(
            testCase.description.contains('Fail response'),
            'Expected to have failure in description of case but did not'
        );
    }
}