force-app/main/default/objects/Case/fields/VCC_Case_Outcome__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case_Outcome__c</fullName>
    <description>Specify the Outcome of the Case</description>
    <inlineHelpText>Specify the Outcome of the Case</inlineHelpText>
    <label>Case Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>911</fullName>
            </value>
            <value>
                <fullName>Call Dropped/Not Resolved</fullName>
            </value>
            <value>
                <fullName>Call Dropped - Could not Reconnect</fullName>
            </value>
            <value>
                <fullName>CCC VCV No Follow-Up Needed</fullName>
            </value>
            <value>
                <fullName>CCC Virtual Clinic Visit</fullName>
            </value>
            <value>
                <fullName>Consult to CCC Pharmacist</fullName>
            </value>
            <value>
                <fullName>Consult to Local Pharmacy</fullName>
            </value>
            <value>
                <fullName>Diagnostics Ordered</fullName>
            </value>
            <value>
                <fullName>Emergency Dept</fullName>
            </value>
            <value>
                <fullName>Follow Up PACT/VAMC</fullName>
            </value>
            <value>
                <fullName>Lead Pharmacy Technician Resolved</fullName>
            </value>
            <value>
                <fullName>Mental Health</fullName>
            </value>
            <value>
                <fullName>Message Sent/ Progress Note</fullName>
            </value>
            <value>
                <fullName>MSA/Scheduling</fullName>
            </value>
            <value>
                <fullName>No Answer Message Left</fullName>
            </value>
            <value>
                <fullName>PACT Team</fullName>
            </value>
            <value>
                <fullName>Patient Stayed Home</fullName>
            </value>
            <value>
                <fullName>Patient was No Show (No Welfare check)</fullName>
            </value>
            <value>
                <fullName>Patient was No Show (Welfare check requested)</fullName>
            </value>
            <value>
                <fullName>Pharmacist Resolved</fullName>
            </value>
            <value>
                <fullName>Pharmacy</fullName>
            </value>
            <value>
                <fullName>Pharmacy Technician Resolved</fullName>
            </value>
            <value>
                <fullName>PN to Clinician</fullName>
            </value>
            <value>
                <fullName>PN to Team</fullName>
            </value>
            <value>
                <fullName>Prescription Ordered</fullName>
            </value>
            <value>
                <fullName>Primary Care</fullName>
            </value>
            <value>
                <fullName>Primary Care/PACT</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Refilled Medication</fullName>
            </value>
            <value>
                <fullName>Renewed Medication</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/VCC_Case_Reason_Multi__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case_Reason_Multi__c</fullName>
    <description>Reason why patient is calling-Multiselect</description>
    <inlineHelpText>Reason why patient is calling</inlineHelpText>
    <label>Case Reason</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>VCC_Case_Sub_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Schedule Appointment</fullName>
            </value>
            <value>
                <fullName>Cancel Appointment</fullName>
            </value>
            <value>
                <fullName>Verify Appointment</fullName>
            </value>
            <value>
                <fullName>Request Call Back</fullName>
            </value>
            <value>
                <fullName>Benefits &amp; Enrollment</fullName>
            </value>
            <value>
                <fullName>Community Care/ Mission Act</fullName>
            </value>
            <value>
                <fullName>Consult Request</fullName>
            </value>
            <value>
                <fullName>Death Notification</fullName>
            </value>
            <value>
                <fullName>Home Health/Nursing Home</fullName>
            </value>
            <value>
                <fullName>Lab/ Imaging Result</fullName>
            </value>
            <value>
                <fullName>Medical Equipment Request</fullName>
            </value>
            <value>
                <fullName>Medication Refill/Renewal</fullName>
            </value>
            <value>
                <fullName>Outside Care Performed</fullName>
            </value>
            <value>
                <fullName>Paperwork Request</fullName>
            </value>
            <value>
                <fullName>Update Demographic</fullName>
            </value>
            <value>
                <fullName>Dropped Call</fullName>
            </value>
            <value>
                <fullName>Returned Call</fullName>
            </value>
            <value>
                <fullName>Medication Refill</fullName>
            </value>
            <value>
                <fullName>Medication Renewal</fullName>
            </value>
            <value>
                <fullName>Prescription Status</fullName>
            </value>
            <value>
                <fullName>Prescription Tracking</fullName>
            </value>
            <value>
                <fullName>Facility Information</fullName>
            </value>
            <value>
                <fullName>Community Care Information</fullName>
            </value>
            <value>
                <fullName>Urgent First Fill Issues</fullName>
            </value>
            <value>
                <fullName>Med List Reconciliation</fullName>
            </value>
            <value>
                <fullName>Mission Act Information</fullName>
            </value>
            <value>
                <fullName>Clinical Question(s)</fullName>
            </value>
            <value>
                <fullName>Medication Recall</fullName>
            </value>
            <value>
                <fullName>Side Effect/ADR</fullName>
            </value>
            <value>
                <fullName>Crisis Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/VCC_Case_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case_Sub_Type__c</fullName>
    <description>Categorize the Case for reporting purposes.</description>
    <inlineHelpText>Categorize the Case for reporting purposes.</inlineHelpText>
    <label>Case Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>VCC_Case_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrative</fullName>
            </value>
            <value>
                <fullName>Community Care</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Emergent</fullName>
            </value>
            <value>
                <fullName>Medication Status</fullName>
            </value>
            <value>
                <fullName>Non-Emergent</fullName>
            </value>
            <value>
                <fullName>Telephone Virtual Visit</fullName>
                <label>Phone</label>
            </value>
            <value>
                <fullName>Refill Medication</fullName>
            </value>
            <value>
                <fullName>Renew Medication</fullName>
            </value>
            <value>
                <fullName>Scheduling</fullName>
            </value>
            <value>
                <fullName>Triage</fullName>
            </value>
            <value>
                <fullName>Urgent</fullName>
            </value>
            <value>
                <fullName>Urgent First Fill</fullName>
            </value>
            <value>
                <fullName>Video Virtual Visit</fullName>
                <label>Video</label>
            </value>
            <value>
                <fullName>PHR VCV</fullName>
            </value>
            <value>
                <fullName>Administrative and Scheduling</fullName>
                <label>Scheduling and Administrative</label>
            </value>
            <value>
                <fullName>Pharmacy</fullName>
            </value>
            <value>
                <fullName>Pharmacy Quality Assurance Issue</fullName>
            </value>
            <value>
                <fullName>Medication Error</fullName>
                <isActive>false</isActive>
                <label>Medication Error</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/VCC_Case_Type__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case_Type__c</fullName>
    <description>Type of Case the caller is calling about</description>
    <inlineHelpText>Type of Case the caller is calling about</inlineHelpText>
    <label>Case Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrative</fullName>
            </value>
            <value>
                <fullName>Pharmacy</fullName>
            </value>
            <value>
                <fullName>Symptom</fullName>
            </value>
            <value>
                <fullName>VCV</fullName>
            </value>
            <value>
                <fullName>Tele-Emergency Care</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/Case/fields/VCC_Progress_Note__c.field-meta.xml
<CustomField>
    <fullName>VCC_Progress_Note__c</fullName>
    <description>Check true if there are any Progress Notes, related to the case.</description>
    <formula>IF( VCC_Progress_Notes_Count__c &gt; 0, TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Check true if there are any Progress Notes, related to the case.</inlineHelpText>
    <label>Progress Note</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/Case/fields/VISN__c.field-meta.xml
<CustomField>
    <fullName>VISN__c</fullName>
    <description>VCC Case - Before Upsert populates this field with the value in the Division field based on the user that created the case.</description>
    <label>VISN</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>VISN</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/Case/recordTypes/VCC_Clinical_Triage.recordType-meta.xml
<RecordType>
    <fullName>VCC_Clinical_Triage</fullName>
    <active>true</active>
    <businessProcess>VCC Support Process</businessProcess>
    <description>--VA Health Connect nursing and symptom cases</description>
    <label>Clinical Triage Case</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/VCC_Pharmacy.recordType-meta.xml
<RecordType>
    <fullName>VCC_Pharmacy</fullName>
    <active>true</active>
    <businessProcess>VCC Support Process</businessProcess>
    <description>--VA Health Connect medication and prescription cases</description>
    <label>Pharmacy Case</label>
</RecordType>

sfdx-source/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

sfdx-source/main/default/objects/Task/recordTypes/VCC_Pharmacy_FRR.recordType-meta.xml
<RecordType>
    <fullName>VCC_Pharmacy_FRR</fullName>
    <active>true</active>
    <description>Stores facility specific medications to be requested for renewal at a date in the future.</description>
    <label>VAHC Pharmacy Renewal Request</label>
</RecordType>

sfdx-source/main/default/objects/VCC_Progress_Note__c/VCC_Progress_Note__c.object-meta.xml
<CustomObject>
    <description>Progress Notes</description>
    <label>Progress Note</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>Progress Note</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Case__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case__c</fullName>
    <description>Parent Case for Progress Note</description>
    <inlineHelpText>Case related to Progress Note on the patient record.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Progress Notes</relationshipLabel>
    <relationshipName>Progress_Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note__c/fields/VISN__c.field-meta.xml
<CustomField>
    <fullName>VISN__c</fullName>
    <defaultValue>IF( $User.Division = &quot;VISN8&quot;,&quot;V8-CCC&quot;, &quot;&quot;)</defaultValue>
    <description>Used to select the VISN the PN is related to</description>
    <label>VISN</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>V1-CCC</fullName>
            </value>
            <value>
                <fullName>V2-CCC</fullName>
            </value>
            <value>
                <fullName>V4-CCC</fullName>
            </value>
            <value>
                <fullName>V5-CCC</fullName>
            </value>
            <value>
                <fullName>V6-CCC</fullName>
            </value>
            <value>
                <fullName>V7-CCC</fullName>
            </value>
            <value>
                <fullName>V8-CCC</fullName>
            </value>
            <value>
                <fullName>V9-CCC</fullName>
            </value>
            <value>
                <fullName>V10-CCC</fullName>
            </value>
            <value>
                <fullName>V12-CCC</fullName>
            </value>
            <value>
                <fullName>V15-CCC</fullName>
            </value>
            <value>
                <fullName>V16-CCC</fullName>
            </value>
            <value>
                <fullName>V17-CCC</fullName>
            </value>
            <value>
                <fullName>V19-CCC</fullName>
            </value>
            <value>
                <fullName>V20-CCC</fullName>
            </value>
            <value>
                <fullName>V21-CCC</fullName>
            </value>
            <value>
                <fullName>V22-CCC</fullName>
            </value>
            <value>
                <fullName>V23-CCC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note__c/recordTypes/VCC_Clinical_Triage_Note_Progress_Note.recordType-meta.xml
<RecordType>
    <fullName>VCC_Clinical_Triage_Note_Progress_Note</fullName>
    <active>true</active>
    <description>Holds the fields for the Clinical Triage Progress Note</description>
    <label>Clinical Triage Progress Note</label>
</RecordType>

force-app/main/default/objects/VCC_Progress_Note_Configuration__mdt/VCC_Progress_Note_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>Used for identifying what Attributes belong to a particular Progress Note or Addendum Type.</description>
    <label>VCC Progress Note Configuration</label>
    <pluralLabel>Progress Note Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/VISN__c/VISN__c.object-meta.xml
<CustomObject>
    <label>VISN</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>VISN Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VISNs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/main/default/globalValueSets/VISN.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>VISN 0</fullName>
    </customValue>
    <customValue>
        <fullName>VISN 1</fullName>
    </customValue>
    <customValue>
        <fullName>VISN 2</fullName>
    </customValue>
    <customValue>
        <fullName>VISN 4</fullName>
    </customValue>
    <customValue>
        <fullName>VISN 5</fullName>
    </customValue>
    <customValue>
        <fullName>VISN 6</fullName>
    </customValue>
    <customValue>
        <fullName>VISN 7</fullName>
    </customValue>
    <customValue>
        <fullName>VISN 8</fullName>
    </customValue>
    <customValue>
        <fullName>VISN 9</fullName>
    </customValue>
    <customValue>
        <fullName>VISN 10</fullName>
    </customValue>
    <customValue>
        <fullName>VISN 12</fullName>
    </customValue>
    <customValue>
        <fullName>VISN 15</fullName>
    </customValue>
    <customValue>
        <fullName>VISN 16</fullName>
    </customValue>
    <customValue>
        <fullName>VISN 17</fullName>
    </customValue>
    <customValue>
        <fullName>VISN 19</fullName>
    </customValue>
    <customValue>
        <fullName>VISN 20</fullName>
    </customValue>
    <customValue>
        <fullName>VISN 21</fullName>
    </customValue>
    <customValue>
        <fullName>VISN 22</fullName>
    </customValue>
    <customValue>
        <fullName>VISN 23</fullName>
    </customValue>
    <customValue>
        <fullName>VISN 18</fullName>
        <isActive>false</isActive>
        <label>VISN 18</label>
    </customValue>
    <customValue>
        <fullName>VISN 14</fullName>
        <isActive>false</isActive>
        <label>VISN 14</label>
    </customValue>
    <customValue>
        <fullName>VISN 13</fullName>
        <isActive>false</isActive>
        <label>VISN 13</label>
    </customValue>
    <customValue>
        <fullName>VISN 11</fullName>
        <isActive>false</isActive>
        <label>VISN 11</label>
    </customValue>
    <customValue>
        <fullName>VISN 3</fullName>
        <isActive>false</isActive>
        <label>VISN 3</label>
    </customValue>
    <description>This is being created part of LEAF 808</description>
    <masterLabel>VISN</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/VCC/VCC_ProgressNoteServiceTest.cls
/**
 * @author Booz Allen
 * @date 12/2024
 * @description Test Class for the VCC_ProgressNoteServiceTest methods
 */
@isTest
public with sharing class VCC_ProgressNoteServiceTest {
    /**
     * @description creates test data including user, case, and progress note for testing
     */
    @TestSetup
    static void makeData() {
        User testUser = new VATEST_UserBuilder()
            .withUserProfile('VAVET Base Profile')
            .withPermissionSets(new Set<String>{ 'VAHC_Standard_VCC_User', 'VAHC_Write_Clinical_Triage_Progress_Note' })
            .withStandardData()
            .build(true);

        System.runAs(testUser) {
            Case testCase = (Case) VATEST_SObjectFactory.createSObject(
                new Case(
                    RecordTypeId = new VCR_CaseRepo().recordTypeConstant.fromDeveloperName('VCC_Clinical_Triage').Id
                ),
                true
            );

            VATEST_SObjectFactory.createSObject(
                new VCC_Progress_Note__c(
                    VCC_Case__c = testCase.Id,
                    RecordTypeId = new VCR_ProgressNoteRepo()
                        .recordTypeConstant.fromDeveloperName('VCC_Clinical_Triage_Note_Progress_Note')
                        .Id
                ),
                true
            );
        }
    }

    /**
     * @description create a test user for running tests
     * @return A test user
     */
    public static User getTestUser() {
        return [
            SELECT Id, Title
            FROM User
            WHERE Email LIKE 'Testuser@test.example.com%'
            LIMIT 1
        ];
    }

    /**
     * @description test retrieving the progress note layout positive
     */
    @isTest
    public static void funcGetLayoutByNamePositive() {
        System.runAs(getTestUser()) {
            Metadata.Layout layout;
            Test.startTest();
            layout = VCC_ProgressNoteService.getLayoutByName('VCC Virtual Visit Progress Note');
            Test.stopTest();

            Assert.isNotNull(layout, 'Expected Metadata.Layout, got null');
        }
    }

    /**
     * @description test retrieving config when record type id is not present positive
     */
    @isTest
    public static void funcGetConfigWithoutRecordTypeIdTestPositive() {
        System.runAs(getTestUser()) {
            VCC_Progress_Note__c progressNote = [
                SELECT Id
                FROM VCC_Progress_Note__c
                LIMIT 1
            ];

            VCC_Progress_Note_Configuration__mdt config;
            Test.startTest();
            config = VCC_ProgressNoteService.getConfig(progressNote);
            Test.stopTest();

            Assert.isNotNull(config, 'Expected VCC_Progress_Note_Configuration__mdt, got null');
        }
    }

    /**
     * @description test retrieving config when record type id is present positive
     */
    @isTest
    public static void funcGetConfigWithRecordTypeIdTestPositive() {
        System.runAs(getTestUser()) {
            VCC_Progress_Note__c progressNote = [
                SELECT Id, RecordTypeId
                FROM VCC_Progress_Note__c
                LIMIT 1
            ];

            VCC_Progress_Note_Configuration__mdt config;
            Test.startTest();
            config = VCC_ProgressNoteService.getConfig(progressNote);
            Test.stopTest();

            Assert.isNotNull(config, 'Expected VCC_Progress_Note_Configuration__mdt, got null');
        }
    }

    /**
     * @description test creating a progress note positive
     */
    @IsTest
    static void funcCreateProgressNotePositive() {
        PermissionSetGroup psgTierI = [
            SELECT Id, Status
            FROM PermissionSetGroup
            WHERE DeveloperName = 'VCC_Pharmacy_I'
        ];
        if (psgTierI.Status != 'Updated') {
            Test.calculatePermissionSetGroup(psgTierI.Id);
        }

        User frrUser = new VATEST_UserBuilder()
            .withUserProfile('VAVET Base Profile')
            .withPermissionSets(
                new Set<String>{ 'VCC_Pharmacy_I', 'VAHC_Access_Future_Renewal_Request', 'HealthCloudFoundation' }
            )
            .withStandardData()
            .build(true);

        System.runAs(frrUser) {
            Test.startTest();
            String testMviId = '1013429125V999999';
            // create and insert a new account, which also creates a contact
            Account testAccount = (Account) VATEST_SObjectFactory.createSObject(
                new Account(
                    RecordTypeId = new VCR_AccountRepo().recordTypeConstant.fromDeveloperName('PersonAccount').Id,
                    VCC_MVI_External_Id__pc = testMviId
                ),
                true
            );
            Contact testContact = new VCR_ContactRepo().getContactFromAccountId(testAccount.Id)[0];

            //Create a Pharmacy Case
            Case testCase = (Case) VATEST_SObjectFactory.createSObject(
                new Case(
                    RecordTypeId = new VCR_CaseRepo().recordTypeConstant.fromDeveloperName('VCC_Pharmacy').Id,
                    VCC_Case_Type__c = 'Pharmacy',
                    ContactId = testContact.Id,
                    Status = 'Pending Future Renewal Request',
                    VCC_Case_Sub_Type__c = 'Pharmacy',
                    VCC_Case_Reason_Multi__c = 'Medication Refill',
                    VCC_Case_Outcome__c = 'Pharmacist Resolved'
                ),
                true
            );

            Task tsk = (Task) VATEST_SObjectFactory.createSObject(
                new Task(
                    Subject = 'Test',
                    Description = 'test',
                    WhatId = testCase.Id,
                    WhoId = testCase.ContactId,
                    RecordTypeId = new VCR_TaskRepo().recordTypeConstant.fromDeveloperName('VCC_Pharmacy_FRR').Id,
                    VISN__c = 'VISN 8'
                ),
                true
            );

            String pnString = 'test';
            Boolean controlled = false;
            Boolean nonControlled = true;
            String recordId = tsk.Id;
            String newDescription = 'test';
            VCC_Progress_Note__c progressNote = new VCC_ProgressNoteService()
                .createProgressNote(pnString, controlled, nonControlled, recordId, newDescription, 'a test facility');
            Assert.isNotNull(progressNote, 'There was a problem creating a progress note');
            Test.stopTest();
        }
    }
}