force-app/main/default/objects/Case/fields/VCC_Case_Type__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case_Type__c</fullName>
    <description>Type of Case the caller is calling about</description>
    <inlineHelpText>Type of Case the caller is calling about</inlineHelpText>
    <label>Case Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrative</fullName>
            </value>
            <value>
                <fullName>Pharmacy</fullName>
            </value>
            <value>
                <fullName>Symptom</fullName>
            </value>
            <value>
                <fullName>VCV</fullName>
            </value>
            <value>
                <fullName>Tele-Emergency Care</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/Case/fields/VCC_Progress_Note__c.field-meta.xml
<CustomField>
    <fullName>VCC_Progress_Note__c</fullName>
    <description>Check true if there are any Progress Notes, related to the case.</description>
    <formula>IF( VCC_Progress_Notes_Count__c &gt; 0, TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Check true if there are any Progress Notes, related to the case.</inlineHelpText>
    <label>Progress Note</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/Case/recordTypes/VCC_Clinical_Triage.recordType-meta.xml
<RecordType>
    <fullName>VCC_Clinical_Triage</fullName>
    <active>true</active>
    <businessProcess>VCC Support Process</businessProcess>
    <description>--VA Health Connect nursing and symptom cases</description>
    <label>Clinical Triage Case</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/VCC_Pharmacy.recordType-meta.xml
<RecordType>
    <fullName>VCC_Pharmacy</fullName>
    <active>true</active>
    <businessProcess>VCC Support Process</businessProcess>
    <description>--VA Health Connect medication and prescription cases</description>
    <label>Pharmacy Case</label>
</RecordType>

sfdx-source/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

sfdx-source/main/default/objects/VCC_Addendum__c/VCC_Addendum__c.object-meta.xml
<CustomObject>
    <description>Contains the information regarding updates to a Progress Note</description>
    <label>Addendum</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Addendum Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addendums</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Addendum__c/fields/VCC_Addendum__c.field-meta.xml
<CustomField>
    <fullName>VCC_Addendum__c</fullName>
    <description>Addendum Description/Text</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Addendum Description/Text</inlineHelpText>
    <label>Addendum</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Addendum__c/fields/VCC_Related_Note__c.field-meta.xml
<CustomField>
    <fullName>VCC_Related_Note__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Progress Note that this Addendum is related to.</description>
    <inlineHelpText>The Progress Note that this Addendum is related to.</inlineHelpText>
    <label>Progress Note</label>
    <referenceTo>VCC_Progress_Note__c</referenceTo>
    <relationshipLabel>Addendums</relationshipLabel>
    <relationshipName>Addendums</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/VCC_Progress_Note__c.object-meta.xml
<CustomObject>
    <description>Progress Notes</description>
    <label>Progress Note</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>Progress Note</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Case__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case__c</fullName>
    <description>Parent Case for Progress Note</description>
    <inlineHelpText>Case related to Progress Note on the patient record.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Progress Notes</relationshipLabel>
    <relationshipName>Progress_Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/recordTypes/VCC_Tier_III_Progress_Note.recordType-meta.xml
<RecordType>
    <fullName>VCC_Tier_III_Progress_Note</fullName>
    <active>true</active>
    <description>Holds the fields for the Tier III Progress Note</description>
    <label>Tier III Progress Note</label>
</RecordType>

sfdx-source/main/default/classes/VCC/VCC_AddendumRelatedListControllerTest.cls
@IsTest
public with sharing class VCC_AddendumRelatedListControllerTest {
    private static String testMviId = '1013429125V999999';

    @TestSetup
    private static void makeData() {
        // get the record type id for Person Accounts
        Id rtId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();

        // create and insert a new account, which also creates a contact
        Account a = new Account(FirstName = 'Testly', LastName = 'Person Accounted', RecordTypeId = rtId, VCC_MVI_External_Id__pc = testMviId);
        insert a;

        Id caseRecTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('VCC_Pharmacy').getRecordTypeId();
        Id pnRecTypeId = Schema.SObjectType.VCC_Progress_Note__c.getRecordTypeInfosByDeveloperName().get('VCC_Tier_III_Progress_Note').getRecordTypeId();
        //Retreive contact created in testSetup to update the MVI External Id
        Contact con = [SELECT Id, VCC_MVI_External_Id__c FROM Contact LIMIT 1];
        //Set External Id to static variable
        con.VCC_MVI_External_Id__c = testMviId;
        update con;
        //Create Pharmacy Case
        Case c1 = new Case(RecordTypeId = caseRecTypeId, VCC_Case_Type__c = 'Pharmacy', ContactId = con.Id, Description = 'First');
        insert c1;
        //Create Pharmacy Progress Note
        VCC_Progress_Note__c pn = new VCC_Progress_Note__c(VCC_Case__c = c1.Id, RecordTypeId = pnRecTypeId);
        insert pn;
        //Addendums
        List<VCC_Addendum__c> addendumList = new List<VCC_Addendum__c>();
        Integer count = 0;
        for (Integer i = 0; i < 6; i++) {
            VCC_Addendum__c addendum = new VCC_Addendum__c(VCC_Related_Note__c = pn.Id, VCC_Addendum__c = 'Test text' + String.valueOf(count));
            addendumList.add(addendum);
            count++;
        }
        insert addendumList;

        Id caseRecTypeId2 = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('VCC_Clinical_Triage').getRecordTypeId();
        //Create Other Pharmacy Case
        Case c2 = new Case(RecordTypeId = caseRecTypeId2, VCC_Case_Type__c = 'Symptom', ContactId = con.Id, Description = 'No Progress Notes, No Addendums');
        insert c2;
    }

    @IsTest
    private static void requestDataFromCaseWithAddendums_Success() {
        User u = VCC_TestDataFactory.insertUser('Standard User');
        VCC_TestDataFactory.addPermSetGroupToUser('VCC_Registered_Nurse', u);
        VCC_TestDataFactory.assignPermissionSetByName(u, 'HealthCloudFoundation');

        Case c = [SELECT Id FROM Case WHERE VCC_Case_Type__c = 'Pharmacy' LIMIT 1];

        List<VCC_Addendum__c> addendums = new List<VCC_Addendum__c>();
        Exception caughtException;

        Test.startTest();
        System.runAs(u) {
            try {
                addendums = VCC_AddendumRelatedListController.getRelatedAddendums(c.Id);
            } catch (Exception e) {
                System.debug(LoggingLevel.ERROR, e.getMessage());
                System.debug(LoggingLevel.ERROR, e.getStackTraceString());
                caughtException = e;
            }
        }
        Test.stopTest();

        System.debug('results size: ' + addendums.size());

        System.assert(caughtException == null, 'An exception was thrown.');
        System.assert(addendums != null, 'Data not returned as expected.');
        System.assert(addendums.size() == 6, 'Expected 6 results.');
    }

    @IsTest
    private static void requestDataFromCaseWithNoAddendums_Success() {
        User u = VCC_TestDataFactory.insertUser('Standard User');
        VCC_TestDataFactory.addPermSetGroupToUser('VCC_Registered_Nurse', u);
        VCC_TestDataFactory.assignPermissionSetByName(u, 'HealthCloudFoundation');

        Case c = [SELECT Id FROM Case WHERE VCC_Case_Type__c = 'Symptom' LIMIT 1];

        List<VCC_Addendum__c> addendums = new List<VCC_Addendum__c>();
        Exception caughtException;

        Test.startTest();
        System.runAs(u) {
            try {
                addendums = VCC_AddendumRelatedListController.getRelatedAddendums(c.Id);
            } catch (Exception e) {
                System.debug(LoggingLevel.ERROR, e.getMessage());
                System.debug(LoggingLevel.ERROR, e.getStackTraceString());
                caughtException = e;
            }
        }
        Test.stopTest();

        System.debug('results size: ' + addendums.size());

        System.assert(caughtException == null, 'An exception was thrown.');
        System.assert(addendums != null, 'Data not returned as expected.');
        System.assert(addendums.size() == 0, 'Expected no results.');
    }

    @IsTest
    private static void requestDataUsingBadId_Failure() {
        User u = VCC_TestDataFactory.insertUser('Standard User');
        VCC_TestDataFactory.addPermSetGroupToUser('VCC_Registered_Nurse', u);
        VCC_TestDataFactory.assignPermissionSetByName(u, 'HealthCloudFoundation');

        Case c = [SELECT Id FROM Case LIMIT 1];

        List<VCC_Addendum__c> addendums = new List<VCC_Addendum__c>();
        Exception caughtException;

        Test.startTest();
        System.runAs(u) {
            try {
                addendums = VCC_AddendumRelatedListController.getRelatedAddendums('badId');
            } catch (Exception e) {
                System.debug(LoggingLevel.ERROR, e.getMessage());
                System.debug(LoggingLevel.ERROR, e.getStackTraceString());
                caughtException = e;
            }
        }
        Test.stopTest();

        System.debug('results size: ' + addendums.size());

        System.assert(caughtException != null, 'An exception was not thrown.');
        System.assert(addendums.size() < 1, 'Results returned.');
    }

    @IsTest
    private static void requestDataUsingIncorrectUserAccess_Failure() {
        User u = VCC_TestDataFactory.insertUser('Standard User');

        Case c = [SELECT Id FROM Case WHERE VCC_Case_Type__c = 'Pharmacy' LIMIT 1];

        List<VCC_Addendum__c> addendums = new List<VCC_Addendum__c>();
        Exception caughtException;

        Test.startTest();
        System.runAs(u) {
            try {
                addendums = VCC_AddendumRelatedListController.getRelatedAddendums(c.Id);
            } catch (Exception e) {
                System.debug(LoggingLevel.ERROR, e.getMessage());
                System.debug(LoggingLevel.ERROR, e.getStackTraceString());
                caughtException = e;
            }
        }
        Test.stopTest();

        System.debug('results size: ' + addendums.size());

        System.assert(caughtException != null, 'An exception was not thrown.');
        System.assert(addendums.size() < 1, 'Results returned.');
    }
}