force-app/main/default/objects/Case/fields/VCC_Caller_Name__c.field-meta.xml
<CustomField>
    <fullName>VCC_Caller_Name__c</fullName>
    <description>The name of the caller if the the Caller Relation to Veteran is not &quot;Self&quot;. Populated via the Verify Caller process.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The name of the caller if the the Caller Relation to Veteran is not &quot;Self&quot;. Populated via the Verify Caller process.</inlineHelpText>
    <label>Caller Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/Case/fields/VCC_Caller_Relation__c.field-meta.xml
<CustomField>
    <fullName>VCC_Caller_Relation__c</fullName>
    <description>Identifies the relationship of the Caller to the Patient</description>
    <inlineHelpText>Identifies the relationship of the Caller to the Patient. Populated via the Verify Patient process.</inlineHelpText>
    <label>Caller/Recipient Relation to Patient</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Self</fullName>
            </value>
            <value>
                <fullName>Caregiver</fullName>
            </value>
            <value>
                <fullName>Power of Attorney</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Anonymous</fullName>
                <isActive>false</isActive>
                <label>Anonymous</label>
            </value>
            <value>
                <fullName>Aunt</fullName>
                <isActive>false</isActive>
                <label>Aunt</label>
            </value>
            <value>
                <fullName>Daughter</fullName>
                <isActive>false</isActive>
                <label>Daughter</label>
            </value>
            <value>
                <fullName>Father</fullName>
                <isActive>false</isActive>
                <label>Father</label>
            </value>
            <value>
                <fullName>Home Health</fullName>
                <isActive>false</isActive>
                <label>Home Health</label>
            </value>
            <value>
                <fullName>Internal Review Only</fullName>
                <isActive>false</isActive>
                <label>Internal Review Only</label>
            </value>
            <value>
                <fullName>Mother</fullName>
                <isActive>false</isActive>
                <label>Mother</label>
            </value>
            <value>
                <fullName>Neighbor</fullName>
                <isActive>false</isActive>
                <label>Neighbor</label>
            </value>
            <value>
                <fullName>Psychiatrist</fullName>
                <isActive>false</isActive>
                <label>Psychiatrist</label>
            </value>
            <value>
                <fullName>Relative</fullName>
                <isActive>false</isActive>
                <label>Relative</label>
            </value>
            <value>
                <fullName>Sibling</fullName>
                <isActive>false</isActive>
                <label>Sibling</label>
            </value>
            <value>
                <fullName>Son</fullName>
                <isActive>false</isActive>
                <label>Son</label>
            </value>
            <value>
                <fullName>Spouse</fullName>
                <isActive>false</isActive>
                <label>Spouse</label>
            </value>
            <value>
                <fullName>Uncle</fullName>
                <isActive>false</isActive>
                <label>Uncle</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/Case/fields/VCC_Progress_Note__c.field-meta.xml
<CustomField>
    <fullName>VCC_Progress_Note__c</fullName>
    <description>Check true if there are any Progress Notes, related to the case.</description>
    <formula>IF( VCC_Progress_Notes_Count__c &gt; 0, TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Check true if there are any Progress Notes, related to the case.</inlineHelpText>
    <label>Progress Note</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/Case/fields/VCC_Relation_Type_Other__c.field-meta.xml
<CustomField>
    <fullName>VCC_Relation_Type_Other__c</fullName>
    <description>Identifies the relationship type of Caller, if not listed in the Caller Relation to Veteran. Populated via the Verify Caller flow.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>If Caller Relation to Veteran is Other, describe caller relation to Veteran. Populated via the Verify Caller process.</inlineHelpText>
    <label>Relation Type (if Other)</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/VCC_Progress_Note__c.object-meta.xml
<CustomObject>
    <description>Progress Notes</description>
    <label>Progress Note</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>Progress Note</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Caller_Name__c.field-meta.xml
<CustomField>
    <fullName>VCC_Caller_Name__c</fullName>
    <description>If caller is not veteran, name of caller, populated from case.</description>
    <formula>VCC_Case__r.VCC_Caller_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>If caller is not veteran, name of caller, populated from case.</inlineHelpText>
    <label>Caller Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note__c/fields/VCC_Caller_Name_Text__c.field-meta.xml
<CustomField>
    <fullName>VCC_Caller_Name_Text__c</fullName>
    <description>Caller Name is populated from the Phone Call/Case, if different from the Veteran.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Caller Name is populated from the Phone Call/Case, if different from the Veteran.</inlineHelpText>
    <label>Caller Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Case__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case__c</fullName>
    <description>Parent Case for Progress Note</description>
    <inlineHelpText>Case related to Progress Note on the patient record.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Progress Notes</relationshipLabel>
    <relationshipName>Progress_Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Controlled_medication__c.field-meta.xml
<CustomField>
    <fullName>VCC_Controlled_medication__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that the requested VA medication is a controlled substance</description>
    <inlineHelpText>Check if the requested VA medication is controlled substance. SUD Labs will auto populate on Save if selected.</inlineHelpText>
    <label>Controlled VA Medication</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Facility__c.field-meta.xml
<CustomField>
    <fullName>VCC_Facility__c</fullName>
    <description>This is the facility identifier for this progress note to drive facility enabled logic.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>VCC Facility</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_If_Other_Describe_Relation_Patient__c.field-meta.xml
<CustomField>
    <fullName>VCC_If_Other_Describe_Relation_Patient__c</fullName>
    <description>Identifies the relationship type of Caller, if not listed in the Caller Relation to Veteran.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>If Caller Relation to Veteran is Other, describe caller relation to Veteran.</inlineHelpText>
    <label>If Other Describe Relation to Patient</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Medication_Fill_Renewal__c.field-meta.xml
<CustomField>
    <fullName>VCC_Medication_Fill_Renewal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that the patient is calling about a medication renewal.</description>
    <inlineHelpText>Check if the patient is calling about a medication renewal.</inlineHelpText>
    <label>Medication Renewal</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Non_controlled_medication__c.field-meta.xml
<CustomField>
    <fullName>VCC_Non_controlled_medication__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that the requested VA medication is NOT a controlled substance</description>
    <inlineHelpText>Check if the requested VA medication is NOT a controlled substance</inlineHelpText>
    <label>Non-controlled VA Medication</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Relative_Type__c.field-meta.xml
<CustomField>
    <fullName>VCC_Relative_Type__c</fullName>
    <description>Relationship of Caller to Veteran. Populated from the Phone Call/Case via a Flow.</description>
    <inlineHelpText>Relationship of the Caller to the Veteran. This is populated from the Phone Call/Case, if captured.</inlineHelpText>
    <label>Caller/Recipient Relation to Patient</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Self</fullName>
            </value>
            <value>
                <fullName>Caregiver</fullName>
            </value>
            <value>
                <fullName>Power of Attorney</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Anonymous</fullName>
                <isActive>false</isActive>
                <label>Anonymous</label>
            </value>
            <value>
                <fullName>Aunt</fullName>
                <isActive>false</isActive>
                <label>Aunt</label>
            </value>
            <value>
                <fullName>Daughter</fullName>
                <isActive>false</isActive>
                <label>Daughter</label>
            </value>
            <value>
                <fullName>Father</fullName>
                <isActive>false</isActive>
                <label>Father</label>
            </value>
            <value>
                <fullName>Home Health</fullName>
                <isActive>false</isActive>
                <label>Home Health</label>
            </value>
            <value>
                <fullName>Mother</fullName>
                <isActive>false</isActive>
                <label>Mother</label>
            </value>
            <value>
                <fullName>Neighbor</fullName>
                <isActive>false</isActive>
                <label>Neighbor</label>
            </value>
            <value>
                <fullName>Sibling</fullName>
                <isActive>false</isActive>
                <label>Sibling</label>
            </value>
            <value>
                <fullName>Son</fullName>
                <isActive>false</isActive>
                <label>Son</label>
            </value>
            <value>
                <fullName>Spouse</fullName>
                <isActive>false</isActive>
                <label>Spouse</label>
            </value>
            <value>
                <fullName>Uncle</fullName>
                <isActive>false</isActive>
                <label>Uncle</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Requested_Medication__c.field-meta.xml
<CustomField>
    <fullName>VCC_Requested_Medication__c</fullName>
    <description>The name of the VA medication that the patient is requesting for a renewal</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter the name of the VA medication that the patient is requesting for a renewal</inlineHelpText>
    <label>Requested VA Medication - Renew</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/VCC/VCC_ProgressNoteDomain.cls
public with sharing class VCC_ProgressNoteDomain extends fflib_SObjectDomain {
    // Constructors.
    public VCC_ProgressNoteDomain() {
        super(new List<VCC_Progress_Note__c>());
    }

    public VCC_ProgressNoteDomain(List<VCC_Progress_Note__c> records) {
        super(records);
    }

    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> records) {
            return new VCC_ProgressNoteDomain(records);
        }
    }

    // Trigger Handling
    /**
     * @description           fflib trigger on before updates
     * @param existingRecords trigger new map of records
     */
    public override void onBeforeUpdate(Map<Id, SObject> existingRecords) {
        Logger.info('Progress Note onBeforeUpdate called. Validating SObject prior to save.');
    }

    public override void onValidate(Map<Id, SObject> previousMap) {
        charLimitError(this.Records, previousMap);
    }

    // Methods

    /**
     * @description       throw custom validation rule when text or text area fields character limit is maxed out, to prevent accidental truncation of field value risk.
     * @param recs        new list of Progress Note records from trigger
     * @param previousMap old list of Progress Note records from trigger
     */
    public void charLimitError(List<VCC_Progress_Note__c> recs, Map<Id, SObject> previousMap) {
        Map<String, SObjectField> objFieldsMap = Schema.SObjectType.VCC_Progress_Note__c.fields.getMap();
        Map<String, Integer> fieldName2FieldLengthMap = new Map<String, Integer>();
        Map<String, String> fieldName2LabelMap = new Map<String, String>();
        List<String> charLimitErrorFields = new List<String>();

        for (String fieldName : objFieldsMap.keySet()) {
            Schema.DescribeFieldResult fieldDesc = objFieldsMap.get(fieldName).getDescribe();

            if (fieldDesc.getType() == Schema.DisplayType.String || fieldDesc.getType() == Schema.DisplayType.TextArea) {
                fieldName2FieldLengthMap.put(fieldName, fieldDesc.getLength());
                fieldName2LabelMap.put(fieldName, fieldDesc.getLabel());
            }
        }

        for (VCC_Progress_Note__c progNote : recs) {
            for (String fld : fieldName2FieldLengthMap.keySet()) {
                String fieldValue = String.valueOf(progNote.get(fld));
                if (fieldValue != null && fieldValue.length() >= fieldName2FieldLengthMap.get(fld) && fieldValue != String.valueOf(previousMap.get(progNote.Id).get((fld)))) {
                    String fieldLabel = fieldName2LabelMap.get(fld);
                    charLimitErrorFields.add(fieldLabel);
                    progNote.addError(fld, 'Character limit for ' + fieldLabel + ' has been reached.  Please review entry and remove character(s) to save.');
                }
            }

            if (!charLimitErrorFields.isEmpty()) {
                String errMsg =
                    'Character limit for ' +
                    String.join(charLimitErrorFields, ', ') +
                    ' has been reached.  Please review entry, validate that entry was not truncated, and remove character(s) to save.';
                progNote.addError(errMsg);
            }
        }
    }

    /**
     * @description         instantiate Progress Note, assign field values, and return it. Need to address excessive params warning in future.
     * @param pnString      assign value to requested medication field
     * @param controlled    assign value to controlled medication field
     * @param nonControlled assign value to non controlled medication field
     * @param cse           assign value to case field
     * @param pnRecTypeId   assign value to record type field
     * @param facilityName assign value to facility field
     * @return              `VCC_Progress_Note__c`
     */
    @SuppressWarnings('PMD.ExcessiveParameterList')
    public VCC_Progress_Note__c newProgressNote(String pnString, Boolean controlled, Boolean nonControlled, Case cse, Id pnRecTypeId, String facilityName) {
        VCC_Progress_Note__c progNote = new VCC_Progress_Note__c();
        progNote.VCC_Requested_Medication__c = pnString;
        progNote.VCC_Medication_Fill_Renewal__c = true;
        progNote.VCC_Controlled_medication__c = controlled;
        progNote.VCC_Non_controlled_medication__c = nonControlled;
        progNote.RecordTypeId = pnRecTypeId;
        progNote.VCC_Case__c = cse.Id;
        progNote.VCC_Relative_Type__c = cse.VCC_Caller_Relation__c; //? same as case
        progNote.VCC_If_Other_Describe_Relation_Patient__c = cse.VCC_Relation_Type_Other__c; //? relation type (if Other)
        progNote.VCC_Caller_Name_Text__c = cse.VCC_Caller_Name__c;
        progNote.VCC_Facility__c = facilityName;

        return progNote;
    }
}