force-app/main/default/objects/LogEntry__c/fields/ExceptionMessage__c.field-meta.xml
<CustomField>
    <fullName>ExceptionMessage__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Exception Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/main/default/objects/LogEntry__c/fields/ExceptionType__c.field-meta.xml
<CustomField>
    <fullName>ExceptionType__c</fullName>
    <label>Exception Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Flow.FaultError</fullName>
            </value>
            <value>
                <fullName>JavaScript.Error</fullName>
            </value>
            <value>
                <fullName>System.AsyncException</fullName>
            </value>
            <value>
                <fullName>System.CalloutException</fullName>
            </value>
            <value>
                <fullName>System.DmlException</fullName>
            </value>
            <value>
                <fullName>System.EmailException</fullName>
            </value>
            <value>
                <fullName>System.ExternalObjectException</fullName>
            </value>
            <value>
                <fullName>System.InvalidParameterValueException</fullName>
            </value>
            <value>
                <fullName>System.JSONException</fullName>
            </value>
            <value>
                <fullName>System.LimitException</fullName>
            </value>
            <value>
                <fullName>System.ListException</fullName>
            </value>
            <value>
                <fullName>System.MathException</fullName>
            </value>
            <value>
                <fullName>System.NoAccessException</fullName>
            </value>
            <value>
                <fullName>System.NoDataFoundException</fullName>
            </value>
            <value>
                <fullName>System.NoSuchElementException</fullName>
            </value>
            <value>
                <fullName>System.NullPointerException</fullName>
            </value>
            <value>
                <fullName>System.QueryException</fullName>
            </value>
            <value>
                <fullName>System.SearchException</fullName>
            </value>
            <value>
                <fullName>System.SecurityException</fullName>
            </value>
            <value>
                <fullName>System.SerializationException</fullName>
            </value>
            <value>
                <fullName>System.SObjectException</fullName>
            </value>
            <value>
                <fullName>System.StringException</fullName>
            </value>
            <value>
                <fullName>System.TypeException</fullName>
            </value>
            <value>
                <fullName>System.VisualforceException</fullName>
            </value>
            <value>
                <fullName>System.XmlException</fullName>
            </value>
            <value>
                <fullName>HDR_DOWN</fullName>
            </value>
            <value>
                <fullName>MPI_DOWN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LogEntry__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/VCC/VCC_NotificationServiceTest.cls
@isTest
class VCC_NotificationServiceTest {
    @testSetup
    static void makeData() {
        VCC_TestDataFactory.insertUser('System Administrator');
    }
    /**
     * @description create a test user for running tests
     * @return A test user
     **/
    public static User getTestUser() {
        return [SELECT Id FROM User WHERE LastName = 'Testing' LIMIT 1];
    }
    @isTest
    static void testNotifyOnRemoteSystemDown() {
        System.runAs(getTestUser()) {
            Test.startTest();
            VCC_NotificationService.notifyOnRemoteSystemDown('Test');
            VCC_NotificationService.notifyOnRemoteSystemDown('Test');
            Test.stopTest();
            List<LogEntry__c> logEntriesMPIDown = [
                SELECT Id, Message__c, ExceptionMessage__c, ExceptionType__c, CreatedDate
                FROM LogEntry__c
                WHERE ExceptionType__c = :VCC_NotificationService.NEBULA_EXCEPTION_TYPE_MPI_DOWN AND CreatedDate = TODAY
            ];

            System.assert.areequal(logEntriesMPIDown.size(), 2);
        }
    }
}