force-app/main/default/objects/TUC_Kanban_Config__mdt/TUC_Kanban_Config__mdt.object-meta.xml
<CustomObject>
    <label>TUC Kanban Config</label>
    <pluralLabel>TUC Kanban Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/TUC_Kanban_Config__mdt/fields/Field_Type_Map__c.field-meta.xml
<CustomField>
    <fullName>Field_Type_Map__c</fullName>
    <description>This field is meant to represent the expected field-to-type mapping that Aura needs in order to digest the incoming information and set up and hyperlink field correctly while displaying UI friendly information rather than raw IDs.

Setup:
Provide a semi-colon separated list of fields to display on the card. This is to be provided in a fieldName to map format, seprated by commas. The map of mapping type to mappingType is separated by colon. If additional entries are needed they are separated by hyphen.

Each field entry is separated by semi-colon.

examples:
CaseNumber,type:STRING;
ContactId,relationName:Contact~*!Name-type:REFERENCE</description>
    <inlineHelpText>Provide a semi-colon separated list of fields to display on the card. This is to be provided in a fieldName to map format, seprated by commas. The map of mapping type to mappingType is separated by colon. If additional entries are needed they are separated by hyphen.

Each field entry is separated by semi-colon.

examples:
CaseNumber,type:STRING;
ContactId,relationName:Contact~*!Name-type:REFERENCE</inlineHelpText>
    <label>Field Type Map</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/main/default/objects/TUC_Kanban_Config__mdt/fields/Fields_To_Display_on_Card__c.field-meta.xml
<CustomField>
    <fullName>Fields_To_Display_on_Card__c</fullName>
    <description
    >Provide a semi-colon separated list of fields to display on the card. Do not use dot operators such as if the object was Case and the field desired was the related Account
        name, use AccountId, not Account.Name. ex on Case - AccountId;ContactId;</description>
    <inlineHelpText
    >Provide a semi-colon separated list of fields to display on the card. Do not use dot operators such as if the object was Case and the field desired was the related Account
        name, use AccountId, not Account.Name - Case - AccountId;ContactId;</inlineHelpText>
    <label>Fields To Display on Card</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/main/default/objects/TUC_Kanban_Config__mdt/fields/Fields_To_Display_on_Popup__c.field-meta.xml
<CustomField>
    <fullName>Fields_To_Display_on_Popup__c</fullName>
    <description>Provide a semi-colon separated list of fields to display on the card. This is to be provided in a String,String format separated by semi-colon, ie &apos;Value&apos;,&apos;Display Name&apos;;&apos;Value2&apos;,&apos;Other Field Display Name&apos;</description>
    <inlineHelpText>Provide a semi-colon separated list of fields to display on the card. This is to be provided in a String,String format separated by semi-colon, ie &apos;Value&apos;,&apos;Display Name&apos;;&apos;Value2&apos;,&apos;Other Field Display Name&apos;</inlineHelpText>
    <label>Fields To Display on Popup</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TUC_Kanban_Config__mdt/fields/Home_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Home_Object_Name__c</fullName>
    <description>Give the name of the Object the Kanban is based off in a Home Page</description>
    <inlineHelpText>Give the name of the Object the Kanban is based off in a Home Page</inlineHelpText>
    <label>Home Object Name</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/TUC_Kanban_Config__mdt/fields/Included_Recordtype_Developer_names__c.field-meta.xml
<CustomField>
    <fullName>Included_Recordtype_Developer_names__c</fullName>
    <description>A semi-colon separated list of DeveloperNames to limit the queries to.</description>
    <label>Included Recordtype Developer names</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TUC_Kanban_Config__mdt/fields/Kanban_Group_By__c.field-meta.xml
<CustomField>
    <fullName>Kanban_Group_By__c</fullName>
    <description
    >Enter the Kanban Field group by field API Name. For example, if the only Object is Case, and you would like to see the cases on the kanban column sorted by Status, you
        would enter Status in this field. Remember to enter the __c if this is a custom field.</description>
    <inlineHelpText
    >Enter the Kanban Field group by field API Name. For example, if the only Object is Case, and you would like to see the cases on the kanban column sorted by Status, you
        would enter Status in this field. Remember to enter the __c if this is a custom field.</inlineHelpText>
    <label>Kanban Group By</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TUC_Kanban_Config__mdt/fields/SOQL_limit_for_closed_statuses__c.field-meta.xml
<CustomField>
    <fullName>SOQL_limit_for_closed_statuses__c</fullName>
    <defaultValue>100</defaultValue>
    <description>This is the limit used by the SOQL query for CLOSED statuses - in this case, just the status &apos;closed&apos;</description>
    <inlineHelpText>A number between 1-999</inlineHelpText>
    <label>SOQL limit for closed statuses</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/main/default/objects/TUC_Kanban_Config__mdt/fields/SOQL_limit_for_open_statuses__c.field-meta.xml
<CustomField>
    <fullName>SOQL_limit_for_open_statuses__c</fullName>
    <defaultValue>25</defaultValue>
    <description>This is the limit used in SOQL queries for all open statuses.</description>
    <inlineHelpText>This is a number, between 1 and 999.</inlineHelpText>
    <label>SOQL limit for open statuses</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TUC_Kanban_Config__mdt/fields/Statuses_to_sort_by_TUC_wait_time__c.field-meta.xml
<CustomField>
    <fullName>Statuses_to_sort_by_TUC_wait_time__c</fullName>
    <description>These statuses must be present in the Values_To_Include_for_Group_By__c field. The statuses listed here will be sorted by the TUC_Wait_Time__c</description>
    <label>Statuses to sort by TUC wait time</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

sfdx-source/main/default/objects/TUC_Kanban_Config__mdt/fields/Values_To_Exclude_From_Group_By__c.field-meta.xml
<CustomField>
    <fullName>Values_To_Exclude_From_Group_By__c</fullName>
    <description
    >Use a semi-colon separated list if to exclude the values from the Group By. For example, if the object is Case and the columns are Grouped on the field Status. To exclude
        &quot;New&quot; and &quot;Closed&quot; cases, enter in this field: New;Closed</description>
    <inlineHelpText
    >Use a semi-colon separated list if to exclude the values from the Group By. For example, if the object is Case and the columns are Grouped on the field Status. To exclude
        &quot;New&quot; and &quot;Closed&quot; cases, enter in this field: New;Closed</inlineHelpText>
    <label>Values To Exclude From Group By</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TUC_Kanban_Config__mdt/fields/Values_To_Include_for_Group_By__c.field-meta.xml
<CustomField>
    <fullName>Values_To_Include_for_Group_By__c</fullName>
    <description
    >Use a semi-colon separated list if to include the values for the Group By. For example, if the object is Case and the columns are Grouped on the field Status. To exclude
        &quot;New&quot; and &quot;Closed&quot; cases, enter in this field: New;Closed Make sure the order is the proper order as well.</description>
    <inlineHelpText
    >Use a semi-colon separated list if to include the values for the Group By. For example, if the object is Case and the columns are Grouped on the field Status. To exclude
        &quot;New&quot; and &quot;Closed&quot; cases, enter in this field: New;Closed Make sure the order is the proper order as well.</inlineHelpText>
    <label>Values To Include for Group By</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/TUC/TUC_KanbanConfigMdtRepo.cls
/**
 * @description This repository is for the TUC_Kanban_Config__mdt Metadata.
 * @author Booz Allen Hamilton
 *
 * @see VTC_BaseRepo
 * @see TUC_KanbanConfigMdtRepoTest
 */
public virtual inherited sharing class TUC_KanbanConfigMdtRepo extends VTC_BaseRepo {
    /**
     * @description Constructor function for TUC_KanbanConfigMdtRepo. Calls super constructor which sets this.sObjectType to
     * TUC_Kanban_Config__mdt
     */
    public TUC_KanbanConfigMdtRepo() {
        super(TUC_Kanban_Config__mdt.sObjectType);
    }

    /**
     * @description - This method is responsible for fetching the controlling metadata record.
     * @param metadataDevName - The Dev Name of a desired TUC_Kanban_Config__mdt
     *
     * @return TUC_Kanban_Config__mdt - The metadata record that controls the kanban board.
     */
    public TUC_Kanban_Config__mdt fetchControllingMetadataRecord(String metadataDevName) {
        if (String.isBlank(metadataDevName)) {
            return null;
        }
        String selectClause = 'SELECT Id,DeveloperName,Fields_To_Display_on_Card__c,Fields_To_Display_on_Popup__c,Field_Type_Map__c,Home_Object_Name__c,Included_Recordtype_Developer_names__c,Kanban_Group_By__c,SOQL_limit_for_closed_statuses__c,SOQL_limit_for_open_statuses__c,Statuses_to_sort_by_TUC_wait_time__c,Values_To_Exclude_From_Group_By__c,Values_To_Include_for_Group_By__c ';
        String fromClause = 'FROM TUC_Kanban_Config__mdt ';
        String whereClause = 'WHERE DeveloperName = :metadataDevName LIMIT 1';
        String query = selectClause + fromClause + whereClause;
        Map<String, Object> bindParams = new Map<String, Object>{ 'metadataDevName' => metadataDevName };
        List<TUC_Kanban_Config__mdt> metadataList = this.fetch(query, bindParams);
        TUC_Kanban_Config__mdt metadataToReturn;
        if (!metadataList.isEmpty()) {
            metadataToReturn = metadataList.get(0);
        }
        return metadataToReturn;
    }
}