sfdx-source/main/default/objects/VCC_Clinic__c/VCC_Clinic__c.object-meta.xml
<CustomObject>
    <description>Clinic Object for ISS Scheduling</description>
    <label>Clinic</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Clinic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clinics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Clinic__c/fields/VCC_IEN__c.field-meta.xml
<CustomField>
    <fullName>VCC_IEN__c</fullName>
    <description>The unique Id for the Clinic</description>
    <encryptionScheme>None</encryptionScheme>
    <label>IEN</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/VCC_Provider__c/VCC_Provider__c.object-meta.xml
<CustomObject>
    <description>Provider Object for ISS</description>
    <label>Provider</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Provider__c/fields/VCC_IEN__c.field-meta.xml
<CustomField>
    <fullName>VCC_IEN__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>IEN</label>
    <description>Internal Entry Number (UniqueId) for the Provider</description>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCC_Provider_Clinic_Assignment__c/VCC_Provider_Clinic_Assignment__c.object-meta.xml
<CustomObject>
    <description>Junction Object between Clinic and Provider objects for ISS.</description>
    <label>Provider Clinic Assignment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provider Clinic Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VCC_Provider_Clinic_Assignment__c/fields/VCC_Clinic__c.field-meta.xml
<CustomField>
    <fullName>VCC_Clinic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinic</label>
    <description>Links to the associated Clinic record</description>
    <referenceTo>VCC_Clinic__c</referenceTo>
    <relationshipLabel>Provider Clinic Assignments</relationshipLabel>
    <relationshipName>VCC_Provider_Clinic_Assignment</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Provider_Clinic_Assignment__c/fields/VCC_IEN__c.field-meta.xml
<CustomField>
    <fullName>VCC_IEN__c</fullName>
    <description>Internal Entry Number related to Provider/Clinic</description>
    <encryptionScheme>None</encryptionScheme>
    <label>IEN</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCC_Provider_Clinic_Assignment__c/fields/VCC_Provider__c.field-meta.xml
<CustomField>
    <fullName>VCC_Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provider</label>
    <description>Links to the associated Provider record</description>
    <referenceTo>VCC_Provider__c</referenceTo>
    <relationshipLabel>Provider Clinic Assignments</relationshipLabel>
    <relationshipName>VCC_Provider_Clinic_Assignment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VCC/VCC_ClinicByProviderMockRSTransform.cls
/**
 * @description The purpose of this class is to act as a transformer for the mock sObject's VCC_Provider_Clinic_Assignment__c.
 *  This allows us to transform the shape of these objects into the actual shape of the api response. Working with the data in the shape of the api response will allow us to develop the lwc's to be data source
 * agnostic, and will reduce double work.
 * @author Booz Allen Hamilton
 * @since 4/23/2024
 */
public with sharing class VCC_ClinicByProviderMockRSTransform {
    @AuraEnabled
    public List<String> associatedClinicIEN = new List<String>();
    @AuraEnabled
    public List<String> associatedClinicName = new List<String>();
    @AuraEnabled
    public String providerName;
    @AuraEnabled
    public String providerIEN;
    @AuraEnabled
    public String pbspID;

    /**
     * @description  Constructor for VCC_ClinicByProviderMockRSTransform. Accepts a list of VCC_Provider_Clinic_Assignment__c records that will be used to parse into the appropriate shape that matches the API response
     * @param mockClinics Array of VCC_Provider_Clinic_Assignment__c records to parse into the appropriate shape that matches the API response
     */
    public VCC_ClinicByProviderMockRSTransform(List<VCC_Provider_Clinic_Assignment__c> mockClinics) {
        if (mockClinics == null || mockClinics.isEmpty()) {
            return;
        }
        this.providerName = mockClinics[0].VCC_Provider__r.Name;
        this.providerIEN = mockClinics[0].VCC_IEN__c;
        for (VCC_Provider_Clinic_Assignment__c mockClinic : mockClinics) {
            this.associatedClinicIEN.add(mockClinic.VCC_Clinic__r.VCC_IEN__c);
            this.associatedClinicName.add(mockClinic.VCC_Clinic__r.Name);
        }
    }
}