sfdx-source/main/default/objects/VCC_Clinic__c/VCC_Clinic__c.object-meta.xml
<CustomObject>
    <description>Clinic Object for ISS Scheduling</description>
    <label>Clinic</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Clinic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clinics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Clinic__c/fields/VCC_IEN__c.field-meta.xml
<CustomField>
    <fullName>VCC_IEN__c</fullName>
    <description>The unique Id for the Clinic</description>
    <encryptionScheme>None</encryptionScheme>
    <label>IEN</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/VCC_Clinic__c/fields/VCC_Station_Id__c.field-meta.xml
<CustomField>
    <fullName>VCC_Station_Id__c</fullName>
    <description>Parent Facility Id associated with Clinic</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Station Id</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCC_Provider__c/VCC_Provider__c.object-meta.xml
<CustomObject>
    <description>Provider Object for ISS</description>
    <label>Provider</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Provider__c/fields/VCC_IEN__c.field-meta.xml
<CustomField>
    <fullName>VCC_IEN__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>IEN</label>
    <description>Internal Entry Number (UniqueId) for the Provider</description>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCC_Provider_Clinic_Assignment__c/VCC_Provider_Clinic_Assignment__c.object-meta.xml
<CustomObject>
    <description>Junction Object between Clinic and Provider objects for ISS.</description>
    <label>Provider Clinic Assignment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provider Clinic Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VCC_Provider_Clinic_Assignment__c/fields/VCC_Clinic__c.field-meta.xml
<CustomField>
    <fullName>VCC_Clinic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinic</label>
    <description>Links to the associated Clinic record</description>
    <referenceTo>VCC_Clinic__c</referenceTo>
    <relationshipLabel>Provider Clinic Assignments</relationshipLabel>
    <relationshipName>VCC_Provider_Clinic_Assignment</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Provider_Clinic_Assignment__c/fields/VCC_IEN__c.field-meta.xml
<CustomField>
    <fullName>VCC_IEN__c</fullName>
    <description>Internal Entry Number related to Provider/Clinic</description>
    <encryptionScheme>None</encryptionScheme>
    <label>IEN</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCC_Provider_Clinic_Assignment__c/fields/VCC_Provider__c.field-meta.xml
<CustomField>
    <fullName>VCC_Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provider</label>
    <description>Links to the associated Provider record</description>
    <referenceTo>VCC_Provider__c</referenceTo>
    <relationshipLabel>Provider Clinic Assignments</relationshipLabel>
    <relationshipName>VCC_Provider_Clinic_Assignment</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/classes/VCR/VCR_ProviderClinicAssignmentRepo.cls
/**
 * @description Repository class for the VCC_Provider_Clinic_Assignment__c object
 * @author  Booz Allen Hamilton
 * @since  4/2/2024
 */
public inherited sharing class VCR_ProviderClinicAssignmentRepo extends VTC_BaseRepo {
    /**
     * @description Constructor for VCR_ProviderClinicAssignmentRepo
     */
    public VCR_ProviderClinicAssignmentRepo() {
        super(VCC_Provider_Clinic_Assignment__c.sObjectType);
    }
    /**
     * @description Returns a list of Provider Clinic Assignments based on provider SEC ID, and available Facility Codes
     * @return List<VCC_Provider_Clinic_Assignment__c> returns a list of VCC_Provider_Clinic_Assignment__c records
     * @param providerIEN    String of Provider IEN for identifying the Provider
     * @param facilityCode       Facility Code for filtering which Clinics are under Facility
     */
    public List<VCC_Provider_Clinic_Assignment__c> getProviderClinicsInternal(String providerIEN, String facilityCode) {
        //Get Clinic IENs where Provider works at:
        Map<String, Object> binds = new Map<String, Object>{
            'providerIEN' => providerIEN,
            'facilityCode' => facilityCode
        };
        String selectClause = 'SELECT VCC_Clinic__r.VCC_IEN__c, VCC_Clinic__r.Name, VCC_Clinic__r.VCC_Station_Id__c, VCC_Provider__r.Name, VCC_IEN__c ';
        String fromClause = this.calculateFromClause();
        String whereClause = ' WHERE VCC_Provider__r.VCC_IEN__c = :providerIEN AND VCC_Clinic__r.VCC_Station_Id__c = :facilityCode';
        String query = selectClause + ' ' + fromClause + ' ' + whereClause;
        return this.fetch(query, binds);
    }
    /**
     * @description Returns a list of Provider Clinic Assignments based on the clinic's IEN
     * @return List<VCC_Provider_Clinic_Assignment__c> returns a list of VCC_Provider_Clinic_Assignment__c records
     * @param clinicIEN    String of Clinic IEN for identifying the Provider
     */
    public List<VCC_Provider_Clinic_Assignment__c> getProvidersInternal(String clinicIEN) {
        //Get Providers where Provider works at:
        Map<String, Object> binds = new Map<String, Object>{ 'clinicIEN' => clinicIEN };
        String selectClause = 'SELECT VCC_Provider__r.Name, VCC_IEN__c, VCC_Clinic__r.VCC_IEN__c ';
        String fromClause = this.calculateFromClause();
        String whereClause = ' WHERE VCC_Clinic__r.VCC_IEN__c = :clinicIEN';
        String query = selectClause + ' ' + fromClause + ' ' + whereClause;
        return this.fetch(query, binds);
    }
}