sfdx-source/main/default/objects/VCC_Service_Appointment_Metrics__c/VCC_Service_Appointment_Metrics__c.object-meta.xml
<CustomObject>
    <description>An extension to the Service Appointment object created to store information related to the Service Appointment for reporting purposes.</description>
    <label>Service Appointment Metrics</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Service Appointment Metrics Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Appointment Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VCC_Service_Appointment_Metrics__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Case object of the VCV Case related to the Service Appointment. Used for reporting purposes.</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Service Appointment Metrics</relationshipLabel>
    <relationshipName>Service_Appointment_Metrics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCC_Service_Appointment_Metrics__c/fields/Case_Metrics__c.field-meta.xml
<CustomField>
    <fullName>Case_Metrics__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Looking up to the Case Metrics record for the VCV Case associated with the Service Appointment. Used for reporting purposes.</description>
    <label>Case Metrics</label>
    <referenceTo>VCC_Case_Metrics__c</referenceTo>
    <relationshipLabel>Service Appointment Metrics</relationshipLabel>
    <relationshipName>Service_Appointment_Metrics</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Service_Appointment_Metrics__c/fields/Service_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Service_Appointment__c</fullName>
    <description>The Service Appointment record for which the Service Appointment Metrics record has been created.</description>
    <label>Service Appointment</label>
    <referenceTo>ServiceAppointment</referenceTo>
    <relationshipLabel>Service Appointment Metrics</relationshipLabel>
    <relationshipName>Service_Appointment_Metrics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/VCR/VCR_ServiceAppointmentMetricsRepo.cls
/**
 * @description       : This is a repository class that is used to fetch or put data related to Service Appointment Metrics custom object.
 * @author BAH
 * @see VCC_ServiceAppointmentMetrics
 * @see VCC_Service_Appointment_Metrics__c
 */
public inherited sharing class VCR_ServiceAppointmentMetricsRepo extends VTC_BaseRepo {
    private static final Set<String> DEFAULT_FIELDS = new Set<String>{
        'Case__c',
        'Case_Metrics__c',
        'CreatedById',
        'CreatedDate',
        'Id',
        'IsDeleted',
        'LastModifiedById',
        'LastModifiedDate',
        'Name',
        'Service_Appointment__c'
    };
    /**
     * @description constructor
     */
    public VCR_ServiceAppointmentMetricsRepo() {
        super(VCC_Service_Appointment_Metrics__c.SObjectType);
        this.defaultSelectFields.addAll(DEFAULT_FIELDS);
    }

    /**
     * @description       : This method is used to fetch the Service Appointment Metrics record by the Service Appointment record id.
     * @param recordId     : Record id to be used in the where clause.
     * @return VCC_Service_Appointment_Metrics__c : Service Appointment Metrics record.
     */
    public VCC_Service_Appointment_Metrics__c getServiceAppointmentMetricsByServiceAppointmentId(String recordId) {
        return this.getServiceAppointmentMetricsByField('Service_Appointment__c', recordId);
    }

    /**
     * @description       : This method is used to upsert the Service Appointment Metrics record.
     * @param serviceAppointmentMetrics : List of Service Appointment Metrics records to be upserted.
     * @return List<Database.UpsertResult> : List of upsert results.
     */
    public List<Database.UpsertResult> upsertServiceAppointmentMetrics(
        List<VCC_Service_Appointment_Metrics__c> serviceAppointmentMetrics
    ) {
        return this.doUpsert(serviceAppointmentMetrics);
    }

    /**
     * @description       : This method is used to fetch the Service Appointment Metrics record by the field name and record id.
     * @param fieldName    : Field name to be used in the where clause.
     * @param recordId     : Record id to be used in the where clause.
     * @return VCC_Service_Appointment_Metrics__c : Service Appointment Metrics record.
     */
    @TestVisible
    private VCC_Service_Appointment_Metrics__c getServiceAppointmentMetricsByField(String fieldName, Id recordId) {
        String selectClause = calculateSelectClause();
        String fromClause = this.calculateFromClause();
        String whereClause = 'WHERE ' + fieldName + ' = :recordId';
        String query = selectClause + ' ' + fromClause + ' ' + whereClause;
        Map<String, Object> params = new Map<String, Object>{ 'recordId' => recordId };
        return (VCC_Service_Appointment_Metrics__c) this.fetch(query, params).get(0);
    }

    /**
     * @description       : This method is used to calculate the select clause for the object.
     * @return String      : Select clause for the object.
     */
    @TestVisible
    private static String calculateSelectClause() {
        List<String> fieldNames = new List<String>();
        fieldNames.addAll(DEFAULT_FIELDS);
        List<String> fieldNamesList = new List<String>();
        for (String fieldName : fieldNames) {
            fieldNamesList.add(fieldName);
        }
        return 'SELECT ' + String.join(fieldNamesList, ', ');
    }
}