sfdx-source/main/default/objects/Contact/fields/User_ID__c.field-meta.xml
<CustomField>
    <fullName>User_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Finds USER ID from Users Standard object, can be used later in formulas.</description>
    <label>User ID</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/objects/Functional_Queue__c/Functional_Queue__c.object-meta.xml
<CustomObject>
    <description>Record used to represent a group and a queue in the backend when functional queue members are related to it.</description>
    <label>Functional Queue</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Functional Queue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functional Queues</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/Functional_Queue__c/fields/Public_Group_ID__c.field-meta.xml
<CustomField>
    <fullName>Public_Group_ID__c</fullName>
    <description>ID of the corresponding public group. This is autopopulated when a member is added to the functional queue.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Public Group ID will auto-populate after members are added to the functional queue.</inlineHelpText>
    <label>Public Group ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Functional_Queue__c/fields/Queue_ID__c.field-meta.xml
<CustomField>
    <fullName>Queue_ID__c</fullName>
    <description>Id of the corresponding Queue. This is autopopulated when a member is added to the functional queue.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Queue ID will auto-populate after members are added to the functional queue.</inlineHelpText>
    <label>Queue ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/Functional_Queue_Member__c/Functional_Queue_Member__c.object-meta.xml
<CustomObject>
    <description>Junction object to connect contacts to functional queues.</description>
    <label>Functional Queue Member</label>
    <nameField>
        <displayFormat>FQM-{0000}</displayFormat>
        <label>Functional Queue Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Functional Queue Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/Functional_Queue_Member__c/fields/Contact_Member__c.field-meta.xml
<CustomField>
    <fullName>Contact_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Member</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.User_ID__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Functional Queue Membership</relationshipLabel>
    <relationshipName>Functional_Queue_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/objects/Functional_Queue_Member__c/fields/Functional_Queue__c.field-meta.xml
<CustomField>
    <fullName>Functional_Queue__c</fullName>
    <label>Functional Queue</label>
    <referenceTo>Functional_Queue__c</referenceTo>
    <relationshipLabel>Functional Queue Members</relationshipLabel>
    <relationshipName>Functional_Queue_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/main/default/objects/Functional_Queue_Member__c/fields/User_ID__c.field-meta.xml
<CustomField>
    <fullName>User_ID__c</fullName>
    <formula>Contact_Member__r.User_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>User ID</label>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/classes/FunctionalQueueMemberHandler.cls
/**
 * @description       :
 * @author            : jonathon.schleicher@b3groupinc.com
 * @group             :
 * @last modified on  : 10-21-2021
 * @last modified by  : jonathon.schleicher@b3groupinc.com
 **/
public without sharing class FunctionalQueueMemberHandler {
    public void OnBeforeInsert(List<Functional_Queue_Member__c> newFunctionalQueueMembers) {
        Set<Id> relatedFunctionalQueueIds = getRelatedFunctionalQueueIds(newFunctionalQueueMembers);
        FunctionalQueueUtility.createQueueGroupIfAssociatedFunctionalQueueIsNonExistent(relatedFunctionalQueueIds);

        Map<Id, Set<Id>> functionalQueueToContactsMap = getFunctionalQueueToContactsMap(relatedFunctionalQueueIds);
        for (Functional_Queue_Member__c newMember : newFunctionalQueueMembers) {
            if (memberIsDuplicate(functionalQueueToContactsMap, newMember)) {
                newMember.addError('This contact is already a member of this functional queue.');
            }
        }
    }

    public void OnAfterInsert(List<Functional_Queue_Member__c> newFunctionalQueueMembers) {
        Set<Id> newMemberIds = new Set<Id>();
        for (Functional_Queue_Member__c newMember : newFunctionalQueueMembers) {
            newMemberIds.add(newMember.Id);
        }
        addNewMembersToCorrespondingGroups(newMemberIds);
    }

    public void OnBeforeDelete(List<Functional_Queue_Member__c> deletedFunctionalQueueMembers) {
        Set<Id> groupMemberIdsToDelete = getGroupMemberIdsToDelete(deletedFunctionalQueueMembers);
        deleteFunctionalQueueGroupMembers(groupMemberIdsToDelete);
    }

    /*****************************************************************************
     *  Returns a set of any Functional Queue IDs related to the newly created
     *  functional queue members
     ****************************************************************************/
    private Set<Id> getRelatedFunctionalQueueIds(List<Functional_Queue_Member__c> functionalQueueMembers) {
        Set<Id> functionalQueueIds = new Set<Id>();
        for (Functional_Queue_Member__c member : functionalQueueMembers) {
            functionalQueueIds.add(member.Functional_Queue__c);
        }
        return functionalQueueIds;
    }

    /*****************************************************************************
     *  Returns a map that correlates functional queues to their respective
     *  existing member contact IDs in order to make it easy to check for dupes
     ****************************************************************************/
    private Map<Id, Set<Id>> getFunctionalQueueToContactsMap(Set<Id> functionalQueueIds) {
        List<Functional_Queue_Member__c> existingFunctionalQueueMembers = [
            SELECT Contact_Member__c, Functional_Queue__c
            FROM Functional_Queue_Member__c
            WHERE Functional_Queue__c IN :functionalQueueIds
        ];
        Map<Id, Set<Id>> functionalQueueToContactsMap = new Map<Id, Set<Id>>();
        for (Functional_Queue_Member__c existingMember : existingFunctionalQueueMembers) {
            if (functionalQueueToContactsMap.containsKey(existingMember.Functional_Queue__c)) {
                functionalQueueToContactsMap.get(existingMember.Functional_Queue__c).add(existingMember.Contact_Member__c);
            } else {
                functionalQueueToContactsMap.put(existingMember.Functional_Queue__c, new Set<Id>{ existingMember.Contact_Member__c });
            }
        }

        return functionalQueueToContactsMap;
    }

    /*****************************************************************************
     *  Checks the functionalQueueToContactsMap if the new functional queue
     *  member contact matches an existing contact on the same functional queue
     ****************************************************************************/
    private Boolean memberIsDuplicate(Map<Id, Set<Id>> functionalQueueToContactsMap, Functional_Queue_Member__c functionalQueueMember) {
        if (functionalQueueToContactsMap.containsKey(functionalQueueMember.Functional_Queue__c)) {
            return functionalQueueToContactsMap.get(functionalQueueMember.Functional_Queue__c).contains(functionalQueueMember.Contact_Member__c);
        }
        return false;
    }

    /*****************************************************************************
     *  Creates the corresponding group members for each of the new functional
     *  queue member IDs
     ****************************************************************************/
    @future
    public static void addNewMembersToCorrespondingGroups(Set<Id> newFunctionalQueueMemberIds) {
        List<Functional_Queue_Member__c> newFunctionalQueueMembers = [
            SELECT
                Functional_Queue__c,
                Functional_Queue__r.Queue_ID__c,
                Functional_Queue__r.Public_Group_ID__c,
                Contact_Member__c,
                Contact_Member__r.User_ID__c,
                RecordType.DeveloperName
            FROM Functional_Queue_Member__c
            WHERE Id IN :newFunctionalQueueMemberIds
        ];
        List<GroupMember> newMembersToInsert = new List<GroupMember>();
        for (Functional_Queue_Member__c newQueueMember : newFunctionalQueueMembers) {
            newMembersToInsert.add(
                FunctionalQueueUtility.createGroupMemberByGroupIdAndUserOrGroupId(
                    newQueueMember.Functional_Queue__r.Public_Group_ID__c,
                    newQueueMember.Contact_Member__r.User_ID__c
                )
            );
        }

        insert newMembersToInsert;
    }

    /*****************************************************************************
     *  Returns a set of IDs that represent the group members that correspond
     *  to deleted Functional Queue Members
     *  -  Query for functional queue member merge fields to get corresponding
     *       group and user IDs
     *  -  Query for group members that belong to the relevant public groups
     *  -  Loop through deleted functional queue members to match them to
     *     corresponding group members
     ****************************************************************************/
    private Set<Id> getGroupMemberIdsToDelete(List<Functional_Queue_Member__c> deletedFunctionalQueueMembers) {
        Set<Id> deletedMemberIds = new Set<Id>();
        for (Functional_Queue_Member__c deletedMember : deletedFunctionalQueueMembers) {
            deletedMemberIds.add(deletedMember.Id);
        }
        List<Functional_Queue_Member__c> membersToRemove = [
            SELECT Functional_Queue__r.Public_Group_ID__c, Contact_Member__r.User_ID__c
            FROM Functional_Queue_Member__c
            WHERE Id IN :deletedMemberIds
        ];

        Set<Id> relatedGroupIds = new Set<Id>();
        for (Functional_Queue_Member__c deletedMember : membersToRemove) {
            relatedGroupIds.add(deletedMember.Functional_Queue__r.Public_Group_ID__c);
        }
        List<GroupMember> relatedGroupMembers = [SELECT UserOrGroupId, GroupId FROM GroupMember WHERE GroupId IN :relatedGroupIds];

        Set<Id> groupMemberIdsToDelete = new Set<Id>();
        for (Functional_Queue_Member__c deletedMember : membersToRemove) {
            for (GroupMember relatedGroupMember : relatedGroupMembers) {
                if (
                    relatedGroupMember.UserOrGroupId == deletedMember.Contact_Member__r.User_ID__c &&
                    relatedGroupMember.GroupId == deletedMember.Functional_Queue__r.Public_Group_ID__c
                ) {
                    groupMemberIdsToDelete.add(relatedGroupMember.Id);
                }
            }
        }
        return groupMemberIdsToDelete;
    }

    @future
    public static void deleteFunctionalQueueGroupMembers(Set<Id> groupMemberIds) {
        List<GroupMember> groupMembersToDelete = [SELECT Id FROM GroupMember WHERE Id IN :groupMemberIds];
        delete groupMembersToDelete;
    }
}