sfdx-source/main/default/objects/VCC_Workstream_Settings__mdt/VCC_Workstream_Settings__mdt.object-meta.xml
<CustomObject>
    <description>Metadata to capture specific needs and settings per workstream (ex: Meds retrieval time frame)</description>
    <label>VCC Workstream Setting</label>
    <pluralLabel>VCC Workstream Settings</pluralLabel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Workstream_Settings__mdt/fields/VCC_Consults_Duration__c.field-meta.xml
<CustomField>
    <fullName>VCC_Consults_Duration__c</fullName>
    <description>This field determines the length of time in months that the component can pull from HDR.</description>
    <label>VCC Consults Duration</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/main/default/classes/VCC/VCC_ConsultsController.cls
/**
 * @author Kumar Balan
 * @group API - Bridg - Consults
 */
@SuppressWarnings('PMD')
public with sharing class VCC_ConsultsController {
    @AuraEnabled
    public static VCC_ConsultResponseWrp getConsults(VCC_ConsultLightningRequestWrp consultReqWrp) {
        /*if (!Test.isRunningTest() && VCC_TrainingModeService.isTrainingModeEnabled()) {
            VCC_ConsultResponseWrp consultResponseWrp = new VCC_ConsultResponseWrp();
            consultResponseWrp.consultModal = (VCC_ConsultModal) JSON.deserialize(VCC_TrainingModeService.getConsultsByAccountId(consultReqWrp.recordId), VCC_ConsultModal.class);
            return consultResponseWrp;
        }*/

        VCC_Workstream_Settings__mdt workstreamSettings = VCC_WorkstreamSettingsController.getWorkstreamSettings();
        VCC_BridgConsultsRQ consultsRQ = new VCC_BridgConsultsRQ(
            VCC_QuerySelector.getContactNationalID(consultReqWrp.recordId),
            'USVHA',
            Integer.valueOf(workstreamSettings.VCC_Consults_Duration__c)
        );

        return VCC_Adapter_BridgToLWC.vccConsult(
            (new VCC_BridgClient(new Set<VCC_BaseClient.ClientOption>{})).consults(consultsRQ)
        );
    }
}