sfdx-source/main/default/objects/VCC_Call_Tracking__c/VCC_Call_Tracking__c.object-meta.xml
<CustomObject>
    <description>The Call Tracking object is used to track unsuccessful outbound phone call attempts to a patient or caregiver at or after their scheduled appointment time, so that the CCC has documented date/timestamps of those attempts.</description>
    <label>Call Tracking</label>
    <nameField>
        <displayFormat>CALL-{00000}</displayFormat>
        <label>Call Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Tracking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VCC_Call_Tracking__c/fields/VCC_Call_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>VCC_Call_Date_Time__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>The date/time that the call has occurred</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Call Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/VCC_Call_Tracking__c/fields/VCC_Progress_Note__c.field-meta.xml
<CustomField>
    <fullName>VCC_Progress_Note__c</fullName>
    <label>Progress Note</label>
    <referenceTo>VCC_Progress_Note__c</referenceTo>
    <relationshipLabel>Call Tracking</relationshipLabel>
    <relationshipName>Call_Tracking</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/VCC_Progress_Note__c.object-meta.xml
<CustomObject>
    <description>Progress Notes</description>
    <label>Progress Note</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>Progress Note</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/VCR/VCR_CallTrackingRepo.cls
/**
 * @description This repository is for VCC_Call_Tracking__c Database Operations
 * @author Booz Allen
 * @see VTC_BaseRepo
 */
public virtual inherited sharing class VCR_CallTrackingRepo extends VTC_BaseRepo {
    /**
     * @description Constructor for the Call Tracking Repository. Calls super constructor which sets this.sObjectType to 'VCC_Call_Tracking__c'
     * Adds additional defaultSelectFields
     */
    public VCR_CallTrackingRepo() {
        super(VCC_Call_Tracking__c.SObjectType);
        this.defaultSelectFields.addAll(new Set<String>{ 'VCC_Call_Date_Time__c', 'CreatedDate' });
    }

    // Other queries can be copy pasted here.
    /**
     * @description Retrieves VCC_Call_Tracking__c data that is associated with the record Id passed in.
     * @param recordId - record id
     * @return List<VCC_Call_Tracking__c> - list of Call Tracking Date/Times and Created Dates matching the record id
     */
    public List<VCC_Call_Tracking__c> fetchCallTrackingList(String recordId) {
        Map<String, Object> bindParams = new Map<String, Object>();
        bindParams.put('recordId', recordId);
        String selectClause = this.calculateSelectClause(new Set<String>{ 'VCC_Call_Date_Time__c', 'CreatedDate' });
        String fromClause = this.calculateFromClause();
        String whereClause = 'WHERE VCC_Progress_Note__c = :recordId ';
        String orderByClause = 'ORDER BY VCC_Call_Date_Time__c ASC';
        String query = selectClause + ' ' + fromClause + ' ' + whereClause + orderByClause;
        return this.fetch(query, bindParams);
    }
}