sfdx-source/main/default/objects/Functional_Queue__c/Functional_Queue__c.object-meta.xml
<CustomObject>
    <description>Record used to represent a group and a queue in the backend when functional queue members are related to it.</description>
    <label>Functional Queue</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Functional Queue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functional Queues</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Functional_Queue__c/fields/Associated_Application__c.field-meta.xml
<CustomField>
    <fullName>Associated_Application__c</fullName>
    <label>Associated Application</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PSIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/Functional_Queue__c/fields/Public_Group_ID__c.field-meta.xml
<CustomField>
    <fullName>Public_Group_ID__c</fullName>
    <description>ID of the corresponding public group. This is autopopulated when a member is added to the functional queue.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Public Group ID will auto-populate after members are added to the functional queue.</inlineHelpText>
    <label>Public Group ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Functional_Queue__c/fields/Queue_ID__c.field-meta.xml
<CustomField>
    <fullName>Queue_ID__c</fullName>
    <description>Id of the corresponding Queue. This is autopopulated when a member is added to the functional queue.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Queue ID will auto-populate after members are added to the functional queue.</inlineHelpText>
    <label>Queue ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FunctionalQueueHandlerTest.cls
/**
 * @description       :
 * @author            : jonathon.schleicher@b3groupinc.com
 * @group             :
 * @last modified on  : 11-09-2021
 * @last modified by  : jonathon.schleicher@b3groupinc.com
 **/
@IsTest
public with sharing class FunctionalQueueHandlerTest {
    @IsTest
    public static void deleteFunctionalQueueGroups_givenDeletedFunctionalQueue_shouldDeleteCorrespondingGroupAndQueue() {
        Functional_Queue__c testFunctionalQueue = createTestFunctionalQueue('Test Functional Queue terst');
        insert testFunctionalQueue;
        Group testGroup = createTestGroup('test public group 123', 'Regular');
        Group testQueue = createTestGroup('test queue 123', 'Queue');
        testFunctionalQueue.Public_Group_ID__c = testGroup.Id;
        testFunctionalQueue.Queue_ID__c = testQueue.Id;

        Test.startTest();
        update testFunctionalQueue;
        Test.stopTest();

        delete testFunctionalQueue;

        List<Group> correspondingGroups = [SELECT Id FROM Group WHERE Id = :testGroup.Id OR Id = :testQueue.Id];
        System.assertEquals(0, correspondingGroups.size());
    }

    @isTest
    static void onAfterUpdate_givenUpdatedFunctionalQueueAssociatedApplications_updatesExpectedSupportedObjects() {
        Group queueTest = TestUtility.createQueue('queue test');
        insert queueTest;

        Functional_Queue__c functionalQueue = createTestFunctionalQueue('Test FuncQueue');
        functionalQueue.Associated_Application__c = null;
        functionalQueue.Queue_ID__c = queueTest.Id;
        insert functionalQueue;

        String associatedApplication = 'PSIP';
        functionalQueue.Associated_Application__c = associatedApplication;
        update functionalQueue;

        List<String> functionalQueueSupportedObjects = FunctionalQueueUtility.getFunctionalQueueSupportedObjectNamesByApp(associatedApplication);

        Test.startTest();
        List<QueueSobject> actualSupportedQueueObjects = [SELECT Id, SobjectType FROM QueueSobject WHERE QueueId = :functionalQueue.Id];
        Test.stopTest();

        if (actualSupportedQueueObjects.size() > 0) {
            for (QueueSobject queueObject : actualSupportedQueueObjects) {
                System.assert(functionalQueueSupportedObjects.contains(queueObject.SobjectType));
            }
        } else {
            System.debug('No Custom Metadata record exists for associated Application Name VIEWS');
        }
    }

    private static Functional_Queue__c createTestFunctionalQueue(String functionalQueueName) {
        Functional_Queue__c testFunctionalQueue = new Functional_Queue__c();
        testFunctionalQueue.Associated_Application__c = 'PSIP';
        testFunctionalQueue.Name = functionalQueueName;
        return testFunctionalQueue;
    }

    private static Group createTestGroup(String groupName, String groupType) {
        Group testGroup = new Group(Name = groupName, Type = groupType);
        insert testGroup;
        return testGroup;
    }
}