force-app/main/default/objects/PC_NDTH__c/PC_NDTH__c.object-meta.xml
<CustomObject>
    <description>Nationally Designated Telehealth Hub Reflects the meta data of a TOS</description>
    <label>PrC NDTH</label>
    <nameField>
        <displayFormat>PCNDTH- {0000000000}</displayFormat>
        <label>PrC NDTH Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrC NDTHs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PC_NDTH__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Check if the NDTH Agreement is active or not.</description>
    <inlineHelpText>If checkbox is checked, then NDTH is active</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/PC_NDTH_Service_Locations__c/PC_NDTH_Service_Locations__c.object-meta.xml
<CustomObject>
    <description>This is a junction object between Nationally Designated Telehealth Hubs and FLP Locations</description>
    <label>PrC NDTH Service Locations</label>
    <nameField>
        <displayFormat>FLPLOC-{0000000000}</displayFormat>
        <label>NDTH FLP Location Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrC NDTH Service Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/PC_NDTH_Service_Locations__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Check if the Service Location (FLP Location) under NDTH is active or not.</description>
    <inlineHelpText>If the checkbox is checked, then the Service Location is active.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PC_NDTH_Service_Locations__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>PrC NDTH Service Locations</relationshipLabel>
    <relationshipName>PrC_NDTH_Service_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PC_NDTH_Service_Locations__c/fields/NDTH__c.field-meta.xml
<CustomField>
    <fullName>NDTH__c</fullName>
    <label>NDTH</label>
    <referenceTo>PC_NDTH__c</referenceTo>
    <relationshipLabel>PrC NDTH Service Locations</relationshipLabel>
    <relationshipName>PC_NDTH_Service_Locations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/main/default/classes/PC/PC_NDTHServiceLocationRepo.cls
/**
 * @description Repository class for the PrC NDTH Service Locations object to hold its respective query and DML logic.
 * @author Booz Allen
 * @since  2024
 */
public inherited sharing class PC_NDTHServiceLocationRepo extends VTC_BaseRepo {
    /**
     * @description Constructor function for PC_NDTHServiceLocationRepo. Calls super constructor which sets this.sObjectType to 'PC_NDTH_Service_Locations__c'
     */
    public PC_NDTHServiceLocationRepo() {
        super(PC_NDTH_Service_Locations__c.sObjectType);
        this.defaultSelectFields = new Set<String>{ 'Id', 'NDTH__c' };
    }

    /**
     * @description             retrieves a list of NDTH Service Location junctions that are related to a given Location
     * @param serviceLocationId the Id of the Location
     * @return                  `List<PC_NDTH_Service_Locations__c>` List of NDTH Service Location junctions related to the given Location
     */
    public List<PC_NDTH_Service_Locations__c> getNDTHServiceLocsFromLocId(Id serviceLocationId) {
        String selectClause = this.calculateSelectClause(this.defaultSelectFields);
        String fromClause = this.calculateFromClause();
        String whereClause = 'WHERE Location__c = :serviceLocationId AND Is_Active__c = TRUE AND NDTH__r.Is_Active__c = TRUE';
        String query = selectClause + ' ' + fromClause + ' ' + whereClause;
        return (List<PC_NDTH_Service_Locations__c>) this.fetch(
            query,
            new Map<String, Object>{ 'serviceLocationId' => serviceLocationId }
        );
    }

    /**
     * @description             gets a Set of IDs for NDTH agreements that are available for a given Location
     * @param serviceLocationId the Id of the Location
     * @return                  `Set<Id>` set of NDTH Ids
     */
    public Set<Id> getNDTHsIdSetFromLocation(Id serviceLocationId) {
        Set<Id> ndthIdSet = new Set<Id>();
        for (PC_NDTH_Service_Locations__c ndthServiceLocation : this.getNDTHServiceLocsFromLocId(serviceLocationId)) {
            ndthIdSet.add(ndthServiceLocation.NDTH__c);
        }
        return ndthIdSet;
    }

    /**
     * @description             gets a Set of IDs for NDTH agreements that are available for a given Location
     *                          throws an exception if there are no NDTH Agreements servicing your current location
     * @param serviceLocationId the Id of the Location
     * @return                  `Set<Id>` set of NDTH Ids
     */
    public Set<Id> getNDTHsIdSetFromLocationWithEmptyResultHandling(Id serviceLocationId) {
        Set<Id> ndthIdSet = this.getNDTHsIdSetFromLocation(serviceLocationId);

        if ((ndthIdSet == null || ndthIdSet.isEmpty())) {
            throw new PC_CustomException(System.Label.PC_No_NDTH_Agreements);
        } else {
            return ndthIdSet;
        }
    }
}