force-app/main/default/objects/PC_NDTH__c/PC_NDTH__c.object-meta.xml
<CustomObject>
    <description>Nationally Designated Telehealth Hub Reflects the meta data of a TOS</description>
    <label>PrC NDTH</label>
    <nameField>
        <displayFormat>PCNDTH- {0000000000}</displayFormat>
        <label>PrC NDTH Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrC NDTHs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PC_NDTH__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Check if the NDTH Agreement is active or not.</description>
    <inlineHelpText>If checkbox is checked, then NDTH is active</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/PC_NDTH__c/fields/NDTH_Name__c.field-meta.xml
<CustomField>
    <fullName>NDTH_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Telehealth Hub Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/PC_NDTH__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description
    >Field is required so that user can select whether a Nationally Designated Telehealth Hub (NDTH) is related to a Terms of Service Agreement (TOS) or Telehealth Service
        Agreement (TSA).</description>
    <inlineHelpText>Field is required to select whether agreement is TOS or TSA.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TOS</fullName>
            </value>
            <value>
                <fullName>TSA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PC_NDTH_Host_Locations__c/PC_NDTH_Host_Locations__c.object-meta.xml
<CustomObject>
    <description>This is a junction object between Nationally Designated Telehealth Hubs and Specialists Facility/Locations</description>
    <label>PrC NDTH Host Locations</label>
    <nameField>
        <displayFormat>SPLLOC-{0000000000}</displayFormat>
        <label>NDTH Specialist Location Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrC NDTH Host Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/PC_NDTH_Host_Locations__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Check if the Host Location (Specialist Location) under NDTH is active or
not.</description>
    <inlineHelpText>If the checkbox is checked, then the Host Location is active.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/PC_NDTH_Host_Locations__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>PrC NDTH Host Locations</relationshipLabel>
    <relationshipName>PrC_NDTH_Host_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/main/default/objects/PC_NDTH_Host_Locations__c/fields/NDTH__c.field-meta.xml
<CustomField>
    <fullName>NDTH__c</fullName>
    <label>NDTH ID</label>
    <referenceTo>PC_NDTH__c</referenceTo>
    <relationshipLabel>PrC NDTH Host Locations</relationshipLabel>
    <relationshipName>PC_NDTH_Host_Locations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PC/PC_NDTHHostLocationRepoTest.cls
/**
 * @description test class for PC_NDTHHostLocationRepo
 * @author      Booz Allen
 * @since       2024
 * @see         PC_NDTHHostLocationRepo
 */
@IsTest
private with sharing class PC_NDTHHostLocationRepoTest {
    private final static PC_NDTHHostLocationRepo REPO_TO_TEST;
    private final static User FLP_USER;
    static {
        //mixed DML error workaround
        System.runAs(new User(Id = UserInfo.getUserId())) {
            FLP_USER = new VATEST_UserBuilder()
                .withUserProfile('VAVET Base Profile')
                .withStandardData()
                .withPermissionSet('PrC_FLP_Users')
                .build(true);

            REPO_TO_TEST = new PC_NDTHHostLocationRepo();
        }
    }

    /**
     * @description test setup for re-usable data
     */
    @testSetup
    private static void testSetup() {
        //create NDTH data
        PC_NDTH__c ndth = (PC_NDTH__c) VATEST_SObjectFactory.createSObject(
            new PC_NDTH__c(NDTH_Name__c = 'Test Telehealth Hub', Type__c = 'TOS', Is_Active__c = true),
            true
        );

        Schema.Location location1 = (Schema.Location) VATEST_SObjectFactory.createSObject(
            new Schema.Location(
                Name = 'Test Location1',
                RecordTypeId = Schema.SObjectType.Location.getRecordTypeInfosByName()
                    .get('VA Facility')
                    .getRecordTypeId(),
                VAF_Facility_Type__c = 'va_health_facility',
                LocationType = 'Site',
                VAF_Facility_ID__c = '100'
            ),
            true
        );

        VATEST_SObjectFactory.createSObject(
            new PC_NDTH_Host_Locations__c(NDTH__c = ndth.Id, Location__c = location1.Id, Is_Active__c = true),
            true
        );
    }

    /**
     * @description positive test of getSpecialistLocationIdsForNDTHsWithEmptyResultHandling method (and incidentally also the getSpecialistLocationIdsForNDTHs method)
     */
    @IsTest
    private static void funcGetSpecialistLocationIdsForNDTHsPositive() {
        // Test data setup
        Id ndthId = [SELECT Id FROM PC_NDTH__c WHERE NDTH_Name__c = 'Test Telehealth Hub' LIMIT 1].Id;

        User runAsUser = FLP_USER;

        VATEST_SObjectFactory.createSObject(
            new PC_NDTH__Share(
                ParentId = ndthId,
                UserOrGroupId = runAsUser.Id,
                RowCause = 'Manual',
                AccessLevel = 'Read'
            ),
            true
        );

        // Actual test
        Test.startTest();

        Set<Id> results;
        System.runAs(runAsUser) {
            results = REPO_TO_TEST.getSpecialistLocationIdsForNDTHsWithEmptyResultHandling(new Set<Id>{ ndthId });
        }

        Test.stopTest();

        // Asserts
        Assert.isTrue(
            results.size() > 0,
            'Expected the Test Telehealth Hub\'s host locations to be retrieved successfully, but they were not.'
        );
    }

    /**
     * @description negative test of getSpecialistLocationIdsForNDTHsWithEmptyResultHandling method that should thrown an exception due to no query results
     */
    @IsTest
    private static void funcGetSpecialistLocationIdsForNDTHsNegative() {
        // Test data setup
        User runAsUser = FLP_USER;

        Id ndthId = [SELECT Id FROM PC_NDTH__c WHERE NDTH_Name__c = 'Test Telehealth Hub' LIMIT 1].Id;

        //delete all existing host location junctions tied to our test NDTH
        delete [SELECT ID FROM PC_NDTH_Host_Locations__c WHERE NDTH__c = :ndthId];

        Boolean threwError = false;

        // Actual test
        Test.startTest();

        System.runAs(runAsUser) {
            try {
                REPO_TO_TEST.getSpecialistLocationIdsForNDTHsWithEmptyResultHandling(new Set<Id>{ ndthId });
            } catch (Exception caughtException) {
                threwError = true;
            }
        }

        Test.stopTest();

        // Asserts
        Assert.isTrue(
            threwError,
            'Expected the getSpecialistLocationIdsForNDTHsWithEmptyResultHandling method to throw an exception due to no results from the query, but no exception was thrown.'
        );
    }
}