force-app/main/default/objects/PC_NDTH__c/PC_NDTH__c.object-meta.xml
<CustomObject>
    <description>Nationally Designated Telehealth Hub Reflects the meta data of a TOS</description>
    <label>PrC NDTH</label>
    <nameField>
        <displayFormat>PCNDTH- {0000000000}</displayFormat>
        <label>PrC NDTH Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrC NDTHs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PC_NDTH__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Check if the NDTH Agreement is active or not.</description>
    <inlineHelpText>If checkbox is checked, then NDTH is active</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/PC_NDTH_Clinical_Services__c/PC_NDTH_Clinical_Services__c.object-meta.xml
<CustomObject>
    <description>Child Object of a Master-Detail with PrC NDTH object. This object will store the available clinical service records for the NDTH object.</description>
    <label>PrC NDTH Clinical Services</label>
    <nameField>
        <displayFormat>NDTHSERV- {0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrC NDTH Clinical Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PC_NDTH_Clinical_Services__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Check if Clinical Services under NDTH is active or not.</description>
    <inlineHelpText>If checkbox is checked, then the Clinical Service is active</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/PC_NDTH_Clinical_Services__c/fields/NDTH__c.field-meta.xml
<CustomField>
    <fullName>NDTH__c</fullName>
    <label>NDTH</label>
    <referenceTo>PC_NDTH__c</referenceTo>
    <relationshipLabel>PrC NDTH Clinical Services</relationshipLabel>
    <relationshipName>PC_NDTH_Clinical_Services</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/main/default/objects/PC_NDTH_Clinical_Services__c/fields/PC_Specialty__c.field-meta.xml
<CustomField>
    <fullName>PC_Specialty__c</fullName>
    <description>Skill dropdown will be displayed based on the PC Specialties global value set. This field will identify the skill associated with the NDTH object.</description>
    <label>Specialty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PC_Specialties</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/PC_Specialties.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Addiction Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>Allergy/Immunology</fullName>
    </customValue>
    <customValue>
        <fullName>Amputation Clinic</fullName>
    </customValue>
    <customValue>
        <fullName>Anesthesiology</fullName>
    </customValue>
    <customValue>
        <fullName>Anti-Coagulation Clinic</fullName>
    </customValue>
    <customValue>
        <fullName>Audiology</fullName>
    </customValue>
    <customValue>
        <fullName>Blood Pressure Evaluation</fullName>
    </customValue>
    <customValue>
        <fullName>Brain Injury</fullName>
    </customValue>
    <customValue>
        <fullName>Bros (Blind Rehab O/P Spec)</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiac Catheterization</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiac Implantable Electronic Devices (Cied)</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiac Surgery</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiology</fullName>
    </customValue>
    <customValue>
        <fullName>Chart Consult</fullName>
    </customValue>
    <customValue>
        <fullName>Clinical Pharmacy</fullName>
    </customValue>
    <customValue>
        <fullName>Community Care Consult</fullName>
    </customValue>
    <customValue>
        <fullName>Community Nursing Home (Cnh) Follow-Up</fullName>
    </customValue>
    <customValue>
        <fullName>Computerized Tomography (Ct)</fullName>
    </customValue>
    <customValue>
        <fullName>Cysto Room Unit For Outpatient</fullName>
    </customValue>
    <customValue>
        <fullName>Dental</fullName>
    </customValue>
    <customValue>
        <fullName>Dermatology</fullName>
    </customValue>
    <customValue>
        <fullName>Diabetes</fullName>
    </customValue>
    <customValue>
        <fullName>Eeg</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>Endocrinology</fullName>
    </customValue>
    <customValue>
        <fullName>Epilepsy</fullName>
    </customValue>
    <customValue>
        <fullName>Eye Telehealth Screening</fullName>
    </customValue>
    <customValue>
        <fullName>Gastroenterology</fullName>
    </customValue>
    <customValue>
        <fullName>General Internal Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>General Surgery</fullName>
    </customValue>
    <description>DO NOT CHANGE API NAME OF PICKLIST VALUES</description>
    <masterLabel>PC Specialties</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/PC/PC_NDTHClinicalServicesRepo.cls
/**
 * @description Repository class for the PrC NDTH Clinical Services object to hold its respective query and DML logic.
 * @author Booz Allen
 * @since  2024
 */
public inherited sharing class PC_NDTHClinicalServicesRepo extends VTC_BaseRepo {
    /**
     * @description Constructor function for PC_NDTHClinicalServicesRepo. Calls super constructor which sets this.sObjectType to 'PC_NDTH_Clinical_Services__c'
     */
    public PC_NDTHClinicalServicesRepo() {
        super(PC_NDTH_Clinical_Services__c.sObjectType);
    }

    /**
     * @description     Gets a list of Clinical Services junctions related to the provided NDTH agreements
     * @param ndthIdSet NDTH agreement ids
     * @return          `List<PC_NDTH_Clinical_Services__c>` list of Clinical Service Junctions (with a selected Speciality) related to the NDTH agreements
     */
    public List<PC_NDTH_Clinical_Services__c> getClinicalServicesFromNDTHs(Set<Id> ndthIdSet) {
        String selectClause = 'SELECT PC_Specialty__c';
        String fromClause = this.calculateFromClause();
        String whereClause = 'WHERE NDTH__c IN :ndthIdSet AND PC_Specialty__c != NULL AND Is_Active__c = TRUE AND NDTH__r.Is_Active__c = TRUE';
        String query = selectClause + ' ' + fromClause + ' ' + whereClause;
        return (List<PC_NDTH_Clinical_Services__c>) this.fetch(
            query,
            new Map<String, Object>{ 'ndthIdSet' => ndthIdSet }
        );
    }

    /**
     * @description     Gets a list of Clinical Services junctions related to the provided NDTH agreements and skill (specialty)
     * @param ndthIdSet NDTH agreement ids
     * @param skillName resource skill name (specialty)
     * @return          `List<PC_NDTH_Clinical_Services__c>` list of Clinical Service Junctions (with a selected Speciality) related to the NDTH agreements and skill
     */
    public List<PC_NDTH_Clinical_Services__c> getClinicalServicesFromNDTHsandSkills(
        Set<Id> ndthIdSet,
        String skillName
    ) {
        String selectClause = 'SELECT Id, PC_Specialty__c, NDTH__c';
        String fromClause = this.calculateFromClause();
        String whereClause = 'WHERE NDTH__c IN :ndthIdSet AND PC_Specialty__c = :skillName AND Is_Active__c = TRUE AND NDTH__r.Is_Active__c = TRUE';
        String query = selectClause + ' ' + fromClause + ' ' + whereClause;
        return (List<PC_NDTH_Clinical_Services__c>) this.fetch(
            query,
            new Map<String, Object>{ 'ndthIdSet' => ndthIdSet, 'skillName' => skillName }
        );
    }

    /**
     * @description     Gets a list of names for Specialties (Skills) provided by NDTH agreements (via a Clinical Service junction)
     * @param ndthIdSet set of NDTH agreement ids
     * @return          `Set<String>` list of Specialty names
     */
    public Set<String> getSpecialtiesForNDTHs(Set<Id> ndthIdSet) {
        Set<String> specialtiesSet = new Set<String>();
        for (PC_NDTH_Clinical_Services__c ndthClinicalService : this.getClinicalServicesFromNDTHs(ndthIdSet)) {
            specialtiesSet.add(ndthClinicalService.PC_Specialty__c);
        }
        return specialtiesSet;
    }

    /**
     * @description     Gets a list of names for Specialties (Skills) provided by NDTH agreements (via a Clinical Service junction)
     * @throw           throws exception if no Specialties available under the NDTH Agreements servicing your current location
     * @param ndthIdSet set of NDTH agreement ids
     * @return          `Set<String>` list of Specialty names
     */
    public Set<String> getSpecialtiesForNDTHsWithEmptyResultHandling(Set<Id> ndthIdSet) {
        Set<String> specialtiesSet = this.getSpecialtiesForNDTHs(ndthIdSet);

        if ((specialtiesSet == null || specialtiesSet.isEmpty())) {
            throw new PC_CustomException(System.Label.PC_No_Specialties_Available);
        } else {
            return specialtiesSet;
        }
    }
}