force-app/main/default/objects/PC_Case__c/PC_Case__c.object-meta.xml
<CustomObject>
    <description>Object to hold Provider Connect cases</description>
    <label>PrC Case</label>
    <nameField>
        <displayFormat>PCC-{0000000000}</displayFormat>
        <label>Provider Connect Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrC Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/PC_Case_Feedback_Answer__c/PC_Case_Feedback_Answer__c.object-meta.xml
<CustomObject>
    <label>PrC Case Feedback Answer</label>
    <nameField>
        <displayFormat>PCCFA-{00000}</displayFormat>
        <label>PC Case Feedback Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrC Case Feedback Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PC_Case_Feedback_Answer__c/fields/PC_Answer__c.field-meta.xml
<CustomField>
    <fullName>PC_Answer__c</fullName>
    <label>Answer</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/PC_Case_Feedback_Answer__c/fields/PC_Question__c.field-meta.xml
<CustomField>
    <fullName>PC_Question__c</fullName>
    <label>Question</label>
    <referenceTo>PC_Case_Feedback_Question__c</referenceTo>
    <relationshipName>PC_Survey_Question_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/main/default/objects/PC_Case_Feedback_Answer__c/fields/Provider_Connect_Case__c.field-meta.xml
<CustomField>
    <fullName>Provider_Connect_Case__c</fullName>
    <description>Provider Connect Case to which this feedback answer relates</description>
    <label>Provider Connect Case</label>
    <referenceTo>PC_Case__c</referenceTo>
    <relationshipLabel>PC Case Feedback Answers</relationshipLabel>
    <relationshipName>PC_Case_Feedback_Answers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PC_Case_Feedback_Question__c/PC_Case_Feedback_Question__c.object-meta.xml
<CustomObject>
    <description>Questions for the case feedback.</description>
    <label>PrC Case Feedback Question</label>
    <nameField>
        <displayFormat>PCCFQ-{00000}</displayFormat>
        <label>PC Case Feedback Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrC Case Feedback Questions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PC_Case_Feedback_Question__c/fields/PC_Active__c.field-meta.xml
<CustomField>
    <fullName>PC_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Determines if the question is available to use.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/PC_Case_Feedback_Question__c/fields/PC_Question__c.field-meta.xml
<CustomField>
    <fullName>PC_Question__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Question</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

sfdx-source/main/default/objects/PC_Case_Feedback_Question__c/fields/PC_Role__c.field-meta.xml
<CustomField>
    <fullName>PC_Role__c</fullName>
    <description>Ability to distinguish between survey customer.</description>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Specialist</fullName>
            </value>
            <value>
                <fullName>FLP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/classes/PC/PC_CaseFeedbackController.cls
/**
 * @description       : controller class for pcCaseFeedback LWC component
 * @author            : WagnerJ@BAH
 * @group             :
 * @last modified on  : 07-25-2023
 * @last modified by  : WagnerJ@BAH
 **/
public without sharing class PC_CaseFeedbackController {
    /**
     * @description repository for custom PC Case Feedback Answer object
     */
    @TestVisible
    private static PC_CaseFeedbackAnswerRepo caseFeedbackAnswerRepo {
        get {
            if (caseFeedbackAnswerRepo == null) {
                caseFeedbackAnswerRepo = new PC_CaseFeedbackAnswerRepo();
            }
            return caseFeedbackAnswerRepo;
        }
        set;
    }
    /**
     * @description repository for custom PC Case object
     */
    @TestVisible
    private static PC_PrcCaseRepo prcCaseRepo {
        get {
            if (prcCaseRepo == null) {
                prcCaseRepo = new PC_PrcCaseRepo();
            }
            return prcCaseRepo;
        }
        set;
    }

    /**
     * @description check if feedback has already submitted submitted on this case for the specified role
     * @author WagnerJ@BAH | 07-25-2023
     * @param Id recordId
     * @param String role
     * @return Boolean
     **/
    @AuraEnabled(cacheable=true)
    public static Boolean getIsSubmitted(Id recordId, String role) {
        return [
                SELECT Id
                FROM PC_Case_Feedback_Answer__c
                WHERE
                    Provider_Connect_Case__c = :recordId
                    AND PC_Question__r.PC_Role__c = :role
                    AND PC_Question__r.PC_Active__c = TRUE
                WITH SECURITY_ENFORCED
                LIMIT 1
            ]
            .size() > 0;
    }

    /**
     * @description get a list of active case feedback questions for the specified role. The results are returned in pre-prepared feedback answer records for use on the front end.
     * @author WagnerJ@BAH | 07-25-2023
     * @param Id recordId
     * @param String role
     * @return List<PC_Case_Feedback_Answer__c>
     **/
    @AuraEnabled(cacheable=true)
    public static List<PC_Case_Feedback_Answer__c> getFeedbackQuestions(Id recordId, String role) {
        List<PC_Case_Feedback_Answer__c> feedbackAnswerList = new List<PC_Case_Feedback_Answer__c>();

        List<PC_Case_Feedback_Question__c> feedbackQuestionList = [
            SELECT Id, Name, PC_Question__c
            FROM PC_Case_Feedback_Question__c
            WHERE PC_Role__c = :role AND PC_Active__c = TRUE
            WITH SECURITY_ENFORCED
        ];

        for (PC_Case_Feedback_Question__c question : feedbackQuestionList) {
            feedbackAnswerList.add(
                new PC_Case_Feedback_Answer__c(
                    Provider_Connect_Case__c = recordId,
                    PC_Question__c = question.Id,
                    PC_Question__r = question,
                    PC_Answer__c = ''
                )
            );
        }

        return feedbackAnswerList;
    }

    /**
     * @description submit the feedback answers filled out by the user on the front end for insertion
     * @author WagnerJ@BAH | 07-25-2023
     * @param String feedbackAnswersJSON
     **/
    @AuraEnabled
    public static void submitFeedback(String feedbackAnswersJSON) {
        List<PC_Case_Feedback_Answer__c> feedbackAnswersList = (List<PC_Case_Feedback_Answer__c>) JSON.deserialize(
            feedbackAnswersJSON,
            List<PC_Case_Feedback_Answer__c>.class
        );

        //System.debug(feedbackAnswersList);

        try {
            if (!Schema.sObjectType.PC_Case_Feedback_Answer__c.isCreateable()) {
                throw new PC_CustomException(
                    'You do not have the permissions required to submit case feedback. Please contact your System Administrator for assistance.'
                );
            }
            insert feedbackAnswersList;
        } catch (Exception e) {
            log_LogService.log('PC_CaseFeedbackController.submitFeedback Exception', log_LogService.LogType.ERROR, e);
            log_LogService.publish();
            throw new AuraHandledException(e.getMessage());
        }
    }
    /**
     * @description Get cases needing feedback for a specified individual (last 60 days)
     * @author Edwin Schaeffer | 07-27-2023
     * @param void
     * @return Map<Id, PC_Case__c>
     **/
    @AuraEnabled(cacheable=true)
    public static Map<Id, PC_Case__c> getCasesNeedingFeedback() {
        Id userId = UserInfo.getUserId();
        // Defining the PCP on a case as one who CREATED the case and the Specialist as one who OWNS the case.
        // Currently Specialists do not have access to the Provider Connect super screen to create cases.

        List<PC_Case__c> cases = prcCaseRepo.getRecentlyClosedCasesForUser(userId);

        Map<Id, PC_Case__c> caseMap = new Map<Id, PC_Case__c>(cases);

        List<PC_Case_Feedback_Answer__c> answers = caseFeedbackAnswerRepo.getFeedbackAnswersFromPrcCases(
            caseMap.keySet()
        );

        // If the user answered just one question as a PCP or Specialist, the Feedback is considered complete.
        for (PC_Case_Feedback_Answer__c ans : answers) {
            if (caseMap.containsKey(ans.Provider_Connect_Case__c)) {
                caseMap.remove(ans.Provider_Connect_Case__c);
            }
        }
        return caseMap;
    }
}