force-app/main/default/objects/PC_Case__c/PC_Case__c.object-meta.xml
<CustomObject>
    <description>Object to hold Provider Connect cases</description>
    <label>PrC Case</label>
    <nameField>
        <displayFormat>PCC-{0000000000}</displayFormat>
        <label>Provider Connect Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrC Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PC_Case__c/fields/Closed__c.field-meta.xml
<CustomField>
    <fullName>Closed__c</fullName>
    <formula>IF(ISBLANK(Closed_Date__c),FALSE,TRUE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Closed</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/PC_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Note</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed Resolved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/classes/PC/PC_CancelCaseController.cls
/**
 * @description Class is responsible for providing data to multiple LWC components and Apex classes for Provider Connect.
 * @author      Booz Allen Hamilton
 * @see         pcCancelCase Lighting Web Component
 **/

public with sharing class PC_CancelCaseController {
    @TestVisible
    private static final String CASE_ID_BLANK_ERROR_MESSAGE = System.Label.CASE_ID_BLANK_ERROR_MESSAGE;
    @TestVisible
    private static final String CASE_ALREADY_CLOSED_STATUS = System.Label.CASE_ALREADY_CLOSED_STATUS;
    @TestVisible
    private static final String CASE_CANCELED_STATUS = System.Label.CASE_CANCELED_STATUS;
    private static final String CLOSED_CASE = 'Closed__c';

    /**
     * @description repository for custom PC Case object
     */
    @TestVisible
    private static PC_PrcCaseRepo prcCaseRepo {
        get {
            return prcCaseRepo = prcCaseRepo ?? new PC_PrcCaseRepo();
        }
        set;
    }

    /**
     * @description Method to cancel the specified case
     * @param caseId - String value of the ProviderConnect Case Id
     * @return       `PC_Case__c` Closed case
     **/
    @AuraEnabled
    public static PC_Case__c cancelCase(String caseId) {
        if (String.isBlank(caseId)) {
            throw new PC_CustomException(CASE_ID_BLANK_ERROR_MESSAGE);
        }

        try {
            PC_Case__c caseToCancel = (PC_Case__c) prcCaseRepo.fetchById(caseId, new Set<String>{ CLOSED_CASE });

            if (caseToCancel.Closed__c) {
                throw new PC_CustomException(CASE_ALREADY_CLOSED_STATUS);
            }
            caseToCancel.Status__c = CASE_CANCELED_STATUS;
            prcCaseRepo.doUpdate(caseToCancel);

            return caseToCancel;
        } catch (Exception caughtException) {
            throw PC_ExceptionUtils.logAndCreateAuraHandledException(caughtException.getMessage(), caughtException);
        }
    }
}