force-app/main/default/objects/PC_Case__c/PC_Case__c.object-meta.xml
<CustomObject>
    <description>Object to hold Provider Connect cases</description>
    <label>PrC Case</label>
    <nameField>
        <displayFormat>PCC-{0000000000}</displayFormat>
        <label>Provider Connect Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrC Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PC_Case__c/fields/Case_Details__c.field-meta.xml
<CustomField>
    <fullName>Case_Details__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Reason for Consultation</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/main/default/objects/PC_Case__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Teams</fullName>
                <label>Teams Video</label>
            </value>
            <value>
                <fullName>Phone</fullName>
                <label>Phone Callback</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PC_Case__c/fields/Closed__c.field-meta.xml
<CustomField>
    <fullName>Closed__c</fullName>
    <formula>IF(ISBLANK(Closed_Date__c),FALSE,TRUE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PC_Case__c/fields/Patient_Account__c.field-meta.xml
<CustomField>
    <fullName>Patient_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookups up to the related a Veteran&apos;s Account record.</description>
    <inlineHelpText>Veteran&apos;s related Account record.</inlineHelpText>
    <label>Patient Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PrC Cases</relationshipLabel>
    <relationshipName>PrC_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PC_Case__c/fields/PCP__c.field-meta.xml
<CustomField>
    <fullName>PCP__c</fullName>
    <description>The PCP who created the case</description>
    <formula>CreatedBy.FirstName &amp; &quot; &quot; &amp; CreatedBy.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FLP</label>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/PC_Case__c/fields/Specialist_Notes__c.field-meta.xml
<CustomField>
    <fullName>Specialist_Notes__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Specialist Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PC_Case__c/fields/Specialty__c.field-meta.xml
<CustomField>
    <fullName>Specialty__c</fullName>
    <label>Specialty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PC_Specialties</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/PC_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Note</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed Resolved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PC_Case__c/fields/Training_Case__c.field-meta.xml
<CustomField>
    <fullName>Training_Case__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allows users to identify when a record was created for training purposes only.</description>
    <inlineHelpText>If checked this case record is used for training purposes only.</inlineHelpText>
    <label>Training Case</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/PC_Case__c/recordTypes/Provider_Connect_Case.recordType-meta.xml
<RecordType>
    <fullName>Provider_Connect_Case</fullName>
    <active>true</active>
    <label>Provider Connect Case</label>
</RecordType>

force-app/main/default/globalValueSets/PC_Specialties.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Addiction Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>Allergy/Immunology</fullName>
    </customValue>
    <customValue>
        <fullName>Amputation Clinic</fullName>
    </customValue>
    <customValue>
        <fullName>Anesthesiology</fullName>
    </customValue>
    <customValue>
        <fullName>Anti-Coagulation Clinic</fullName>
    </customValue>
    <customValue>
        <fullName>Audiology</fullName>
    </customValue>
    <customValue>
        <fullName>Blood Pressure Evaluation</fullName>
    </customValue>
    <customValue>
        <fullName>Brain Injury</fullName>
    </customValue>
    <customValue>
        <fullName>Bros (Blind Rehab O/P Spec)</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiac Catheterization</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiac Implantable Electronic Devices (Cied)</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiac Surgery</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiology</fullName>
    </customValue>
    <customValue>
        <fullName>Chart Consult</fullName>
    </customValue>
    <customValue>
        <fullName>Clinical Pharmacy</fullName>
    </customValue>
    <customValue>
        <fullName>Community Care Consult</fullName>
    </customValue>
    <customValue>
        <fullName>Community Nursing Home (Cnh) Follow-Up</fullName>
    </customValue>
    <customValue>
        <fullName>Computerized Tomography (Ct)</fullName>
    </customValue>
    <customValue>
        <fullName>Cysto Room Unit For Outpatient</fullName>
    </customValue>
    <customValue>
        <fullName>Dental</fullName>
    </customValue>
    <customValue>
        <fullName>Dermatology</fullName>
    </customValue>
    <customValue>
        <fullName>Diabetes</fullName>
    </customValue>
    <customValue>
        <fullName>Eeg</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>Endocrinology</fullName>
    </customValue>
    <customValue>
        <fullName>Epilepsy</fullName>
    </customValue>
    <customValue>
        <fullName>Eye Telehealth Screening</fullName>
    </customValue>
    <customValue>
        <fullName>Gastroenterology</fullName>
    </customValue>
    <customValue>
        <fullName>General Internal Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>General Surgery</fullName>
    </customValue>
    <description>DO NOT CHANGE API NAME OF PICKLIST VALUES</description>
    <masterLabel>PC Specialties</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

sfdx-source/main/default/classes/PC/PC_PrcCaseRepo.cls
/**
 * @description Repository class for the PC_Case__c object to hold its respective query and DML logic.
 * @author      Booz Allen Hamilton
 */
public inherited sharing class PC_PrcCaseRepo extends VTC_BaseRepo {
    private static final Map<String, Schema.SObjectField> PC_CASE_FIELD_MAP = PC_Case__c.SobjectType.getDescribe(
            Schema.SObjectDescribeOptions.DEFERRED
        )
        .fields.getMap();

    /**
     * @description Constructor function for PC_PrcCaseRepo. Calls super constructor which sets this.sObjectType to 'PC_Case__c'
     */
    public PC_PrcCaseRepo() {
        super(PC_Case__c.sObjectType);
    }

    /**
     * @description  retrieves a list of open PC Cases owned by the provided user in SF
     * @param userId SF User Id of the owner for the PC Cases to retrieve
     * @return       `List<PC_Case__c>` list of Open PC Cases owned by the provided user
     */
    public List<PC_Case__c> getOpenPrcCasesOwnedByUser(Id userId) {
        Map<String, Object> bindParams = new Map<String, Object>{
            'recordTypeId' => this.recordTypeConstant.fromDeveloperName('Provider_Connect_Case').Id,
            'userId' => userId
        };
        String selectClause = 'SELECT Id, Specialist_Notes__c';
        String fromClause = this.calculateFromClause();
        String whereClause = 'WHERE RecordTypeId = :recordTypeId AND OwnerId = :userId AND Closed__c = FALSE ';
        String query = selectClause + ' ' + fromClause + ' ' + whereClause;
        return (List<PC_Case__c>) this.fetch(query, bindParams);
    }

    /**
     * @description  retrieves the oldest open PC Case owned by the provided user in SF
     * @param userId User Id of the owner for the PC Cases
     * @return       `List<PC_Case__c>` list of Open PC Cases owned by the provided user
     */
    public List<PC_Case__c> getOldestOpenPrcCaseOwnedByUser(Id userId) {
        Map<String, Object> bindParams = new Map<String, Object>{
            'recordTypeId' => this.recordTypeConstant.fromDeveloperName('Provider_Connect_Case').Id,
            'userId' => userId
        };

        String selectClause = 'SELECT Id, Name, Specialty__c, PCP__c, Case_Details__c, CreatedDate, Specialist_Notes__c';
        if (this.isFieldReadableByRunningUser('Patient_Account__c')) {
            selectClause += ', Patient_Account__c, Patient_Account__r.Name';
        }
        String fromClause = this.calculateFromClause();
        String whereClause = 'WHERE RecordTypeId = :recordTypeId AND OwnerId = :userId AND Status__c = \'Open\'';
        String query = selectClause + ' ' + fromClause + ' ' + whereClause + ' Order By CreatedDate ASC LIMIT 1';
        return (List<PC_Case__c>) this.fetch(query, bindParams);
    }

    /**
     * @description gets a list of PrC Cases where related Case Feedback Answers are needed
     * @param userId User Id of logged in person
     * @return 'List<PC_Case__c>' list of PrC Case to be evaluated
     */
    public List<PC_Case__c> getRecentlyClosedCasesForUser(Id userId) {
        String selectClause = 'SELECT Id,Name,CreatedDate,Specialty__c,Channel__c,OwnerId,CreatedById';
        String fromClause = this.calculateFromClause();
        String whereClause = 'WHERE CreatedDate = LAST_N_DAYS:60 AND (OwnerId = :userId OR CreatedById = :userId) AND Closed__c = TRUE AND Status__c != \'Cancelled\' AND Training_Case__c = FALSE';
        String query = selectClause + ' ' + fromClause + ' ' + whereClause;
        return (List<PC_Case__c>) this.fetch(query, new Map<String, Object>{ 'userId' => userId });
    }

    /**
     * @description     checks if the running user has read access to the provided field on the PrC Case object
     * @param fieldName API name of the field to check
     * @return          `Boolean` true if the running user has read access to the field
     */
    private Boolean isFieldReadableByRunningUser(String fieldName) {
        return PC_CASE_FIELD_MAP.containsKey(fieldName) &&
            PC_CASE_FIELD_MAP.get(fieldName).getDescribe().isAccessible();
    }
}