force-app/main/default/objects/PC_Case__c/PC_Case__c.object-meta.xml
<CustomObject>
    <description>Object to hold Provider Connect cases</description>
    <label>PrC Case</label>
    <nameField>
        <displayFormat>PCC-{0000000000}</displayFormat>
        <label>Provider Connect Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrC Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PC_Case__c/fields/Callback_Number__c.field-meta.xml
<CustomField>
    <fullName>Callback_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Callback Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PC_Case__c/fields/Case_Details__c.field-meta.xml
<CustomField>
    <fullName>Case_Details__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Reason for Consultation</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/main/default/objects/PC_Case__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Teams</fullName>
                <label>Teams Video</label>
            </value>
            <value>
                <fullName>Phone</fullName>
                <label>Phone Callback</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PC_Case__c/fields/Closed__c.field-meta.xml
<CustomField>
    <fullName>Closed__c</fullName>
    <formula>IF(ISBLANK(Closed_Date__c),FALSE,TRUE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PC_Case__c/fields/isRunningTest_DO_NOT_USE__c.field-meta.xml
<CustomField>
    <fullName>isRunningTest_DO_NOT_USE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isRunningTest-DO NOT USE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PC_Case__c/fields/Patient_Account__c.field-meta.xml
<CustomField>
    <fullName>Patient_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookups up to the related a Veteran&apos;s Account record.</description>
    <inlineHelpText>Veteran&apos;s related Account record.</inlineHelpText>
    <label>Patient Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PrC Cases</relationshipLabel>
    <relationshipName>PrC_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PC_Case__c/fields/Specialty__c.field-meta.xml
<CustomField>
    <fullName>Specialty__c</fullName>
    <label>Specialty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PC_Specialties</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/PC_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Note</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed Resolved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/PC_Case__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>This is equivalent to the regular subject field on Case</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is equivalent to the regular subject field on Case</inlineHelpText>
    <label>Subject</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/PC_Case__c/recordTypes/Provider_Connect_Case.recordType-meta.xml
<RecordType>
    <fullName>Provider_Connect_Case</fullName>
    <active>true</active>
    <label>Provider Connect Case</label>
</RecordType>

force-app/main/default/globalValueSets/PC_Specialties.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Addiction Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>Allergy/Immunology</fullName>
    </customValue>
    <customValue>
        <fullName>Amputation Clinic</fullName>
    </customValue>
    <customValue>
        <fullName>Anesthesiology</fullName>
    </customValue>
    <customValue>
        <fullName>Anti-Coagulation Clinic</fullName>
    </customValue>
    <customValue>
        <fullName>Audiology</fullName>
    </customValue>
    <customValue>
        <fullName>Blood Pressure Evaluation</fullName>
    </customValue>
    <customValue>
        <fullName>Brain Injury</fullName>
    </customValue>
    <customValue>
        <fullName>Bros (Blind Rehab O/P Spec)</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiac Catheterization</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiac Implantable Electronic Devices (Cied)</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiac Surgery</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiology</fullName>
    </customValue>
    <customValue>
        <fullName>Chart Consult</fullName>
    </customValue>
    <customValue>
        <fullName>Clinical Pharmacy</fullName>
    </customValue>
    <customValue>
        <fullName>Community Care Consult</fullName>
    </customValue>
    <customValue>
        <fullName>Community Nursing Home (Cnh) Follow-Up</fullName>
    </customValue>
    <customValue>
        <fullName>Computerized Tomography (Ct)</fullName>
    </customValue>
    <customValue>
        <fullName>Cysto Room Unit For Outpatient</fullName>
    </customValue>
    <customValue>
        <fullName>Dental</fullName>
    </customValue>
    <customValue>
        <fullName>Dermatology</fullName>
    </customValue>
    <customValue>
        <fullName>Diabetes</fullName>
    </customValue>
    <customValue>
        <fullName>Eeg</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>Endocrinology</fullName>
    </customValue>
    <customValue>
        <fullName>Epilepsy</fullName>
    </customValue>
    <customValue>
        <fullName>Eye Telehealth Screening</fullName>
    </customValue>
    <customValue>
        <fullName>Gastroenterology</fullName>
    </customValue>
    <customValue>
        <fullName>General Internal Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>General Surgery</fullName>
    </customValue>
    <description>DO NOT CHANGE API NAME OF PICKLIST VALUES</description>
    <masterLabel>PC Specialties</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

sfdx-source/main/default/classes/PC/PC_CancelCaseControllerTest.cls
/**
 * @description Test class for PC_PC_CancelCaseController.
 * @author      Booz Allen
 * @see         PC_CancelCaseController
 **/
@isTest
private with sharing class PC_CancelCaseControllerTest {
    private final static User FLP_USER;
    private final static User SPECIALIST_USER;
    static {
        //mixed DML error workaround
        System.runAs(new User(Id = UserInfo.getUserId())) {
            FLP_USER = new VATEST_UserBuilder()
                .withUserProfile('VAVET Base Profile')
                .withStandardData()
                .withPermissionSet('PrC_FLP_Users')
                .build(true);
            SPECIALIST_USER = new VATEST_UserBuilder()
                .withUserProfile('VAVET Base Profile')
                .withStandardData()
                .withPermissionSet('PrC_Specialist_Users')
                .build(true);
        }
    }

    /**
     * @description positive test of cancelCase to ensure a PC Case's status successfully changes to Cancelled
     */
    @IsTest
    static void unitCancelCasePositive() {
        //Set routing to default skill-based routing from the utility class
        PC_PrcConfigSettingsUtility.ndthRoutingEnabled = false;
        PC_PrcConfigSettingsUtility.visnRoutingEnabled = false;
        PC_PrcCaseRepo realCaseRepo = new PC_PrcCaseRepo();

        User provider = FLP_USER;

        PC_Case__c testCase = (PC_Case__c) VATEST_SObjectFactory.createSObject(
            new PC_Case__c(
                RecordTypeId = realCaseRepo.recordTypeConstant.fromDeveloperName('Provider_Connect_Case').Id,
                Case_Details__c = 'Test Details',
                Subject__c = 'Chat - Test PC Provider',
                Specialty__c = 'Cardiac Surgery',
                Status__c = 'Open',
                Channel__c = 'Chat',
                Callback_Number__c = null,
                Patient_Account__c = null,
                isRunningTest_DO_NOT_USE__c = true
            )
        );

        PC_Case__c clonedCase = testCase.clone(true, true, true, true);
        clonedCase.Status__c = 'Cancelled';

        PC_PrcCaseRepo mockedCaseRepo = (PC_PrcCaseRepo) new VATEST_StubBuilder(PC_PrcCaseRepo.class)
            .mockingMethodCall('fetchById')
            .withParameterTypes(Id.class, Set<String>.class)
            .withParameterValues(testCase.Id, new Set<String>{ 'Closed__c' })
            .returning(testCase)
            .mockingMethodCall('doUpdate')
            .withParameterTypes(SObject.class)
            .withParameterValues(clonedCase)
            .returning()
            .defineStub();

        PC_CancelCaseController.prcCaseRepo = mockedCaseRepo;

        System.runAs(provider) {
            Test.startTest();

            PC_Case__c closedCase = PC_CancelCaseController.cancelCase(testCase.Id);

            Test.stopTest();

            Assert.areEqual('Cancelled', closedCase.Status__c, 'Expected the PC Case to be Cancelled.');
        }
    }

    /**
     * @description negative test of cancelCase to ensure a PC Custom Exception is thrown with a blank input
     */
    @IsTest
    static void unitCancelCaseBlankInputNegative() {
        //Set routing to default skill-based routing from the utility class
        PC_PrcConfigSettingsUtility.ndthRoutingEnabled = false;
        PC_PrcConfigSettingsUtility.visnRoutingEnabled = false;

        User provider = FLP_USER;

        String expectedExceptionMessage = PC_CancelCaseController.CASE_ID_BLANK_ERROR_MESSAGE;

        Test.startTest();

        String caughtMessage;
        System.runAs(provider) {
            try {
                PC_CancelCaseController.cancelCase(null);
            } catch (PC_CustomException caughtException) {
                caughtMessage = caughtException.getMessage();
            }
        }

        Test.stopTest();

        Assert.areEqual(
            expectedExceptionMessage,
            caughtMessage,
            'Expected a custom exception to be thrown when the provided caseId is blank.'
        );
    }

    /**
     * @description negative test of cancelCase to ensure an exception is thrown indicating the case is already closed
     */
    @IsTest
    static void unitCancelCaseAlreadyClosedNegative() {
        //Set routing to default skill-based routing from the utility class
        PC_PrcConfigSettingsUtility.ndthRoutingEnabled = false;
        PC_PrcConfigSettingsUtility.visnRoutingEnabled = false;

        User provider = SPECIALIST_USER;

        // We cannot use the Object Factory because we need to set a value on the closed field which is not writeable, using JSON.serialize.
        Id caseId = VATEST_IdFactory.get(Type.forName('PC_Case__c'));
        Map<String, Object> toForceCaseToPcCase = new Map<String, Object>();
        toForceCaseToPcCase.put('Closed__c', true);
        String intermediate = JSON.serialize(toForceCaseToPcCase);
        PC_Case__c testCase = (PC_Case__c) JSON.deserialize(intermediate, PC_Case__c.class);
        testCase.Id = caseId;

        PC_PrcCaseRepo mockedCaseRepo = (PC_PrcCaseRepo) new VATEST_StubBuilder(PC_PrcCaseRepo.class)
            .mockingMethodCall('fetchById')
            .withParameterTypes(Id.class, Set<String>.class)
            .withParameterValues(caseId, new Set<String>{ 'Closed__c' })
            .returning(testCase)
            .defineStub();

        PC_CancelCaseController.prcCaseRepo = mockedCaseRepo;

        String expectedExceptionMessage = 'This case is already closed. Please refresh the page.';

        Test.startTest();

        String caughtMessage;
        System.runAs(provider) {
            try {
                PC_CancelCaseController.cancelCase(caseId);
            } catch (AuraHandledException caughtException) {
                caughtMessage = caughtException.getMessage();
            }
        }

        Test.stopTest();

        Assert.areEqual(
            expectedExceptionMessage,
            caughtMessage,
            'Expected an exception to be thrown by cancelCase indicating that it is already closed.'
        );
    }

    /**
     * @description negative test of cancelCase to ensure a DML exception is thrown
     */
    @IsTest
    static void unitCancelCaseDmlExceptionNegative() {
        //Set routing to default skill-based routing from the utility class
        PC_PrcConfigSettingsUtility.ndthRoutingEnabled = false;
        PC_PrcConfigSettingsUtility.visnRoutingEnabled = false;

        User provider = SPECIALIST_USER;

        String expectedExceptionMessage = 'DML Exception Message.';
        // We cannot use the Object Factory because we need to set a value on the closed field which is not writeable, using JSON.serialize.
        Id caseId = VATEST_IdFactory.get(Type.forName('PC_Case__c'));
        Map<String, Object> toForceCaseToPcCase = new Map<String, Object>();
        toForceCaseToPcCase.put('Closed__c', false);
        String intermediate = JSON.serialize(toForceCaseToPcCase);
        PC_Case__c testCase = (PC_Case__c) JSON.deserialize(intermediate, PC_Case__c.class);
        testCase.Id = caseId;

        PC_Case__c clonedCase = testCase.clone(true, true, true, true);
        clonedCase.Status__c = 'Cancelled';

        PC_PrcCaseRepo mockedCaseRepo = (PC_PrcCaseRepo) new VATEST_StubBuilder(PC_PrcCaseRepo.class)
            .mockingMethodCall('fetchById')
            .withParameterTypes(Id.class, Set<String>.class)
            .withParameterValues(caseId, new Set<String>{ 'Closed__c' })
            .returning(testCase)
            .mockingMethodCall('doUpdate', SObject.class)
            .withParameterValues(clonedCase)
            .throwingException(new DmlException(expectedExceptionMessage))
            .defineStub();

        PC_CancelCaseController.prcCaseRepo = mockedCaseRepo;

        Test.startTest();

        String caughtMessage;
        System.runAs(provider) {
            try {
                PC_CancelCaseController.cancelCase(caseId);
            } catch (AuraHandledException caughtException) {
                caughtMessage = caughtException.getMessage();
            }
        }

        Test.stopTest();

        Assert.areEqual(
            expectedExceptionMessage,
            caughtMessage,
            'Expected a DML exception to be thrown by cancelCase.'
        );
    }

    /**
     * @description negative test of cancelCase to ensure a Query exception is thrown
     */
    @IsTest
    static void unitCancelCaseQueryExceptionNegative() {
        //Set routing to default skill-based routing from the utility class
        PC_PrcConfigSettingsUtility.ndthRoutingEnabled = false;
        PC_PrcConfigSettingsUtility.visnRoutingEnabled = false;

        User provider = SPECIALIST_USER;

        Id caseId = VATEST_IdFactory.get(Type.forName('PC_Case__c'));

        String expectedExceptionMessage = 'Query Exception Message.';

        PC_PrcCaseRepo mockedCaseRepo = (PC_PrcCaseRepo) new VATEST_StubBuilder(PC_PrcCaseRepo.class)
            .mockingMethodCall('fetchById')
            .withParameterTypes(Id.class, Set<String>.class)
            .withParameterValues(caseId, new Set<String>{ 'Closed__c' })
            .throwingException(new QueryException(expectedExceptionMessage))
            .defineStub();

        PC_CancelCaseController.prcCaseRepo = mockedCaseRepo;

        Test.startTest();

        String caughtMessage;
        System.runAs(provider) {
            try {
                PC_CancelCaseController.cancelCase(caseId);
            } catch (AuraHandledException caughtException) {
                caughtMessage = caughtException.getMessage();
            }
        }

        Test.stopTest();

        Assert.areEqual(
            expectedExceptionMessage,
            caughtMessage,
            'Expected a Query exception to be thrown by cancelCase.'
        );
    }
}