force-app/main/default/objects/PC_Case__c/PC_Case__c.object-meta.xml
<CustomObject>
    <description>Object to hold Provider Connect cases</description>
    <label>PrC Case</label>
    <nameField>
        <displayFormat>PCC-{0000000000}</displayFormat>
        <label>Provider Connect Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrC Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/PC_Case__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Teams</fullName>
                <label>Teams Video</label>
            </value>
            <value>
                <fullName>Phone</fullName>
                <label>Phone Callback</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PC_Case__c/fields/Closed__c.field-meta.xml
<CustomField>
    <fullName>Closed__c</fullName>
    <formula>IF(ISBLANK(Closed_Date__c),FALSE,TRUE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PC_Case__c/fields/Closed_Date__c.field-meta.xml
<CustomField>
    <fullName>Closed_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date/Time Closed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/PC_Case__c/fields/isRunningTest_DO_NOT_USE__c.field-meta.xml
<CustomField>
    <fullName>isRunningTest_DO_NOT_USE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isRunningTest-DO NOT USE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PC_Case__c/fields/Specialty__c.field-meta.xml
<CustomField>
    <fullName>Specialty__c</fullName>
    <label>Specialty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PC_Specialties</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/PC_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Note</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed Resolved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PC_Case__c/fields/Training_Case__c.field-meta.xml
<CustomField>
    <fullName>Training_Case__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allows users to identify when a record was created for training purposes only.</description>
    <inlineHelpText>If checked this case record is used for training purposes only.</inlineHelpText>
    <label>Training Case</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/PC_Case__c/recordTypes/Provider_Connect_Case.recordType-meta.xml
<RecordType>
    <fullName>Provider_Connect_Case</fullName>
    <active>true</active>
    <label>Provider Connect Case</label>
</RecordType>

force-app/main/default/globalValueSets/PC_Specialties.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Addiction Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>Allergy/Immunology</fullName>
    </customValue>
    <customValue>
        <fullName>Amputation Clinic</fullName>
    </customValue>
    <customValue>
        <fullName>Anesthesiology</fullName>
    </customValue>
    <customValue>
        <fullName>Anti-Coagulation Clinic</fullName>
    </customValue>
    <customValue>
        <fullName>Audiology</fullName>
    </customValue>
    <customValue>
        <fullName>Blood Pressure Evaluation</fullName>
    </customValue>
    <customValue>
        <fullName>Brain Injury</fullName>
    </customValue>
    <customValue>
        <fullName>Bros (Blind Rehab O/P Spec)</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiac Catheterization</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiac Implantable Electronic Devices (Cied)</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiac Surgery</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiology</fullName>
    </customValue>
    <customValue>
        <fullName>Chart Consult</fullName>
    </customValue>
    <customValue>
        <fullName>Clinical Pharmacy</fullName>
    </customValue>
    <customValue>
        <fullName>Community Care Consult</fullName>
    </customValue>
    <customValue>
        <fullName>Community Nursing Home (Cnh) Follow-Up</fullName>
    </customValue>
    <customValue>
        <fullName>Computerized Tomography (Ct)</fullName>
    </customValue>
    <customValue>
        <fullName>Cysto Room Unit For Outpatient</fullName>
    </customValue>
    <customValue>
        <fullName>Dental</fullName>
    </customValue>
    <customValue>
        <fullName>Dermatology</fullName>
    </customValue>
    <customValue>
        <fullName>Diabetes</fullName>
    </customValue>
    <customValue>
        <fullName>Eeg</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>Endocrinology</fullName>
    </customValue>
    <customValue>
        <fullName>Epilepsy</fullName>
    </customValue>
    <customValue>
        <fullName>Eye Telehealth Screening</fullName>
    </customValue>
    <customValue>
        <fullName>Gastroenterology</fullName>
    </customValue>
    <customValue>
        <fullName>General Internal Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>General Surgery</fullName>
    </customValue>
    <customValue>
        <fullName>Neurology</fullName>
    </customValue>
    <description>DO NOT CHANGE API NAME OF PICKLIST VALUES</description>
    <masterLabel>PC Specialties</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

sfdx-source/main/default/classes/PC/PC_PrcCaseRepoTest.cls
/**
 * @description Test class for PC_PrcCaseRepo.
 * @author      Booz Allen Hamilton
 * @since       2024
 * @see         PC_PrcCaseRepo
 */
@IsTest
private class PC_PrcCaseRepoTest {
    private final static User FLP_USER;
    private final static User SPECIALIST_USER;
    static {
        //mixed DML error workaround
        System.runAs([SELECT Id FROM User WHERE Id = :UserInfo.getUserId()][0]) {
            FLP_USER = new VATEST_UserBuilder()
                .withUserProfile('VAVET Base Profile')
                .withStandardData()
                .withPermissionSet('PrC_FLP_Users')
                .withPermissionSet('PC_PatientAccount_ReadWrite')
                .build(true);

            SPECIALIST_USER = new VATEST_UserBuilder()
                .withUserProfile('VAVET Base Profile')
                .withStandardData()
                .withPermissionSet('PrC_Specialist_Users')
                .withPermissionSet('PC_PatientAccount_Read')
                .build(true);
        }
    }

    @testSetup
    private static void testSetup() {
        PC_PrcCaseRepo repo = new PC_PrcCaseRepo();
        System.runAs(FLP_USER) {
            VATEST_SObjectFactory.createSObject(
                new PC_Case__c(
                    RecordTypeId = repo.recordTypeConstant.fromDeveloperName('Provider_Connect_Case').Id,
                    Status__c = 'Open',
                    Channel__c = 'Chat',
                    Specialty__c = 'Cardiology',
                    isRunningTest_DO_NOT_USE__c = true //this flag prevents the routing Flow from triggering
                ),
                true
            );

            VATEST_SObjectFactory.createSObject(
                new PC_Case__c(
                    RecordTypeId = repo.recordTypeConstant.fromDeveloperName('Provider_Connect_Case').Id,
                    Status__c = 'Open',
                    Channel__c = 'Chat',
                    Specialty__c = 'Neurology',
                    isRunningTest_DO_NOT_USE__c = true //this flag prevents the routing Flow from triggering
                ),
                true
            );

            VATEST_SObjectFactory.createSObject(
                new PC_Case__c(
                    RecordTypeId = repo.recordTypeConstant.fromDeveloperName('Provider_Connect_Case').Id,
                    Status__c = 'Open',
                    Channel__c = 'Chat',
                    Specialty__c = 'Gastroenterology',
                    isRunningTest_DO_NOT_USE__c = true //this flag prevents the routing Flow from triggering
                ),
                true
            );
        }
    }

    @IsTest
    static void unitTestConstructorPositive() {
        Test.startTest();
        PC_PrcCaseRepo repo;
        System.runAs(FLP_USER) {
            repo = new PC_PrcCaseRepo();
        }
        Test.stopTest();

        Assert.isNotNull(repo, 'Expected constructor to properly instantiate a PC_PrcCaseRepo class object');
        Assert.isTrue(
            String.valueOf(repo).containsIgnoreCase('VTC_BaseRepo.sObjectType=PC_Case__c'),
            'Expected the SObject type to be PrC Case'
        );
    }

    @IsTest
    private static void funcGetOpenPrcCasesOwnedByUserPositive() {
        // Test data setup
        PC_PrcCaseRepo repo = new PC_PrcCaseRepo();

        PC_Case__c pcCase = [SELECT Id, OwnerId FROM PC_Case__c LIMIT 1];
        pcCase.OwnerId = FLP_USER.Id;
        repo.doUpdate(pcCase);

        // Actual test
        Test.startTest();

        List<PC_Case__c> results;
        System.runAs(FLP_USER) {
            results = repo.getOpenPrcCasesOwnedByUser(FLP_USER.Id);
        }

        Test.stopTest();

        // Asserts
        Assert.isTrue(
            !results.isEmpty(),
            'getOpenPrcCasesOwnedByUser should have returned a PC Case owned by the FLP test user.'
        );
    }

    /**
     * @description Positive test for retrieval of Recently Closed Cases for a given User
     */
    @IsTest
    private static void funcGetRecentlyClosedCasesForUserPositive() {
        // Test data setup
        PC_PrcCaseRepo repo = new PC_PrcCaseRepo();

        PC_Case__c pcCase = [SELECT Id, OwnerId, Closed_Date__c, Status__c, closed__c FROM PC_Case__c LIMIT 1];

        //Setting Owner here to avoid Closed Case Validation Rule, subsequent update will fulfill intent of the test class
        pcCase.OwnerId = FLP_USER.Id;
        repo.doUpdate(pcCase);

        pcCase.Closed_Date__c = Date.today();
        repo.doUpdate(pcCase);

        // Actual test
        Test.startTest();

        List<PC_Case__c> results;
        System.runAs(FLP_USER) {
            results = repo.getRecentlyClosedCasesForUser(FLP_USER.Id);
        }

        Test.stopTest();

        // Asserts
        Assert.isFalse(
            results.isEmpty(),
            'getRecentlyClosedCasesForUser should have returned a Closed PC Case owned by the FLP test user.'
        );
    }

    /**
     * @description Positive test for retrieval of Recently Closed Cases that do not include Training Cases for a given User
     */
    @IsTest
    private static void funcGetRecentlyClosedCasesForUserWithoutTrainingCasesPositive() {
        // Test data setup
        PC_PrcCaseRepo repo = new PC_PrcCaseRepo();

        PC_Case__c pcCase = [SELECT Id, OwnerId, Closed_Date__c, Status__c, closed__c FROM PC_Case__c LIMIT 1];

        // Adding training case
        pcCase.OwnerId = FLP_USER.Id;
        pcCase.Training_Case__c = true;
        update pcCase;

        // Actual test
        Test.startTest();

        List<PC_Case__c> results;
        System.runAs(FLP_USER) {
            results = repo.getRecentlyClosedCasesForUser(FLP_USER.Id);
        }

        Test.stopTest();

        // Asserts
        Assert.isTrue(
            results.isEmpty(),
            'Expected the results to return empty when executing getRecentlyClosedCasesForUser because this is a training case and observed this is true.'
        );
    }

    /**
     * @description Positive test for retrieval of the oldest open PC Case for a given User
     */
    @IsTest
    private static void funcGetOldestOpenPrcCaseOwnedByUserPositive() {
        // Test data setup
        PC_PrcCaseRepo repo = new PC_PrcCaseRepo();

        List<PC_Case__c> pcCaseList = [
            SELECT Id, OwnerId, Specialty__c, CreatedDate
            FROM PC_Case__c
            WHERE Specialty__c = 'Neurology' OR Specialty__c = 'Gastroenterology'
            LIMIT 2
        ];

        for (PC_Case__c pcCase : pcCaseList) {
            Test.setCreatedDate(pcCase.Id, Date.today().addDays(-1));
            if (pcCase.Specialty__c == 'Gastroenterology') {
                pcCase.OwnerId = SPECIALIST_USER.Id;
            }
        }
        update pcCaseList;

        // Actual test
        Test.startTest();

        List<PC_Case__c> results;
        System.runAs(SPECIALIST_USER) {
            results = repo.getOldestOpenPrcCaseOwnedByUser(SPECIALIST_USER.Id);
        }

        Test.stopTest();

        // Asserts
        Assert.areEqual(results.size(), 1, 'Expected only oldest PrC Case');
        Assert.areEqual(results[0].Specialty__c, 'Gastroenterology', 'Expected pcCase');
    }
}