sfdx-source/main/default/objects/CIP_Settings__c/CIP_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This setting would identify the environment/sandbox configurations for Clinical Intake prioritization module</description>
    <label>CIP Settings</label>
</CustomObject>

sfdx-source/main/default/objects/CIP_Settings__c/fields/AuthProviderName__c.field-meta.xml
<CustomField>
    <fullName>AuthProviderName__c</fullName>
    <description>Name of the Auth Provider that will be used for SSOi</description>
    <encryptionScheme>None</encryptionScheme>
    <label>AuthProviderName</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/CIP_Settings__c/fields/baseUrl__c.field-meta.xml
<CustomField>
    <fullName>baseUrl__c</fullName>
    <description>Salesforce Base Url</description>
    <encryptionScheme>None</encryptionScheme>
    <label>baseUrl</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/CIP_Settings__c/fields/serviceCategory__c.field-meta.xml
<CustomField>
    <fullName>serviceCategory__c</fullName>
    <description>Service Category to be passed as a parameter when calling VDIF WriteNoteAndEncounter.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>serviceCategory</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/CIP_Settings__c/fields/token__c.field-meta.xml
<CustomField>
    <fullName>token__c</fullName>
    <description>Place to store temporary IAM token if needed for testing</description>
    <encryptionScheme>None</encryptionScheme>
    <label>token</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CIP_Settings__c/fields/TXCPipeSymbolReplacement__c.field-meta.xml
<CustomField>
    <fullName>TXCPipeSymbolReplacement__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>TXCPipeSymbolReplacement</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/CIP_Settings__c/fields/VistaNoteLineCharacterLimit__c.field-meta.xml
<CustomField>
    <fullName>VistaNoteLineCharacterLimit__c</fullName>
    <label>VistaNoteLineCharacterLimit</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/main/default/objects/CIP_Settings__c/fields/VitalSearchNumberOfYears__c.field-meta.xml
<CustomField>
    <fullName>VitalSearchNumberOfYears__c</fullName>
    <description>Number of years to go back in time when retrieving patient&apos;s vitals from CPRS.</description>
    <label>VitalSearchNumberOfYears</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CIP_UserAttribute__c/CIP_UserAttribute__c.object-meta.xml
<CustomObject>
    <label>User Attribute</label>
    <nameField>
        <displayFormat>UA-{000000000}</displayFormat>
        <label>User Attribute Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/CIP_UserAttribute__c/fields/LocalSiteId__c.field-meta.xml
<CustomField>
    <fullName>LocalSiteId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Local Site Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CIP_UserAttribute__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Attributes</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/objects/Triage__c/Triage__c.object-meta.xml
<CustomObject>
    <label>Triage</label>
    <nameField>
        <displayFormat>NT - {000000000}</displayFormat>
        <label>Nurse Triage Intake ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Triage</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Triage__c/fields/Check_In_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Date_Time__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Check-In Date/Time</label>
    <type>DateTime</type>
</CustomField>

sfdx-source/main/default/objects/Triage__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

sfdx-source/main/default/objects/Triage__c/fields/E_M_Code__c.field-meta.xml
<CustomField>
    <fullName>E_M_Code__c</fullName>
    <label>E&amp;M Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>99211^OFFICE O/P EST MINIMAL PROB</fullName>
                <default>true</default>
                <label>99211^OFFICE O/P EST MINIMAL PROB</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/Triage__c/fields/Facility_Id__c.field-meta.xml
<CustomField>
    <fullName>Facility_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Facility Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/Triage__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>First Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Triage__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Birth Sex</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Triage__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/Triage__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>4775</fullName>
                <label>CC TXCW PACT BLUE TEAM RN</label>
            </value>
            <value>
                <fullName>4777</fullName>
                <label>CC TXCW PACT BROWN TEAM RN</label>
            </value>
            <value>
                <fullName>4779</fullName>
                <label>CC TXCW PACT GRAY TEAM RN</label>
            </value>
            <value>
                <fullName>4778</fullName>
                <label>CC TXCW PACT GREEN TEAM RN</label>
            </value>
            <value>
                <fullName>4776</fullName>
                <label>CC TXCW PACT ORANGE TEAM RN</label>
            </value>
            <value>
                <fullName>4774</fullName>
                <label>CC TXCW PACT PURPLE TEAM RN</label>
            </value>
            <value>
                <fullName>4772</fullName>
                <label>CC TXCW PACT TEAL TEAM RN</label>
            </value>
            <value>
                <fullName>4771</fullName>
                <label>CC TXCW PACT WHITE TEAM RN</label>
            </value>
            <value>
                <fullName>4768</fullName>
                <label>HRL TXCW PACT GRAY TEAM RN</label>
            </value>
            <value>
                <fullName>28391</fullName>
                <label>TO-PACT Focused Care Nurse</label>
            </value>
            <value>
                <fullName>4788</fullName>
                <label>MCA TXCW PACT BLUE RN</label>
            </value>
            <value>
                <fullName>28366</fullName>
                <label>TO-PACT Focused Care-NP</label>
            </value>
            <value>
                <fullName>4781</fullName>
                <label>MCA TXCW PACT FLOAT RN</label>
            </value>
            <value>
                <fullName>4757</fullName>
                <label>LAR TXCW PACT STEEL TEAM RN</label>
            </value>
            <value>
                <fullName>4762</fullName>
                <label>HRL TXCW PACT RED TEAM RN</label>
            </value>
            <value>
                <fullName>4756</fullName>
                <label>LAR TXCW WHITE TEAM RN</label>
            </value>
            <value>
                <fullName>4789</fullName>
                <label>MCA TXCW PACT GOLD RN</label>
            </value>
            <value>
                <fullName>4758</fullName>
                <label>LAR TXCW PACT RED TEAM RN</label>
            </value>
            <value>
                <fullName>4760</fullName>
                <label>HRL TXCW PACT YELLOW TEAM RN</label>
            </value>
            <value>
                <fullName>4812</fullName>
                <label>HRL TXCW TRAVELING VET RN</label>
            </value>
            <value>
                <fullName>4780</fullName>
                <label>HRL TXCW PC FLOAT 1 RN</label>
            </value>
            <value>
                <fullName>4759</fullName>
                <label>LAR TXCW PACT BLUE TEAM RN</label>
            </value>
            <value>
                <fullName>4763</fullName>
                <label>HRL TXCW PACT PURPLE TEAM RN</label>
            </value>
            <value>
                <fullName>4761</fullName>
                <label>HRL TXCW PACT SILVER TEAM RN</label>
            </value>
            <value>
                <fullName>4787</fullName>
                <label>MCA TXCW PACT ORANGE RN</label>
            </value>
            <value>
                <fullName>4764</fullName>
                <label>HRL TXCW PACT ORANGE TEAM RN</label>
            </value>
            <value>
                <fullName>4792</fullName>
                <label>MCA TXCW PACT GRAY RN</label>
            </value>
            <value>
                <fullName>4765</fullName>
                <label>HRL TXCW PACT BLUE TEAM RN</label>
            </value>
            <value>
                <fullName>4769</fullName>
                <label>CC TXCW SPOKE CVT RN</label>
            </value>
            <value>
                <fullName>4767</fullName>
                <label>HRL TXCW PACT GOLD TEAM RN</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Triage__c/fields/Nurse_Notes__c.field-meta.xml
<CustomField>
    <fullName>Nurse_Notes__c</fullName>
    <description>Part of Vitals Intake</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Nurse Notes</label>
    <length>15000</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/main/default/objects/Triage__c/fields/Patient_Local_Pid__c.field-meta.xml
<CustomField>
    <fullName>Patient_Local_Pid__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Patient Local Pid</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/Triage__c/fields/Progress_Note__c.field-meta.xml
<CustomField>
    <fullName>Progress_Note__c</fullName>
    <label>Progress Note Title</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>11011</fullName>
                <label>EK-PACT WALK-IN</label>
            </value>
            <value>
                <fullName>1473</fullName>
                <label>UNSCHEDULED &lt;NURSING NON-MEDICAL UNSCHEDULED VISIT-TXCW&gt;</label>
            </value>
            <value>
                <fullName>1647</fullName>
                <label>UNSCHEDULED &lt;NURSING UNSCHEDULED VISIT&gt;</label>
            </value>
            <value>
                <fullName>2732</fullName>
                <label>UNSCHEDULED &lt;NURSING UNSCHEDULED VISIT-TXCW&gt;</label>
            </value>
            <value>
                <fullName>3754</fullName>
                <label>UNSCHEDULED &lt;PRIME CARE UNSCHEDULED NOTE&gt;</label>
            </value>
            <value>
                <fullName>4242</fullName>
                <label>UPDATE &lt;HCHV MONTHLY UPDATE NOTE&gt;</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Triage__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <description>Reason for changing System Triage will be entered here</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Reason For Triage Class Update</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Triage__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>SSN</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/Triage__c/fields/Triage_Status__c.field-meta.xml
<CustomField>
    <fullName>Triage_Status__c</fullName>
    <label>Triage Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Intake Complete</fullName>
            </value>
            <value>
                <fullName>Screening Complete</fullName>
            </value>
            <value>
                <fullName>Vitals Complete</fullName>
            </value>
            <value>
                <fullName>TXC Complete</fullName>
            </value>
            <value>
                <fullName>Assessment Complete</fullName>
            </value>
            <value>
                <fullName>Note Submitted</fullName>
            </value>
            <value>
                <fullName>Checked In</fullName>
                <isActive>false</isActive>
                <label>Checked In</label>
            </value>
            <value>
                <fullName>Triage Complete</fullName>
                <isActive>false</isActive>
                <label>Triage Complete</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Triage__c/fields/TXC_Results__c.field-meta.xml
<CustomField>
    <fullName>TXC_Results__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>TXC Results</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/main/default/classes/CipTriageHandlerTest.cls
@isTest
public class CipTriageHandlerTest {
    @testSetup
    private static void setupData() {
        User u;
        CIP_UserAttribute__c ua;
        Triage__c tri;

        CIP_Settings__c setting = new CIP_Settings__c();
        setting.Name = 'cipsit';
        setting.VitalSearchNumberOfYears__c = 5;
        setting.serviceCategory__c = 'A';
        setting.AuthProviderName__c = 'VA_SSOi';
        setting.baseUrl__c = 'https://va-vet--cipsit.my.salesforce.com';
        setting.token__c = 'aPdk3dPmQQhBCjWPIjY9YRNwaZNKwnU1WFtiqnQr';
        setting.VistaNoteLineCharacterLimit__c = 80.0;
        setting.TXCPipeSymbolReplacement__c = '-';
        insert setting;

        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1][0];
        UserRole role = new UserRole(Name = 'Tester');
        //String unique = 'Test' + String.valueOf(Integer.valueOf(math.rint(math.random()*1000000)));

        User moi = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1][0];

        System.runAs(moi) {
            insert role;

            u = new User(
                firstname = 'firstName',
                lastName = 'lastName',
                email = 'abc@testcip.org',
                Username = 'abc@testcip.org',
                EmailEncodingKey = 'ISO-8859-1',
                Alias = 'abc',
                TimeZoneSidKey = 'America/Los_Angeles',
                LocaleSidKey = 'en_US',
                LanguageLocaleKey = 'en_US',
                ProfileId = p.Id,
                UserRoleId = role.Id
            );
            insert u;

            Group TopQ = new Group(Name = 'CIP_TopekaTest', DeveloperName = 'CIP_TopekaTest', Type = 'Queue');
            insert TopQ;

            Group TopPG = new Group(Name = 'CIP_TopekaTest', DeveloperName = 'CIP_TopekaTest', Type = 'Regular');
            insert TopPG;

            GroupMember gmPG = new GroupMember(GroupId = TopQ.Id, UserOrGroupId = TopPG.Id);
            insert gmPG;

            QueueSobject qso = new QueueSobject(QueueId = TopQ.Id, SobjectType = 'Triage__c');
            insert qso;

            //Group g = [SELECT Id FROM Group WHERE DeveloperName = 'CIP_Topeka' AND type != 'Queue' LIMIT 1][0];
            GroupMember gm = new GroupMember(GroupId = TopPG.Id, UserOrGroupId = u.Id);
            insert gm;

            ua = new CIP_UserAttribute__c(
                LocalSiteId__c = '984',
                User__c = u.Id
                //Name = 'TEST'
            );

            insert ua;
        }
        System.runAs(u) {
            tri = new Triage__c(
                First_Name__c = 'ONE',
                Last_Name__c = 'AMPLTESTPATIENT',
                Gender__c = 'Male',
                Date_of_Birth__c = Date.newInstance(1916, 7, 14),
                Triage_Status__c = 'Intake Complete',
                Check_In_Date_Time__c = System.now(),
                SSN__c = '308048718',
                Patient_Local_Pid__c = '78',
                Facility_Id__c = '984',
                Location__c = '2289',
                E_M_Code__c = '99211^OFFICE O/P EST MINIMAL PROB',
                Progress_Note__c = '1986',
                Reason__c = 'Reason To Update'
            );
            insert tri;
        }
    }

    @isTest
    static void testMpiPatientSearch() {
        User u = [SELECT Id FROM User WHERE Username = 'abc@testcip.org' LIMIT 1];
        System.runAs(u) {
            Test.startTest();
            // Set mock callout class
            string bod = '{"vets":[{"firstName": "Jack","lastName": "Jones", "ssn":"308048718", "gender": "M","dob": "19441117"},{"firstName": "Kelly","lastName": "Kars","gender": "F","dob": "19481117"}]}';
            string stringCallout = 'mpiSearch';
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(stringCallout));
            //CIP_UserAttribute__c cua = [SELECT Id FROM CIP_UserAttribute__c WHERE User__c = :userInfo.getUserId() LIMIT 1];

            // Call method to test. This causes a fake response to be sent from the class that implements HttpCalloutMock.
            CipTriageHandler.ResponseWrap respwrap = CipTriageHandler.mpiPatientSearch(bod);
            Test.stopTest();
            System.assertequals(respwrap.status, '200', 'ResponseWrap didnot return 200');
        }
    }

    @isTest
    static void testCreateTriage() {
        User u = [SELECT Id FROM User WHERE Username = 'abc@testcip.org' LIMIT 1];
        System.runAs(u) {
            Test.startTest();
            String triage;

            triage = CipTriageHandler.createTriage(
                '{"icn":"1012668137V030567","firstName":"ONE","lastName":"AMPLTESTPATIENT","gender":"M", "medicalCenterFacilities":[{"facilityId":"984","personId":"78"}],"ssn":"308048718","dob":"07-14-1916"}',
                'Intake Complete'
            );
            Test.stopTest();
            System.assert(triage != null, 'Triage record not created');
        }
    }

    @isTest
    static void testPatientFlagMessages() {
        User u = [SELECT Id FROM User WHERE Username = 'abc@testcip.org' LIMIT 1];
        Triage__c tri = [SELECT Id FROM Triage__c WHERE Last_Name__c = 'AMPLTESTPATIENT' LIMIT 1];
        System.runAs(u) {
            Test.startTest();
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator('flagMessages'));
            CipTriageHandler.PatientMessagesResponseWrap response1 = CipTriageHandler.patientFlagMessages(tri.Id);
            CipTriageHandler.PatientMessagesResponseWrap response2 = CipTriageHandler.patientFlagMessages(tri.Id);
            Test.stopTest();
            System.assert(String.isNotBlank(String.valueOf(response1)), 'Patient flags not returned 1');
            System.assert(String.isNotBlank(String.valueOf(response2)), 'Patient flags not returned 2');
        }
    }

    @isTest
    static void testHistoricVitals() {
        User u = [SELECT Id FROM User WHERE Username = 'abc@testcip.org' LIMIT 1];
        Triage__c tri = [SELECT Id FROM Triage__c WHERE Last_Name__c = 'AMPLTESTPATIENT' LIMIT 1];
        System.runAs(u) {
            Test.startTest();
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator('historicVitals'));
            CipTriageHandler.VitalsResponseWrap response1 = CipTriageHandler.historicVitals(tri.Id);
            CipTriageHandler.VitalsResponseWrap response2 = CipTriageHandler.historicVitals(tri.Id);
            Test.stopTest();
            System.assert(String.isNotBlank(String.valueOf(response1)), 'Historic Vitals not returned 2');
            System.assert(String.isNotBlank(String.valueOf(response2)), 'Historic Vitals not returned 2');
        }
    }

    @isTest
    static void testWriteNote() {
        User u = [SELECT Id FROM User WHERE Username = 'abc@testcip.org' LIMIT 1];
        Triage__c tri = [
            SELECT
                Id,
                Nurse_Notes__c,
                TXC_Results__c,
                Mode_of_Arrival__c,
                Accompanied_By__c,
                Reason_for_Visit__c,
                Mental_Health_Screening__c,
                Reason__c,
                Outside_US_30_Days__c,
                Signs_of_Abuse__c,
                Feels_Safe__c,
                Suicidal_Homicidal__c,
                Facility_Id__c,
                Patient_Local_Pid__c,
                Response__c,
                Encounter_String__c,
                First_Name__c,
                Last_Name__c,
                Progress_Note__c,
                E_M_Code__c,
                Location__c,
                ICD10_code__c
            FROM Triage__c
            WHERE Last_Name__c = 'AMPLTESTPATIENT'
            LIMIT 1
        ];
        List<Triage__c> triageList = new List<Triage__c>();
        List<String> noteIdList = new List<String>();

        System.runAs(u) {
            triageList.add(tri);
            Test.startTest();
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator('SaveNoteAndEncounter'));
            //Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator('writeNote'));
            noteIdList = CipTriageHandler.writeNote(triageList);
            Test.stopTest();
        }
        System.assert(!noteIdList.isEmpty(), 'Note Id is not returned');
    }

    @isTest
    static void testGetEncounterString() {
        User u = [SELECT Id FROM User WHERE Username = 'abc@testcip.org' LIMIT 1];
        Triage__c tri = [
            SELECT Id, Progress_Note__c, Location__c, First_Name__c, Last_Name__c, Facility_Id__c, Patient_Local_Pid__c, E_M_Code__c, ICD10_code__c
            FROM Triage__c
            WHERE Last_Name__c = 'AMPLTESTPATIENT'
            LIMIT 1
        ];
        String encounterString;

        System.runAs(u) {
            Test.startTest();
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator('SaveNoteAndEncounter'));
            encounterString = CipTriageHandler.getEncounterString(tri);
            Test.stopTest();
        }
        system.assertEquals(encounterString, '2289;3210824.131819;A');
    }

    @isTest
    static void testGetIAMToken() {
        Test.startTest();
        String IAMToken = CipTriageHandler.getIAMToken('Refresh');
        Test.stopTest();
        system.assertEquals(IAMToken, 'aPdk3dPmQQhBCjWPIjY9YRNwaZNKwnU1WFtiqnQr');
    }

    @isTest
    static void testParseNoteText() {
        String unparsedText = 'Nurse Notes\n\tnull\n\nSymptom Triage Note\nSat, 25 Sep 2021 20:35:17 +0000 UTC\n\nDemographics\n\t61 y/o Male\n\nResults\n\tCC: Black Tongue &#124; Duration 4 Hours\n\tNurse assigned 5-level Triage Class: 2\n\tSystem suggested 5-level Triage Class: 2\n\nAlert\n\n\t1)  This is a HIGHER COMPLEXITY patient.\n\n\nPositive Responses\n\tHPI: confusion, onset since the jaw injury\n\tHPI: jaw injury, within past 2 days\n\tHPI: tongue swelling\n\nVerbal Instructions\n\tBlack Tongue Home Care\n\nWeb Instructions:	https://vha-pip.dshisystems.net/pi.htm?k=TEABhT4gXAAAAAAB2GTONC9DtFuYs\n\nReason for Visit\n\tnull\n\nMode of Arrival\n\tnull\n\nAccompanied By\n\tnull\n\nLogistical Response\n\nnull';
        Test.startTest();
        String parsedString = CipTriageHandler.parseNoteText(unparsedText);
        Test.stopTest();
        system.assertEquals(
            parsedString,
            'Nurse Notes\n\tnull\n\nSymptom Triage Note\nSat, 25 Sep 2021 20:35:17 +0000 UTC\n\nDemographics\n\t61 y/o Male\n\nResults\n\tCC: Black Tongue &#124; Duration 4 Hours\n\tNurse assigned 5-level Triage Class: 2\n\tSystem suggested 5-level Triage Class: 2\n\nAlert\n\n\t1)  This is a HIGHER COMPLEXITY patient.\n\n\nPositive Responses\n\tHPI: confusion, onset since the jaw injury\n\tHPI: jaw injury, within past 2 days\n\tHPI: tongue swelling\n\nVerbal Instructions\n\tBlack Tongue Home Care\n\nWeb Instructions:\t\nhttps://vha-pip.dshisystems.net/pi.htm?k=TEABhT4gXAAAAAAB2GTONC9DtFuYs\n\nReason for Visit\n\tnull\n\nMode of Arrival\n\tnull\n\nAccompanied By\n\tnull\n\nLogistical Response\n\nnull\n'
        );
    }
}