force-app/main/default/objects/Test_Run__c/Test_Run__c.object-meta.xml
<CustomObject>
    <description>Stores aggregated details for related Test_Run_Method_Result__c records.</description>
    <label>Test Run</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Test Run Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Runs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Run_Method_Result__c/Test_Run_Method_Result__c.object-meta.xml
<CustomObject>
    <description>Stores all the results of all the apex unit tests related to a Test_Run__c record.</description>
    <label>Test Run Method Result</label>
    <nameField>
        <displayFormat>TRMR-{0000000000}</displayFormat>
        <label>Test Run Method Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Run Method Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/Test_Run_Method_Result__c/fields/First_Failure__c.field-meta.xml
<CustomField>
    <fullName>First_Failure__c</fullName>
    <description>DateTime of first failed attempt at test</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>DateTime of first failed attempt at test</inlineHelpText>
    <label>First Failure</label>
    <type>DateTime</type>
</CustomField>

sfdx-source/main/default/objects/Test_Run_Method_Result__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Reason for unit test failure</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Reason for unit test failure</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/main/default/objects/Test_Run_Method_Result__c/fields/Method_Pass__c.field-meta.xml
<CustomField>
    <fullName>Method_Pass__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag for if the unit test passed or not</description>
    <inlineHelpText>Flag for if the unit test passed or not</inlineHelpText>
    <label>Method Pass</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/Test_Run_Method_Result__c/fields/Test_Run__c.field-meta.xml
<CustomField>
    <fullName>Test_Run__c</fullName>
    <label>Test Run</label>
    <referenceTo>Test_Run__c</referenceTo>
    <relationshipLabel>Test Run Method Results</relationshipLabel>
    <relationshipName>Test_Run_Method_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/main/default/classes/TestRunEmailControllerTest.cls
/**
 * Author:Jaren Yach
 *  Created Date 05/20/2022
 *  Purpose: Test class for TestRunEmailController
 */
@IsTest
private class TestRunEmailControllerTest {
    @IsTest
    public static void controllerTest() {
        Id jobId = DTCTestUtil.generateId(ApexTestQueueItem.getSObjectType());
        Test_Run__c testRun = DTCTestUtil.createTestRun('Testing Test Run', jobId, false);
        insert testRun;

        Test_Run_Method_Result__c rec1 = DTCTestUtil.createTestRunMethodResult(testRun.Id, 'Test Class', 'Test Method');
        rec1.Message__c = 'Testing email controller';
        rec1.First_Failure__c = Datetime.now();
        rec1.Method_Pass__c = false;

        Test_Run_Method_Result__c rec2 = DTCTestUtil.createTestRunMethodResult(testRun.Id, 'Test Class2', 'Test Method');
        rec2.Message__c = 'Testing email controller';
        rec2.First_Failure__c = Datetime.now();
        rec2.Method_Pass__c = false;
        List<Test_Run_Method_Result__c> methodResults = new List<Test_Run_Method_Result__c>{ rec1, rec2 };

        insert methodResults;

        TestRunEmailController cont = new TestRunEmailController();
        cont.testRunId = testRun.Id;
        Map<String, List<Test_Run_Method_Result__c>> failMap = cont.getFailureMap();
        System.assertEquals(2, failMap.size());
        System.assertNotEquals(null, cont.getbaseURL());
    }
}