force-app/main/default/objects/Test_Run__c/Test_Run__c.object-meta.xml
<CustomObject>
    <description>Stores aggregated details for related Test_Run_Method_Result__c records.</description>
    <label>Test Run</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Test Run Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Runs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/Test_Run__c/fields/Processed__c.field-meta.xml
<CustomField>
    <fullName>Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True when the test run has completed and has been processed by the TestRunProcessorBatch process.</description>
    <inlineHelpText>True when the test run has completed and has been processed by the TestRunProcessorBatch process.</inlineHelpText>
    <label>Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Test_Run__c/fields/Test_Failures__c.field-meta.xml
<CustomField>
    <fullName>Test_Failures__c</fullName>
    <description>The number of failed unit tests for this test run.</description>
    <inlineHelpText>The number of failed unit tests for this test run.</inlineHelpText>
    <label>Test Failures</label>
    <summaryFilterItems>
        <field>Test_Run_Method_Result__c.Method_Pass__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>Test_Run_Method_Result__c.Test_Run__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/TestRunSelector.cls
/**
 * Author:Jaren Yach
 *  Created Date 05/20/2022
 *  Purpose: Selector Class for Test_Run__c
 */
public inherited sharing class TestRunSelector {
    /**
     * Gets records that need to be cleaned up
     *
     * @param days - Number of days
     *
     * @return List<Test_Run__c>
     */
    public List<Test_Run__c> getRecordsToPrune(Integer days) {
        String soql = String.format('SELECT Id FROM Test_Run__c WHERE Processed__c = TRUE AND CreatedDate != LAST_N_DAYS:{0}', new List<Object>{ days });
        return Database.query(soql);
    }

    /**
     * Gets the Test_Run__c record by Id
     * @param recId - Test Run Id
     *
     * @return Test_Run__c
     */
    public Test_Run__c getByRecordId(Id recId) {
        return [SELECT Id, Processed__c, Test_Failures__c FROM Test_Run__c WHERE Id = :recId];
    }
}