sfdx-source/main/default/objects/PC_Service__c/PC_Service__c.object-meta.xml
<CustomObject>
    <description>Object to display related VISNs, Territories, and Locations</description>
    <label>PrC Service</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Service Name (e.g. Eastern Cardio Group)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PrC Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/PC_Service_Team_Member__c/PC_Service_Team_Member__c.object-meta.xml
<CustomObject>
    <description>Object to display Service Team Members</description>
    <label>PrC Service Team Member</label>
    <nameField>
        <displayFormat>STM-{00000}</displayFormat>
        <label>Service Team Member Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrC Service Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PC_Service_Team_Member__c/fields/PC_Service__c.field-meta.xml
<CustomField>
    <fullName>PC_Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>PC_Service__c</referenceTo>
    <relationshipLabel>Service Team Members</relationshipLabel>
    <relationshipName>Service_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PC_Service_Team_Member__c/fields/PC_Service_Resource__c.field-meta.xml
<CustomField>
    <fullName>PC_Service_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Service Team Members</relationshipLabel>
    <relationshipName>Service_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PC_Shift__c/PC_Shift__c.object-meta.xml
<CustomObject>
    <description>Object to provide the ability to create shifts from the service record page that can be added to the service&apos;s schedule.</description>
    <label>PrC Shift</label>
    <nameField>
        <displayFormat>S-{000}</displayFormat>
        <label>Shift</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrC Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PC_Shift__c/fields/PC_Service__c.field-meta.xml
<CustomField>
    <fullName>PC_Service__c</fullName>
    <label>Service</label>
    <referenceTo>PC_Service__c</referenceTo>
    <relationshipLabel>Shifts</relationshipLabel>
    <relationshipName>Shifts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/PC_Shift__c/fields/PC_Service_Team_Member__c.field-meta.xml
<CustomField>
    <fullName>PC_Service_Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Team Member</label>
    <referenceTo>PC_Service_Team_Member__c</referenceTo>
    <relationshipLabel>Shifts</relationshipLabel>
    <relationshipName>Shifts</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/objects/PC_Shift__c/fields/PC_Shift_Status__c.field-meta.xml
<CustomField>
    <fullName>PC_Shift_Status__c</fullName>
    <label>Shift Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Tentative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PC_Shift__c/fields/PC_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>PC_Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

sfdx-source/main/default/objects/ServiceResource/fields/PC_Assigned_Specialty__c.field-meta.xml
<CustomField>
    <fullName>PC_Assigned_Specialty__c</fullName>
    <label>Assigned Specialty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PC_Specialties</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/ServiceResource/recordTypes/PC_Resource.recordType-meta.xml
<RecordType>
    <fullName>PC_Resource</fullName>
    <active>true</active>
    <description>Used for a provider connect specific service resource</description>
    <label>Provider Connect Resource</label>
</RecordType>

force-app/main/default/globalValueSets/PC_Specialties.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Addiction Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>Allergy/Immunology</fullName>
    </customValue>
    <customValue>
        <fullName>Amputation Clinic</fullName>
    </customValue>
    <customValue>
        <fullName>Anesthesiology</fullName>
    </customValue>
    <customValue>
        <fullName>Anti-Coagulation Clinic</fullName>
    </customValue>
    <customValue>
        <fullName>Audiology</fullName>
    </customValue>
    <customValue>
        <fullName>Blood Pressure Evaluation</fullName>
    </customValue>
    <customValue>
        <fullName>Brain Injury</fullName>
    </customValue>
    <customValue>
        <fullName>Bros (Blind Rehab O/P Spec)</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiac Catheterization</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiac Implantable Electronic Devices (Cied)</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiac Surgery</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiology</fullName>
    </customValue>
    <customValue>
        <fullName>Chart Consult</fullName>
    </customValue>
    <customValue>
        <fullName>Clinical Pharmacy</fullName>
    </customValue>
    <customValue>
        <fullName>Community Care Consult</fullName>
    </customValue>
    <customValue>
        <fullName>Community Nursing Home (Cnh) Follow-Up</fullName>
    </customValue>
    <customValue>
        <fullName>Computerized Tomography (Ct)</fullName>
    </customValue>
    <customValue>
        <fullName>Cysto Room Unit For Outpatient</fullName>
    </customValue>
    <customValue>
        <fullName>Dental</fullName>
    </customValue>
    <customValue>
        <fullName>Dermatology</fullName>
    </customValue>
    <customValue>
        <fullName>Diabetes</fullName>
    </customValue>
    <customValue>
        <fullName>Eeg</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>Endocrinology</fullName>
    </customValue>
    <customValue>
        <fullName>Epilepsy</fullName>
    </customValue>
    <customValue>
        <fullName>Eye Telehealth Screening</fullName>
    </customValue>
    <customValue>
        <fullName>Gastroenterology</fullName>
    </customValue>
    <customValue>
        <fullName>General Internal Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>General Surgery</fullName>
    </customValue>
    <description>DO NOT CHANGE API NAME OF PICKLIST VALUES</description>
    <masterLabel>PC Specialties</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/PC/PC_AvailabilityGanttChart.cls
/**
 * @description       : Class used as to serve data to the Gantt Chart
 * @author            : Edwin Schaeffer
 * @group             : Salesforce
 * @last modified on  : 09-11-2023
 * @last modified by  : Edwin Schaeffer
 * Modifications Log
 * Ver   Date         Author                               Modification
 * 1.0   09-11-2023   Edwin Schaeffer                     Initial Version
 **/
public without sharing class PC_AvailabilityGanttChart {
    /**
     * @description       : Fetches shift data, aggregates shift times, and organizes data given a date. The main driver for the Gantt Chart
     * @param             : Date formatted string in MM/DD/YYYY form
     * @return            : returns a complex object shifts by Service Resources organized by Skill.
     **/
    @AuraEnabled
    @SuppressWarnings('PMD.ApexCRUDViolation')
    public static Map<String, Object> getChartData(String startDateStr) {
        if (String.isEmpty(startDateStr)) {
            throw new PC_CustomException('The date cannot be blank.');
        }
        Date startDate = Date.parse(startDateStr);
        Map<String, Object> data = new Map<String, Object>();
        List<PC_Shift__c> shifts;
        if (Schema.sObjectType.PC_Shift__c.isAccessible()) {
            // Cannot assign PCP (provider) users Read permissions to ServiceResource due to Platform license restrictions. Cannnot Security Enforce.
            shifts = [
                SELECT
                    Id,
                    PC_Start_Time__c,
                    PC_End_Time__c,
                    PC_Date__c,
                    PC_Shift_Status__c,
                    PC_Service_Team_Member__r.PC_Service_Resource__c,
                    PC_Service_Team_Member__r.PC_Service_Resource__r.Name,
                    PC_Service_Team_Member__r.PC_Service_Resource__r.PC_Assigned_Specialty__c,
                    PC_Service__c
                FROM PC_Shift__c
                WHERE PC_Date__c = :startDate AND PC_Service_Team_Member__r.PC_Service_Resource__r.IsActive = TRUE
                ORDER BY PC_Service_Team_Member__r.PC_Service_Resource__r.PC_Assigned_Specialty__c ASC, PC_Start_Time__c ASC
            ];
        }

        Map<String, Object> serviceResourceById = new Map<String, Object>();
        Map<String, Object> skillsById = new Map<String, Object>();

        // Check for overlap and aggregate shift times
        String prevSpecialty = '';
        PC_Shift__c prevShift = null;
        Map<Id, PC_Shift__c> overlapMap = new Map<Id, PC_Shift__c>();
        for (PC_Shift__c shift : shifts) {
            String currentSpecialty = shift.PC_Service_Team_Member__r.PC_Service_Resource__r.PC_Assigned_Specialty__c;
            if (prevShift != null && prevSpecialty == currentSpecialty && shift.PC_Start_Time__c <= prevShift.PC_End_Time__c && shift.PC_End_Time__c >= prevShift.PC_End_Time__c) {
                shift.PC_Start_Time__c = prevShift.PC_Start_Time__c;
                overlapMap.put(prevShift.Id, prevShift);
            } // else if other shift completely overlaps, no need to aggregate. Just eliminate from Gantt.
            else if (
                prevShift != null &&
                prevSpecialty == currentSpecialty &&
                shift.PC_Start_Time__c <= prevShift.PC_End_Time__c &&
                shift.PC_End_Time__c <= prevShift.PC_End_Time__c
            ) {
                overlapMap.put(shift.Id, shift);
                continue;
            }
            prevShift = shift;
            prevSpecialty = currentSpecialty;
        }
        // Organize aggregated shifts
        List<PC_Shift__c> finalShiftList = new List<PC_Shift__c>();
        for (PC_Shift__c shift : shifts) {
            if (!overlapMap.containsKey(shift.Id)) {
                finalShiftList.add(shift);
            }
        }

        // display all active resources, skills, and shifts
        for (Object s : PC_AvailabilityGanttChart.getResources()) {
            Map<String, Object> skill = (Map<String, Object>) s;
            Map<String, Object> shiftsByServiceResource = new Map<String, Object>();
            for (PC_Shift__c shift : finalShiftList) {
                String specialty = shift.PC_Service_Team_Member__r.PC_Service_Resource__r.PC_Assigned_Specialty__c;
                if (skill.get('Name') == specialty) {
                    String srId = shift.PC_Service_Team_Member__r.PC_Service_Resource__c;
                    String srName = shift.PC_Service_Team_Member__r.PC_Service_Resource__r.Name;
                    Decimal hoursStart = getHours(String.valueOf(shift.PC_Start_Time__c));
                    Decimal hoursEnd = getHours(String.valueOf(shift.PC_End_Time__c));
                    String timeRange = getHoursRangeString(String.valueOf(shift.PC_Start_Time__c), String.valueOf(shift.PC_End_Time__c));
                    shiftsByServiceResource.put(
                        srId,
                        new Map<String, Object>{
                            'Id' => shift.Id,
                            'PC_Start_Time__c' => shift.PC_Start_Time__c,
                            'PC_End_Time__c' => shift.PC_End_Time__c,
                            'PC_Shift_Status__c' => shift.PC_Shift_Status__c,
                            'timeRange' => timeRange,
                            'SRName' => srName,
                            'left' => hoursStart,
                            'right' => hoursEnd
                        }
                    );
                }
            }

            skillsById.put(
                (String) skill.get('Id'),
                new Map<String, Object>{ 'Id' => skill.get('Id'), 'Name' => skill.get('Name'), 'shiftsByServiceResource' => shiftsByServiceResource }
            );
        }
        data.put('skills', skillsById.values());
        return data;
    }
    /**
     * @description       : Fetches Service Resource and Skills Data to be used on the Gantt Chart
     * @param             : Date formatted string in MM/DD/YYYY form
     * @return            : Returns a list of Skills-By-Resource complex object
     */
    @AuraEnabled
    public static List<Object> getResources() {
        Id pcRTId = Schema.SObjectType.ServiceResource.getRecordTypeInfosByDeveloperName().get('PC_Resource').getRecordTypeId();

        //Cannot grant pcp access through permission set for the Skills object. Cannot enforce security in this query. Apex class is secured by permission set for PC users onlu
        @SuppressWarnings('PMD.ApexCRUDViolation')
        List<ServiceResourceSkill> relevantSkills = [
            SELECT Skill.MasterLabel
            FROM ServiceResourceSkill
            WHERE ServiceResource.ResourceType = 'A' AND ServiceResource.IsActive = TRUE AND ServiceResource.RecordTypeId = :pcRTId
            ORDER BY Skill.MasterLabel ASC
        ];
        List<Object> skills = new List<Object>();
        Set<String> skillSet = new Set<String>();
        for (ServiceResourceSkill sk : relevantSkills) {
            String skillLabel = sk.Skill.MasterLabel;
            if (skillLabel != 'Chat' && skillLabel != 'Phone' && skillLabel != 'Teams') {
                skillSet.add(skillLabel);
            }
        }
        Integer key = 0;
        for (String s : skillSet) {
            skills.add(new Map<String, Object>{ 'Id' => String.valueOf(key), 'Name' => s });
            key++;
        }
        return skills;
    }
    private static Decimal getHours(String strTime) {
        String[] timeStr = strTime.split(':');
        Integer timeHour = Integer.valueOf(timeStr[0]);
        Integer timeMin = Integer.valueOf(timeStr[1]);
        return Decimal.valueOf(timeHour) + timeMin / 60.0;
    }

    private static String getHoursRangeString(String startTime, String endTime) {
        String[] timeStr1 = startTime.split(':');
        String[] timeStr2 = endTime.split(':');
        return timeStr1[0] + ':' + timeStr1[1] + ' - ' + timeStr2[0] + ':' + timeStr2[1];
    }
}