sfdx-source/main/default/objects/PC_Service__c/PC_Service__c.object-meta.xml
<CustomObject>
    <description>Object to display related VISNs, Territories, and Locations</description>
    <label>PrC Service</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Service Name (e.g. Eastern Cardio Group)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PrC Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/PC_Service__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates if a service is active.</description>
    <inlineHelpText>Is this service active?</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/PC_Service__c/fields/PC_Specialty__c.field-meta.xml
<CustomField>
    <fullName>PC_Specialty__c</fullName>
    <label>Specialty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PC_Specialties</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/PC_Service_Team_Member__c/PC_Service_Team_Member__c.object-meta.xml
<CustomObject>
    <description>Object to display Service Team Members</description>
    <label>PrC Service Team Member</label>
    <nameField>
        <displayFormat>STM-{00000}</displayFormat>
        <label>Service Team Member Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrC Service Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PC_Service_Team_Member__c/fields/PC_Service__c.field-meta.xml
<CustomField>
    <fullName>PC_Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>PC_Service__c</referenceTo>
    <relationshipLabel>Service Team Members</relationshipLabel>
    <relationshipName>Service_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PC_Service_Team_Member__c/fields/PC_Service_Resource__c.field-meta.xml
<CustomField>
    <fullName>PC_Service_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Service Team Members</relationshipLabel>
    <relationshipName>Service_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/objects/PC_Service_Team_Member__c/fields/PC_Service_Team_Member_Role__c.field-meta.xml
<CustomField>
    <fullName>PC_Service_Team_Member_Role__c</fullName>
    <label>Member Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Specialist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/PC_Specialties.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Addiction Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>Allergy/Immunology</fullName>
    </customValue>
    <customValue>
        <fullName>Amputation Clinic</fullName>
    </customValue>
    <customValue>
        <fullName>Anesthesiology</fullName>
    </customValue>
    <customValue>
        <fullName>Anti-Coagulation Clinic</fullName>
    </customValue>
    <customValue>
        <fullName>Audiology</fullName>
    </customValue>
    <customValue>
        <fullName>Blood Pressure Evaluation</fullName>
    </customValue>
    <customValue>
        <fullName>Brain Injury</fullName>
    </customValue>
    <customValue>
        <fullName>Bros (Blind Rehab O/P Spec)</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiac Catheterization</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiac Implantable Electronic Devices (Cied)</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiac Surgery</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiology</fullName>
    </customValue>
    <customValue>
        <fullName>Chart Consult</fullName>
    </customValue>
    <customValue>
        <fullName>Clinical Pharmacy</fullName>
    </customValue>
    <customValue>
        <fullName>Community Care Consult</fullName>
    </customValue>
    <customValue>
        <fullName>Community Nursing Home (Cnh) Follow-Up</fullName>
    </customValue>
    <customValue>
        <fullName>Computerized Tomography (Ct)</fullName>
    </customValue>
    <customValue>
        <fullName>Cysto Room Unit For Outpatient</fullName>
    </customValue>
    <customValue>
        <fullName>Dental</fullName>
    </customValue>
    <customValue>
        <fullName>Dermatology</fullName>
    </customValue>
    <customValue>
        <fullName>Diabetes</fullName>
    </customValue>
    <customValue>
        <fullName>Eeg</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>Endocrinology</fullName>
    </customValue>
    <customValue>
        <fullName>Epilepsy</fullName>
    </customValue>
    <customValue>
        <fullName>Eye Telehealth Screening</fullName>
    </customValue>
    <customValue>
        <fullName>Gastroenterology</fullName>
    </customValue>
    <customValue>
        <fullName>General Internal Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>General Surgery</fullName>
    </customValue>
    <description>DO NOT CHANGE API NAME OF PICKLIST VALUES</description>
    <masterLabel>PC Specialties</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

sfdx-source/main/default/classes/PC/PC_LookupControllerTest.cls
@isTest
public class PC_LookupControllerTest {
    @testSetup
    public static void makeData() {
        User manager = PC_TestDataFactory.createManager('TestPCManager55');
        User specialist = PC_TestDataFactory.createSpecialist('TestPCSpecialist');
        System.runAs(manager) {
            ServiceResource sr = PC_TestDataFactory.createServiceResource(specialist.Id, 'TestPCSpecialist', 'Cardiology');
            PC_Service__c pcService = new PC_Service__c(PC_Specialty__c = 'Cardiology', Active__c = true);
            insert pcService;
            PC_Service_Team_Member__c pcstm = new PC_Service_Team_Member__c(
                PC_Service_Team_Member_Role__c = 'Specialist',
                PC_Service__c = pcService.Id,
                PC_Service_Resource__c = sr.Id
            );
            insert pcstm;
        }
    }
    @isTest
    public static void testSearch() {
        User manager = [SELECT Id FROM User WHERE LastName = 'TestPCManager55' LIMIT 1];

        System.runAs(manager) {
            PC_Service__c pcService = [SELECT Id, Name FROM PC_Service__c WHERE PC_Specialty__c = 'Cardiology' LIMIT 1];
            PC_Service_Team_Member__c pcstm = [SELECT Id FROM PC_Service_Team_Member__c LIMIT 1];
            Id[] fixedSearchResults = new Id[1];
            fixedSearchResults[0] = pcstm.Id;
            Test.setFixedSearchResults(fixedSearchResults);
            List<LookupSearchResult> result = PC_LookupController.search('Test', pcService.Id);
            System.assertEquals(1, result.size());
            List<LookupSearchResult> someResults = PC_LookupController.getSomeResults(pcService.Id);
            System.assertEquals(1, someResults.size());
        }
    }
}