sfdx-source/main/default/objects/PC_Service__c/PC_Service__c.object-meta.xml
<CustomObject>
    <description>Object to display related VISNs, Territories, and Locations</description>
    <label>PrC Service</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Service Name (e.g. Eastern Cardio Group)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PrC Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/PC_Service__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates if a service is active.</description>
    <inlineHelpText>Is this service active?</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/PC_Service__c/fields/PC_Specialty__c.field-meta.xml
<CustomField>
    <fullName>PC_Specialty__c</fullName>
    <label>Specialty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PC_Specialties</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/PC_Service_Team_Member__c/PC_Service_Team_Member__c.object-meta.xml
<CustomObject>
    <description>Object to display Service Team Members</description>
    <label>PrC Service Team Member</label>
    <nameField>
        <displayFormat>STM-{00000}</displayFormat>
        <label>Service Team Member Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrC Service Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PC_Service_Team_Member__c/fields/PC_Service__c.field-meta.xml
<CustomField>
    <fullName>PC_Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>PC_Service__c</referenceTo>
    <relationshipLabel>Service Team Members</relationshipLabel>
    <relationshipName>Service_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PC_Service_Team_Member__c/fields/PC_Service_Resource__c.field-meta.xml
<CustomField>
    <fullName>PC_Service_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Service Team Members</relationshipLabel>
    <relationshipName>Service_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/objects/PC_Service_Team_Member__c/fields/PC_Service_Team_Member_Role__c.field-meta.xml
<CustomField>
    <fullName>PC_Service_Team_Member_Role__c</fullName>
    <label>Member Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Specialist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/PC_Specialist_Availability__c/PC_Specialist_Availability__c.object-meta.xml
<CustomObject>
    <description>Object to display when a Specialist is available</description>
    <label>PrC Specialist Availability</label>
    <nameField>
        <displayFormat>SA-{0000000000}</displayFormat>
        <label>Specialist Availability</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrC Specialist Availabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PC_Specialist_Availability__c/fields/PC_Service_Resource__c.field-meta.xml
<CustomField>
    <fullName>PC_Service_Resource__c</fullName>
    <label>Service Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipName>PC_Specialist_Availabilities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PC_Specialist_Availability__c/fields/PC_Week_Ending_Date__c.field-meta.xml
<CustomField>
    <fullName>PC_Week_Ending_Date__c</fullName>
    <description>Week ending date of availability</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Week Ending Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/PC_Specialties.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Addiction Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>Allergy/Immunology</fullName>
    </customValue>
    <customValue>
        <fullName>Amputation Clinic</fullName>
    </customValue>
    <customValue>
        <fullName>Anesthesiology</fullName>
    </customValue>
    <customValue>
        <fullName>Anti-Coagulation Clinic</fullName>
    </customValue>
    <customValue>
        <fullName>Audiology</fullName>
    </customValue>
    <customValue>
        <fullName>Blood Pressure Evaluation</fullName>
    </customValue>
    <customValue>
        <fullName>Brain Injury</fullName>
    </customValue>
    <customValue>
        <fullName>Bros (Blind Rehab O/P Spec)</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiac Catheterization</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiac Implantable Electronic Devices (Cied)</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiac Surgery</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiology</fullName>
    </customValue>
    <customValue>
        <fullName>Chart Consult</fullName>
    </customValue>
    <customValue>
        <fullName>Clinical Pharmacy</fullName>
    </customValue>
    <customValue>
        <fullName>Community Care Consult</fullName>
    </customValue>
    <customValue>
        <fullName>Community Nursing Home (Cnh) Follow-Up</fullName>
    </customValue>
    <customValue>
        <fullName>Computerized Tomography (Ct)</fullName>
    </customValue>
    <customValue>
        <fullName>Cysto Room Unit For Outpatient</fullName>
    </customValue>
    <customValue>
        <fullName>Dental</fullName>
    </customValue>
    <customValue>
        <fullName>Dermatology</fullName>
    </customValue>
    <customValue>
        <fullName>Diabetes</fullName>
    </customValue>
    <customValue>
        <fullName>Eeg</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>Endocrinology</fullName>
    </customValue>
    <customValue>
        <fullName>Epilepsy</fullName>
    </customValue>
    <customValue>
        <fullName>Eye Telehealth Screening</fullName>
    </customValue>
    <customValue>
        <fullName>Gastroenterology</fullName>
    </customValue>
    <customValue>
        <fullName>General Internal Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>General Surgery</fullName>
    </customValue>
    <description>DO NOT CHANGE API NAME OF PICKLIST VALUES</description>
    <masterLabel>PC Specialties</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/PC/PC_AvailabilityGanttChart_Test.cls
/**
 * @description test class for PC_AvailabilityGanttChart
 * @author      Booz Allen
 * @since       2024
 * @see         PC_AvailabilityGanttChart
 **/
@IsTest
public with sharing class PC_AvailabilityGanttChart_Test {
    /**
     * @description       : Creates test setup data
     **/
    @testSetup
    public static void makeData() {
        List<String> channels = new List<String>{ 'Chat', 'Teams', 'Phone' };
        List<Skill> lsChannelSKills = [SELECT Id FROM Skill WHERE MasterLabel IN :channels LIMIT 3];
        ServiceResource pcSR = null;

        User pcManager = generateUserWithAccess('PrC_Specialist_Manager_Users', 'Test Manager');
        User specialistUser = generateUserWithAccess('PrC_Specialist_Users', 'Test PC Specialist');

        System.runAs(pcManager) {
            pcSR = PC_TestDataFactory.createServiceResource(specialistUser.Id, specialistUser.LastName, 'Cardiology');
            PC_TestDataFactory.createServiceResourceSkill(pcSR.Id, lsChannelSKills[0].Id);
        }

        System.runAs(pcManager) {
            PC_Service__c pcService = new PC_Service__c(PC_Specialty__c = 'Cardiology', Active__c = true);
            insert pcService;
            PC_Service_Team_Member__c pcstm = new PC_Service_Team_Member__c(
                PC_Service_Team_Member_Role__c = 'Specialist',
                PC_Service__c = pcService.Id,
                PC_Service_Resource__c = pcSR.Id
            );
            insert pcstm;
            Date shiftDate = Date.newInstance(2023, 9, 10);
            PC_Specialist_Availability__c avail = new PC_Specialist_Availability__c(
                PC_Week_Ending_Date__c = shiftDate,
                PC_Service_Resource__c = pcSR.Id
            );
            insert avail;
            pcScheduleShiftsController.insertShift(pcService.Id, pcstm.Id, '05:00', '12:00', shiftDate, '9/10/2023');
            pcScheduleShiftsController.insertShift(pcService.Id, pcstm.Id, '05:30', '14:00', shiftDate, '9/10/2023');
            pcScheduleShiftsController.insertShift(pcService.Id, pcstm.Id, '06:30', '13:00', shiftDate, '9/10/2023');
        }
    }
    /**
     * @description       : Tests the main chart. Verifies times are producing the correct intervals for the bars
     **/
    @IsTest
    public static void unitGetChartDataTest() {
        ServiceResource serviceRes = [SELECT Id FROM ServiceResource WHERE Name = 'Test PC Specialist' LIMIT 1];
        User provider = generateUserWithAccess('PrC_FLP_Users', 'flp User');
        System.runAs(provider) {
            Map<String, Object> chartData = PC_AvailabilityGanttChart.getChartData('9/10/2023');
            List<Object> chartDataStruct = (List<Object>) chartData.get('skills');
            for (Object skills : chartDataStruct) {
                Map<String, Object> skill = (Map<String, Object>) skills;
                if (skill.get('shiftsByServiceResource') != null) {
                    Map<String, Object> shiftsByServiceResource = (Map<String, Object>) skill.get(
                        'shiftsByServiceResource'
                    );
                    if (!shiftsByServiceResource.isEmpty()) {
                        if (shiftsByServiceResource.containsKey(serviceRes.Id)) {
                            Map<String, Object> shifts = (Map<String, Object>) shiftsByServiceResource.get(
                                serviceRes.Id
                            );
                            System.assertEquals(shifts.get('left'), 5, 'Incorrect Gantt Calculation');
                            System.assertEquals(shifts.get('right'), 14, 'Incorrect Gantt Calculation');
                        }
                    }
                }
            }
        }
    }

    /**
     * @description helper method to generate an test user with the specified permission set groupfor use in test methods
     * @param       permissionSetGroupName api name of the permission set group to give the user
     * @param       lastName Controller class executes with last name = 'Test PC Manager'
     * @return      `User` Salesforce user with the appropriate permission set group
     */
    private static User generateUserWithAccess(String permissionSetGroupName, String lastName) {
        VATEST_UserBuilder pcTestUser = new VATEST_UserBuilder();
        pcTestUser.withPermissionSet(permissionSetGroupName).withUserProfile('VAVET Base Profile').withStandardData();
        pcTestUser.resultingUser.LastName = lastName;
        return pcTestUser.build(true);
    }
}