sfdx-source/main/default/objects/External_VA_Link__mdt/External_VA_Link__mdt.object-meta.xml
<CustomObject>
    <description
    >Records of the Custom Metadata Type drive the behavior of the vccExternalVaLinks lightning web component. the &quot;vcc&quot; prefix has been deliberately omitted, as part
        of a coordinated effort to build a Global Dynamic Links component. The vccExternalVaLinks component is slated for deprecation, and this MDT will survive to drive the
        behavior of the generic &quot;ExternalVALinks&quot; lightning web component.</description>
    <label>External VA Link</label>
    <pluralLabel>External VA Links</pluralLabel>
</CustomObject>

force-app/main/default/objects/External_VA_Link__mdt/fields/Audience__c.field-meta.xml
<CustomField>
    <fullName>Audience__c</fullName>
    <description>This field determines which users a given link will be displayed to.</description>
    <inlineHelpText>This field determines which users a given link will be displayed to.</inlineHelpText>
    <label>Audience</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
                <default>true</default>
                <label>All</label>
            </value>
            <value>
                <fullName>VCC</fullName>
            </value>
            <value>
                <fullName>TUC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/External_VA_Link__mdt/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>Links are shown in the ascending order, based on this field value.</description>
    <inlineHelpText>Links are shown in the ascending order, based on this field value.</inlineHelpText>
    <label>Sort Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/main/default/objects/External_VA_Link__mdt/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>This value determines the Redirection Target when clicked by a user.</description>
    <inlineHelpText>This value determines the Redirection Target when clicked by a user.</inlineHelpText>
    <label>URL</label>
    <type>Url</type>
</CustomField>

sfdx-source/main/default/classes/VCR/VCR_ExternalVaLinksRepo.cls
/**
 * @description This repository is for the External VA Links custom metadata records
 * @author Booz Allen Hamilton
 * @since 05/2024
 */
public virtual inherited sharing class VCR_ExternalVaLinksRepo extends VTC_BaseRepo {
    /**
     * @description Constructor function for VCR_ExternalVaLinksRepo. Calls super constructor which sets this.sObjectType to
     * External_VA_Link__mdt and adds additional fields on query return
     */
    public VCR_ExternalVaLinksRepo() {
        super(External_VA_Link__mdt.sObjectType);
        this.defaultSelectFields.addAll(
            new Set<String>{ 'Audience__c', 'Sort_Order__c', 'URL__c', 'DeveloperName', 'MasterLabel' }
        );
    }

    /**
     * @description retrieves all of the External VA Links that match the audience criteria
     * @param audiences - list of audiences
     * @param limitCount - the limit at the end of the query
     * @return List<External_VA_Link__mdt> - list of External VA Link records matching the criteria
     */
    public List<External_VA_Link__mdt> getVALinksFromAudience(List<String> audiences, Integer limitCount) {
        String listElements = '\'' + String.join(audiences, '\',\'') + '\'';

        String selectClause = 'SELECT Audience__c, Sort_Order__c, URL__c, DeveloperName, MasterLabel ';
        String fromClause = 'FROM External_VA_Link__mdt ';
        String whereClause = 'WHERE Audience__c IN (' + listElements + ') ';
        String orderClause = 'ORDER BY Sort_Order__c ASC ';
        String limitClause = 'LIMIT ' + String.valueOf(limitCount);
        String query = selectClause + fromClause + whereClause + orderClause + limitClause;

        return this.fetch(query);
    }
}