sfdx-source/main/default/objects/PC_Operating_Hours__c/PC_Operating_Hours__c.object-meta.xml
<CustomObject>
    <description>Object to display operating hours of a service and to hold time slots</description>
    <label>PrC Operating Hours</label>
    <nameField>
        <displayFormat>OH - {00000}</displayFormat>
        <label>Operating Hours</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrC Operating Hours</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/PC_Service__c/PC_Service__c.object-meta.xml
<CustomObject>
    <description>Object to display related VISNs, Territories, and Locations</description>
    <label>PrC Service</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Service Name (e.g. Eastern Cardio Group)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PrC Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PC_Service__c/fields/PC_Operating_Hours__c.field-meta.xml
<CustomField>
    <fullName>PC_Operating_Hours__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Standard OperatingHours object. Likely not needed, can be removed later as we have a lookup field to the PC Operating Hours object</description>
    <label>Operating Hours Standard</label>
    <referenceTo>OperatingHours</referenceTo>
    <relationshipName>Services_Standard</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/objects/PC_Service_Team_Member__c/PC_Service_Team_Member__c.object-meta.xml
<CustomObject>
    <description>Object to display Service Team Members</description>
    <label>PrC Service Team Member</label>
    <nameField>
        <displayFormat>STM-{00000}</displayFormat>
        <label>Service Team Member Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrC Service Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PC_Service_Team_Member__c/fields/PC_Service__c.field-meta.xml
<CustomField>
    <fullName>PC_Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>PC_Service__c</referenceTo>
    <relationshipLabel>Service Team Members</relationshipLabel>
    <relationshipName>Service_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PC_Service_Team_Member__c/fields/PC_Service_Resource__c.field-meta.xml
<CustomField>
    <fullName>PC_Service_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Service Team Members</relationshipLabel>
    <relationshipName>Service_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PC_Shift__c/PC_Shift__c.object-meta.xml
<CustomObject>
    <description>Object to provide the ability to create shifts from the service record page that can be added to the service&apos;s schedule.</description>
    <label>PrC Shift</label>
    <nameField>
        <displayFormat>S-{000}</displayFormat>
        <label>Shift</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrC Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PC_Shift__c/fields/PC_Service__c.field-meta.xml
<CustomField>
    <fullName>PC_Service__c</fullName>
    <label>Service</label>
    <referenceTo>PC_Service__c</referenceTo>
    <relationshipLabel>Shifts</relationshipLabel>
    <relationshipName>Shifts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/PC_Shift__c/fields/PC_Service_Team_Member__c.field-meta.xml
<CustomField>
    <fullName>PC_Service_Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Team Member</label>
    <referenceTo>PC_Service_Team_Member__c</referenceTo>
    <relationshipLabel>Shifts</relationshipLabel>
    <relationshipName>Shifts</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/objects/PC_Shift__c/fields/PC_Shift_Status__c.field-meta.xml
<CustomField>
    <fullName>PC_Shift_Status__c</fullName>
    <label>Shift Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Tentative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PC_Shift__c/fields/PC_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>PC_Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

sfdx-source/main/default/objects/PC_Specialist_Availability__c/PC_Specialist_Availability__c.object-meta.xml
<CustomObject>
    <description>Object to display when a Specialist is available</description>
    <label>PrC Specialist Availability</label>
    <nameField>
        <displayFormat>SA-{0000000000}</displayFormat>
        <label>Specialist Availability</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrC Specialist Availabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/PC_Specialist_Availability__c/fields/PC_End__c.field-meta.xml
<CustomField>
    <fullName>PC_End__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/PC_Specialist_Availability__c/fields/PC_Service_Resource__c.field-meta.xml
<CustomField>
    <fullName>PC_Service_Resource__c</fullName>
    <label>Service Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipName>PC_Specialist_Availabilities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/main/default/objects/PC_Specialist_Availability__c/fields/PC_Start__c.field-meta.xml
<CustomField>
    <fullName>PC_Start__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/PC_Specialist_Availability__c/fields/PC_Week_Ending_Date__c.field-meta.xml
<CustomField>
    <fullName>PC_Week_Ending_Date__c</fullName>
    <description>Week ending date of availability</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Week Ending Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PC_Time_Slot__c/PC_Time_Slot__c.object-meta.xml
<CustomObject>
    <description>Object to collect specific information for coverage hours and exceptions.</description>
    <label>PrC Time Slot</label>
    <nameField>
        <displayFormat>TS-{00000}</displayFormat>
        <label>Time Slot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrC Time Slots</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PC_Time_Slot__c/fields/Availability__c.field-meta.xml
<CustomField>
    <fullName>Availability__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A specialist&apos;s availability</description>
    <label>Availability</label>
    <referenceTo>PC_Specialist_Availability__c</referenceTo>
    <relationshipLabel>PC_Time Slots</relationshipLabel>
    <relationshipName>PC_Time_Slots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PC_Time_Slot__c/fields/PC_Date__c.field-meta.xml
<CustomField>
    <fullName>PC_Date__c</fullName>
    <defaultValue>Now()</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PC_Time_Slot__c/fields/PC_End__c.field-meta.xml
<CustomField>
    <fullName>PC_End__c</fullName>
    <defaultValue>TIMEVALUE(&quot;17:00:00.000&quot;)</defaultValue>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/PC_Time_Slot__c/fields/PC_Operating_Hours__c.field-meta.xml
<CustomField>
    <fullName>PC_Operating_Hours__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Operating Hours</label>
    <referenceTo>PC_Operating_Hours__c</referenceTo>
    <relationshipLabel>PC_Time Slots</relationshipLabel>
    <relationshipName>Time_Slot</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/objects/PC_Time_Slot__c/fields/PC_Service_Resource__c.field-meta.xml
<CustomField>
    <fullName>PC_Service_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipName>Time_Slot</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PC_Time_Slot__c/fields/PC_Start__c.field-meta.xml
<CustomField>
    <fullName>PC_Start__c</fullName>
    <defaultValue>TIMEVALUE(&quot;08:00:00.000&quot;)</defaultValue>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

sfdx-source/main/default/objects/ServiceResource/fields/PC_Assigned_Specialty__c.field-meta.xml
<CustomField>
    <fullName>PC_Assigned_Specialty__c</fullName>
    <label>Assigned Specialty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PC_Specialties</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/PC_Specialties.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Addiction Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>Allergy/Immunology</fullName>
    </customValue>
    <customValue>
        <fullName>Amputation Clinic</fullName>
    </customValue>
    <customValue>
        <fullName>Anesthesiology</fullName>
    </customValue>
    <customValue>
        <fullName>Anti-Coagulation Clinic</fullName>
    </customValue>
    <customValue>
        <fullName>Audiology</fullName>
    </customValue>
    <customValue>
        <fullName>Blood Pressure Evaluation</fullName>
    </customValue>
    <customValue>
        <fullName>Brain Injury</fullName>
    </customValue>
    <customValue>
        <fullName>Bros (Blind Rehab O/P Spec)</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiac Catheterization</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiac Implantable Electronic Devices (Cied)</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiac Surgery</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiology</fullName>
    </customValue>
    <customValue>
        <fullName>Chart Consult</fullName>
    </customValue>
    <customValue>
        <fullName>Clinical Pharmacy</fullName>
    </customValue>
    <customValue>
        <fullName>Community Care Consult</fullName>
    </customValue>
    <customValue>
        <fullName>Community Nursing Home (Cnh) Follow-Up</fullName>
    </customValue>
    <customValue>
        <fullName>Computerized Tomography (Ct)</fullName>
    </customValue>
    <customValue>
        <fullName>Cysto Room Unit For Outpatient</fullName>
    </customValue>
    <customValue>
        <fullName>Dental</fullName>
    </customValue>
    <customValue>
        <fullName>Dermatology</fullName>
    </customValue>
    <customValue>
        <fullName>Diabetes</fullName>
    </customValue>
    <customValue>
        <fullName>Eeg</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>Endocrinology</fullName>
    </customValue>
    <customValue>
        <fullName>Epilepsy</fullName>
    </customValue>
    <customValue>
        <fullName>Eye Telehealth Screening</fullName>
    </customValue>
    <customValue>
        <fullName>Gastroenterology</fullName>
    </customValue>
    <customValue>
        <fullName>General Internal Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>General Surgery</fullName>
    </customValue>
    <description>DO NOT CHANGE API NAME OF PICKLIST VALUES</description>
    <masterLabel>PC Specialties</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/PC/pcScheduleShiftsController.cls
@SuppressWarnings('PMD.ApexDoc, PMD.ClassNamingConventions, PMD.CognitiveComplexity')
public without sharing class pcScheduleShiftsController {
    @AuraEnabled
    public static Map<Id, List<ShiftStatus>> getNext7DaysShifts(String startDay, Id pcServiceId) {
        Date startDate = Date.parse(startDay);
        Set<Date> next7Days = new Set<Date>();
        for (Integer i = 0; i < 7; i++) {
            Date day = startDate.addDays(i);
            next7Days.add(day);
        }
        List<PC_Service_Team_Member__c> pcTeamMemberList = [
            SELECT Id, PC_Service_Resource__r.RelatedRecord.Name
            FROM PC_Service_Team_Member__c
            WHERE PC_Service__c = :pcServiceId
            WITH SECURITY_ENFORCED
        ];
        List<PC_Shift__c> pcShiftList = [
            SELECT PC_End_Time__c, PC_Start_Time__c, PC_Date__c, PC_Shift_Status__c, PC_Service_Team_Member__c, PC_Service__c
            FROM PC_Shift__c
            WHERE PC_Service__c = :pcServiceId AND PC_Date__c IN :next7Days
            WITH SECURITY_ENFORCED
        ];
        Map<Id, List<ShiftStatus>> shiftTeamMemberMap = new Map<Id, List<ShiftStatus>>();
        for (PC_Service_Team_Member__c pcstm : pcTeamMemberList) {
            List<ShiftStatus> stList = new List<ShiftStatus>();
            for (Date d : next7Days) {
                ShiftStatus st = new ShiftStatus();
                st.serviceResourceId = pcstm.PC_Service_Resource__c;
                st.serviceResourceName = pcstm.PC_Service_Resource__r.RelatedRecord.Name;
                st.serviceTeamMemberId = pcstm.Id;
                st.serviceDate = d;
                //PTEMSPC-473 used to make make LWC column header date in "Day of Week" M/dd format
                DateTime serviceDateTime = DateTime.newInstance(d, Time.newInstance(0, 0, 0, 0));
                st.serviceDateString = serviceDateTime != null ? serviceDateTime.format('E. M/dd') : '';
                stList.add(st);
            }
            shiftTeamMemberMap.put(pcstm.Id, stList);
        }

        for (Id key : shiftTeamMemberMap.keySet()) {
            List<ShiftStatus> stList = shiftTeamMemberMap.get(key);
            for (ShiftStatus shiftStatus : stList) {
                List<PC_Shift__c> shiftList = new List<PC_Shift__c>();
                for (PC_Shift__c shift : pcShiftList) {
                    if (shiftStatus.serviceDate == shift.PC_Date__c && shift.PC_Service_Team_Member__c == shiftStatus.serviceTeamMemberId) {
                        shiftList.add(shift);
                    }
                }
                shiftStatus.shifts = shiftList;
            }
        }
        return shiftTeamMemberMap;
    }
    @AuraEnabled
    public static List<PC_Time_Slot__c> getSpecialistAvailability(Id serviceTeamMemberId) {
        List<PC_Service_Team_Member__c> pcServiceTeamMember = [
            SELECT PC_Service_Resource__c
            FROM PC_Service_Team_Member__c
            WHERE Id = :serviceTeamMemberId
            WITH SECURITY_ENFORCED
        ];
        if (String.isBlank(pcServiceTeamMember[0].PC_Service_Resource__c)) {
            throw new PC_CustomException('Error: The Team Member selected must be linked to a Service Resource.');
        }
        List<PC_Specialist_Availability__c> pcSpecAvailList = [
            SELECT Id, PC_Week_Ending_Date__c
            FROM PC_Specialist_Availability__c
            WHERE PC_Service_Resource__c = :pcServiceTeamMember[0].PC_Service_Resource__c
            WITH SECURITY_ENFORCED
            ORDER BY PC_Week_Ending_Date__c DESC
            LIMIT 1
        ];
        if (pcSpecAvailList.isEmpty()) {
            throw new PC_CustomException('The Team Member did not create a Specialist Availability record.');
        }
        List<PC_Time_Slot__c> pcTs = [
            SELECT Id, PC_Service_Resource__c, PC_Day_of_Week__c, Availability__r.LastModifiedDate, PC_Operating_Hours__c, PC_End__c, PC_Start__c
            FROM PC_Time_Slot__c
            WHERE Availability__c = :pcSpecAvailList[0].Id
            WITH SECURITY_ENFORCED
        ];
        if (pcTs.isEmpty()) {
            throw new PC_CustomException(
                'There is no time slots created for the Team Member\'s most recent Availability record. Please ask the Team member to make time slots for the "Specialist Availabilty" record with the week ending: ' +
                pcSpecAvailList[0].PC_Week_Ending_Date__c
            );
        }
        return pcTs;
    }

    @SuppressWarnings('PMD.ExcessiveParameterList')
    @AuraEnabled
    public static Map<Id, List<ShiftStatus>> insertShift(Id pcServiceId, Id pcServiceMemberId, String startTime, String endTime, Date shiftDate, String startDay) {
        PC_Shift__c pcShift = new PC_Shift__c(PC_Service__c = pcServiceId, PC_Service_Team_Member__c = pcServiceMemberId, PC_Date__c = shiftDate, PC_Shift_Status__c = 'Tentative');
        Time startT = convertStringtoTime(startTime);
        Time endT = convertStringtoTime(endTime);
        pcShift.PC_Start_Time__c = startT;
        pcShift.PC_End_Time__c = endT;
        if (Schema.sObjectType.PC_Shift__c.isCreateable()) {
            insert pcShift;
            return getNext7DaysShifts(startDay, pcServiceId);
        } else {
            throw new PC_CustomException('You do not have permission to create a Shift.');
        }
    }
    @AuraEnabled
    public static Map<Id, List<ShiftStatus>> updateShift(Id pcShiftId, String startTime, String endTime, Date shiftDate, String startDay, Id pcServiceId) {
        PC_Shift__c pcShift = new PC_Shift__c(Id = pcShiftId);
        Time startT = convertStringtoTime(startTime);
        Time endT = convertStringtoTime(endTime);
        pcShift.PC_Start_Time__c = startT;
        pcShift.PC_End_Time__c = endT;
        pcShift.PC_Date__c = shiftDate;
        if (Schema.sObjectType.PC_Shift__c.isUpdateable()) {
            update pcShift;
            return getNext7DaysShifts(startDay, pcServiceId);
        } else {
            throw new PC_CustomException('You do not have permission to update a Shift.');
        }
    }
    @AuraEnabled
    public static Map<Id, List<ShiftStatus>> deleteShift(Id pcShiftId, String startDay, Id pcServiceId) {
        PC_Shift__c pcShift = new PC_Shift__c(Id = pcShiftId);
        if (Schema.sObjectType.PC_Shift__c.isDeletable()) {
            delete pcShift;
            return getNext7DaysShifts(startDay, pcServiceId);
        } else {
            throw new PC_CustomException('You do not have permission to delete a Shift.');
        }
    }

    @AuraEnabled
    public static Map<Id, String> getSpecialities(List<String> serviceResourceIds) {
        try {
            List<ServiceResource> serviceResources = [
                SELECT Id, PC_Assigned_Specialty__c
                FROM ServiceResource
                WHERE Id = :serviceResourceIds
                WITH SECURITY_ENFORCED
            ];
            Map<Id, String> specialities = new Map<Id, String>();
            for (ServiceResource sr : serviceResources) {
                specialities.put(sr.Id, sr.PC_Assigned_Specialty__c);
            }
            return specialities;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    private static Time convertStringtoTime(String strTime) {
        String[] strTimeSplit = strTime.split(':');
        Time timeChange = Time.newInstance(Integer.valueOf(strTimeSplit[0]), Integer.valueOf(strTimeSplit[1]), 0, 0);
        return timeChange;
    }

    public class ShiftStatus {
        @AuraEnabled
        public Id serviceTeamMemberId;
        @AuraEnabled
        public Id serviceResourceId;
        @AuraEnabled
        public String serviceResourceName;
        @AuraEnabled
        public Date serviceDate;
        @AuraEnabled
        public String serviceDateString;
        @AuraEnabled
        public List<PC_Shift__c> shifts;
    }
}