force-app/main/default/objects/HealthcareFacility/fields/VCC_Personas__c.field-meta.xml
<CustomField>
    <fullName>VCC_Personas__c</fullName>
    <description>Used to filter locations available to each role.</description>
    <inlineHelpText>Used to filter locations available to each role.</inlineHelpText>
    <label>Personas</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Personas</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/HealthcareFacility/fields/VCC_VISN__c.field-meta.xml
<CustomField>
    <fullName>VCC_VISN__c</fullName>
    <description>The VISN that the Facility is located in</description>
    <encryptionScheme>None</encryptionScheme>
    <label>VISN</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/VCC_Progress_Note__c.object-meta.xml
<CustomObject>
    <description>Progress Notes</description>
    <label>Progress Note</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>Progress Note</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VCC_Progress_Note_Configuration__mdt/VCC_Progress_Note_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>Used for identifying what Attributes belong to a particular Progress Note or Addendum Type.</description>
    <label>VCC Progress Note Configuration</label>
    <pluralLabel>Progress Note Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/VCC_Progress_Note_Configuration__mdt/fields/VCC_Personas__c.field-meta.xml
<CustomField>
    <fullName>VCC_Personas__c</fullName>
    <label>Personas</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

sfdx-source/main/default/objects/VCC_VISN__c/VCC_VISN__c.object-meta.xml
<CustomObject>
    <description>Tracks the VISNs for the Service Onboarding Tracker App</description>
    <label>VISN</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>VISN Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VISNs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Personas.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>MSA</fullName>
    </customValue>
    <customValue>
        <fullName>PHARM</fullName>
    </customValue>
    <customValue>
        <fullName>PHARM III</fullName>
    </customValue>
    <customValue>
        <fullName>RN</fullName>
    </customValue>
    <customValue>
        <fullName>TED</fullName>
    </customValue>
    <customValue>
        <fullName>TEDRN</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Addiction Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Allergy/Immunology</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Amputation Clinic</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Anesthesiology</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Anti-Coagulation Clinic</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Audiology</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Blood Pressure Evaluation</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Brain Injury</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Bros (Blind Rehab O/P Spec)</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Cardiac Catheterization</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Cardiac Implantable Electronic Devices (Cied)</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Cardiac Surgery</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Cardiology</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Chart Consult</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Clinical Pharmacy</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Community Care Consult</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Community Nursing Home (Cnh) Follow-Up</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Computerized Tomography (Ct)</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Cysto Room Unit For Outpatient</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Dental</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Dermatology</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Diabetes</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Eeg</fullName>
    </customValue>
    <description>Used to filter locations available on PN to users in various roles.</description>
    <masterLabel>Personas</masterLabel>
</GlobalValueSet>

sfdx-source/main/default/classes/VCC/VCC_LookupController.cls
/**
 * @description Provides searching and return of healthcare facilities.
 * @author Booz Allen Hamilton
 * @group Object - VCC_Progress_Note__c
 */
public with sharing class VCC_LookupController {
    @TestVisible
    private static VCC_HealthcareFacilitySelector healthcareFacilitySelector = new VCC_HealthcareFacilitySelector();
    @TestVisible
    private static VCC_ProgressNoteConfigSelector progressNoteConfigurationSelector = new VCC_ProgressNoteConfigSelector();

    /**
     * @description aura enabled search function
     * @param siteId site id to use when searching
     * @param searchParam parameters to use when searching
     * @param persona the persona of the current user
     *
     * @return `List<SObject>` generic list of information for the configuration and facilities
     */
    @AuraEnabled
    public static List<SObject> findRecords(String siteId, String searchParam, String persona) {
        VCC_Progress_Note_Configuration__mdt progressNoteConfiguration = progressNoteConfigurationSelector.selectByRecordTypeAPIName(
            persona
        );

        List<HealthcareFacility> healthcareFacilityList = new List<HealthcareFacility>();
        if (progressNoteConfiguration != null) {
            healthcareFacilitySelector.addSObjectFields(new List<SObjectField>{ HealthcareFacility.VCC_VISN__c });
            healthcareFacilityList = healthcareFacilitySelector.selectBySiteIdAndPersona(
                Integer.valueOf(siteId),
                VCC_String_Utilities.splitUnique(progressNoteConfiguration.VCC_Personas__c, ',')
            );
        }

        return healthcareFacilityList;
    }
}