force-app/main/default/objects/HealthcareFacility/fields/VCC_Personas__c.field-meta.xml
<CustomField>
    <fullName>VCC_Personas__c</fullName>
    <description>Used to filter locations available to each role.</description>
    <inlineHelpText>Used to filter locations available to each role.</inlineHelpText>
    <label>Personas</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Personas</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/HealthcareFacility/fields/VCC_Site_Id__c.field-meta.xml
<CustomField>
    <fullName>VCC_Site_Id__c</fullName>
    <description>The site ID number that is associated with the healthcare facility. The Site ID can be seen on the person account page under the station column in the facilities
        component.</description>
    <label>Site Id</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Personas.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>MSA</fullName>
    </customValue>
    <customValue>
        <fullName>PHARM</fullName>
    </customValue>
    <customValue>
        <fullName>PHARM III</fullName>
    </customValue>
    <customValue>
        <fullName>RN</fullName>
    </customValue>
    <customValue>
        <fullName>TED</fullName>
    </customValue>
    <customValue>
        <fullName>TEDRN</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Addiction Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Allergy/Immunology</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Amputation Clinic</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Anesthesiology</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Anti-Coagulation Clinic</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Audiology</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Blood Pressure Evaluation</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Brain Injury</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Bros (Blind Rehab O/P Spec)</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Cardiac Catheterization</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Cardiac Implantable Electronic Devices (Cied)</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Cardiac Surgery</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Cardiology</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Chart Consult</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Clinical Pharmacy</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Community Care Consult</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Community Nursing Home (Cnh) Follow-Up</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Computerized Tomography (Ct)</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Cysto Room Unit For Outpatient</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Dental</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Dermatology</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Diabetes</fullName>
    </customValue>
    <customValue>
        <fullName>PRC Eeg</fullName>
    </customValue>
    <description>Used to filter locations available on PN to users in various roles.</description>
    <masterLabel>Personas</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/VCC/VCC_HealthcareFacilitySelectorTest.cls
@isTest
public with sharing class VCC_HealthcareFacilitySelectorTest {
    @TestSetup
    static void makeData() {
        Account a = new Account(Name = 'Test Account 1');
        insert a;
        insert new List<HealthcareFacility>{
            new HealthcareFacility(Name = 'Facility 1', VCC_Personas__c = 'MD', VCC_Site_Id__c = 983, AccountId = a.Id),
            new HealthcareFacility(Name = 'Facility 2', VCC_Personas__c = 'RN', VCC_Site_Id__c = 983, AccountId = a.Id),
            new HealthcareFacility(Name = 'Facility 3', VCC_Personas__c = 'RN', VCC_Site_Id__c = 984, AccountId = a.Id)
        };
    }

    @isTest
    public static void instantiationTest() {
        Test.startTest();
        VCC_HealthcareFacilitySelector healthcareFacilitySel = new VCC_HealthcareFacilitySelector();
        Test.stopTest();

        Assert.isTrue(healthcareFacilitySel != null, 'Did not instantiate as expected.');
    }

    @isTest
    public static void addSObjectFieldsTest() {
        VCC_HealthcareFacilitySelector healthcareFacilitySel = new VCC_HealthcareFacilitySelector();

        Assert.isTrue(!healthcareFacilitySel.getSObjectFieldList().contains(HealthcareFacility.SystemModstamp), 'Selector already contains the field to test.');

        Test.startTest();
        healthcareFacilitySel.addSObjectFields(new List<SObjectField>{ HealthcareFacility.SystemModstamp });
        Test.stopTest();

        Assert.isTrue(healthcareFacilitySel.getSObjectFieldList().contains(HealthcareFacility.SystemModstamp), 'Selector did not add SObject field correctly.');
    }

    @isTest
    public static void selectByIdsTest() {
        VCC_HealthcareFacilitySelector healthcareFacilitySel = new VCC_HealthcareFacilitySelector();
        HealthcareFacility hcf = [
            SELECT Id
            FROM HealthcareFacility
            LIMIT 1
        ];

        Test.startTest();
        List<HealthcareFacility> hcfs = healthcareFacilitySel.selectByIds(new Set<Id>{ hcf.Id });
        Test.stopTest();

        Assert.isTrue(hcfs.size() == 1, 'Expected one record returned.');
    }

    @isTest
    public static void UnitSelectBySiteIdAndPersonaTestPositive() {
        VCC_HealthcareFacilitySelector healthcareFacilitySel = new VCC_HealthcareFacilitySelector();

        Test.startTest();
        List<HealthcareFacility> hcfs = healthcareFacilitySel.selectBySiteIdAndPersona(983, new Set<String>{ 'MD' });
        Test.stopTest();

        Assert.isTrue(hcfs.size() == 1, 'Expected one record returned.');
    }

    @isTest
    public static void UnitSelectBySiteIdAndPersonaTestNegative() {
        VCC_HealthcareFacilitySelector healthcareFacilitySel = new VCC_HealthcareFacilitySelector();

        Test.startTest();
        List<HealthcareFacility> hcfs = healthcareFacilitySel.selectBySiteIdAndPersona(983, new Set<String>{ 'PHARM' });
        Test.stopTest();

        Assert.isTrue(hcfs.size() == 0, 'Expected zero records returned.');
    }
}