sfdx-source/main/default/objects/Account/fields/Is_Training_Account__c.field-meta.xml
<CustomField>
    <fullName>Is_Training_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flags the account as a training account.</description>
    <label>Is Training Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VCC_Training_Mode_Data__c/VCC_Training_Mode_Data__c.object-meta.xml
<CustomObject>
    <description>Used to house mock data by user and account for training purposes.</description>
    <label>VCC Training Mode Data</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VCC Training Mode Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VCC_Training_Mode_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Parent account for the given training data.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>VCC Training Mode Data</relationshipLabel>
    <relationshipName>VCC_Training_Mode_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Training_Mode_Data__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Training_Mode_Data__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Allergies</fullName>
            </value>
            <value>
                <fullName>Appointments</fullName>
            </value>
            <value>
                <fullName>Consults</fullName>
            </value>
            <value>
                <fullName>Discharge Summaries</fullName>
            </value>
            <value>
                <fullName>Directives</fullName>
            </value>
            <value>
                <fullName>Flags</fullName>
            </value>
            <value>
                <fullName>Imaging</fullName>
            </value>
            <value>
                <fullName>Immunizations</fullName>
            </value>
            <value>
                <fullName>Labs</fullName>
            </value>
            <value>
                <fullName>Medications</fullName>
            </value>
            <value>
                <fullName>Orders</fullName>
            </value>
            <value>
                <fullName>PACT</fullName>
            </value>
            <value>
                <fullName>Problems</fullName>
            </value>
            <value>
                <fullName>Progress Notes</fullName>
            </value>
            <value>
                <fullName>Vet Info</fullName>
            </value>
            <value>
                <fullName>Visits</fullName>
            </value>
            <value>
                <fullName>Vitals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VCC/VCC_TrainingModeTestDataFactory.cls
@IsTest
public with sharing class VCC_TrainingModeTestDataFactory {
    public static Account createTrainingModeAccount(String firstName, String lastName) {
        return new Account(
            FirstName = firstName,
            LastName = lastName,
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId(),
            Is_Training_Account__c = true
        );
    }

    public static Account createMasterTrainingModeAccount(String firstName, String lastName) {
        return new Account(
            FirstName = firstName,
            LastName = lastName,
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId(),
            Is_Training_Account__c = true
        );
    }

    public static VCC_Training_Mode_Data__c createTrainingModeData(String accountId, String name, String typ, String data) {
        return new VCC_Training_Mode_Data__c(Account__c = accountId, Name = name, Type__c = typ, Data__c = data);
    }
}