sfdx-source/main/default/objects/Account/fields/VCC_Current_Location__c.field-meta.xml
<CustomField>
    <fullName>VCC_Current_Location__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Current Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/Case/fields/VCC_Call_back_phone_number__c.field-meta.xml
<CustomField>
    <fullName>VCC_Call_back_phone_number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter the preferred telephone number where the caller may be reached if the call disconnects.</inlineHelpText>
    <label>Call Back Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/Case/fields/VCC_Current_location__c.field-meta.xml
<CustomField>
    <fullName>VCC_Current_location__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter the caller&apos;s current physical location. An address is preferred, but if address is unknown, a description may be entered.</inlineHelpText>
    <label>Current Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/Case/fields/VCC_Progress_Note__c.field-meta.xml
<CustomField>
    <fullName>VCC_Progress_Note__c</fullName>
    <description>Check true if there are any Progress Notes, related to the case.</description>
    <formula>IF( VCC_Progress_Notes_Count__c &gt; 0, TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Check true if there are any Progress Notes, related to the case.</inlineHelpText>
    <label>Progress Note</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/Case/recordTypes/VCC_Clinical_Triage.recordType-meta.xml
<RecordType>
    <fullName>VCC_Clinical_Triage</fullName>
    <active>true</active>
    <businessProcess>VCC Support Process</businessProcess>
    <description>--VA Health Connect nursing and symptom cases</description>
    <label>Clinical Triage Case</label>
</RecordType>

sfdx-source/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

sfdx-source/main/default/objects/VCC_Progress_Note__c/VCC_Progress_Note__c.object-meta.xml
<CustomObject>
    <description>Progress Notes</description>
    <label>Progress Note</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>Progress Note</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Additional_Comments__c.field-meta.xml
<CustomField>
    <fullName>VCC_Additional_Comments__c</fullName>
    <description>Used to add any additional comments about lost medication</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter any additional comments about lost medication</inlineHelpText>
    <label>Additional Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Case__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case__c</fullName>
    <description>Parent Case for Progress Note</description>
    <inlineHelpText>Case related to Progress Note on the patient record.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Progress Notes</relationshipLabel>
    <relationshipName>Progress_Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note__c/fields/VCC_Comments_patient_in_crisis__c.field-meta.xml
<CustomField>
    <fullName>VCC_Comments_patient_in_crisis__c</fullName>
    <description>Enter comments related to the patient that is in crisis</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter comments related to the patient in crisis</inlineHelpText>
    <label>Comments - Patient in crisis</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Current_Location__c.field-meta.xml
<CustomField>
    <fullName>VCC_Current_Location__c</fullName>
    <description>Current location of patient, if different from Primary Address</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Current location of patient, if different from Primary Address</inlineHelpText>
    <label>Current Location</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>VCC_Date_of_Birth__c</fullName>
    <description>Patient&apos;s date of birth</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Patient&apos;s date of birth</inlineHelpText>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note__c/fields/VCC_Emergency_Contact__c.field-meta.xml
<CustomField>
    <fullName>VCC_Emergency_Contact__c</fullName>
    <description>Name of Patient&apos;s Emergency Contact from Account</description>
    <formula>VCC_Case__r.Contact.VCC_Emergency_Contact__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Name of Patient&apos;s Emergency Contact from Account</inlineHelpText>
    <label>Emergency Contact</label>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Emergency_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>VCC_Emergency_Contact_Phone__c</fullName>
    <description>Phone Number of Patient&apos;s Emergency Contact from Account</description>
    <formula>VCC_Case__r.Contact.VCC_Emergency_Contact_Phone__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Phone Number of Patient&apos;s Emergency Contact from Account</inlineHelpText>
    <label>Emergency Contact Phone</label>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Gender__c.field-meta.xml
<CustomField>
    <fullName>VCC_Gender__c</fullName>
    <description>Used for Vitals intake. Patient&apos;s birth sex.</description>
    <inlineHelpText>Patient&apos;s birth sex</inlineHelpText>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note__c/fields/VCC_Patient_Age__c.field-meta.xml
<CustomField>
    <fullName>VCC_Patient_Age__c</fullName>
    <description>The patient&apos;s age calculated from their date of birth to the current day</description>
    <formula
    >IF( NOT( ISBLANK( VCC_Date_of_Birth__c) ) , IF( DATE( 2000 , MONTH( VCC_Date_of_Birth__c) , DAY( VCC_Date_of_Birth__c) ) &lt;= DATE( 2000 , MONTH( TODAY() ) , DAY( TODAY()
        ) ), YEAR (Today()) - YEAR ( VCC_Date_of_Birth__c), YEAR (Today()) - YEAR ( VCC_Date_of_Birth__c) -1 ), null)</formula>
    <inlineHelpText>Current age of patient based on DOB.</inlineHelpText>
    <label>Patient Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note__c/recordTypes/VCC_Clinical_Triage_Note_Progress_Note.recordType-meta.xml
<RecordType>
    <fullName>VCC_Clinical_Triage_Note_Progress_Note</fullName>
    <active>true</active>
    <description>Holds the fields for the Clinical Triage Progress Note</description>
    <label>Clinical Triage Progress Note</label>
</RecordType>

force-app/main/default/objects/VCC_Recent_View__c/VCC_Recent_View__c.object-meta.xml
<CustomObject>
    <label>VCC Recent View</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>VCC Recent View Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VCC Recent View</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VCC_Recent_View__c/fields/VCC_Account__c.field-meta.xml
<CustomField>
    <fullName>VCC_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VCC Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>VCC Recent View</relationshipLabel>
    <relationshipName>VCC_Recent_View</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCC_Recent_View__c/fields/VCC_Type__c.field-meta.xml
<CustomField>
    <fullName>VCC_Type__c</fullName>
    <label>VCC Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flags</fullName>
            </value>
            <value>
                <fullName>SensitivePatient</fullName>
            </value>
            <value>
                <fullName>VerifyPatient</fullName>
            </value>
            <value>
                <fullName>InPatient</fullName>
            </value>
            <value>
                <fullName>FacilityAccess</fullName>
            </value>
            <value>
                <fullName>PharmacyVerified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/VCC_Recent_View__c/fields/VCC_User__c.field-meta.xml
<CustomField>
    <fullName>VCC_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VCC User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>VCC_Recent_View</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VCC/VCC_FlagsControllerTest.cls
/**
 * @author Booz Allen Hamilton
 * @description Test class for `VCC_FlagsController`
 * @see `VCC_FlagsController`
 */

@IsTest
private with sharing class VCC_FlagsControllerTest {
    private static final User RN_USER;
    private static final Set<String> CONTACT_FIELDS;
    private static final Set<String> CASE_FIELDS;
    private static final Set<String> PROGRESS_NOTE_FIELDS;
    private static final Set<String> ACCOUNT_FIELDS;
    private static VCC_Progress_Note__c progressNote;
    private static Case caseRecord;
    private static Account accountRecord;
    private static Account accountRecord2;

    static {
        RN_USER = new VATEST_UserBuilder()
            .withPermissionSets(
                new Set<String>{
                    'HealthCloudFoundation',
                    'VCC_Registered_Nurse',
                    'VAHC_RN_User',
                    'VAHC_Write_Clinical_Triage_Progress_Note',
                    'VAHC_Standard_VCC_User'
                }
            )
            .withUserProfile('VAVET Base Profile')
            .withStandardData()
            .build(true);

        CONTACT_FIELDS = new Set<String>{ 'AccountId', 'VCC_Emergency_Contact__c', 'VCC_Emergency_Contact_Phone__c' };
        CASE_FIELDS = new Set<String>{ 'VCC_Call_back_phone_number__c', 'ContactId' };
        PROGRESS_NOTE_FIELDS = new Set<String>{
            'VCC_Date_of_Birth__c',
            'VCC_Patient_Age__c',
            'VCC_Gender__c',
            'VCC_Current_Location__c',
            'VCC_Case__c'
        };
        ACCOUNT_FIELDS = new Set<String>{ 'VCC_Gender_Identity__c' };
    }

    /**
     * @description Creates test data including Account, Case, and Progress Note records.
     */
    private static void makeData() {
        Id personAccountRecTypeId = new VCR_AccountRepo()
            .recordTypeConstant.developerNameToRecordType.get('PersonAccount')
            .Id;
        // Create test Account
        accountRecord = new Account();
        accountRecord.FirstName = 'Test Account First';
        accountRecord.LastName = 'Last Name';
        accountRecord.put('VCC_Gender_Identity__c', 'Female');
        accountRecord.RecordTypeId = personAccountRecTypeId;
        Assert.isNotNull(RN_USER, 'RN_USER was not created');
        System.runAs(RN_USER) {
            VATEST_SObjectFactory.createSObject(accountRecord, true);
        }
        // Create second test Account
        accountRecord2 = new Account();
        accountRecord2.FirstName = 'Test Account 2 First';
        accountRecord2.LastName = 'Last Name ' + System.now();
        accountRecord2.put('VCC_Gender_Identity__c', 'Female');
        accountRecord2.RecordTypeId = personAccountRecTypeId;
        System.runAs(RN_USER) {
            VATEST_SObjectFactory.createSObject(accountRecord2, true);
        }
        // Create test Case
        caseRecord = new Case();
        caseRecord.ContactId = accountRecord.PersonContactId;
        caseRecord.Subject = 'Test Case';
        caseRecord.put('VCC_Call_back_phone_number__c', '123-456-7890');
        System.runAs(RN_USER) {
            VATEST_SObjectFactory.createSObject(caseRecord, true);
        }

        // Create test Progress Note
        progressNote = new VCC_Progress_Note__c();
        progressNote.VCC_Case__c = caseRecord.Id;
        progressNote.put('VCC_Date_of_Birth__c', Date.newInstance(1990, 1, 1));
        progressNote.put('VCC_Gender__c', 'M');
        progressNote.put('VCC_Current_Location__c', 'Test Location');
        System.runAs(RN_USER) {
            VATEST_SObjectFactory.createSObject(progressNote, true);
        }
    }

    @IsTest
    private static void funcAcknowledgeAndGetFlagsDifferentEnvsPositive() {
        makeData();
        System.runAs(RN_USER) {
            List<Account> accounts = [
                SELECT Id
                FROM Account
                LIMIT 2
            ];
            VCC_FlagsController.acknowledgeFlag(accounts[1].Id);
            VCC_FlagsController.acknowledgeFlag(accounts[0].Id);
            Test.setMock(HttpCalloutMock.class, new VCC_HttpMock());
            Test.startTest();
            VCC_FlagLightningRequestWrp flagReqWrp = new VCC_FlagLightningRequestWrp();
            flagReqWrp.recordId = accounts[0].Id;
            flagReqWrp.facility = '613';
            flagReqWrp.startDate = '1950-01-01';
            flagReqWrp.endDate = '2050-01-01';
            VCC_FlagService.enviornment = 'PROD';
            VCC_FlagResponseWrp flagResWrp = VCC_FlagsController.getFlags(flagReqWrp);
            Assert.areNotEqual(
                202,
                flagResWrp.statusCode,
                'Expected a different value than 202 from getFlags() but observed them to be the same'
            );

            VCC_FlagService.enviornment = 'TEST';
            flagResWrp = VCC_FlagsController.getFlags(flagReqWrp);
            Assert.areNotEqual(
                202,
                flagResWrp.statusCode,
                'Expected a different value than 202 from getFlags() after changing environment to TEST but observed them to be the same'
            );

            Test.stopTest();
        }
    }

    @IsTest
    private static void funcGetFlagsForMostRecentViewAcctPositive() {
        makeData();
        System.runAs(RN_USER) {
            List<Account> accounts = [
                SELECT Id
                FROM Account
                LIMIT 2
            ];
            Test.setMock(HttpCalloutMock.class, new VCC_HttpMock());
            VCC_Recent_View__c recentViewObj = new VCC_Recent_View__c();
            recentViewObj.VCC_Account__c = accounts[0].Id;
            recentViewObj.VCC_User__c = RN_USER.Id;
            insert recentViewObj;
            Test.startTest();
            VCC_FlagLightningRequestWrp flagReqWrp = new VCC_FlagLightningRequestWrp();

            flagReqWrp = new VCC_FlagLightningRequestWrp();
            flagReqWrp.recordId = accounts[1].Id;
            flagReqWrp.facility = '613';
            flagReqWrp.startDate = '1950-01-01';
            flagReqWrp.endDate = '2050-01-01';
            VCC_FlagService.enviornment = 'PROD';
            VCC_FlagResponseWrp flagResWrp1 = VCC_FlagsController.getFlags(flagReqWrp);
            Assert.areNotEqual(
                202,
                flagResWrp1.statusCode,
                'Expected a different value than 202 from getFlags() for PROD but observed them to be the same'
            );
            Test.stopTest();
        }
    }
    @IsTest
    private static void funcGetFlagsForChangeToRecentViewAcctWithoutGetFlagStatusPositive() {
        makeData();
        System.runAs(RN_USER) {
            List<Account> accounts = [
                SELECT Id
                FROM Account
                LIMIT 2
            ];
            Test.setMock(HttpCalloutMock.class, new VCC_HttpMock());
            VCC_Recent_View__c recentViewObj = new VCC_Recent_View__c();
            recentViewObj.VCC_Account__c = accounts[1].Id;
            recentViewObj.VCC_Type__c = 'Flags';
            recentViewObj.VCC_User__c = RN_USER.Id;
            insert recentViewObj;
            Test.startTest();
            VCC_FlagLightningRequestWrp flagReqWrp = new VCC_FlagLightningRequestWrp();

            flagReqWrp = new VCC_FlagLightningRequestWrp();
            flagReqWrp.recordId = accounts[0].Id;
            flagReqWrp.facility = '613';
            flagReqWrp.startDate = '1950-01-01';
            flagReqWrp.endDate = '2050-01-01';
            VCC_FlagService.enviornment = 'PROD';
            VCC_FlagResponseWrp flagResWrp1 = VCC_FlagsController.getFlags(flagReqWrp);
            Assert.areNotEqual(
                202,
                flagResWrp1.statusCode,
                'Expected a different value than 202 from getFlags() for PROD but observed them to be the same'
            );

            Test.stopTest();
        }
    }
    @IsTest
    private static void funcGetFlagsForChangeToRecentViewAcctPositive() {
        makeData();
        System.runAs(RN_USER) {
            List<Account> accounts = [
                SELECT Id
                FROM Account
                LIMIT 2
            ];
            Test.setMock(HttpCalloutMock.class, new VCC_HttpMock());
            VCC_Recent_View__c recentViewObj = new VCC_Recent_View__c();
            recentViewObj.VCC_Account__c = accounts[1].Id;
            recentViewObj.VCC_Type__c = 'Flags';
            recentViewObj.VCC_User__c = UserInfo.getUserId();
            insert recentViewObj;
            Test.startTest();
            VCC_FlagLightningRequestWrp flagReqWrp = new VCC_FlagLightningRequestWrp();

            flagReqWrp = new VCC_FlagLightningRequestWrp();
            flagReqWrp.recordId = accounts[0].Id;
            flagReqWrp.facility = '613';
            flagReqWrp.startDate = '1950-01-01';
            flagReqWrp.endDate = '2050-01-01';
            VCC_FlagService.enviornment = 'PROD';
            VCC_FlagsController.getFlagStatus(new List<String>{ accounts[0].Id });

            VCC_FlagResponseWrp flagResWrp = new VCC_FlagResponseWrp();
            flagResWrp = VCC_FlagsController.getFlags(flagReqWrp);
            Assert.areNotEqual(
                202,
                flagResWrp.statusCode,
                'Expected a different value than 202 from getFlags() but observed them to be the same'
            );

            Test.stopTest();
        }
    }
    @IsTest
    private static void funcGetFlagsForChangeToRecentViewAcctWithRelatedDataPositive() {
        makeData();
        System.runAs(RN_USER) {
            List<Account> accounts = [
                SELECT Id
                FROM Account
                LIMIT 2
            ];

            Case testCase = new Case(
                AccountId = accounts[0].Id,
                RecordTypeId = new VCR_CaseRepo()
                    .recordTypeConstant.developerNameToRecordType.get('VCC_Clinical_Triage')
                    .Id
            );
            insert testCase;
            insert new VCC_Progress_Note__c(
                VCC_Additional_Comments__c = 'Some additional comment.',
                VCC_Comments_patient_in_crisis__c = 'some long string that will be longer than 80 characters long to demonstrate the line breaking',
                VCC_Case__c = testCase.Id,
                RecordTypeId = new VCR_ProgressNoteRepo()
                    .recordTypeConstant.developerNameToRecordType.get('VCC_Clinical_Triage_Note_Progress_Note')
                    .Id
            );

            Test.setMock(HttpCalloutMock.class, new VCC_HttpMock());
            VCC_Recent_View__c recentViewObj = new VCC_Recent_View__c();
            recentViewObj.VCC_Account__c = accounts[1].Id;
            recentViewObj.VCC_Type__c = 'Flags';
            recentViewObj.VCC_User__c = UserInfo.getUserId();
            insert recentViewObj;
            Test.startTest();
            VCC_FlagLightningRequestWrp flagReqWrp = new VCC_FlagLightningRequestWrp();

            flagReqWrp = new VCC_FlagLightningRequestWrp();
            flagReqWrp.recordId = accounts[0].Id;
            flagReqWrp.facility = '613';
            flagReqWrp.startDate = '1950-01-01';
            flagReqWrp.endDate = '2050-01-01';
            VCC_FlagService.enviornment = 'PROD';
            VCC_FlagsController.getFlagStatus(new List<String>{ testCase.Id });

            VCC_FlagResponseWrp flagResWrp = new VCC_FlagResponseWrp();
            VCC_FlagsController.getFlags(flagReqWrp);
            Assert.areNotEqual(
                202,
                flagResWrp.statusCode,
                'Expected a different value than 202 from getFlags() but observed them to be the same'
            );

            Test.stopTest();
        }
    }
    @IsTest
    private static void funcGetFlagsByAccountIdFromTrainingServicePositive() {
        makeData();
        System.runAs(RN_USER) {
            Test.startTest();
            List<Account> accounts = [
                SELECT Id
                FROM Account
                LIMIT 2
            ];

            Case testCase = new Case(
                AccountId = accounts[0].Id,
                RecordTypeId = new VCR_CaseRepo()
                    .recordTypeConstant.developerNameToRecordType.get('VCC_Clinical_Triage')
                    .Id
            );
            insert testCase;
            insert new VCC_Progress_Note__c(
                VCC_Additional_Comments__c = 'Some additional comment.',
                VCC_Comments_patient_in_crisis__c = 'some long string that will be longer than 80 characters long to demonstrate the line breaking',
                VCC_Case__c = testCase.Id,
                RecordTypeId = new VCR_ProgressNoteRepo()
                    .recordTypeConstant.developerNameToRecordType.get('VCC_Clinical_Triage_Note_Progress_Note')
                    .Id
            );
            String recordId = accounts[0].Id;
            String responseBody = '';
            responseBody = VCC_TrainingModeService.getFlagsByAccountId(recordId);
            Integer responseCode = 0;
            responseCode = 200;
            Assert.areEqual(
                200,
                responseCode,
                'Expected a successful HTTP status code for getFlagsByAccountId() but observed a different value'
            );
            Test.stopTest();
        }
    }
}