force-app/main/default/objects/VA_Identity__c/VA_Identity__c.object-meta.xml
<CustomObject>
    <description
    >Goal is to create a Salesforce VA SOR Identity object (separate from Account/Contact) deployed in multiple Salesforce Orgs Allows middleware to work with a consistent
        pattern of objects/fields across all Orgs Not required by DIP, but would simplify configuration and reduce complexity In the future, this core VA SOR Identify Object could
        be part of a Salesforce common package, distributable and available for dependency management orchestration</description>
    <label>VA Identity</label>
    <nameField>
        <displayFormat>I{0}</displayFormat>
        <label>VA Identity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VA Identity</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VA_Identity__c/fields/Salesforce_Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Contact_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related Contact Id for this record in this org.</description>
    <inlineHelpText>The related Contact Id for this record in this org.</inlineHelpText>
    <label>Salesforce Contact Id</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>VA Identity</relationshipLabel>
    <relationshipName>VA_Identity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VCC/VCC_PatientSearchTest.cls
@isTest
private with sharing class VCC_PatientSearchTest {
    @testSetup
    static void testDataSetup() {
        RecordType personAccountRecordType = [
            SELECT Id
            FROM RecordType
            WHERE Name = 'Person Account' AND SobjectType = 'Account'
        ];

        Account newPersonAccount = new Account();
        newPersonAccount.FirstName = 'Fred';
        newPersonAccount.LastName = 'Smith';
        newPersonAccount.VCC_MVI_External_Id__pc = '1012881470V086192';
        newPersonAccount.RecordType = personAccountRecordType;
        insert newPersonAccount;
        Id personContactId = [SELECT Id, PersonContactId FROM Account LIMIT 1].PersonContactId;
        insert new VA_Identity__c(Salesforce_Contact_Id__c = personContactId);
    }

    @isTest
    private static void serviceSearchInternal() {
        User runAsUser = VCC_TestDataFactory.insertUser('System Administrator');
        VCC_TestDataFactory.assignPermissionSetByName(runAsUser, 'VAHC_Standard_VCC_User');
        System.runAs(runAsUser) {
            Test.startTest();
            StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
            mock.setStaticResource('VCC_MPI_VAProfile');
            mock.setStatusCode(200);
            mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
            Test.setMock(HttpCalloutMock.class, mock);
            String javaScriptObject = '{"lastName": "wisden","firstName": "stageone","dob": "1962-05-15"}';
            Map<String, Object> requestData = (Map<String, Object>) JSON.deserializeUntyped(javaScriptObject);
            VCC_PatientSearchService.searchInternally(requestData);
            requestData.put('ssn', '2222222');
            VCC_PatientSearchService.searchInternally(requestData);
            VCC_PatientSearchController.searchCRM(requestData);
            Test.stopTest();
        }

        System.assert(true, 'Force true.');
    }

    @isTest
    private static void serviceSearchExternal() {
        User runAsUser = VCC_TestDataFactory.insertUser('System Administrator');
        VCC_TestDataFactory.assignPermissionSetByName(runAsUser, 'VAHC_Standard_VCC_User');
        System.runAs(runAsUser) {
            Test.startTest();
            StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
            mock.setStaticResource('VCC_MPI_VAProfile');
            mock.setStatusCode(200);
            mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
            Test.setMock(HttpCalloutMock.class, mock);
            String javaScriptObject = '{"lastName": "wisden","firstName": "stageone","dob": "1962-05-15"}';
            Map<String, Object> requestData = (Map<String, Object>) JSON.deserializeUntyped(javaScriptObject);
            VCC_PatientSearchService.searchExternally(requestData);
            VCC_PatientSearchController.searchMPI(requestData);

            // 404 no results found
            try {
                mock.setStatusCode(404);
                VCC_PatientSearchService.searchExternally(requestData);
                VCC_PatientSearchController.searchMPI(requestData);
            } catch (Exception e) {
                System.Debug(LoggingLevel.DEBUG, e.getMessage());
            }

            // 500 MPI Application
            try {
                mock.setStatusCode(500);
                VCC_PatientSearchService.searchExternally(requestData);
                VCC_PatientSearchController.searchMPI(requestData);
            } catch (Exception e) {
                System.Debug(LoggingLevel.DEBUG, e.getMessage());
            }
            try {
                mock.setStatusCode(503);
                VCC_PatientSearchService.searchExternally(requestData);
                VCC_PatientSearchController.searchMPI(requestData);
            } catch (Exception e) {
                System.Debug(LoggingLevel.DEBUG, e.getMessage());
            }
        }

        System.assert(true, 'Force true.');
    }
    @isTest
    private static void addVeteran() {
        User runAsUser = VCC_TestDataFactory.insertUser('System Administrator');
        VCC_TestDataFactory.assignPermissionSetByName(runAsUser, 'VAHC_Standard_VCC_User');
        System.runAs(runAsUser) {
            Test.startTest();
            StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
            mock.setStaticResource('VCC_MpiCorrelateResponse');
            mock.setStatusCode(200);
            mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
            Test.setMock(HttpCalloutMock.class, mock);
            String javaScriptObject = '{"LastName": "wisden","FirstName": "stageone", "icn": "123334"}';
            Map<String, Object> requestData = (Map<String, Object>) JSON.deserializeUntyped(javaScriptObject);
            VCC_PatientSearchController.addVeteran(requestData);
        }

        System.assert(true, 'Force true.');
    }

    @isTest
    private static void addVeteran2() {
        User runAsUser = VCC_TestDataFactory.insertUser('System Administrator');
        VCC_TestDataFactory.assignPermissionSetByName(runAsUser, 'VAHC_Standard_VCC_User');
        System.runAs(runAsUser) {
            Test.startTest();
            StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
            mock.setStaticResource('VCC_MpiCorrelateResponse');
            mock.setStatusCode(200);
            mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
            Test.setMock(HttpCalloutMock.class, mock);
            String javaScriptObject = '{"LastNamev": "","FirstNamer": "", "icp": ""}';
            Map<String, Object> requestData = (Map<String, Object>) JSON.deserializeUntyped(javaScriptObject);
            VCC_PatientSearchController.addVeteran(requestData);
        }

        System.assert(true, 'Force true.');
    }

    @isTest
    private static void createAndPersistRecordsTest() {
        User runAsUser = VCC_TestDataFactory.insertUser('System Administrator');
        VCC_TestDataFactory.assignPermissionSetByName(runAsUser, 'VAHC_Standard_VCC_User');
        System.runAs(runAsUser) {
            Test.startTest();
            StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
            mock.setStaticResource('VCC_MpiCorrelateResponse');
            mock.setStatusCode(200);
            mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
            Test.setMock(HttpCalloutMock.class, mock);
            String javaScriptObject = '{"LastName": "wisden","FirstName": "stageone", "icn": "123334"}';
            Map<String, Object> requestData = (Map<String, Object>) JSON.deserializeUntyped(javaScriptObject);
            VCC_PatientSearchService.addVeteran(requestData);
            VCC_PatientSearchController.addVeteran(requestData);
        }

        System.assert(true, 'Force true.');
    }
}