sfdx-source/main/default/objects/Case/fields/Service_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Service_Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Appointment</label>
    <referenceTo>ServiceAppointment</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup from the Service Appointment object to Case that is auto-created and populated when an appointment has been created by an MSA</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>VCV Appointments</relationshipLabel>
    <relationshipName>VCV_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Service_Appointment_Metrics__c/VCC_Service_Appointment_Metrics__c.object-meta.xml
<CustomObject>
    <description>An extension to the Service Appointment object created to store information related to the Service Appointment for reporting purposes.</description>
    <label>Service Appointment Metrics</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Service Appointment Metrics Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Appointment Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VCC_Service_Appointment_Metrics__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Case object of the VCV Case related to the Service Appointment. Used for reporting purposes.</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Service Appointment Metrics</relationshipLabel>
    <relationshipName>Service_Appointment_Metrics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCC_Service_Appointment_Metrics__c/fields/Case_Metrics__c.field-meta.xml
<CustomField>
    <fullName>Case_Metrics__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Looking up to the Case Metrics record for the VCV Case associated with the Service Appointment. Used for reporting purposes.</description>
    <label>Case Metrics</label>
    <referenceTo>VCC_Case_Metrics__c</referenceTo>
    <relationshipLabel>Service Appointment Metrics</relationshipLabel>
    <relationshipName>Service_Appointment_Metrics</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Service_Appointment_Metrics__c/fields/Service_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Service_Appointment__c</fullName>
    <description>The Service Appointment record for which the Service Appointment Metrics record has been created.</description>
    <label>Service Appointment</label>
    <referenceTo>ServiceAppointment</referenceTo>
    <relationshipLabel>Service Appointment Metrics</relationshipLabel>
    <relationshipName>Service_Appointment_Metrics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/VCR/Tests/VCR_ServiceAppointmentMetricsRepoTest.cls
/**
 * @description : To test the service appointment metrics repository
 * @author BAH
 * @see VCR_ServiceAppointmentMetricsRepo
 */
@IsTest
public with sharing class VCR_ServiceAppointmentMetricsRepoTest {
    private static final String STRING_QUERY =
        'SELECT Case__c, Case_Metrics__c, CreatedById, CreatedDate, Id, IsDeleted, LastModifiedById, ' +
        'LastModifiedDate, Name, Service_Appointment__c';

    private static final User ADMIN_USER;
    static {
        ADMIN_USER = new VATEST_UserBuilder()
            .withUserProfile('System Administrator')
            .withPermissionSet('VAHC_Standard_VCC_User')
            .withStandardData()
            .build(true);
    }
    /**
     * @description : To test the constructor
     * Positive test case
     * @see VCR_ServiceAppointmentMetricsRepo
     */
    @IsTest
    static void unitTestConstructorPositive() {
        System.runAs(ADMIN_USER) {
            VCR_ServiceAppointmentMetricsRepo repo;
            Test.startTest();

            repo = new VCR_ServiceAppointmentMetricsRepo();

            Test.stopTest();
            Assert.isTrue(repo != null, 'VCR_ServiceAppointmentMetricsRepo instance is not created');
        }
    }
    /**
     * @description : To test the constructor
     * Negative test case
     * @see VCR_ServiceAppointmentMetricsRepo
     */
    @IsTest
    static void unitTestConstructorNegative() {
        System.runAs(ADMIN_USER) {
            VCR_ServiceAppointmentMetricsRepo repo;
            Test.startTest();

            repo = null;
            Test.stopTest();
            Assert.isNull(repo, 'VCR_ServiceAppointmentMetricsRepo instance is not null');
        }
    }
    /**
     * @description : To test the calculate select clause
     * Positive test case
     * @see VCR_ServiceAppointmentMetricsRepo.calculateSelectClause
     */
    @IsTest
    static void unitTestCalculateSelectClausePositive() {
        System.runAs(ADMIN_USER) {
            String selectClause;
            Test.startTest();

            selectClause = VCR_ServiceAppointmentMetricsRepo.calculateSelectClause();

            Test.stopTest();
            Assert.areEqual(
                selectClause,
                STRING_QUERY,
                'Expected calculateSelectClause to return a string representing the select clause'
            );
        }
    }

    /**
     * @description : To test the fetch service appointment metrics by id
     * Positive test case
     * @see VCR_ServiceAppointmentMetricsRepo.getServiceAppointmentMetricsByServiceAppointmentId
     */
    @IsTest
    static void funcTestingFetchServiceAppointmentMetricsByIdPositive() {
        System.runAs(ADMIN_USER) {
            VCC_Service_Appointment_Metrics__c result;
            String appointmentMetricsId;
            Case testCase = (Case) VATEST_SObjectFactory.createSObject(new Case(), true);
            ServiceAppointment serviceAppointment = (ServiceAppointment) VATEST_SObjectFactory.createSObject(
                new ServiceAppointment(ParentRecordId = testCase.Id),
                true
            );
            VCC_Service_Appointment_Metrics__c serviceAppointmentMetrics = (VCC_Service_Appointment_Metrics__c) VATEST_SObjectFactory.createSObject(
                new VCC_Service_Appointment_Metrics__c(Service_Appointment__c = serviceAppointment.Id),
                true
            );
            Test.startTest();

            VCR_ServiceAppointmentMetricsRepo repo = new VCR_ServiceAppointmentMetricsRepo();
            appointmentMetricsId = serviceAppointmentMetrics.Service_Appointment__c;
            result = repo.getServiceAppointmentMetricsByServiceAppointmentId(appointmentMetricsId);
            Test.stopTest();
            Assert.areEqual(
                result.Service_Appointment__c,
                appointmentMetricsId,
                'Expected getServiceAppointmentMetriccById to return a record with the given id'
            );
        }
    }

    /**
     * @description test the upsert service appointment metrics method
     * Positive test case
     * @see VCR_ServiceAppointmentMetricsRepo.upsertServiceAppointmentMetrics
     */
    @IsTest
    static void funcTestUpsertServiceAppointmentMetricsPositive() {
        System.runAs(ADMIN_USER) {
            VCC_Service_Appointment_Metrics__c result;
            String appointmentMetricsId;
            Case testCase = (Case) VATEST_SObjectFactory.createSObject(new Case(), true);
            ServiceAppointment serviceAppointment = (ServiceAppointment) VATEST_SObjectFactory.createSObject(
                new ServiceAppointment(ParentRecordId = testCase.Id),
                true
            );
            VCC_Service_Appointment_Metrics__c serviceAppointmentMetrics = new VCC_Service_Appointment_Metrics__c(
                Service_Appointment__c = serviceAppointment.Id
            );
            appointmentMetricsId = serviceAppointmentMetrics.Service_Appointment__c;
            List<VCC_Service_Appointment_Metrics__c> upsertList = new List<VCC_Service_Appointment_Metrics__c>();
            upsertList.add(serviceAppointmentMetrics);
            Test.startTest();

            VCR_ServiceAppointmentMetricsRepo repo = new VCR_ServiceAppointmentMetricsRepo();
            repo.upsertServiceAppointmentMetrics(upsertList);
            result = repo.getServiceAppointmentMetricsByServiceAppointmentId(appointmentMetricsId);

            Test.stopTest();
            Assert.areEqual(
                result.Service_Appointment__c,
                appointmentMetricsId,
                'Expected upsertServiceAppointmentMetrics to upsert a record'
            );
        }
    }
}