sfdx-source/main/default/objects/Case/fields/VCC_Progress_Note__c.field-meta.xml
<CustomField>
    <fullName>VCC_Progress_Note__c</fullName>
    <description>Check true if there are any Progress Notes, related to the case.</description>
    <formula>IF( VCC_Progress_Notes_Count__c &gt; 0, TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Check true if there are any Progress Notes, related to the case.</inlineHelpText>
    <label>Progress Note</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VCC_Case_Metrics__c/VCC_Case_Metrics__c.object-meta.xml
<CustomObject>
    <description>An extension of the Case object to track metrics for reporting purposes.</description>
    <label>Case Metrics</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>Case Metrics Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VCC_Case_Metrics__c/fields/VCC_Case__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case__c</fullName>
    <description>The parent case of the Case Metrics record.</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Metrics</relationshipLabel>
    <relationshipName>Case_Metrics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/VCC_Progress_Note__c.object-meta.xml
<CustomObject>
    <description>Progress Notes</description>
    <label>Progress Note</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>Progress Note</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Case__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case__c</fullName>
    <description>Parent Case for Progress Note</description>
    <inlineHelpText>Case related to Progress Note on the patient record.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Progress Notes</relationshipLabel>
    <relationshipName>Progress_Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note__c/fields/VCC_Case_Metrics__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case_Metrics__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field is used to relate the PN to the Case metric record of the parent Case</description>
    <label>Case Metrics</label>
    <referenceTo>VCC_Case_Metrics__c</referenceTo>
    <relationshipLabel>Progress Notes</relationshipLabel>
    <relationshipName>Progress_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VCC/VCC_ProgressNoteCaseMetricBatch.cls
/**
 * @description this is the  class that houses the business logic for updating the Case Metric Field on historical Progress Notes
 * @see VCR_VCR_ProgressNoteRepo
 * @see VCC_GenericBatch
 */

public with sharing class VCC_ProgressNoteCaseMetricBatch extends ABS_BatchExecutioner {
    private static final String EXECUTIONER_NAME = 'VCC_ProgressNoteCaseMetrics';
    private final Map<String, Object> bindVariables;
    private final String queryLocatorString;
    private List<VCC_Progress_Note__c> progressNotes;

    /**
     * @description property for the pnRepo object
     * provides access to the methods in the VCR_ProgressNoteRepo class
     * static so that it can be accessed from the test class
     * @see VCR_ProgressNoteRepo
     */

    @TestVisible
    private static VCR_ProgressNoteRepo pnRepo {
        get {
            return pnRepo ?? new VCR_ProgressNoteRepo();
        }
        set;
    }

    /**
     * @description property for the caseMetricRepo object
     * provides access to the methods in the VCR_CaseMetricRepo class
     * static so that it can be accessed from the test class
     * @see VCR_CaseMetricRepo
     */

    @TestVisible
    private static VCR_CaseMetricRepo caseMetricRepo {
        get {
            return caseMetricRepo ?? new VCR_CaseMetricRepo();
        }
        set;
    }

    /**
     * @description This is the constructor for the VCC_ProgressNoteCaseMetricBatch class.
     * It initializes the object by querying and locating the necessary data.
     */
    public VCC_ProgressNoteCaseMetricBatch() {
        queryLocatorString = getQueryLocatorString();
        bindVariables = getBindVariables();
        super.executionerName = EXECUTIONER_NAME;
    }

    /**
     * @description This method fetches the bind parameters for our SOQL Query
     * @return Map of Bind Values.
     */
    public override Map<String, Object> getBindVariables() {
        Map<String, Object> bindParameters = new Map<String, Object>{};
        return bindParameters;
    }

    /**
     * @description This method fetches and returns the query string from the Progress Note Repo.
     * @return String Returns the query string.
     */
    public override String getQueryLocatorString() {
        return pnRepo.getQueryLocatorString();
    }

    /**
     * @description This method fetches and returns the query locator from the caseRepo.
     * @param query The query string to process
     * @return Database.QueryLocator Returns the query locator.
     */
    public override Database.QueryLocator getQueryLocator(String query) {
        return pnRepo.getQueryLocator(queryLocatorString);
    }

    /**
     * @description Method to execute the VCC_Progress_Note__c Case Metrics Field Batch
     * @param progressNotesInputs List<VCC_Progress_Note__c> to execute the batch for
     */
    public override void execute(List<SObject> progressNotesInputs) {
        this.progressNotes = (List<VCC_Progress_Note__c>) progressNotesInputs;
        Set<Id> caseIdsFromProgressNotes = new Set<Id>();
        for (VCC_Progress_Note__c progressNote : progressNotes) {
            caseIdsFromProgressNotes.add(progressNote.VCC_Case__c);
        }

        // Get all the Case Metrics that have the Same Case Id as the Progress Note Case Id

        List<VCC_Case_Metrics__c> caseMetrics = new List<VCC_Case_Metrics__c>();

        if (VCC_Case_Metrics__c.SObjectType.getDescribe(SObjectDescribeOptions.DEFERRED).isAccessible()) {
            caseMetrics = caseMetricRepo.fetchCaseMetricByCaseId(caseIdsFromProgressNotes);
        }

        // Put all the case metrics in a map so we can find them based on case id
        Map<String, Object> caseMetricsByCaseIdMap = new Map<String, VCC_Case_Metrics__c>();
        for (VCC_Case_Metrics__c caseMetric : caseMetrics) {
            caseMetricsByCaseIdMap.put(caseMetric.VCC_Case__c, caseMetric);
        }
        // Build up a list of progress notes that have been updated with the metric that matches with that progress note
        List<VCC_Progress_Note__c> progressNotesToUpdate = new List<VCC_Progress_Note__c>();
        for (VCC_Progress_Note__c progressNote : progressNotes) {
            if (caseMetricsByCaseIdMap.containsKey(progressNote.VCC_Case__c)) {
                progressNote.VCC_Case_Metrics__c = ((VCC_Case_Metrics__c) caseMetricsByCaseIdMap.get(
                        progressNote.VCC_Case__c
                    ))
                    .Id;
                //progressNotesToUpdate.add(progressNote);
            }
            progressNotesToUpdate.add(progressNote);
        }
        pnRepo.updateProgressNotes(progressNotesToUpdate);
    }
}