sfdx-source/main/default/objects/Case/fields/VCC_Case_Outcome_Multi__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case_Outcome_Multi__c</fullName>
    <description>Case outcome field used on the Administrative and Scheduling Case that allows MSAs to select multiple outcomes for why the case was created</description>
    <inlineHelpText>Action Completed for the Veteran</inlineHelpText>
    <label>Case Outcome</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processed Medication Refill</fullName>
            </value>
            <value>
                <fullName>Entered Progress Note</fullName>
            </value>
            <value>
                <fullName>Entered Unsigned Order</fullName>
            </value>
            <value>
                <fullName>Provided Medication Extension</fullName>
            </value>
            <value>
                <fullName>Provided Status of Rx</fullName>
            </value>
            <value>
                <fullName>Provided Medication Counseling</fullName>
            </value>
            <value>
                <fullName>Provided Requested Information</fullName>
            </value>
            <value>
                <fullName>Provided Bridge Supply</fullName>
            </value>
            <value>
                <fullName>Provider Care Coordination</fullName>
            </value>
            <value>
                <fullName>Adjudicated Retail Billing</fullName>
            </value>
            <value>
                <fullName>Processed Pending Order</fullName>
            </value>
            <value>
                <fullName>Processed Early Fill</fullName>
            </value>
            <value>
                <fullName>Notified Local Site</fullName>
            </value>
            <value>
                <fullName>Transferred to CCC Nurse</fullName>
            </value>
            <value>
                <fullName>Transferred to CCC Scheduling</fullName>
            </value>
            <value>
                <fullName>Transferred to Veterans Crisis Line</fullName>
            </value>
            <value>
                <fullName>Contacted Emergency Services</fullName>
            </value>
            <value>
                <fullName>Call Dropped - Could not Reconnect</fullName>
            </value>
            <value>
                <fullName>Caller Terminated</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Cannot Complete Scheduling Action</fullName>
            </value>
            <value>
                <fullName>Completed Scheduling Action</fullName>
            </value>
            <value>
                <fullName>Progress Note to PACT</fullName>
            </value>
            <value>
                <fullName>Refilled Medication</fullName>
            </value>
            <value>
                <fullName>Requested Medication Renewal</fullName>
            </value>
            <value>
                <fullName>Transferred Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/VCC_Case_Reason_Multi__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case_Reason_Multi__c</fullName>
    <description>Reason why patient is calling-Multiselect</description>
    <inlineHelpText>Reason why patient is calling</inlineHelpText>
    <label>Case Reason</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>VCC_Case_Sub_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Schedule Appointment</fullName>
            </value>
            <value>
                <fullName>Cancel Appointment</fullName>
            </value>
            <value>
                <fullName>Verify Appointment</fullName>
            </value>
            <value>
                <fullName>Request Call Back</fullName>
            </value>
            <value>
                <fullName>Benefits &amp; Enrollment</fullName>
            </value>
            <value>
                <fullName>Community Care/ Mission Act</fullName>
            </value>
            <value>
                <fullName>Consult Request</fullName>
            </value>
            <value>
                <fullName>Death Notification</fullName>
            </value>
            <value>
                <fullName>Home Health/Nursing Home</fullName>
            </value>
            <value>
                <fullName>Lab/ Imaging Result</fullName>
            </value>
            <value>
                <fullName>Medical Equipment Request</fullName>
            </value>
            <value>
                <fullName>Medication Refill/Renewal</fullName>
            </value>
            <value>
                <fullName>Outside Care Performed</fullName>
            </value>
            <value>
                <fullName>Paperwork Request</fullName>
            </value>
            <value>
                <fullName>Update Demographic</fullName>
            </value>
            <value>
                <fullName>Dropped Call</fullName>
            </value>
            <value>
                <fullName>Returned Call</fullName>
            </value>
            <value>
                <fullName>Medication Refill</fullName>
            </value>
            <value>
                <fullName>Medication Renewal</fullName>
            </value>
            <value>
                <fullName>Prescription Status</fullName>
            </value>
            <value>
                <fullName>Prescription Tracking</fullName>
            </value>
            <value>
                <fullName>Facility Information</fullName>
            </value>
            <value>
                <fullName>Community Care Information</fullName>
            </value>
            <value>
                <fullName>Urgent First Fill Issues</fullName>
            </value>
            <value>
                <fullName>Med List Reconciliation</fullName>
            </value>
            <value>
                <fullName>Mission Act Information</fullName>
            </value>
            <value>
                <fullName>Clinical Question(s)</fullName>
            </value>
            <value>
                <fullName>Medication Recall</fullName>
            </value>
            <value>
                <fullName>Side Effect/ADR</fullName>
            </value>
            <value>
                <fullName>Crisis Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/VCC_Case_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case_Sub_Type__c</fullName>
    <description>Categorize the Case for reporting purposes.</description>
    <inlineHelpText>Categorize the Case for reporting purposes.</inlineHelpText>
    <label>Case Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>VCC_Case_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrative</fullName>
            </value>
            <value>
                <fullName>Community Care</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Emergent</fullName>
            </value>
            <value>
                <fullName>Medication Status</fullName>
            </value>
            <value>
                <fullName>Non-Emergent</fullName>
            </value>
            <value>
                <fullName>Telephone Virtual Visit</fullName>
                <label>Phone</label>
            </value>
            <value>
                <fullName>Refill Medication</fullName>
            </value>
            <value>
                <fullName>Renew Medication</fullName>
            </value>
            <value>
                <fullName>Scheduling</fullName>
            </value>
            <value>
                <fullName>Triage</fullName>
            </value>
            <value>
                <fullName>Urgent</fullName>
            </value>
            <value>
                <fullName>Urgent First Fill</fullName>
            </value>
            <value>
                <fullName>Video Virtual Visit</fullName>
                <label>Video</label>
            </value>
            <value>
                <fullName>PHR VCV</fullName>
            </value>
            <value>
                <fullName>Administrative and Scheduling</fullName>
                <label>Scheduling and Administrative</label>
            </value>
            <value>
                <fullName>Pharmacy</fullName>
            </value>
            <value>
                <fullName>Pharmacy Quality Assurance Issue</fullName>
            </value>
            <value>
                <fullName>Medication Error</fullName>
                <isActive>false</isActive>
                <label>Medication Error</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/VCC_Case_Type__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case_Type__c</fullName>
    <description>Type of Case the caller is calling about</description>
    <inlineHelpText>Type of Case the caller is calling about</inlineHelpText>
    <label>Case Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrative</fullName>
            </value>
            <value>
                <fullName>Pharmacy</fullName>
            </value>
            <value>
                <fullName>Symptom</fullName>
            </value>
            <value>
                <fullName>VCV</fullName>
            </value>
            <value>
                <fullName>Tele-Emergency Care</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/Case/fields/VCC_No_of_Refills__c.field-meta.xml
<CustomField>
    <fullName>VCC_No_of_Refills__c</fullName>
    <description># of Refills on this Pharmacy Case</description>
    <inlineHelpText># of Refills on this Pharmacy Case</inlineHelpText>
    <label># of Refills</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>&gt;10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/Case/recordTypes/VCC_Administrative.recordType-meta.xml
<RecordType>
    <fullName>VCC_Administrative</fullName>
    <active>true</active>
    <businessProcess>VCC Support Process</businessProcess>
    <description>--VA Health Connect scheduling, medication refills, enrollment, and other administrative cases</description>
    <label>Administrative and Scheduling Case</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/VCC_Pharmacy.recordType-meta.xml
<RecordType>
    <fullName>VCC_Pharmacy</fullName>
    <active>true</active>
    <businessProcess>VCC Support Process</businessProcess>
    <description>--VA Health Connect medication and prescription cases</description>
    <label>Pharmacy Case</label>
</RecordType>

sfdx-source/main/default/classes/VCC/VCC_CaseDomain.cls
public with sharing class VCC_CaseDomain {
    private static final String CASE_TYPE_PHARMACY = 'Pharmacy';
    private static final String CASE_SUB_TYPE_PHARMACY = 'Pharmacy';
    private static final String CASE_REASON_MED_REFILL = 'Medication Refill';
    private static final String NEW_LINE = '\n';
    private static final String EMPTY_STRING = '';
    private static final String HYPHEN = ' - ';

    public VCC_CaseDomain() {
        // System.debug(LoggingLevel.INFO, 'Default VCC_CaseDomain constructor.');
    }

    public Case createMedicationRefillCase(Account account, Integer numberOfRefills, Boolean allSuccessful) {
        Boolean hasMSACustomPermission = FeatureManagement.checkPermission('VCC_MSA');
        String caseOutcome;

        Case cse = new Case();
        cse.Origin = 'Inbound Call';
        cse.Subject = 'Refill Medication';
        cse.Priority = 'Low';
        caseOutcome = 'Processed Medication Refill';

        if (hasMSACustomPermission) {
            cse.RecordTypeId = new VCR_CaseRepo().recordTypeConstant.fromDeveloperName('VCC_Administrative').Id;
            cse.Type = 'Administrative';
            cse.VCC_Case_Type__c = 'Administrative';
            cse.VCC_Case_Sub_Type__c = 'Administrative and Scheduling';
            cse.VCC_Case_Reason_Multi__c = 'Medication Refill/Renewal';
            caseOutcome = 'Refilled Medication';
        } else {
            cse.RecordTypeId = new VCR_CaseRepo().recordTypeConstant.fromDeveloperName('VCC_Pharmacy').Id;
            cse.Type = CASE_TYPE_PHARMACY;
            cse.VCC_Case_Sub_Type__c = CASE_SUB_TYPE_PHARMACY;
            cse.VCC_Case_Reason_Multi__c = CASE_REASON_MED_REFILL;
        }

        if (allSuccessful) {
            cse.Status = 'Closed - Resolved';
            cse.VCC_Case_Outcome_Multi__c = caseOutcome;
        } else {
            cse.Status = 'Open';
        }

        if (numberOfRefills < 11) {
            cse.VCC_No_of_Refills__c = String.valueOf(numberOfRefills);
        } else {
            cse.VCC_No_of_Refills__c = '>10';
        }

        cse.AccountId = account.Id;
        cse.ContactId = account.PersonContactId;
        return cse;
    }

    public void setMedicationRefillDescription(
        Case cse,
        List<VCC_DivaClient.ResponseJSON> medRefillResults,
        List<VCC_MedsService.MedRefillRequest> medRefillRequests
    ) {
        //? sync up the medRefillResults & medRefillRequests
        List<RefillDescriptionLayout> medicationsWithMessages = new List<RefillDescriptionLayout>();
        for (VCC_DivaClient.ResponseJSON medRefillResult : medRefillResults) {
            for (VCC_MedsService.MedRefillRequest medRefillRequest : medRefillRequests) {
                if (medRefillResult.prescriptionId == medRefillRequest.prescriptionId) {
                    RefillDescriptionLayout rdl = new RefillDescriptionLayout();
                    rdl.prescriptionId = medRefillRequest.prescriptionId;
                    rdl.prescriptionName = medRefillRequest.prescriptionName;
                    rdl.success = medRefillResult.success;
                    rdl.successValue = medRefillResult.success ? 'Success' : 'Fail';
                    rdl.message = medRefillResult.message;
                    medicationsWithMessages.add(rdl);
                }
            }
        }

        //? build out the description from the medRefillResults & medRefillRequests
        List<String> medicationStrings = new List<String>();
        for (RefillDescriptionLayout med : medicationsWithMessages) {
            medicationStrings.add(
                med.prescriptionId +
                    HYPHEN +
                    med.prescriptionName +
                    HYPHEN +
                    med.successValue +
                    (med.success ? EMPTY_STRING : (HYPHEN + med.message) + NEW_LINE)
            );
        }

        if (cse.Description != null) {
            cse.Description += '\n' + String.join(medicationStrings, ' ').removeEnd('\n');
        } else {
            cse.Description = String.join(medicationStrings, ' ').removeEnd('\n');
        }
    }

    @TestVisible
    private class RefillDescriptionLayout {
        public String prescriptionId { get; set; }
        public String prescriptionName { get; set; }
        public Boolean success { get; set; }
        public String successValue { get; set; }
        public String message { get; set; }

        public RefillDescriptionLayout() {
            this.success = true;
        }
    }
}