sfdx-source/main/default/objects/Case/fields/VCC_Progress_Note__c.field-meta.xml
<CustomField>
    <fullName>VCC_Progress_Note__c</fullName>
    <description>Check true if there are any Progress Notes, related to the case.</description>
    <formula>IF( VCC_Progress_Notes_Count__c &gt; 0, TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Check true if there are any Progress Notes, related to the case.</inlineHelpText>
    <label>Progress Note</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VA_Identity__c/VA_Identity__c.object-meta.xml
<CustomObject>
    <description
    >Goal is to create a Salesforce VA SOR Identity object (separate from Account/Contact) deployed in multiple Salesforce Orgs Allows middleware to work with a consistent
        pattern of objects/fields across all Orgs Not required by DIP, but would simplify configuration and reduce complexity In the future, this core VA SOR Identify Object could
        be part of a Salesforce common package, distributable and available for dependency management orchestration</description>
    <label>VA Identity</label>
    <nameField>
        <displayFormat>I{0}</displayFormat>
        <label>VA Identity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VA Identity</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Progress_Note__c/VCC_Progress_Note__c.object-meta.xml
<CustomObject>
    <description>Progress Notes</description>
    <label>Progress Note</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>Progress Note</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Update_UI__e/VCC_Update_UI__e.object-meta.xml
<CustomObject>
    <description>Platform event that informs the current UI to refresh itself.</description>
    <label>VCC Update UI</label>
    <pluralLabel>VCC Update UI</pluralLabel>
</CustomObject>

force-app/main/default/classes/VCC/VCC_UoWDomain.cls
/**
 * VCC_UoWDomain
 * @description VCC_UoWDomain class for creating units of work.
 * @author Liberty
 * @date 1/16/2024
 */

public with sharing class VCC_UoWDomain {
    /**
     * @description creating a unit of work
     */
    public static fflib_SObjectUnitOfWork createUoW() {
        return new fflib_SObjectUnitOfWork(
            new List<Schema.SObjectType>{
                Account.SObjectType,
                Contact.SObjectType,
                Opportunity.SObjectType,
                Case.SObjectType,
                Task.SObjectType,
                VCC_Progress_Note__c.SObjectType,
                VCC_Update_UI__e.SObjectType,
                VA_Identity__c.SObjectType
            }
        );
    }
}