sfdx-source/main/default/objects/Case/fields/VCC_Progress_Note__c.field-meta.xml
<CustomField>
    <fullName>VCC_Progress_Note__c</fullName>
    <description>Check true if there are any Progress Notes, related to the case.</description>
    <formula>IF( VCC_Progress_Notes_Count__c &gt; 0, TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Check true if there are any Progress Notes, related to the case.</inlineHelpText>
    <label>Progress Note</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/VCC_Vitrual_Clinic_Visit.recordType-meta.xml
<RecordType>
    <fullName>VCC_Vitrual_Clinic_Visit</fullName>
    <active>true</active>
    <businessProcess>VCC Support Process</businessProcess>
    <description>--VA Health Connect virtual visits with medical providers</description>
    <label>Virtual Clinic Visit Case</label>
</RecordType>

force-app/main/default/objects/VCC_Case_Metrics__c/VCC_Case_Metrics__c.object-meta.xml
<CustomObject>
    <description>An extension of the Case object to track metrics for reporting purposes.</description>
    <label>Case Metrics</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>Case Metrics Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VCC_Case_Metrics__c/fields/VCC_Case__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case__c</fullName>
    <description>The parent case of the Case Metrics record.</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Metrics</relationshipLabel>
    <relationshipName>Case_Metrics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/VCC_Progress_Note__c.object-meta.xml
<CustomObject>
    <description>Progress Notes</description>
    <label>Progress Note</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>Progress Note</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Case__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case__c</fullName>
    <description>Parent Case for Progress Note</description>
    <inlineHelpText>Case related to Progress Note on the patient record.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Progress Notes</relationshipLabel>
    <relationshipName>Progress_Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note__c/fields/VCC_Case_Metrics__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case_Metrics__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field is used to relate the PN to the Case metric record of the parent Case</description>
    <label>Case Metrics</label>
    <referenceTo>VCC_Case_Metrics__c</referenceTo>
    <relationshipLabel>Progress Notes</relationshipLabel>
    <relationshipName>Progress_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Progress_Note_Title_IEN__c.field-meta.xml
<CustomField>
    <fullName>VCC_Progress_Note_Title_IEN__c</fullName>
    <description>This field is used to capture the Title IEN of the note title for the VistA site where the note was written to.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Captures the Title IEN of the note title for the VistA site where the note was written to.</inlineHelpText>
    <label>Progress Note Title IEN</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VCC/VCC_ProgressNoteCaseMetricBatchTest.cls
/**
 * @description Tests forVCC_ProgressNoteCaseMetricBatch class
 * @author BAH
 * @see VCC_ProgressNoteCaseMetricBatch
 */

@isTest
private class VCC_ProgressNoteCaseMetricBatchTest {
    private static final Set<String> PERMISSION_SETS = new Set<String>{
        'VAHC_Write_Clinical_Triage_Progress_Note',
        'VAHC_Standard_VCC_User'
    };
    private static final User ADMIN_USER;
    static {
        ADMIN_USER = new VATEST_UserBuilder()
            .withUserProfile('System Administrator')
            .withPermissionSets(PERMISSION_SETS)
            .withStandardData()
            .build(true);
    }

    /**
     * @description Test to get the VCR_ProgressNoteRepo instance
     * Positive test case
     * @see VCC_ProgressNoteCaseMetricBatch.pnRepo
     */
    @IsTest
    static void unitTestVCRPNRepoInstancePositive() {
        System.runAs(ADMIN_USER) {
            VCR_ProgressNoteRepo vcrPNrepo;
            Test.startTest();
            vcrPNrepo = VCC_ProgressNoteCaseMetricBatch.pnRepo;
            Test.stopTest();
            Assert.isTrue(vcrPNrepo != null, 'VCR_ProgressNoteRepo instance is null');
        }
    }

    /**
     * @description Test to get the bind variables
     * Positive test case
     * @see VCC_ProgressNoteCaseMetricBatch.getBindVariables
     */

    @IsTest
    static void unitTestGetBindVariablesPositive() {
        System.runAs(ADMIN_USER) {
            Test.startTest();
            VCC_ProgressNoteCaseMetricBatch vccProgressNotesMetric = new VCC_ProgressNoteCaseMetricBatch();
            Map<String, Object> result = vccProgressNotesMetric.getBindVariables();
            Test.stopTest();
            Assert.isTrue(
                result.isEmpty(),
                'Expected bind variables not returned from the VCC_ProgressNoteCaseMetricBatch.getBindVariables() method'
            );
        }
    }

    /**
     * @description Test to get the query locator
     * Positive test case
     * @see VCC_ProgressNoteCaseMetricBatch.getQueryLocator
     */
    @IsTest
    static void funcTestGetQueryLocatorPositive() {
        System.runAs(ADMIN_USER) {
            Database.QueryLocator result;
            Test.startTest();
            VCC_ProgressNoteCaseMetricBatch vccPNMetrics = new VCC_ProgressNoteCaseMetricBatch();
            result = vccPNMetrics.getQueryLocator(vccPNMetrics.getQueryLocatorString());
            Test.stopTest();
            Assert.isTrue(result != null, 'VCC_ProgressNoteCaseMetricBatch.getQueryLocator() returned null');
        }
    }

    /**
     * @description Test to execute the VCC_ProgressNoteCaseMetricBatch class
     * Positive test case
     * Scenario that finds Progress Note records that have do not have
     * VCC_Case_Metric__c field populated and updates them with the correct values base on the related case
     * @see VCC_ProgressNoteCaseMetricBatch.execute
     */
    @IsTest
    static void funcTestExecutePositivePNUpdate() {
        System.runAs(ADMIN_USER) {
            List<VCC_Progress_Note__c> pnList = new List<VCC_Progress_Note__c>();
            List<VCC_Case_Metrics__c> cmList = new List<VCC_Case_Metrics__c>();
            User provider = (User) VATEST_UserFactory.createTestUser('VAVET Base Profile', true);
            String recordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName()
                .get('VCC_Vitrual_Clinic_Visit')
                .getRecordTypeId();
            List<Case> pnCases = (List<Case>) VATEST_SObjectFactory.createSObjects(
                new Case(OwnerId = provider.Id, RecordTypeId = recordTypeId),
                5,
                true
            );

            for (Integer count = 0; count < pnCases.size(); count++) {
                VCC_Progress_Note__c progressNote = (VCC_Progress_Note__c) VATEST_SObjectFactory.createSObject(
                    new VCC_Progress_Note__c(
                        VCC_Case__c = pnCases[count].Id,
                        VCC_Progress_Note_Title_IEN__c = 'CM PNotes'
                    ),
                    true
                );
                pnList.add(progressNote);
            }

            for (Integer count = 0; count < pnCases.size(); count++) {
                VCC_Case_Metrics__c caseMetric = (VCC_Case_Metrics__c) VATEST_SObjectFactory.createSObject(
                    new VCC_Case_Metrics__c(VCC_Case__c = pnCases[count].Id),
                    true
                );
                cmList.add(caseMetric);
            }

            Test.startTest();
            VCC_ProgressNoteCaseMetricBatch pnMetrics = new VCC_ProgressNoteCaseMetricBatch();
            pnMetrics.execute(pnList);

            Test.stopTest();

            List<VCC_Progress_Note__c> progressNotesList = [
                SELECT Id, VCC_Case_Metrics__c, VCC_Case__c
                FROM VCC_Progress_Note__c
                WHERE VCC_Progress_Note_Title_IEN__c = 'CM PNotes'
            ];

            for (VCC_Progress_Note__c progressNote : progressNotesList) {
                Assert.isTrue(progressNote.VCC_Case_Metrics__c != null, 'Expected Case Metric to be populated');
            }
        }

    }
}