sfdx-source/main/default/objects/Case/fields/VCC_Progress_Note__c.field-meta.xml
<CustomField>
    <fullName>VCC_Progress_Note__c</fullName>
    <description>Check true if there are any Progress Notes, related to the case.</description>
    <formula>IF( VCC_Progress_Notes_Count__c &gt; 0, TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Check true if there are any Progress Notes, related to the case.</inlineHelpText>
    <label>Progress Note</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

sfdx-source/main/default/objects/VCC_Progress_Note__c/VCC_Progress_Note__c.object-meta.xml
<CustomObject>
    <description>Progress Notes</description>
    <label>Progress Note</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>Progress Note</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Case__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case__c</fullName>
    <description>Parent Case for Progress Note</description>
    <inlineHelpText>Case related to Progress Note on the patient record.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Progress Notes</relationshipLabel>
    <relationshipName>Progress_Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/VCC/VCC_ProgressNoteTest.cls
@IsTest
/**
 * @description Test class for VCC_Progress_Note__c
 * @author Patrick Skamarak
 * @since 02/13/2024 - added code coverage for VCC_ProgressNoteTrigger apex trigger
 */
private class VCC_ProgressNoteTest {
    @testSetup
    static void makeData() {
        VCC_TestDataFactory.insertUser('System Administrator');
    }
    /**
     * @description create a test user for running tests
     * @return A test user
     **/
    public static User getTestUser() {
        return [SELECT Id FROM User WHERE LastName = 'Testing' LIMIT 1];
    }
    @IsTest
    static void validateApex() {
        System.runAs(getTestUser()) {
            Test.startTest();
            VCC_ProgressNote note = new VCC_ProgressNote();
            Test.stopTest();
            System.assert(note != null, 'ProgressNote was not created as expected');
        }
    }

    @IsTest
    static void progressNoteTriggerCodeCoverageTest() {
        Test.startTest();
        System.runAs(getTestUser()) {
            try {
                Account accountForProgressNoteCreation = new Account(
                    LastName = 'Test',
                    RecordTypeId = Account.getSObjectType().getDescribe().getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId()
                );
                insert accountForProgressNoteCreation;
                Case caseForProgressNoteCreation = new Case(AccountId = accountForProgressNoteCreation.Id);
                insert caseForProgressNoteCreation;
                VCC_Progress_Note__c progressNoteForDelete = new VCC_Progress_Note__c(VCC_Case__c = caseForProgressNoteCreation.Id);
                insert progressNoteForDelete;
                delete progressNoteForDelete;
            } catch (Exception thrownException) {
                Assert.fail('Unexpected exception thrown ' + thrownException);
            }
        }
        Test.stopTest();
    }
}