sfdx-source/main/default/objects/Case/fields/VCC_Progress_Note__c.field-meta.xml
<CustomField>
    <fullName>VCC_Progress_Note__c</fullName>
    <description>Check true if there are any Progress Notes, related to the case.</description>
    <formula>IF( VCC_Progress_Notes_Count__c &gt; 0, TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Check true if there are any Progress Notes, related to the case.</inlineHelpText>
    <label>Progress Note</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

sfdx-source/main/default/objects/VCC_Progress_Note__c/VCC_Progress_Note__c.object-meta.xml
<CustomObject>
    <description>Progress Notes</description>
    <label>Progress Note</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>Progress Note</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Case__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case__c</fullName>
    <description>Parent Case for Progress Note</description>
    <inlineHelpText>Case related to Progress Note on the patient record.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Progress Notes</relationshipLabel>
    <relationshipName>Progress_Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/main/default/classes/VCC/VCC_HDRHelperTest.cls
@isTest
public with sharing class VCC_HDRHelperTest {
    @isTest
    public static void generateHdrTest() {
        Account a = new Account(
            FirstName = 'test',
            LastName = 'mctest',
            VCC_MVI_External_Id__pc = 'testing',
            RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'PersonAccount' LIMIT 1]
            .Id
        );
        insert a;

        Test.startTest();
        VCC_HDRHelper.generateBRIDG(a.Id, 'vccBridgNotes', String.valueOf(a.getSObjectType()), true);
        VCC_HDRHelper.generateBRIDG(a.Id, 'vccBridgNotes', String.valueOf(a.getSObjectType()), false);
        VCC_HDRHelper.generateBRIDG(a.Id, 'vccBridgMeds', String.valueOf(a.getSObjectType()), true);
        VCC_HDRHelper.generateBRIDG(a.Id, 'vccBridgVitals', String.valueOf(a.getSObjectType()), true);
        Test.stopTest();

        //empty assert because of implied assertion (if it executes without exception)
        System.assert(true, 'Empty assert.');
    }

    @isTest
    static void testUsingOtherSObjects() {
        Account a = new Account(
            FirstName = 'test',
            LastName = 'mctest',
            VCC_MVI_External_Id__pc = 'testing',
            RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'PersonAccount' LIMIT 1]
            .Id
        );
        insert a;

        Case c = new Case(Subject = 'Case HDR Helper', AccountId = a.id);
        insert c;

        VCC_Progress_Note__c pn = new VCC_Progress_Note__c(VCC_Case__c = c.id);
        insert pn;

        Test.startTest();
        VCC_HDRHelper.generateBRIDG(a.Id, 'vccBridgNotes', String.valueOf(a.getSObjectType()), true);
        VCC_HDRHelper.generateBRIDG(c.Id, 'vccBridgNotes', String.valueOf(c.getSObjectType()), true);
        VCC_HDRHelper.generateBRIDG(pn.Id, 'vccBridgNotes', String.valueOf(pn.getSObjectType()), true);
        VCC_HDRHelper.generateBRIDG(a.Id, 'vccBridgNotes', String.valueOf(a.getSObjectType()), false);
        VCC_HDRHelper.generateBRIDG(a.Id, 'vccBridgMeds', String.valueOf(a.getSObjectType()), true);
        VCC_HDRHelper.generateBRIDG(a.Id, 'vccBridgVitals', String.valueOf(a.getSObjectType()), true);
        Test.stopTest();

        //empty assert because of implied assertion (if it executes without exception)
        System.assert(true, 'Empty assert.');
    }
}