sfdx-source/main/default/objects/Case/fields/VCC_Progress_Note__c.field-meta.xml
<CustomField>
    <fullName>VCC_Progress_Note__c</fullName>
    <description>Check true if there are any Progress Notes, related to the case.</description>
    <formula>IF( VCC_Progress_Notes_Count__c &gt; 0, TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Check true if there are any Progress Notes, related to the case.</inlineHelpText>
    <label>Progress Note</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Addendum__c/VCC_Addendum__c.object-meta.xml
<CustomObject>
    <description>Contains the information regarding updates to a Progress Note</description>
    <label>Addendum</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Addendum Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addendums</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Addendum__c/fields/VCC_Addendum__c.field-meta.xml
<CustomField>
    <fullName>VCC_Addendum__c</fullName>
    <description>Addendum Description/Text</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Addendum Description/Text</inlineHelpText>
    <label>Addendum</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/VCC_Progress_Note__c.object-meta.xml
<CustomObject>
    <description>Progress Notes</description>
    <label>Progress Note</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>Progress Note</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Case__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case__c</fullName>
    <description>Parent Case for Progress Note</description>
    <inlineHelpText>Case related to Progress Note on the patient record.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Progress Notes</relationshipLabel>
    <relationshipName>Progress_Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/VCC/DAS/VCC_DASServiceUtilitiesTest.cls
@IsTest
public with sharing class VCC_DASServiceUtilitiesTest {
    @IsTest
    static void getRecordTypeApiNameAddendumTest() {
        VCC_Addendum__c addendum = new VCC_Addendum__c();
        Test.startTest();
        try {
            Assert.areEqual(
                'VCC_Addendum__c',
                VCC_DAS.SERVICES.UTILITIES.getRecordTypeApiName(addendum),
                'Unexpected value.'
            );
        } catch (Exception e) {
            Assert.fail('Unexpected exception: ' + e.getMessage());
        }
        Test.stopTest();
    }

    @IsTest
    static void getRecordTypeApiNameProgressNoteTestHappy() {
        Case c = new Case();
        insert c;

        Map<String, RecordTypeInfo> recordTypeInfosByDeveloperName = VCC_Progress_Note__c.getSObjectType()
            .getDescribe()
            .getRecordTypeInfosByDeveloperName();
        String recordTypeName = new List<String>(recordTypeInfosByDeveloperName.keySet())[0];
        VCC_Progress_Note__c progressNote = new VCC_Progress_Note__c(
            VCC_Case__c = c.Id,
            RecordTypeId = recordTypeInfosByDeveloperName.get(recordTypeName).getRecordTypeId()
        );
        insert progressNote;

        Test.startTest();
        try {
            Assert.areEqual(
                recordTypeName,
                VCC_DAS.SERVICES.UTILITIES.getRecordTypeApiName(progressNote),
                'Unexpected value.'
            );
        } catch (Exception e) {
            Assert.fail('Unexpected exception: ' + e.getMessage());
        }
        Test.stopTest();
    }

    @IsTest
    static void getRecordTypeApiNameProgressNoteTestHappyNullRecordTypeId() {
        Case c = new Case();
        insert c;

        Map<String, RecordTypeInfo> recordTypeInfosByDeveloperName = VCC_Progress_Note__c.getSObjectType()
            .getDescribe()
            .getRecordTypeInfosByDeveloperName();
        String recordTypeName = new List<String>(recordTypeInfosByDeveloperName.keySet())[0];
        VCC_Progress_Note__c progressNote = new VCC_Progress_Note__c(
            VCC_Case__c = c.Id,
            RecordTypeId = recordTypeInfosByDeveloperName.get(recordTypeName).getRecordTypeId()
        );
        insert progressNote;

        Test.startTest();
        try {
            Assert.areEqual(
                recordTypeName,
                VCC_DAS.SERVICES.UTILITIES.getRecordTypeApiName(new VCC_Progress_Note__c(Id = progressNote.Id)),
                'Unexpected value.'
            );
        } catch (Exception e) {
            Assert.fail('Unexpected exception: ' + e.getMessage());
        }
        Test.stopTest();
    }

    @IsTest
    static void getRecordTypeApiNameProgressNoteTestSadNullAll() {
        Test.startTest();
        try {
            Assert.isNull(
                VCC_DAS.SERVICES.UTILITIES.getRecordTypeApiName(new VCC_Progress_Note__c()),
                'Expected null.'
            );
        } catch (Exception e) {
            Assert.fail('Unexpected exception: ' + e.getMessage());
        }
        Test.stopTest();
    }

    @IsTest
    static void getRecordTypeApiNameSadOtherSObject() {
        Case c = new Case();

        Test.startTest();
        try {
            Assert.isNull(VCC_DAS.SERVICES.UTILITIES.getRecordTypeApiName(c), 'Expected null.');
        } catch (Exception e) {
            Assert.fail('Unexpected exception: ' + e.getMessage());
        }
        Test.stopTest();
    }

    @IsTest
    static void getProviderDuzTest() {
        Test.startTest();
        Assert.areEqual(
            'test',
            VCC_DAS.SERVICES.UTILITIES.getProviderDuz(null, null),
            'Expected dummy value of \'test\'.'
        );
        Test.stopTest();
    }

    @IsTest
    static void generateTransactionIdTestHappy() {
        Case c = new Case();
        insert c;

        VCC_Progress_Note__c progressNote = new VCC_Progress_Note__c(VCC_Case__c = c.Id);
        insert progressNote;

        Test.startTest();
        try {
            String txId = VCC_DAS.SERVICES.UTILITIES.generateTransactionId(
                VCC_DAS.Endpoint.CREATE_ADDENDUM,
                progressNote.Id
            );
            Assert.isNotNull(txId, 'Expected non-null value.');
        } catch (Exception e) {
            Assert.fail('Unexpected exception: ' + e.getMessage() + e.getStackTraceString());
        }
        Test.stopTest();
    }
}