sfdx-source/main/default/objects/Case/fields/VCC_Progress_Note__c.field-meta.xml
<CustomField>
    <fullName>VCC_Progress_Note__c</fullName>
    <description>Check true if there are any Progress Notes, related to the case.</description>
    <formula>IF( VCC_Progress_Notes_Count__c &gt; 0, TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Check true if there are any Progress Notes, related to the case.</inlineHelpText>
    <label>Progress Note</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/Case/recordTypes/VCC_Clinical_Triage.recordType-meta.xml
<RecordType>
    <fullName>VCC_Clinical_Triage</fullName>
    <active>true</active>
    <businessProcess>VCC Support Process</businessProcess>
    <description>--VA Health Connect nursing and symptom cases</description>
    <label>Clinical Triage Case</label>
</RecordType>

sfdx-source/main/default/objects/VCC_Progress_Note__c/VCC_Progress_Note__c.object-meta.xml
<CustomObject>
    <description>Progress Notes</description>
    <label>Progress Note</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>Progress Note</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Case__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case__c</fullName>
    <description>Parent Case for Progress Note</description>
    <inlineHelpText>Case related to Progress Note on the patient record.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Progress Notes</relationshipLabel>
    <relationshipName>Progress_Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/main/default/classes/VCC/VCC_CaseControllerTest.cls
@IsTest
private class VCC_CaseControllerTest {
    private static String username = 'caseCont';

    @TestSetup
    public static void makeData() {
        User testUser = VCC_TestDataFactory.insertUser('VAVET Base Profile');
        VCC_TestDataFactory.addPermSetGroupToUser('VCC_Registered_Nurse', testUser);
        testUser.Username = username + testUser.Username;
        update testUser;
    }

    public static User getTestUser() {
        return [SELECT Id FROM User WHERE Username LIKE :username + '%' LIMIT 1];
    }

    @IsTest
    static void getCaseInfoTestCaseId() {
        Test.startTest();
        System.runAs(getTestUser()) {
            Case c = new Case(
                RecordTypeId = Case.getSObjectType().getDescribe().getRecordTypeInfosByDeveloperName().get('VCC_Clinical_Triage').getRecordTypeId(),
                Subject = 'Test Subject'
            );
            insert c;

            VCC_CaseController.CaseInfo caseInfo = VCC_CaseController.getCaseInfo(c.Id);

            System.assert(caseInfo.id == c.Id, 'Failed caseInfo assert, incorrect info received.');
            System.assert(caseInfo.subject == c.Subject, 'Failed caseInfo assert, incorrect info received.');
            System.assert(caseInfo.recordTypeDeveloperName == 'VCC_Clinical_Triage', 'Failed caseInfo assert, incorrect info received.');
            System.assert(
                caseInfo.recordTypeId == Case.getSObjectType().getDescribe().getRecordTypeInfosByDeveloperName().get('VCC_Clinical_Triage').getRecordTypeId(),
                'Failed caseInfo assert, incorrect info received.'
            );
        }
        Test.stopTest();
    }

    @IsTest
    static void getCaseInfoTestProgressNoteId() {
        Test.startTest();
        System.runAs(getTestUser()) {
            Case c = new Case(
                RecordTypeId = Case.getSObjectType().getDescribe().getRecordTypeInfosByDeveloperName().get('VCC_Clinical_Triage').getRecordTypeId(),
                Subject = 'Test Subject'
            );
            insert c;

            VCC_Progress_Note__c pn = new VCC_Progress_Note__c(VCC_Case__c = c.Id);
            insert pn;

            VCC_CaseController.CaseInfo caseInfo = VCC_CaseController.getCaseInfo(pn.Id);

            System.assert(caseInfo.id == c.Id, 'Failed caseInfo assert, incorrect info received.');
            System.assert(caseInfo.subject == c.Subject, 'Failed caseInfo assert, incorrect info received.');
            System.assert(caseInfo.recordTypeDeveloperName == 'VCC_Clinical_Triage', 'Failed caseInfo assert, incorrect info received.');
            System.assert(
                caseInfo.recordTypeId == Case.getSObjectType().getDescribe().getRecordTypeInfosByDeveloperName().get('VCC_Clinical_Triage').getRecordTypeId(),
                'Failed caseInfo assert, incorrect info received.'
            );
        }
        Test.stopTest();
    }

    @IsTest
    static void getCaseInfoWrapperTest() {
        Case c = new Case(
            RecordTypeId = Case.getSObjectType().getDescribe().getRecordTypeInfosByDeveloperName().get('VCC_Clinical_Triage').getRecordTypeId(),
            Subject = 'Test Subject'
        );
        insert c;

        Test.startTest();
        String caseInfoResult = VCC_CaseController.getCaseInfoWrapper(c.Id);
        System.assert(caseInfoResult.length() > 0, 'String length should be longer than zero');
        Test.stopTest();
    }
}