sfdx-source/main/default/objects/Case/fields/VCC_Progress_Note__c.field-meta.xml
<CustomField>
    <fullName>VCC_Progress_Note__c</fullName>
    <description>Check true if there are any Progress Notes, related to the case.</description>
    <formula>IF( VCC_Progress_Notes_Count__c &gt; 0, TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Check true if there are any Progress Notes, related to the case.</inlineHelpText>
    <label>Progress Note</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/Case/recordTypes/VCC_Clinical_Triage.recordType-meta.xml
<RecordType>
    <fullName>VCC_Clinical_Triage</fullName>
    <active>true</active>
    <businessProcess>VCC Support Process</businessProcess>
    <description>--VA Health Connect nursing and symptom cases</description>
    <label>Clinical Triage Case</label>
</RecordType>

sfdx-source/main/default/objects/VCC_Addendum__c/VCC_Addendum__c.object-meta.xml
<CustomObject>
    <description>Contains the information regarding updates to a Progress Note</description>
    <label>Addendum</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Addendum Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addendums</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Addendum__c/fields/VCC_Addendum__c.field-meta.xml
<CustomField>
    <fullName>VCC_Addendum__c</fullName>
    <description>Addendum Description/Text</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Addendum Description/Text</inlineHelpText>
    <label>Addendum</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Addendum__c/fields/VCC_Related_Note__c.field-meta.xml
<CustomField>
    <fullName>VCC_Related_Note__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Progress Note that this Addendum is related to.</description>
    <inlineHelpText>The Progress Note that this Addendum is related to.</inlineHelpText>
    <label>Progress Note</label>
    <referenceTo>VCC_Progress_Note__c</referenceTo>
    <relationshipLabel>Addendums</relationshipLabel>
    <relationshipName>Addendums</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/VCC_Progress_Note__c.object-meta.xml
<CustomObject>
    <description>Progress Notes</description>
    <label>Progress Note</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>Progress Note</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Case__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case__c</fullName>
    <description>Parent Case for Progress Note</description>
    <inlineHelpText>Case related to Progress Note on the patient record.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Progress Notes</relationshipLabel>
    <relationshipName>Progress_Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note__c/recordTypes/VCC_Clinical_Triage_Note_Progress_Note.recordType-meta.xml
<RecordType>
    <fullName>VCC_Clinical_Triage_Note_Progress_Note</fullName>
    <active>true</active>
    <description>Holds the fields for the Clinical Triage Progress Note</description>
    <label>Clinical Triage Progress Note</label>
</RecordType>

force-app/main/default/objects/VCC_Signers__c/VCC_Signers__c.object-meta.xml
<CustomObject>
    <description>Object use to Identify Signers of Notes or Addendums</description>
    <label>Signers</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Signer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Signers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Signers__c/fields/VCC_Addendum__c.field-meta.xml
<CustomField>
    <fullName>VCC_Addendum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Signers for the Addendums</description>
    <inlineHelpText>Signers for the Addendums</inlineHelpText>
    <label>Addendum</label>
    <referenceTo>VCC_Addendum__c</referenceTo>
    <relationshipLabel>Signers</relationshipLabel>
    <relationshipName>Signers</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Signers__c/fields/VCC_DUZ__c.field-meta.xml
<CustomField>
    <fullName>VCC_DUZ__c</fullName>
    <description>Signer&apos;s Unique Identifier</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Signer&apos;s Unique Identifier</inlineHelpText>
    <label>DUZ #</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCC_Signers__c/fields/VCC_Progress_Note__c.field-meta.xml
<CustomField>
    <fullName>VCC_Progress_Note__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Progress Note Signers</description>
    <inlineHelpText>Progress Note Signers</inlineHelpText>
    <label>Progress Note</label>
    <referenceTo>VCC_Progress_Note__c</referenceTo>
    <relationshipLabel>Signers</relationshipLabel>
    <relationshipName>Signers</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/classes/VCC/VCC_SignersServiceTest.cls
@isTest
public with sharing class VCC_SignersServiceTest {
    @TestVisible
    private static VATEST_MockedMethod getMockedMethodGetSignerDuzListForCallout() {
        return new VATEST_MockedMethod(
            new VATEST_MethodSignature('getSignerDuzListForCallout', new List<System.Type>{ Id.class })
        );
    }

    @TestVisible
    private static VATEST_Stub stubSignersService(List<VATEST_MockedMethod> mockedMethods) {
        VATEST_Stub signersServiceStub = new VATEST_Stub(VCC_SignersService.class, mockedMethods);
        VCC_SignersService.privateInstance = (VCC_SignersService) signersServiceStub.createStub();
        return signersServiceStub;
    }

    @IsTest
    static void stubTest() {
        Test.startTest();
        VCC_Stub signersServiceStub = VCC_SignersService.stub();
        System.assert(signersServiceStub.instance === VCC_SignersService.instance, 'Expected strict equality.');
        Test.stopTest();
    }

    @IsTest
    static void getSignersForRecordTestStubbedAddendum() {
        Case testCase = new Case(
            RecordTypeId = Case.getSObjectType()
                .getDescribe()
                .getRecordTypeInfosByDeveloperName()
                .get('VCC_Clinical_Triage')
                .getRecordTypeId()
        );
        insert testCase;
        VCC_Progress_Note__c testProgressNote = new VCC_Progress_Note__c(
            VCC_Case__c = testCase.Id,
            RecordTypeId = VCC_Progress_Note__c.getSObjectType()
                .getDescribe()
                .getRecordTypeInfosByDeveloperName()
                .get('VCC_Clinical_Triage_Note_Progress_Note')
                .getRecordTypeId()
        );
        insert testProgressNote;
        VCC_Addendum__c addendum = new VCC_Addendum__c(
            VCC_Related_Note__c = testProgressNote.Id,
            VCC_Addendum__c = 'Hello World'
        );
        insert addendum;

        VCC_Stub signersSelectorStub = new VCC_Stub(VCC_SignersSelector.class);
        VCC_SignersSelector signersSelector = (VCC_SignersSelector) signersSelectorStub.instance;
        signersSelectorStub.setReturnValue(
            'selectSignersByAddendumId',
            new List<VCC_Signers__c>{ new VCC_Signers__c(VCC_DUZ__c = 'test') }
        );

        Test.startTest();
        System.assert(
            VCC_SignersService.instance.getSignersForRecord(addendum.Id, signersSelector)[0].VCC_DUZ__c == 'test',
            'Expected duz to match stubbed value'
        );
        signersSelectorStub.assertInvoked('selectSignersByAddendumId');
        Test.stopTest();
    }

    @IsTest
    static void getSignersForRecordTestStubbedPn() {
        Case testCase = new Case(
            RecordTypeId = Case.getSObjectType()
                .getDescribe()
                .getRecordTypeInfosByDeveloperName()
                .get('VCC_Clinical_Triage')
                .getRecordTypeId()
        );
        insert testCase;
        VCC_Progress_Note__c testProgressNote = new VCC_Progress_Note__c(
            VCC_Case__c = testCase.Id,
            RecordTypeId = VCC_Progress_Note__c.getSObjectType()
                .getDescribe()
                .getRecordTypeInfosByDeveloperName()
                .get('VCC_Clinical_Triage_Note_Progress_Note')
                .getRecordTypeId()
        );
        insert testProgressNote;

        VCC_Stub signersSelectorStub = new VCC_Stub(VCC_SignersSelector.class);
        VCC_SignersSelector signersSelector = (VCC_SignersSelector) signersSelectorStub.instance;
        signersSelectorStub.setReturnValue(
            'selectSignersByProgressNoteId',
            new List<VCC_Signers__c>{ new VCC_Signers__c(VCC_DUZ__c = 'test') }
        );

        Test.startTest();
        System.assert(
            VCC_SignersService.instance.getSignersForRecord(testProgressNote.Id, signersSelector)[0].VCC_DUZ__c ==
            'test',
            'Expected duz to match stubbed value'
        );
        signersSelectorStub.assertInvoked('selectSignersByProgressNoteId');
        Test.stopTest();
    }

    @IsTest
    static void getSignersForRecordTestStubbedOther() {
        Case testCase = new Case(
            RecordTypeId = Case.getSObjectType()
                .getDescribe()
                .getRecordTypeInfosByDeveloperName()
                .get('VCC_Clinical_Triage')
                .getRecordTypeId()
        );
        insert testCase;

        VCC_Stub signersSelectorStub = new VCC_Stub(VCC_SignersSelector.class);
        VCC_SignersSelector signersSelector = (VCC_SignersSelector) signersSelectorStub.instance;

        Test.startTest();
        List<VCC_Signers__c> resultingSignersList = VCC_SignersService.instance.getSignersForRecord(
            testCase.Id,
            signersSelector
        );
        Assert.isNotNull(resultingSignersList, 'Expected non-null result from getSignersForRecord');
        Assert.isTrue(resultingSignersList.isEmpty(), 'Expected empty list from getSignersForRecord');
        signersSelectorStub.assertNotInvoked('selectSignersByProgressNoteId');
        signersSelectorStub.assertNotInvoked('selectSignersByAddendumId');
        Test.stopTest();
    }

    @IsTest
    static void getSignersForRecordTestStubbedNull() {
        VCC_Stub signersSelectorStub = new VCC_Stub(VCC_SignersSelector.class);
        VCC_SignersSelector signersSelector = (VCC_SignersSelector) signersSelectorStub.instance;

        Test.startTest();
        List<VCC_Signers__c> resultingSignersList = VCC_SignersService.instance.getSignersForRecord(
            null,
            signersSelector
        );
        Assert.isNotNull(resultingSignersList, 'Expected resulting signers list to be non-null');
        Assert.isTrue(resultingSignersList.isEmpty(), 'Expected resulting signers list to be empty');
        signersSelectorStub.assertNotInvoked('selectSignersByProgressNoteId');
        signersSelectorStub.assertNotInvoked('selectSignersByAddendumId');
        Test.stopTest();
    }

    @IsTest
    static void getSignersForRecordTestAddendum() {
        Case testCase = new Case(
            RecordTypeId = Case.getSObjectType()
                .getDescribe()
                .getRecordTypeInfosByDeveloperName()
                .get('VCC_Clinical_Triage')
                .getRecordTypeId()
        );
        insert testCase;
        VCC_Progress_Note__c testProgressNote = new VCC_Progress_Note__c(
            VCC_Case__c = testCase.Id,
            RecordTypeId = VCC_Progress_Note__c.getSObjectType()
                .getDescribe()
                .getRecordTypeInfosByDeveloperName()
                .get('VCC_Clinical_Triage_Note_Progress_Note')
                .getRecordTypeId()
        );
        insert testProgressNote;
        VCC_Addendum__c addendum = new VCC_Addendum__c(
            VCC_Related_Note__c = testProgressNote.Id,
            VCC_Addendum__c = 'Hello World'
        );
        insert addendum;
        insert new List<VCC_Signers__c>{ new VCC_Signers__c(VCC_Addendum__c = addendum.Id) };

        Test.startTest();
        System.assert(VCC_SignersService.instance.getSignersForRecord(addendum.Id).size() == 1, 'Expected one signers');
        Test.stopTest();
    }

    @IsTest
    static void getSignersForRecordTestProgressNote() {
        Case testCase = new Case(
            RecordTypeId = Case.getSObjectType()
                .getDescribe()
                .getRecordTypeInfosByDeveloperName()
                .get('VCC_Clinical_Triage')
                .getRecordTypeId()
        );
        insert testCase;
        VCC_Progress_Note__c testProgressNote = new VCC_Progress_Note__c(
            VCC_Case__c = testCase.Id,
            RecordTypeId = VCC_Progress_Note__c.getSObjectType()
                .getDescribe()
                .getRecordTypeInfosByDeveloperName()
                .get('VCC_Clinical_Triage_Note_Progress_Note')
                .getRecordTypeId()
        );
        insert testProgressNote;
        insert new List<VCC_Signers__c>{ new VCC_Signers__c(VCC_Progress_Note__c = testProgressNote.Id) };

        Test.startTest();
        Assert.isTrue(
            VCC_SignersService.instance.getSignersForRecord(testProgressNote.Id).size() == 1,
            'Expected one signers'
        );
        Test.stopTest();
    }

    @IsTest
    static void getSignersForRecordTestNull() {
        Test.startTest();
        System.assert(VCC_SignersService.instance.getSignersForRecord(null).size() == 0, 'Expected no signers');
        Test.stopTest();
    }

    @IsTest
    static void getSignerDuzListForCalloutTest() {
        Case testCase = new Case(
            RecordTypeId = Case.getSObjectType()
                .getDescribe()
                .getRecordTypeInfosByDeveloperName()
                .get('VCC_Clinical_Triage')
                .getRecordTypeId()
        );
        insert testCase;
        VCC_Progress_Note__c testProgressNote = new VCC_Progress_Note__c(
            VCC_Case__c = testCase.Id,
            RecordTypeId = VCC_Progress_Note__c.getSObjectType()
                .getDescribe()
                .getRecordTypeInfosByDeveloperName()
                .get('VCC_Clinical_Triage_Note_Progress_Note')
                .getRecordTypeId()
        );
        insert testProgressNote;
        insert new List<VCC_Signers__c>{
            new VCC_Signers__c(VCC_Progress_Note__c = testProgressNote.Id, VCC_DUZ__c = '123')
        };

        Test.startTest();
        System.assert(
            VCC_SignersService.instance.getSignerDuzListForCallout(testProgressNote.Id) == new List<String>{ '123' },
            'Expected to find a list with one value matching that of test VCC_Signers__c record'
        );
        Test.stopTest();
    }
}