sfdx-source/main/default/objects/Case/fields/VCC_Progress_Note__c.field-meta.xml
<CustomField>
    <fullName>VCC_Progress_Note__c</fullName>
    <description>Check true if there are any Progress Notes, related to the case.</description>
    <formula>IF( VCC_Progress_Notes_Count__c &gt; 0, TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Check true if there are any Progress Notes, related to the case.</inlineHelpText>
    <label>Progress Note</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/Case/recordTypes/VCC_Clinical_Triage.recordType-meta.xml
<RecordType>
    <fullName>VCC_Clinical_Triage</fullName>
    <active>true</active>
    <businessProcess>VCC Support Process</businessProcess>
    <description>--VA Health Connect nursing and symptom cases</description>
    <label>Clinical Triage Case</label>
</RecordType>

sfdx-source/main/default/objects/VCC_Addendum__c/VCC_Addendum__c.object-meta.xml
<CustomObject>
    <description>Contains the information regarding updates to a Progress Note</description>
    <label>Addendum</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Addendum Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addendums</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Addendum__c/fields/VCC_Addendum__c.field-meta.xml
<CustomField>
    <fullName>VCC_Addendum__c</fullName>
    <description>Addendum Description/Text</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Addendum Description/Text</inlineHelpText>
    <label>Addendum</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Addendum__c/fields/VCC_Related_Note__c.field-meta.xml
<CustomField>
    <fullName>VCC_Related_Note__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Progress Note that this Addendum is related to.</description>
    <inlineHelpText>The Progress Note that this Addendum is related to.</inlineHelpText>
    <label>Progress Note</label>
    <referenceTo>VCC_Progress_Note__c</referenceTo>
    <relationshipLabel>Addendums</relationshipLabel>
    <relationshipName>Addendums</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/VCC_Progress_Note__c.object-meta.xml
<CustomObject>
    <description>Progress Notes</description>
    <label>Progress Note</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>Progress Note</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Case__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case__c</fullName>
    <description>Parent Case for Progress Note</description>
    <inlineHelpText>Case related to Progress Note on the patient record.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Progress Notes</relationshipLabel>
    <relationshipName>Progress_Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note__c/recordTypes/VCC_Clinical_Triage_Note_Progress_Note.recordType-meta.xml
<RecordType>
    <fullName>VCC_Clinical_Triage_Note_Progress_Note</fullName>
    <active>true</active>
    <description>Holds the fields for the Clinical Triage Progress Note</description>
    <label>Clinical Triage Progress Note</label>
</RecordType>

force-app/main/default/objects/VCC_Signers__c/VCC_Signers__c.object-meta.xml
<CustomObject>
    <description>Object use to Identify Signers of Notes or Addendums</description>
    <label>Signers</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Signer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Signers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Signers__c/fields/VCC_Addendum__c.field-meta.xml
<CustomField>
    <fullName>VCC_Addendum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Signers for the Addendums</description>
    <inlineHelpText>Signers for the Addendums</inlineHelpText>
    <label>Addendum</label>
    <referenceTo>VCC_Addendum__c</referenceTo>
    <relationshipLabel>Signers</relationshipLabel>
    <relationshipName>Signers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCC_Signers__c/fields/VCC_Progress_Note__c.field-meta.xml
<CustomField>
    <fullName>VCC_Progress_Note__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Progress Note Signers</description>
    <inlineHelpText>Progress Note Signers</inlineHelpText>
    <label>Progress Note</label>
    <referenceTo>VCC_Progress_Note__c</referenceTo>
    <relationshipLabel>Signers</relationshipLabel>
    <relationshipName>Signers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VCC/VCC_SignersSelectorTest.cls
@IsTest
public with sharing class VCC_SignersSelectorTest {
    @isTest
    public static void addSObjectFieldsTest() {
        VCC_SignersSelector signersSelector = new VCC_SignersSelector();
        System.assert(!signersSelector.getSObjectFieldList().contains(VCC_Signers__c.SystemModStamp), 'SObject field list already contains this field.');
        Test.startTest();
        signersSelector.addSObjectFields(new List<SObjectField>{ VCC_Signers__c.SystemModStamp });
        Test.stopTest();
        System.assert(signersSelector.getSObjectFieldList().contains(VCC_Signers__c.SystemModStamp), 'SObject field was not added as expected.');
    }

    @isTest
    public static void selectSignersByAddendumIdTest() {
        Case c = new Case(RecordTypeId = Case.getSObjectType().getDescribe().getRecordTypeInfosByDeveloperName().get('VCC_Clinical_Triage').getRecordTypeId());
        insert c;
        VCC_Progress_Note__c pn = new VCC_Progress_Note__c(
            VCC_Case__c = c.Id,
            RecordTypeId = VCC_Progress_Note__c.getSObjectType().getDescribe().getRecordTypeInfosByDeveloperName().get('VCC_Clinical_Triage_Note_Progress_Note').getRecordTypeId()
        );
        insert pn;
        VCC_Addendum__c addendum = new VCC_Addendum__c(VCC_Related_Note__c = pn.Id, VCC_Addendum__c = 'Hello World');
        insert addendum;
        insert new List<VCC_Signers__c>{ new VCC_Signers__c(VCC_Addendum__c = addendum.Id) };

        Test.startTest();
        List<VCC_Signers__c> signers = (new VCC_SignersSelector()).selectSignersByAddendumId(addendum.Id);
        System.assert(signers.size() == 1, 'Expected one signer.');
        Test.stopTest();
    }

    @isTest
    public static void selectSignersByProgressNoteIdTest() {
        Case c = new Case(RecordTypeId = Case.getSObjectType().getDescribe().getRecordTypeInfosByDeveloperName().get('VCC_Clinical_Triage').getRecordTypeId());
        insert c;
        VCC_Progress_Note__c pn = new VCC_Progress_Note__c(
            VCC_Case__c = c.Id,
            RecordTypeId = VCC_Progress_Note__c.getSObjectType().getDescribe().getRecordTypeInfosByDeveloperName().get('VCC_Clinical_Triage_Note_Progress_Note').getRecordTypeId()
        );
        insert pn;
        insert new List<VCC_Signers__c>{ new VCC_Signers__c(VCC_Progress_Note__c = pn.Id) };

        Test.startTest();
        List<VCC_Signers__c> signers = (new VCC_SignersSelector()).selectSignersByProgressNoteId(pn.Id);
        System.assert(signers.size() == 1, 'Expected one signer.');
        Test.stopTest();
    }
}