sfdx-source/main/default/objects/Case/fields/VCC_Progress_Note__c.field-meta.xml
<CustomField>
    <fullName>VCC_Progress_Note__c</fullName>
    <description>Check true if there are any Progress Notes, related to the case.</description>
    <formula>IF( VCC_Progress_Notes_Count__c &gt; 0, TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Check true if there are any Progress Notes, related to the case.</inlineHelpText>
    <label>Progress Note</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Addendum__c/VCC_Addendum__c.object-meta.xml
<CustomObject>
    <description>Contains the information regarding updates to a Progress Note</description>
    <label>Addendum</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Addendum Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addendums</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Addendum__c/fields/VCC_Addendum__c.field-meta.xml
<CustomField>
    <fullName>VCC_Addendum__c</fullName>
    <description>Addendum Description/Text</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Addendum Description/Text</inlineHelpText>
    <label>Addendum</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Addendum__c/fields/VCC_Related_Note__c.field-meta.xml
<CustomField>
    <fullName>VCC_Related_Note__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Progress Note that this Addendum is related to.</description>
    <inlineHelpText>The Progress Note that this Addendum is related to.</inlineHelpText>
    <label>Progress Note</label>
    <referenceTo>VCC_Progress_Note__c</referenceTo>
    <relationshipLabel>Addendums</relationshipLabel>
    <relationshipName>Addendums</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/VCC_Progress_Note__c.object-meta.xml
<CustomObject>
    <description>Progress Notes</description>
    <label>Progress Note</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>Progress Note</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Case__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case__c</fullName>
    <description>Parent Case for Progress Note</description>
    <inlineHelpText>Case related to Progress Note on the patient record.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Progress Notes</relationshipLabel>
    <relationshipName>Progress_Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/main/default/classes/VCC/VCC_Flow_UtilitiesTest.cls
@IsTest
/**
 * @description
 * @author Patrick Skamarak
 * @since 8/5/2021
 * @see VCC_Flow_Utilities
 * @group Test Classes
 */
public class VCC_Flow_UtilitiesTest {
    @TestSetup
    static void makeData() {
        Case testCase = new Case();
        testCase.RecordTypeId = Case.SObjectType.getDescribe().getRecordTypeInfosByName().get('Clinical Triage Case').getRecordTypeId();
        insert testCase;
        VCC_Progress_Note__c pn = new VCC_Progress_Note__c(VCC_Case__c = testCase.Id);
        insert pn;
        VCC_Addendum__c ad = new VCC_Addendum__c(VCC_Related_Note__c = pn.Id, VCC_Addendum__c = 'Addendum Description here...');
        insert ad;
    }
    @IsTest
    public static void getSObjectTypeTest() {
        VCC_Flow_Utilities.ActionParams params = new VCC_Flow_Utilities.ActionParams();
        params.actionName = 'GetSObjectTypeForId';
        params.recordId = [
            SELECT Id
            FROM VCC_Progress_Note__c
            LIMIT 1
        ]
        .Id;
        System.assert(VCC_Flow_Utilities.flowUtility(new List<VCC_Flow_Utilities.ActionParams>{ params })[0] == 'VCC_Progress_Note__c');

        params.recordId = [
            SELECT Id
            FROM VCC_Addendum__c
            LIMIT 1
        ]
        .Id;
        System.assert(VCC_Flow_Utilities.flowUtility(new List<VCC_Flow_Utilities.ActionParams>{ params })[0] == 'VCC_Addendum__c');
    }
}