sfdx-source/main/default/objects/Case/fields/VCC_Progress_Note__c.field-meta.xml
<CustomField>
    <fullName>VCC_Progress_Note__c</fullName>
    <description>Check true if there are any Progress Notes, related to the case.</description>
    <formula>IF( VCC_Progress_Notes_Count__c &gt; 0, TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Check true if there are any Progress Notes, related to the case.</inlineHelpText>
    <label>Progress Note</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/Case/recordTypes/VCC_Clinical_Triage.recordType-meta.xml
<RecordType>
    <fullName>VCC_Clinical_Triage</fullName>
    <active>true</active>
    <businessProcess>VCC Support Process</businessProcess>
    <description>--VA Health Connect nursing and symptom cases</description>
    <label>Clinical Triage Case</label>
</RecordType>

sfdx-source/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

sfdx-source/main/default/objects/VCC_Progress_Note__c/VCC_Progress_Note__c.object-meta.xml
<CustomObject>
    <description>Progress Notes</description>
    <label>Progress Note</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>Progress Note</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Case__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case__c</fullName>
    <description>Parent Case for Progress Note</description>
    <inlineHelpText>Case related to Progress Note on the patient record.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Progress Notes</relationshipLabel>
    <relationshipName>Progress_Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Signed__c.field-meta.xml
<CustomField>
    <fullName>VCC_Signed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Progress Note has been electronically signed.</description>
    <inlineHelpText>Progress Note has been electronically signed.</inlineHelpText>
    <label>Signed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note__c/recordTypes/VCC_Clinical_Triage_Note_Progress_Note.recordType-meta.xml
<RecordType>
    <fullName>VCC_Clinical_Triage_Note_Progress_Note</fullName>
    <active>true</active>
    <description>Holds the fields for the Clinical Triage Progress Note</description>
    <label>Clinical Triage Progress Note</label>
</RecordType>

sfdx-source/main/default/classes/VCC/VCC_ProgressNote_PreventSignedDeleteTest.cls
@IsTest
public with sharing class VCC_ProgressNote_PreventSignedDeleteTest {
    @IsTest
    static void unitPreventProgressNoteDeleteNullArgNegative() {
        Test.startTest();
        try {
            (new VCC_ProgressNote_PreventSignedDelete_BD()).beforeDelete(null);
        } catch (Exception thrownException) {
            Assert.fail('Expected no exception, instead found ' + thrownException.getTypeName());
        }
        Test.stopTest();
    }

    @IsTest
    static void unitPreventProgressNoteDeleteEmptyListNegative() {
        Test.startTest();
        try {
            (new VCC_ProgressNote_PreventSignedDelete_BD()).beforeDelete(new List<VCC_Progress_Note__c>());
        } catch (Exception thrownException) {
            Assert.fail('Expected no exception, instead found ' + thrownException.getTypeName());
        }
        Test.stopTest();
    }

    @IsTest
    static void unitPreventProgressNoteDeleteSignedPositive() {
        List<VCC_Progress_Note__c> progressNoteList = new List<VCC_Progress_Note__c>{
            new VCC_Progress_Note__c(VCC_Signed__c = true)
        };
        Test.startTest();
        try {
            (new VCC_ProgressNote_PreventSignedDelete_BD()).beforeDelete(progressNoteList);
            List<Database.Error> triggerErrors = progressNoteList[0].getErrors();
            Assert.areEqual(1, triggerErrors.size(), 'Expected one Database.Error');
            Assert.areEqual(
                VCC_ProgressNote_PreventSignedDelete_BD.PREVENT_DELETE_ERROR_MESSAGE,
                triggerErrors[0].getMessage(),
                'Expected error stored in static property PREVENT_DELETE_ERROR_MESSAGE'
            );
        } catch (Exception thrownException) {
            Assert.fail('Expected no exception, instead found ' + thrownException.getTypeName());
        }
        Test.stopTest();
    }

    @IsTest
    static void unitPreventProgressNoteDeleteUnsignedPositive() {
        List<VCC_Progress_Note__c> progressNoteList = new List<VCC_Progress_Note__c>{
            new VCC_Progress_Note__c(VCC_Signed__c = false)
        };
        Test.startTest();
        try {
            (new VCC_ProgressNote_PreventSignedDelete_BD()).beforeDelete(progressNoteList);
            List<Database.Error> triggerErrors = progressNoteList[0].getErrors();
            Assert.areEqual(0, triggerErrors.size(), 'Expected no Database.Error\'s');
        } catch (Exception thrownException) {
            Assert.fail('Expected no exception, instead found ' + thrownException.getTypeName());
        }
        Test.stopTest();
    }

    @IsTest
    static void funcBeforeDeleteSignedPositive() {
        System.runAs((new VATEST_UserBuilder())
            .withStandardData()
            .withUserProfile('System Administrator')
            .withPermissionSet('VAHC_Write_Clinical_Triage_Progress_Note')
            .withPermissionSet('VAHC_RN_User')
            .build(true)) {
            Account testAccount = new Account(
                LastName = 'Test',
                RecordTypeId = Account.SObjectType.getDescribe(SObjectDescribeOptions.DEFERRED)
                    .getRecordTypeInfosByDeveloperName()
                    .get('PersonAccount')
                    .getRecordTypeId()
            );
            (new VCR_AccountRepo()).doCreate(testAccount);
            Case clinicalTriageCase = new Case(
                AccountId = testAccount.Id,
                RecordTypeId = Case.SObjectType.getDescribe(SObjectDescribeOptions.DEFERRED)
                    .getRecordTypeInfosByDeveloperName()
                    .get('VCC_Clinical_Triage')
                    .getRecordTypeId()
            );
            (new VCR_CaseRepo()).doCreate(clinicalTriageCase);
            VCC_Progress_Note__c clinicalTriageProgressNote = new VCC_Progress_Note__c(
                VCC_Case__c = clinicalTriageCase.Id,
                VCC_Signed__c = true,
                RecordTypeId = VCC_Progress_Note__c.SObjectType.getDescribe(SObjectDescribeOptions.DEFERRED)
                    .getRecordTypeInfosByDeveloperName()
                    .get('VCC_Clinical_Triage_Note_Progress_Note')
                    .getRecordTypeId()
            );
            VCR_ProgressNoteRepo progressNoteRepo = new VCR_ProgressNoteRepo();
            progressNoteRepo.doCreate(clinicalTriageProgressNote);
            Test.startTest();
            try {
                progressNoteRepo.doDelete(new VCC_Progress_Note__c(Id = clinicalTriageProgressNote.Id));
                Assert.fail('Expected an exception to be thrown, preventing delete of the progress note');
            } catch (Exception thrownException) {
                Assert.areEqual(
                    VCC_ProgressNote_PreventSignedDelete_BD.PREVENT_DELETE_ERROR_MESSAGE,
                    thrownException.getDmlMessage(0),
                    'Expected to find the correct error message stored in VCC_ProgressNote_PreventSignedDelete_BD.PREVENT_DELETE_ERROR_MESSAGE'
                );
            }
            Test.stopTest();
        }
    }

    @IsTest
    static void funcBeforeDeleteUnsignedNegative() {
        System.runAs((new VATEST_UserBuilder())
            .withStandardData()
            .withUserProfile('System Administrator')
            .withPermissionSet('VAHC_Write_Clinical_Triage_Progress_Note')
            .withPermissionSet('VAHC_RN_User')
            .build(true)) {
            Account testAccount = new Account(
                LastName = 'Test',
                RecordTypeId = Account.SObjectType.getDescribe(SObjectDescribeOptions.DEFERRED)
                    .getRecordTypeInfosByDeveloperName()
                    .get('PersonAccount')
                    .getRecordTypeId()
            );
            (new VCR_AccountRepo()).doCreate(testAccount);
            Case clinicalTriageCase = new Case(
                AccountId = testAccount.Id,
                RecordTypeId = Case.SObjectType.getDescribe(SObjectDescribeOptions.DEFERRED)
                    .getRecordTypeInfosByDeveloperName()
                    .get('VCC_Clinical_Triage')
                    .getRecordTypeId()
            );
            (new VCR_CaseRepo()).doCreate(clinicalTriageCase);
            VCC_Progress_Note__c clinicalTriageProgressNote = new VCC_Progress_Note__c(
                VCC_Case__c = clinicalTriageCase.Id,
                VCC_Signed__c = false,
                RecordTypeId = VCC_Progress_Note__c.SObjectType.getDescribe(SObjectDescribeOptions.DEFERRED)
                    .getRecordTypeInfosByDeveloperName()
                    .get('VCC_Clinical_Triage_Note_Progress_Note')
                    .getRecordTypeId()
            );
            VCR_ProgressNoteRepo progressNoteRepo = new VCR_ProgressNoteRepo();
            progressNoteRepo.doCreate(clinicalTriageProgressNote);
            Test.startTest();
            try {
                progressNoteRepo.doDelete(new VCC_Progress_Note__c(Id = clinicalTriageProgressNote.Id));
            } catch (Exception thrownException) {
                Assert.fail('Expected the progress note to be deleted');
            }
            Test.stopTest();
        }
    }
}