sfdx-source/main/default/objects/Case/fields/VCC_Caller_Relation__c.field-meta.xml
<CustomField>
    <fullName>VCC_Caller_Relation__c</fullName>
    <description>Identifies the relationship of the Caller to the Patient</description>
    <inlineHelpText>Identifies the relationship of the Caller to the Patient. Populated via the Verify Patient process.</inlineHelpText>
    <label>Caller/Recipient Relation to Patient</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Self</fullName>
            </value>
            <value>
                <fullName>Caregiver</fullName>
            </value>
            <value>
                <fullName>Power of Attorney</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Anonymous</fullName>
                <isActive>false</isActive>
                <label>Anonymous</label>
            </value>
            <value>
                <fullName>Aunt</fullName>
                <isActive>false</isActive>
                <label>Aunt</label>
            </value>
            <value>
                <fullName>Daughter</fullName>
                <isActive>false</isActive>
                <label>Daughter</label>
            </value>
            <value>
                <fullName>Father</fullName>
                <isActive>false</isActive>
                <label>Father</label>
            </value>
            <value>
                <fullName>Home Health</fullName>
                <isActive>false</isActive>
                <label>Home Health</label>
            </value>
            <value>
                <fullName>Internal Review Only</fullName>
                <isActive>false</isActive>
                <label>Internal Review Only</label>
            </value>
            <value>
                <fullName>Mother</fullName>
                <isActive>false</isActive>
                <label>Mother</label>
            </value>
            <value>
                <fullName>Neighbor</fullName>
                <isActive>false</isActive>
                <label>Neighbor</label>
            </value>
            <value>
                <fullName>Psychiatrist</fullName>
                <isActive>false</isActive>
                <label>Psychiatrist</label>
            </value>
            <value>
                <fullName>Relative</fullName>
                <isActive>false</isActive>
                <label>Relative</label>
            </value>
            <value>
                <fullName>Sibling</fullName>
                <isActive>false</isActive>
                <label>Sibling</label>
            </value>
            <value>
                <fullName>Son</fullName>
                <isActive>false</isActive>
                <label>Son</label>
            </value>
            <value>
                <fullName>Spouse</fullName>
                <isActive>false</isActive>
                <label>Spouse</label>
            </value>
            <value>
                <fullName>Uncle</fullName>
                <isActive>false</isActive>
                <label>Uncle</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/Case/fields/VCC_Progress_Note__c.field-meta.xml
<CustomField>
    <fullName>VCC_Progress_Note__c</fullName>
    <description>Check true if there are any Progress Notes, related to the case.</description>
    <formula>IF( VCC_Progress_Notes_Count__c &gt; 0, TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Check true if there are any Progress Notes, related to the case.</inlineHelpText>
    <label>Progress Note</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/User/fields/MVIICN__c.field-meta.xml
<CustomField>
    <fullName>MVIICN__c</fullName>
    <description>MVI ICN returned by IAM SSO.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>MVI ICN</label>
    <length>29</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/VCC_Progress_Note__c.object-meta.xml
<CustomObject>
    <description>Progress Notes</description>
    <label>Progress Note</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>Progress Note</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Additional_Comments__c.field-meta.xml
<CustomField>
    <fullName>VCC_Additional_Comments__c</fullName>
    <description>Used to add any additional comments about lost medication</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter any additional comments about lost medication</inlineHelpText>
    <label>Additional Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note__c/fields/VCC_Caller_Name_Text__c.field-meta.xml
<CustomField>
    <fullName>VCC_Caller_Name_Text__c</fullName>
    <description>Caller Name is populated from the Phone Call/Case, if different from the Veteran.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Caller Name is populated from the Phone Call/Case, if different from the Veteran.</inlineHelpText>
    <label>Caller Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Caregiver_Name__c.field-meta.xml
<CustomField>
    <fullName>VCC_Caregiver_Name__c</fullName>
    <description>Name of caregiver speaking on behalf of the patient</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Name of caregiver speaking on behalf of the patient</inlineHelpText>
    <label>Caller/Recipient Name</label>
    <type>TextArea</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Case__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case__c</fullName>
    <description>Parent Case for Progress Note</description>
    <inlineHelpText>Case related to Progress Note on the patient record.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Progress Notes</relationshipLabel>
    <relationshipName>Progress_Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note__c/fields/VCC_Comments_patient_in_crisis__c.field-meta.xml
<CustomField>
    <fullName>VCC_Comments_patient_in_crisis__c</fullName>
    <description>Enter comments related to the patient that is in crisis</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter comments related to the patient in crisis</inlineHelpText>
    <label>Comments - Patient in crisis</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Relative_Type__c.field-meta.xml
<CustomField>
    <fullName>VCC_Relative_Type__c</fullName>
    <description>Relationship of Caller to Veteran. Populated from the Phone Call/Case via a Flow.</description>
    <inlineHelpText>Relationship of the Caller to the Veteran. This is populated from the Phone Call/Case, if captured.</inlineHelpText>
    <label>Caller/Recipient Relation to Patient</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Self</fullName>
            </value>
            <value>
                <fullName>Caregiver</fullName>
            </value>
            <value>
                <fullName>Power of Attorney</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Anonymous</fullName>
                <isActive>false</isActive>
                <label>Anonymous</label>
            </value>
            <value>
                <fullName>Aunt</fullName>
                <isActive>false</isActive>
                <label>Aunt</label>
            </value>
            <value>
                <fullName>Daughter</fullName>
                <isActive>false</isActive>
                <label>Daughter</label>
            </value>
            <value>
                <fullName>Father</fullName>
                <isActive>false</isActive>
                <label>Father</label>
            </value>
            <value>
                <fullName>Home Health</fullName>
                <isActive>false</isActive>
                <label>Home Health</label>
            </value>
            <value>
                <fullName>Mother</fullName>
                <isActive>false</isActive>
                <label>Mother</label>
            </value>
            <value>
                <fullName>Neighbor</fullName>
                <isActive>false</isActive>
                <label>Neighbor</label>
            </value>
            <value>
                <fullName>Sibling</fullName>
                <isActive>false</isActive>
                <label>Sibling</label>
            </value>
            <value>
                <fullName>Son</fullName>
                <isActive>false</isActive>
                <label>Son</label>
            </value>
            <value>
                <fullName>Spouse</fullName>
                <isActive>false</isActive>
                <label>Spouse</label>
            </value>
            <value>
                <fullName>Uncle</fullName>
                <isActive>false</isActive>
                <label>Uncle</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Signed__c.field-meta.xml
<CustomField>
    <fullName>VCC_Signed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Progress Note has been electronically signed.</description>
    <inlineHelpText>Progress Note has been electronically signed.</inlineHelpText>
    <label>Signed</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_T2T_Assessment_Completed__c.field-meta.xml
<CustomField>
    <fullName>VCC_T2T_Assessment_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description
    >Field that is used to track if a T2T Assessment has been completed for a given progress note, displaying this field in the record is a visual confirmation for the user,
        and the T2T flow checks this field to decide if another T2T Assessment can be launched.</description>
    <inlineHelpText>Indicates if a Test to Treat assessment has been completed for this patient.</inlineHelpText>
    <label>T2T Assessment Completed</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/recordTypes/VCC_Virtual_Visit_Progress_Note.recordType-meta.xml
<RecordType>
    <fullName>VCC_Virtual_Visit_Progress_Note</fullName>
    <active>true</active>
    <description>Progress Note Object with Virtual Visit</description>
    <label>Virtual Visit Progress Note</label>
</RecordType>

sfdx-source/main/default/objects/VCC_Progress_Note_Detail__c/VCC_Progress_Note_Detail__c.object-meta.xml
<CustomObject>
    <description>Stores details from the progress note</description>
    <label>Progress Note Detail</label>
    <nameField>
        <displayFormat>PND-{00000}</displayFormat>
        <label>Progress Note Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Progress_Note_Detail__c/fields/VCC_Progress_Note__c.field-meta.xml
<CustomField>
    <fullName>VCC_Progress_Note__c</fullName>
    <description>This is the master-detail relationship to the parent Progress Note custom object which is a one to one relationship.</description>
    <label>Progress Note</label>
    <referenceTo>VCC_Progress_Note__c</referenceTo>
    <relationshipLabel>Progress Notes Detail</relationshipLabel>
    <relationshipName>Progress_Notes_Detail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note_Detail__c/fields/VCC_T2T_Data__c.field-meta.xml
<CustomField>
    <fullName>VCC_T2T_Data__c</fullName>
    <description>This field stores the data for the Test to Treat data when Medical Provider does an assessment.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>T2T Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/VCC/VCC_InterviewsByRecordController_Test.cls
@IsTest
public with sharing class VCC_InterviewsByRecordController_Test {
    private static final String username = 'antv';
    @TestSetup
    static void makeData() {
        List<User> userList = new List<User>();
        List<String> psgNames = new List<String>{ 'VCC_Registered_Nurse', 'VCC_Medical_Provider' };
        List<Id> psgIds = new List<Id>();
        for (PermissionSetGroup psg : [SELECT Id FROM PermissionSetGroup WHERE DeveloperName IN :psgNames]) {
            psgIds.add(psg.Id);
        }
        Test.calculatePermissionSetGroup(psgIds);
        for (Integer i = 0; i < psgNames.size(); i++) {
            User testUser = VCC_TestDataFactory.insertUser('VAVET Base Profile');
            userList.add(testUser);
            VCC_TestDataFactory.addPermSetGroupToUser(psgNames[i], testUser);
            VCC_TestDataFactory.assignPermissionSetByName(testUser, 'HealthCloudFoundation');
            testUser.username = username + testUser.username + i;
            testUser.Title = psgNames[i];
        }
        update userList;
    }
    private static User getTestUser(Integer offset) {
        return [SELECT Id, MVIICN__c, Title FROM User WHERE Username LIKE :username + '%' LIMIT 1 OFFSET :offset];
    }
    public static VCC_Progress_Note__c insertTestPN(User testUser) {
        Account testAccount = TestUtility.createAccount('testAccount');
        insert testAccount;
        Contact testContact = TestUtility.createContact(testUser.Id, 'lastName', testAccount.Id);
        insert testContact;
        Case testCase = new Case(
            RecordTypeId = Case.SObjectType.getDescribe().getRecordTypeInfosByName().get('Virtual Clinic Visit Case').getRecordTypeId(),
            VCC_Caller_Relation__c = 'Self',
            ContactId = testContact.Id
        );
        insert testCase;
        insert new CaseShare(CaseId = testCase.Id, CaseAccessLevel = 'Edit', UserOrGroupId = testUser.Id);
        VCC_Progress_Note__c pn = new VCC_Progress_Note__c(
            VCC_Case__r = testCase,
            VCC_Case__c = testCase.Id,
            VCC_Relative_Type__c = 'Self',
            VCC_Additional_Comments__c = 'Some additional comment.',
            VCC_Comments_patient_in_crisis__c = 'some long string that will be longer than 80 characters long to demonstrate the line breaking',
            RecordTypeId = Schema.SObjectType.VCC_Progress_Note__c.getRecordTypeInfosByDeveloperName().get('VCC_Virtual_Visit_Progress_Note').getRecordTypeId()
        );
        insert pn;
        return pn;
    }
    @IsTest
    private static void getPausedIdTestRN() {
        User testUser = getTestUser(0);
        VCC_Progress_Note__c pn = insertTestPN(testUser);
        List<VCC_Progress_Note__c> recordIds = [
            SELECT Id
            FROM VCC_Progress_Note__c
            WHERE Id = :pn.Id
            LIMIT 1
        ];
        Test.startTest();
        String paused;
        System.runAs(testUser) {
            try {
                paused = VCC_InterviewsByRecordController.getPausedId(recordIds.get(0).Id);
            } catch (Exception e) {
                Assert.fail('Perm Set Group ' + testUser.Title + ' Unexpected exception: ' + e.getMessage());
            }
            System.assertEquals(null, paused, 'Paused interview incorrectly retrieved');
        }
        Test.stopTest();
    }

    @IsTest
    private static void getPausedIdTestMP() {
        User testUser = getTestUser(1);
        VCC_Progress_Note__c pn = insertTestPN(testUser);
        List<VCC_Progress_Note__c> recordIds = [
            SELECT Id
            FROM VCC_Progress_Note__c
            WHERE Id = :pn.Id
            LIMIT 1
        ];
        Test.startTest();
        String paused;
        System.runAs(testUser) {
            try {
                paused = VCC_InterviewsByRecordController.getPausedId(recordIds.get(0).Id);
            } catch (Exception e) {
                Assert.fail('Perm Set Group ' + testUser.Title + ' Unexpected exception: ' + e.getMessage());
            }
            System.assertEquals(null, paused, 'Paused interview incorrectly retrieved');
        }
        Test.stopTest();
    }
    @IsTest
    private static void retrieveInterviewsTestRN() {
        User testUser = getTestUser(0);
        VCC_Progress_Note__c pn = insertTestPN(testUser);
        List<String> PNID = new List<String>();
        for (VCC_Progress_Note__c notes : [
            SELECT Id
            FROM VCC_Progress_Note__c
            WHERE Id = :pn.Id
            LIMIT 1
        ])
            PNID.add(notes.Id);

        Test.startTest();
        List<String> paused;
        System.runAs(testUser) {
            try {
                paused = VCC_InterviewsByRecordController.retrieveInterviews(PNID);
            } catch (Exception e) {
                Assert.fail('Perm Set Group ' + testUser.Title + ' Unexpected exception: ' + e.getMessage());
            }
        }
        System.assertEquals(null, paused, 'Paused interviews found where none exist');
        Test.stopTest();
    }

    @IsTest
    private static void retrieveInterviewsTestMP() {
        User testUser = getTestUser(1);
        VCC_Progress_Note__c pn = insertTestPN(testUser);
        List<String> PNID = new List<String>();
        for (VCC_Progress_Note__c notes : [
            SELECT Id
            FROM VCC_Progress_Note__c
            WHERE Id = :pn.Id
            LIMIT 1
        ])
            PNID.add(notes.Id);

        Test.startTest();
        List<String> paused;
        System.runAs(testUser) {
            try {
                paused = VCC_InterviewsByRecordController.retrieveInterviews(PNID);
            } catch (Exception e) {
                Assert.fail('Perm Set Group ' + testUser.Title + ' Unexpected exception: ' + e.getMessage());
            }
        }
        System.assertEquals(null, paused, 'Paused interviews found where none exist');
        Test.stopTest();
    }
    @IsTest
    private static void removeInterviewsTestRN() {
        User testUser = getTestUser(0);
        VCC_Progress_Note__c pn = insertTestPN(testUser);
        List<Id> PNID = new List<String>();
        for (VCC_Progress_Note__c notes : [
            SELECT Id
            FROM VCC_Progress_Note__c
            WHERE Id = :pn.Id
            LIMIT 1
        ])
            PNID.add(notes.Id);

        Test.startTest();
        Boolean removed;
        System.runAs(testUser) {
            try {
                removed = VCC_InterviewsByRecordController.removeInterview(PNID.get(0));
            } catch (Exception e) {
                Assert.fail('Perm Set Group ' + testUser.Title + ' Unexpected exception: ' + e.getMessage());
            }
            System.assertEquals(false, removed, 'Removed interviews where none exist');
        }
        Test.stopTest();
    }

    @IsTest
    private static void removeInterviewsTestMP() {
        User testUser = getTestUser(1);
        VCC_Progress_Note__c pn = insertTestPN(testUser);
        List<Id> PNID = new List<String>();
        for (VCC_Progress_Note__c notes : [
            SELECT Id
            FROM VCC_Progress_Note__c
            WHERE Id = :pn.Id
            LIMIT 1
        ])
            PNID.add(notes.Id);

        Test.startTest();
        Boolean removed;
        System.runAs(testUser) {
            try {
                removed = VCC_InterviewsByRecordController.removeInterview(PNID.get(0));
            } catch (Exception e) {
                Assert.fail('Perm Set Group ' + testUser.Title + ' Unexpected exception: ' + e.getMessage());
            }
            System.assertEquals(false, removed, 'Removed interviews where none exist');
        }
        Test.stopTest();
    }
    public static VCC_Progress_Note__c insertTestPNforData(User testUser) {
        Account testAccount = TestUtility.createAccount('testAccount');
        insert testAccount;
        Contact testContact = TestUtility.createContact(testUser.Id, 'lastName', testAccount.Id);
        insert testContact;
        Case testCase = new Case(
            RecordTypeId = Case.SObjectType.getDescribe().getRecordTypeInfosByName().get('Virtual Clinic Visit Case').getRecordTypeId(),
            VCC_Caller_Relation__c = 'Self',
            ContactId = testContact.Id
        );
        insert testCase;
        insert new CaseShare(CaseId = testCase.Id, CaseAccessLevel = 'Edit', UserOrGroupId = testUser.Id);
        VCC_Progress_Note__c pn = new VCC_Progress_Note__c(
            VCC_Case__r = testCase,
            VCC_Case__c = testCase.Id,
            VCC_Relative_Type__c = 'Self',
            VCC_Additional_Comments__c = 'Some additional comment.',
            VCC_Comments_patient_in_crisis__c = 'some long string that will be longer than 80 characters long to demonstrate the line breaking',
            RecordTypeId = Schema.SObjectType.VCC_Progress_Note__c.getRecordTypeInfosByDeveloperName().get('VCC_Virtual_Visit_Progress_Note').getRecordTypeId(),
            VCC_T2T_Assessment_Completed__c = true
        );
        insert pn;
        VCC_Progress_Note_Detail__c note = new VCC_Progress_Note_Detail__c();
        note.VCC_Progress_Note__c = pn.Id;
        note.VCC_T2T_Data__c =
            '[{"Index": 1, "fieldName": "Field1", "id": "Id1", "label": "Label1", "response": "Response1", "review": "Review1"},' +
            '{"Index": 2, "fieldName": "Field2", "id": "Id2", "label": "Label2", "response": "Response2", "review": "Review2"}]';
        insert note;
        return pn;
    }
    @IsTest
    static void testresetT2TDataRN() {
        User testUser = getTestUser(0);
        VCC_Progress_Note__c pn = insertTestPNforData(testUser);
        String recordId = pn.Id;
        Test.startTest();
        VCC_Progress_Note__c pResult;
        VCC_Progress_Note_Detail__c dResult;
        System.runAs(testUser) {
            try {
                VCC_InterviewsByRecordController.resetT2TData(recordId);
                pResult = [
                    SELECT Id, Name, LastModifiedDate, VCC_Signed__c, VCC_Relative_Type__c, VCC_Caller_Name_Text__c, VCC_Caregiver_Name__c, VCC_T2T_Assessment_Completed__c
                    FROM VCC_Progress_Note__c
                    WHERE Id = :recordId
                    LIMIT 1
                ];
                dResult = [
                    SELECT Id, Name, VCC_Progress_Note__c, VCC_T2T_Data__c
                    FROM VCC_Progress_Note_Detail__c
                    WHERE VCC_Progress_Note__c = :recordId
                    LIMIT 1
                ];
            } catch (Exception e) {
                Assert.fail('Perm Set Group ' + testUser.Title + ' Unexpected exception: ' + e.getMessage());
            }
        }
        System.assertEquals(null, dResult.VCC_T2T_Data__c);
        System.assertEquals(false, pResult.VCC_T2T_Assessment_Completed__c);
        Test.stopTest();
    }

    @IsTest
    static void testresetT2TDataMP() {
        User testUser = getTestUser(1);
        VCC_Progress_Note__c pn = insertTestPNforData(testUser);
        String recordId = pn.Id;
        Test.startTest();
        VCC_Progress_Note__c pResult;
        VCC_Progress_Note_Detail__c dResult;
        System.runAs(testUser) {
            try {
                VCC_InterviewsByRecordController.resetT2TData(recordId);
                pResult = [
                    SELECT Id, Name, LastModifiedDate, VCC_Signed__c, VCC_Relative_Type__c, VCC_Caller_Name_Text__c, VCC_Caregiver_Name__c, VCC_T2T_Assessment_Completed__c
                    FROM VCC_Progress_Note__c
                    WHERE Id = :recordId
                    LIMIT 1
                ];
                dResult = [
                    SELECT Id, Name, VCC_Progress_Note__c, VCC_T2T_Data__c
                    FROM VCC_Progress_Note_Detail__c
                    WHERE VCC_Progress_Note__c = :recordId
                    LIMIT 1
                ];
            } catch (Exception e) {
                Assert.fail('Perm Set Group ' + testUser.Title + ' Unexpected exception: ' + e.getMessage());
            }
        }
        System.assertEquals(null, dResult.VCC_T2T_Data__c);
        System.assertEquals(false, pResult.VCC_T2T_Assessment_Completed__c);
        Test.stopTest();
    }
    @IsTest
    private static void testGetFieldValueRN() {
        User testUser = getTestUser(0);
        VCC_Progress_Note__c pn = insertTestPNforData(testUser);

        // Arrange
        List<VCC_Progress_Note__c> recordIds = [
            SELECT Id, VCC_T2T_Assessment_Completed__c
            FROM VCC_Progress_Note__c
            WHERE Id = :pn.Id
            LIMIT 1
        ];
        VCC_Progress_Note__c progressNote = recordIds.get(0);
        // Act
        Test.startTest();
        Boolean fieldValue;
        System.runAs(testUser) {
            try {
                fieldValue = VCC_InterviewsByRecordController.getFieldValue(progressNote.Id);
            } catch (Exception e) {
                Assert.fail('Perm Set Group ' + testUser.Title + ' Unexpected exception: ' + e.getMessage());
            }
        }
        // Assert
        System.assertEquals(progressNote.VCC_T2T_Assessment_Completed__c, fieldValue, 'Field value mismatch');
        Test.stopTest();
    }
    @IsTest
    private static void testGetFieldValueMP() {
        User testUser = getTestUser(1);
        VCC_Progress_Note__c pn = insertTestPNforData(testUser);

        // Arrange
        List<VCC_Progress_Note__c> recordIds = [
            SELECT Id, VCC_T2T_Assessment_Completed__c
            FROM VCC_Progress_Note__c
            WHERE Id = :pn.Id
            LIMIT 1
        ];
        VCC_Progress_Note__c progressNote = recordIds.get(0);
        // Act
        Test.startTest();
        Boolean fieldValue;
        System.runAs(testUser) {
            try {
                fieldValue = VCC_InterviewsByRecordController.getFieldValue(progressNote.Id);
            } catch (Exception e) {
                Assert.fail('Perm Set Group ' + testUser.Title + ' Unexpected exception: ' + e.getMessage());
            }
        }
        // Assert
        System.assertEquals(progressNote.VCC_T2T_Assessment_Completed__c, fieldValue, 'Field value mismatch');
        Test.stopTest();
    }
}