force-app/main/default/objects/VCC_Appointment_Batch_Delete_Config__mdt/VCC_Appointment_Batch_Delete_Config__mdt.object-meta.xml
<CustomObject>
    <description>Configuration used for Scheduled Batch Class to clean up stale Appointment and Appointment Request records.</description>
    <label>VCC Appointment Batch Delete Config</label>
    <pluralLabel>VCC Appointment Batch Delete Configs</pluralLabel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Appointment_Batch_Delete_Config__mdt/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <description>Variable to set the number of records per batch.</description>
    <label>Batch Size</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VCC_Appointment_Batch_Delete_Config__mdt/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>Class name passed as a string via callable.</description>
    <label>Class Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Appointment_Batch_Delete_Config__mdt/fields/Number_of_Days_for_Closed_Reqs__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Days_for_Closed_Reqs__c</fullName>
    <description>Used to calculate number of days in the past, to delete Closed Appointment Request records older than that.</description>
    <label>Number of Days for Closed Reqs</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VCC_Appointment_Batch_Delete_Config__mdt/fields/Number_of_Hours_for_Appts_and_Open_Reqs__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Hours_for_Appts_and_Open_Reqs__c</fullName>
    <description>Used to calculate number of hours in the past, to delete records older than that.
Value is used for query for and delete Appointment records and Appointment Request records that are not closed.</description>
    <label>Number of Hours for Appts and Open Reqs</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VCC_Appointment_Batch_Delete_Config__mdt/fields/Run_Batch__c.field-meta.xml
<CustomField>
    <fullName>Run_Batch__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Switch that can be used to run or not run batch class from Schedulable.
Job can remain scheduled, but this field can be set to false if you don&apos;t want it to run temporarily.</description>
    <label>Run Batch</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/classes/VCC/VCC_AppointmentDataSchedulableTest.cls
/**
 * @description Test class for VCC_AppointmentDataSchedulable
 * @author Booz Allen Hamilton
 * @see VCC_AppointmentDataSchedulable
 */
@IsTest
private class VCC_AppointmentDataSchedulableTest {
    final static User ADMIN = new VATEST_UserBuilder()
        .withUserProfile('System Administrator')
        .withStandardData()
        .build(true);
    private static final VCC_Appointment_Batch_Delete_Config__mdt TEST_CONFIG;

    static {
        TEST_CONFIG = new VCC_Appointment_Batch_Delete_Config__mdt(
            Class_Name__c = 'VCC_AppointmentDataBatchDelete',
            Run_Batch__c = true,
            Number_of_Hours_for_Appts_and_Open_Reqs__c = 24,
            Number_of_Days_for_Closed_Reqs__c = 7,
            Batch_Size__c = 2000
        );
    }

    /**
     * @description Test to confirm a job is scheduled using the TEST_CONFIG custom metadata.
     */
    @IsTest
    private static void funcSchedulablePositive() {
        VCC_AppointmentDataSchedulable schedulableInstance = new VCC_AppointmentDataSchedulable();
        schedulableInstance.batchParameters = TEST_CONFIG;
        String jobName = 'VCC_AppointmentDataBatchDelete';
        String cronExpression = '0 0 1 * * ?';

        Test.startTest();
        System.runAs(ADMIN) {
            System.schedule(jobName, cronExpression, schedulableInstance);
        }
        Test.stopTest();

        List<CronTrigger> scheduledJobs = [SELECT Id FROM CronTrigger WHERE CronJobDetail.Name = :jobName];
        Assert.areEqual(
            1,
            scheduledJobs.size(),
            'Expected one job to be scheduled from System.schedule but observed a different result.'
        );
    }
}