force-app/main/default/objects/VCC_CRM_VISN_Service_Assignment__c/VCC_CRM_VISN_Service_Assignment__c.object-meta.xml
<CustomObject>
    <description>This object assigns a Service to a VISN.</description>
    <label>CRM Service VISN Assignment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>CRM Service VISN Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRM Service VISN Assignment</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Service_User_Assignment__c/VCC_Service_User_Assignment__c.object-meta.xml
<CustomObject>
    <description>The Service User Assignment object is a junction object that connects a SOT User to a CRM Service VISN Assignment.</description>
    <label>Service User Assignment</label>
    <nameField>
        <displayFormat>SUA-{0000}</displayFormat>
        <label>Service User Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service User Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VCC_Service_User_Assignment__c/fields/VCC_CRM_VISN_Service_Assignment__c.field-meta.xml
<CustomField>
    <fullName>VCC_CRM_VISN_Service_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A lookup field to connect the Service User Assignment to the CRM Service VISN Assignment for which the SUA is associated.</description>
    <label>CRM Service VISN Assignment</label>
    <referenceTo>VCC_CRM_VISN_Service_Assignment__c</referenceTo>
    <relationshipLabel>Service User Assignments</relationshipLabel>
    <relationshipName>Service_User_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCC_Service_User_Assignment__c/fields/VCC_SOT_User__c.field-meta.xml
<CustomField>
    <fullName>VCC_SOT_User__c</fullName>
    <description>A master detail relationship field connecting the Service User Assignment to the SOT User for which the Service User Assignment was created.</description>
    <label>SOT User</label>
    <referenceTo>VCC_SOT_User__c</referenceTo>
    <relationshipLabel>Service User Assignments</relationshipLabel>
    <relationshipName>Service_User_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/main/default/objects/VCC_SOT_User__c/VCC_SOT_User__c.object-meta.xml
<CustomObject>
    <description>The SOT User object holds the information for the users being tracked with the VAHC Service Onboarding Tracker application.</description>
    <label>SOT User</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SOT User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SOT Users</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/main/default/classes/VCC/VCC_SOT_ServiceUserAssignTriggerHandler.cls
/**
 * @description VCC_SOT_ServiceUserAssignTriggerhandler is for the VAHC Service Onboarding Tracker App to search for existing
 * Service User Assignments by checking for existing records with matching fields CRM Service VISN Assignment and SOT User
 */
public with sharing class VCC_SOT_ServiceUserAssignTriggerHandler {
    /**
     * @description dupSUAError is called by the VCC_SOT_ServiceUserAssignmentTrigger
     * @param newTrigSUA
     */
    public static void dupSUAError(List<VCC_Service_User_Assignment__c> newTrigSUA) {
        List<VCC_Service_User_Assignment__c> allSUAs = [
            SELECT Id, Name, VCC_CRM_VISN_Service_Assignment__c, VCC_SOT_User__c
            FROM VCC_Service_User_Assignment__c
            WITH SECURITY_ENFORCED
            LIMIT 10000
        ];

        for (VCC_Service_User_Assignment__c oneSUATrig : newTrigSUA) {
            for (Integer i = 0; i < allSUAs.size(); i++) {
                if (oneSUATrig.VCC_CRM_VISN_Service_Assignment__c == allSUAs[i].VCC_CRM_VISN_Service_Assignment__c && oneSUATrig.VCC_SOT_User__c == allSUAs[i].VCC_SOT_User__c) {
                    oneSUATrig.addError('This Service User Assignment already exists. Please use the existing record.');
                }
            }
        }
    }
}