force-app/main/default/objects/VCC_Progress_Note_Configuration__mdt/VCC_Progress_Note_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>Used for identifying what Attributes belong to a particular Progress Note or Addendum Type.</description>
    <label>VCC Progress Note Configuration</label>
    <pluralLabel>Progress Note Configurations</pluralLabel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Progress_Note_Configuration__mdt/fields/VCC_Creates_Encounter__c.field-meta.xml
<CustomField>
    <fullName>VCC_Creates_Encounter__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Creates Encounter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note_Configuration__mdt/fields/VCC_Emphasized_Sections__c.field-meta.xml
<CustomField>
    <fullName>VCC_Emphasized_Sections__c</fullName>
    <inlineHelpText>Progress Note sections specified here will stand out from the rest on the &apos;Review and Sign&apos; step of the Progress Note flow.</inlineHelpText>
    <label>Emphasized Sections</label>
    <type>TextArea</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note_Configuration__mdt/fields/VCC_Enable_Primary_Diagnosis__c.field-meta.xml
<CustomField>
    <fullName>VCC_Enable_Primary_Diagnosis__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Primary Diagnosis</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note_Configuration__mdt/fields/VCC_Enable_Procedure_Code__c.field-meta.xml
<CustomField>
    <fullName>VCC_Enable_Procedure_Code__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Procedure Code</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note_Configuration__mdt/fields/VCC_Enable_Secondary_Diagnosis__c.field-meta.xml
<CustomField>
    <fullName>VCC_Enable_Secondary_Diagnosis__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Secondary Diagnosis</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note_Configuration__mdt/fields/VCC_Enable_Visit_Related_Tos__c.field-meta.xml
<CustomField>
    <fullName>VCC_Enable_Visit_Related_Tos__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Visit Related Tos</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note_Configuration__mdt/fields/VCC_Excluded_Page_Layout_Sections__c.field-meta.xml
<CustomField>
    <fullName>VCC_Excluded_Page_Layout_Sections__c</fullName>
    <defaultValue>&quot;Custom Links&quot;&amp;&quot;,&quot;&amp; &quot;Information&quot;&amp;&quot;,&quot;&amp; &quot;System Information&quot;</defaultValue>
    <label>Excluded Page Layout Sections</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note_Configuration__mdt/fields/VCC_Include_Layout_Spaces__c.field-meta.xml
<CustomField>
    <fullName>VCC_Include_Layout_Spaces__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allows blank spaces to be included during the write note process</description>
    <label>Include Layout Spaces</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note_Configuration__mdt/fields/VCC_Page_Layout_Name__c.field-meta.xml
<CustomField>
    <fullName>VCC_Page_Layout_Name__c</fullName>
    <label>Page Layout Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note_Configuration__mdt/fields/VCC_Personas__c.field-meta.xml
<CustomField>
    <fullName>VCC_Personas__c</fullName>
    <label>Personas</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note_Configuration__mdt/fields/VCC_Record_Type_API_Name__c.field-meta.xml
<CustomField>
    <fullName>VCC_Record_Type_API_Name__c</fullName>
    <label>Record Type API Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note_Configuration__mdt/fields/VCC_VistA_Note_Title__c.field-meta.xml
<CustomField>
    <fullName>VCC_VistA_Note_Title__c</fullName>
    <inlineHelpText>This name should be an exact match of the name in &apos;Location to Note IEN Mapping&apos; custom setting.</inlineHelpText>
    <label>VistA Note Title</label>
    <length>120</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VCC/VCC_ProgressNoteConfigSelector.cls
public with sharing class VCC_ProgressNoteConfigSelector extends fflib_SObjectSelector {
    private List<Schema.SObjectField> sObjectFields = new List<Schema.SObjectField>{
        VCC_Progress_Note_Configuration__mdt.VCC_Creates_Encounter__c,
        VCC_Progress_Note_Configuration__mdt.VCC_Enable_Visit_Related_Tos__c,
        VCC_Progress_Note_Configuration__mdt.VCC_Enable_Primary_Diagnosis__c,
        VCC_Progress_Note_Configuration__mdt.VCC_Enable_Secondary_Diagnosis__c,
        VCC_Progress_Note_Configuration__mdt.VCC_Enable_Procedure_Code__c,
        VCC_Progress_Note_Configuration__mdt.VCC_Emphasized_Sections__c,
        VCC_Progress_Note_Configuration__mdt.VCC_Excluded_Page_Layout_Sections__c,
        VCC_Progress_Note_Configuration__mdt.VCC_Include_Layout_Spaces__c,
        VCC_Progress_Note_Configuration__mdt.VCC_Page_Layout_Name__c,
        VCC_Progress_Note_Configuration__mdt.VCC_Personas__c,
        VCC_Progress_Note_Configuration__mdt.VCC_Record_Type_API_Name__c,
        VCC_Progress_Note_Configuration__mdt.VCC_VistA_Note_Title__c
    };

    public Schema.SObjectType getSObjectType() {
        return VCC_Progress_Note_Configuration__mdt.SObjectType;
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return this.sObjectFields;
    }

    public void addSObjectFields(List<Schema.SObjectField> sObjectFields) {
        if (sObjectFields != null && !sObjectFields.isEmpty()) {
            for (Schema.SObjectField field : sObjectFields) {
                if (!this.sObjectFields.contains(field)) {
                    this.sObjectFields.add(field);
                }
            }
        }
    }

    public List<VCC_Progress_Note_Configuration__mdt> selectByIds(Set<Id> ids) {
        return (List<VCC_Progress_Note_Configuration__mdt>) selectSObjectsById(ids);
    }

    public VCC_Progress_Note_Configuration__mdt selectByRecordTypeAPIName(String recTypeName) {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('VCC_Record_Type_API_Name__c = :recTypeName');
        List<VCC_Progress_Note_Configuration__mdt> configs = Database.query(query.toSOQL());
        return (configs != null && configs.size() == 1) ? configs[0] : null;
    }

    public VCC_Progress_Note_Configuration__mdt selectByName(String name) {
        return VCC_Progress_Note_Configuration__mdt.getInstance(name);
    }
}