force-app/main/default/objects/VCC_Org_Settings__mdt/VCC_Org_Settings__mdt.object-meta.xml
<CustomObject>
    <description>This is used to map the various orgs to a specific Org Setting name. Used for mapping specific Sandbox to a particular API integration.</description>
    <label>VCC Org Settings</label>
    <pluralLabel>VCC Org Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/VCC_Org_Settings__mdt/fields/vccOrgId__c.field-meta.xml
<CustomField>
    <fullName>vccOrgId__c</fullName>
    <label>Org Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/VCC_Org_Settings__mdt/fields/vccType__c.field-meta.xml
<CustomField>
    <fullName>vccType__c</fullName>
    <inlineHelpText>DEV, QA, STAGING, PROD</inlineHelpText>
    <label>Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VCC/VCC_OAuthUtility.cls
/**
 * @deprecated Replaced by a managed package.
 */
public without sharing class VCC_OAuthUtility {
    // Get Access Token for User's current oAuth Session
    @AuraEnabled
    public static string getAccessToken(string AuthProviderName) {
        try {
            String accessToken = Auth.AuthToken.getAccessToken(getAuthProvider(AuthProviderName).Id, getAuthProvider(AuthProviderName).FriendlyName);
            return accessToken;
        } catch (Exception ex) {
            Log.debug(string.ValueOf(ex));
            return null;
        }
    }

    // Get Access Token for User's current oAuth Session
    @AuraEnabled
    public static Map<String, String> getRefreshToken(string AuthProviderName) {
        try {
            Map<String, String> refreshToken = Auth.AuthToken.refreshAccessToken(
                getAuthProvider(AuthProviderName).Id,
                getAuthProvider(AuthProviderName).FriendlyName,
                getAccessToken(authProviderName)
            );
            return refreshToken;
        } catch (Exception ex) {
            Log.debug(string.ValueOf(ex));
            if (Test.isRunningTest()) {
                return new Map<String, String>();
            }
            return null;
        }
    }

    @InvocableMethod(category='Auth')
    public static List<String> getVARefreshToken() {
        Map<String, String> refreshToken = getRefreshToken('VA SSOi');
        List<String> returnOfTheStrings = new List<String>();

        if (refreshToken.get('RefreshError') != null) {
            returnOfTheStrings.add(refreshToken.get('RefreshError'));
        } else {
            returnOfTheStrings.add(refreshToken.get('AccessToken'));
        }
        return returnOfTheStrings;
    }
    /*
    @AuraEnabled
    public static string getOrgType() {
    // Get Org Type from Custom Metadata
    String orgType = [SELECT Id, vccType__c FROM VCC_Org_Settings__mdt WHERE vccOrgId__c =: UserInfo.getOrganizationId()].vccType__c;
    return orgType;
    }
    */

    @AuraEnabled
    public static AuthProvider getAuthProvider(string AuthProviderName) {
        /* Get Auth Provider
        AuthProvider authProvider = [SELECT Id, DeveloperName, FriendlyName FROM AuthProvider WHERE DeveloperName =: AuthProviderName + '_' + getOrgType()];
        The line above was previously used, but since each org will have the same AuthProvider name we are removing the suffix.
        */
        AuthProvider authProvider;
        List<AuthProvider> authProviders = [SELECT Id, DeveloperName, FriendlyName FROM AuthProvider WHERE DeveloperName = :AuthProviderName WITH SECURITY_ENFORCED];
        if (!authProviders.isEmpty()) {
            authProvider = authProviders[0];
        }
        if (Test.isRunningTest()) {
            authProvider = new AuthProvider();
        }
        return authProvider;
        //AuthProvider authProvider = [SELECT Id, DeveloperName, FriendlyName FROM AuthProvider WHERE DeveloperName =: AuthProviderName];
        //return authProvider;
    }
}