force-app/main/default/objects/VCC_Org_Settings__mdt/VCC_Org_Settings__mdt.object-meta.xml
<CustomObject>
    <description>This is used to map the various orgs to a specific Org Setting name. Used for mapping specific Sandbox to a particular API integration.</description>
    <label>VCC Org Settings</label>
    <pluralLabel>VCC Org Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/VCC_Org_Settings__mdt/fields/vccType__c.field-meta.xml
<CustomField>
    <fullName>vccType__c</fullName>
    <inlineHelpText>DEV, QA, STAGING, PROD</inlineHelpText>
    <label>Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Site_Specific_Configuration__mdt/VCC_Site_Specific_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>Manage VistA Site specific configurations. Like VDIF or DAS for Sign Note for a given site.</description>
    <label>VCC Site Specific Configuration</label>
    <pluralLabel>VCC Site Specific Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/VCC_Site_Specific_Configuration__mdt/fields/VCC_VistA_Integration__c.field-meta.xml
<CustomField>
    <fullName>VCC_VistA_Integration__c</fullName>
    <description>Integration service used for the signing of Progress Notes to VistA.</description>
    <inlineHelpText>Integration service used for the signing of Progress Notes to VistA.</inlineHelpText>
    <label>VistA Integration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VDIF</fullName>
                <default>true</default>
                <label>VDIF</label>
            </value>
            <value>
                <fullName>DAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VCC/DAS/VCC_DASControllerTest.cls
@IsTest
public with sharing class VCC_DASControllerTest {
    @IsTest
    static void getSiteIntegrationTypeTestHappy() {
        VCC_DASStub metadataStub = new VCC_DASStub(VCC_DASServiceMetadata.class);
        VCC_DAS.SERVICES.metadataService = (VCC_DASServiceMetadata) metadataStub.instance;

        String testIntegrationType = 'DAS';

        VCC_Org_Settings__mdt testOrgSettings = new VCC_Org_Settings__mdt(vccType__c = 'SOME VALUE');
        VCC_Site_Specific_Configuration__mdt testSiteConfiguration = new VCC_Site_Specific_Configuration__mdt(
            VCC_VistA_Integration__c = testIntegrationType
        );

        metadataStub.setReturnValue('getOrgSettings', testOrgSettings);
        metadataStub.setReturnValue('getSiteSpecificConfiguration', testSiteConfiguration);

        Test.startTest();
        try {
            String integrationType = VCC_DASController.getSiteIntegrationType(123);
            Assert.areEqual(testIntegrationType, integrationType, 'Expected correct IntegrationType value.');
        } catch (Exception e) {
            Assert.fail('Unexpected exception: ' + e.getMessage() + e.getStackTraceString());
        }
        Test.stopTest();

        metadataStub.assertInvoked('getOrgSettings');
        metadataStub.assertInvoked('getSiteSpecificConfiguration');
    }

    @IsTest
    static void getSiteIntegrationTypeTestSadDasException() {
        VCC_DASStub metadataStub = new VCC_DASStub(VCC_DASServiceMetadata.class);
        VCC_DAS.SERVICES.metadataService = (VCC_DASServiceMetadata) metadataStub.instance;

        String testIntegrationType = 'DAS';

        VCC_Org_Settings__mdt testOrgSettings = new VCC_Org_Settings__mdt(vccType__c = 'SOME VALUE');
        VCC_Site_Specific_Configuration__mdt testSiteConfiguration = new VCC_Site_Specific_Configuration__mdt(
            VCC_VistA_Integration__c = testIntegrationType
        );

        metadataStub.setException('getOrgSettings', new VCC_DASController.GetSiteIntegrationTypeException());
        metadataStub.setReturnValue('getSiteSpecificConfiguration', testSiteConfiguration);

        Test.startTest();
        try {
            String integrationType = VCC_DASController.getSiteIntegrationType(123);
            Assert.fail('Expected an exception');
        } catch (Exception e) {
            Assert.isInstanceOfType(e, VCC_DASException.class, 'Expected VCC_DASException');
        }
        Test.stopTest();

        metadataStub.assertInvoked('getOrgSettings');
        metadataStub.assertNotInvoked('getSiteSpecificConfiguration');
    }

    @IsTest
    static void getSiteIntegrationTypeTestSadOtherException() {
        VCC_DASStub metadataStub = new VCC_DASStub(VCC_DASServiceMetadata.class);
        VCC_DAS.SERVICES.metadataService = (VCC_DASServiceMetadata) metadataStub.instance;

        String testIntegrationType = 'DAS';

        VCC_Org_Settings__mdt testOrgSettings = new VCC_Org_Settings__mdt(vccType__c = 'SOME VALUE');
        VCC_Site_Specific_Configuration__mdt testSiteConfiguration = new VCC_Site_Specific_Configuration__mdt(
            VCC_VistA_Integration__c = testIntegrationType
        );

        metadataStub.setException('getOrgSettings', new NullPointerException());
        metadataStub.setReturnValue('getSiteSpecificConfiguration', testSiteConfiguration);

        Test.startTest();
        try {
            String integrationType = VCC_DASController.getSiteIntegrationType(123);
            Assert.fail('Expected an exception');
        } catch (Exception e) {
            Assert.isInstanceOfType(e, VCC_DASException.class, 'Expected VCC_DASException');
        }
        Test.stopTest();

        metadataStub.assertInvoked('getOrgSettings');
        metadataStub.assertNotInvoked('getSiteSpecificConfiguration');
    }

    @IsTest
    static void unitSelectPatientPositive() {
        VCC_DASStub apiStub = new VCC_DASStub(VCC_DASServiceApi.class);
        VCC_DAS.SERVICES.apiService = (VCC_DASServiceApi) apiStub.instance;

        List<VCC_DASSelectPatientRS> selectPatientRsList = new List<VCC_DASSelectPatientRS>();
        VCC_DASSelectPatientRS selectPatientRs = new VCC_DASSelectPatientRS();
        selectPatientRs.patientTO = new VCC_DASSelectPatientRS.PatientTO();
        selectPatientRsList.add(selectPatientRs);

        apiStub.setReturnValue('selectPatient', selectPatientRsList);

        VCC_DASController.SelectPatientInput selectPatientInput = new VCC_DASController.SelectPatientInput();
        selectPatientInput.providerLoginSiteCode = '123';

        Test.startTest();
        try {
            VCC_DASController.selectPatient(selectPatientInput);
        } catch (Exception thrownException) {
            Assert.fail(
                'Unexpected exception: ' + thrownException.getMessage() + thrownException.getStackTraceString()
            );
        }
        Test.stopTest();

        apiStub.assertInvoked('selectPatient');
    }

    @IsTest
    static void unitSelectPatientDasExceptionNegative() {
        VCC_DASStub apiStub = new VCC_DASStub(VCC_DASServiceApi.class);
        VCC_DAS.SERVICES.apiService = (VCC_DASServiceApi) apiStub.instance;

        apiStub.setException('selectPatient', new VCC_DASController.SelectPatientException('test'));

        VCC_DASController.SelectPatientInput selectPatientInput = new VCC_DASController.SelectPatientInput();
        selectPatientInput.providerLoginSiteCode = '123';

        Test.startTest();
        try {
            VCC_DASController.selectPatient(selectPatientInput);
            Assert.fail('Expected and exception');
        } catch (VCC_DASException dasException) {
            Assert.isTrue(true, 'Caught exception. Test passes.');
        }
        Test.stopTest();

        apiStub.assertInvoked('selectPatient');
    }

    @IsTest
    static void unitSelectPatientOtherExceptionNegative() {
        VCC_DASStub apiStub = new VCC_DASStub(VCC_DASServiceApi.class);
        VCC_DAS.SERVICES.apiService = (VCC_DASServiceApi) apiStub.instance;

        apiStub.setException('selectPatient', new NullPointerException());

        VCC_DASController.SelectPatientInput selectPatientInput = new VCC_DASController.SelectPatientInput();
        selectPatientInput.providerLoginSiteCode = '123';

        Test.startTest();
        try {
            VCC_DASController.selectPatient(selectPatientInput);
            Assert.fail('Expected and exception');
        } catch (VCC_DASException dasException) {
            Assert.isTrue(true, 'Caught exception. Test passes.');
        }
        Test.stopTest();

        apiStub.assertInvoked('selectPatient');
    }
}