force-app/main/default/objects/VCC_Org_Settings__mdt/VCC_Org_Settings__mdt.object-meta.xml
<CustomObject>
    <description>This is used to map the various orgs to a specific Org Setting name. Used for mapping specific Sandbox to a particular API integration.</description>
    <label>VCC Org Settings</label>
    <pluralLabel>VCC Org Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/VCC_Progress_Note_Configuration__mdt/VCC_Progress_Note_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>Used for identifying what Attributes belong to a particular Progress Note or Addendum Type.</description>
    <label>VCC Progress Note Configuration</label>
    <pluralLabel>Progress Note Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/VCC_Progress_Note_Configuration__mdt/fields/VCC_Record_Type_API_Name__c.field-meta.xml
<CustomField>
    <fullName>VCC_Record_Type_API_Name__c</fullName>
    <label>Record Type API Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note_Custom_Section__mdt/VCC_Progress_Note_Custom_Section__mdt.object-meta.xml
<CustomObject>
    <description>Used for defining custom sections as part of Progress Notes</description>
    <label>VCC Progress Note Custom Section</label>
    <pluralLabel>VCC Progress Note Custom Sections</pluralLabel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Progress_Note_Custom_Section__mdt/fields/VCC_Progress_Note_Configuration__c.field-meta.xml
<CustomField>
    <fullName>VCC_Progress_Note_Configuration__c</fullName>
    <label>Progress Note Configuration</label>
    <referenceTo>VCC_Progress_Note_Configuration__mdt</referenceTo>
    <relationshipLabel>Custom Sections</relationshipLabel>
    <relationshipName>VCC_Progress_Note_Custom_Sections</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Site_Specific_Configuration__mdt/VCC_Site_Specific_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>Manage VistA Site specific configurations. Like VDIF or DAS for Sign Note for a given site.</description>
    <label>VCC Site Specific Configuration</label>
    <pluralLabel>VCC Site Specific Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/VCC_Site_Specific_Configuration__mdt/fields/VCC_SiteID__c.field-meta.xml
<CustomField>
    <fullName>VCC_SiteID__c</fullName>
    <description>VistA SiteID</description>
    <label>SiteID</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VCC_Site_Specific_Configuration__mdt/fields/VCC_VistA_Environment__c.field-meta.xml
<CustomField>
    <fullName>VCC_VistA_Environment__c</fullName>
    <description>VCC Org Settings related Org ID Type</description>
    <label>VistA Environment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PRODUCTION</fullName>
            </value>
            <value>
                <fullName>Pre-Production</fullName>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
            <value>
                <fullName>Dev</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VCC/DAS/VCC_DASServiceMetadataTest.cls
@IsTest
public with sharing class VCC_DASServiceMetadataTest {
    @IsTest
    static void getConfigurationTest() {
        String recordTypeApiName;
        try {
            List<VCC_Progress_Note_Configuration__mdt> configList = VCC_Progress_Note_Configuration__mdt.getAll()
                .values();
            recordTypeApiName = configList[0].VCC_Record_Type_API_Name__c;
        } catch (Exception e) {
            //NOPMD
            //do nothing
        }
        Test.startTest();
        try {
            VCC_Progress_Note_Configuration__mdt resultingConfig = VCC_DAS.SERVICES.METADATA.getConfiguration(
                recordTypeApiName
            );
            if (recordTypeApiName == null) {
                Assert.isNull(resultingConfig, 'Expected null return value.');
            } else {
                Assert.isNotNull(resultingConfig, 'Expected non-null return value.');
            }
        } catch (Exception e) {
            Assert.fail('Unexpected exception: ' + e.getMessage() + '\n' + e.getStackTraceString());
        }
        Test.stopTest();
    }

    @IsTest
    static void getCustomSectionsTest() {
        VCC_Progress_Note_Custom_Section__mdt customSection;
        try {
            customSection = [
                SELECT Id, VCC_Progress_Note_Configuration__c
                FROM VCC_Progress_Note_Custom_Section__mdt
                LIMIT 1
            ][0];
        } catch (Exception e) {
            //NOPMD
            //do nothing
        }

        Test.startTest();
        try {
            List<VCC_Progress_Note_Custom_Section__mdt> customSectionList = VCC_DAS.SERVICES.METADATA.getCustomSections(
                new VCC_Progress_Note_Configuration__mdt(Id = customSection?.VCC_Progress_Note_Configuration__c)
            );
            Assert.isNotNull(customSectionList, 'Expected non-null return value.');
            if (customSectionList.size() > 0) {
                Boolean hasSection = false;
                for (VCC_Progress_Note_Custom_Section__mdt cs : customSectionList) {
                    if (cs.Id == customSection.Id) {
                        hasSection = true;
                    }
                }
                Assert.isTrue(hasSection, 'Expected to find the custom section.');
            }
        } catch (Exception e) {
            if (customSection?.VCC_Progress_Note_Configuration__c != null) {
                Assert.fail('Unexpected exception: ' + e.getMessage() + '\n' + e.getStackTraceString());
            }
        }
        Test.stopTest();
    }

    @IsTest
    static void getOrgSettingsTest() {
        Test.startTest();
        try {
            VCC_Org_Settings__mdt orgSettings = VCC_DAS.SERVICES.METADATA.getOrgSettings();
        } catch (Exception e) {
            Assert.fail('Unexpected exception: ' + e.getMessage() + e.getStackTraceString());
        }
        Test.stopTest();
    }

    @IsTest
    static void getSiteSpecificConfigurationTest() {
        Map<String, VCC_Site_Specific_Configuration__mdt> siteConfigMap = VCC_Site_Specific_Configuration__mdt.getAll();

        Test.startTest();
        try {
            if (siteConfigMap != null && !siteConfigMap.isEmpty()) {
                VCC_Site_Specific_Configuration__mdt testSiteConfig = siteConfigMap.values()[0];
                VCC_Site_Specific_Configuration__mdt actualSiteConfig = VCC_DAS.SERVICES.METADATA.getSiteSpecificConfiguration(
                    Integer.valueOf(testSiteConfig.VCC_SiteID__c),
                    testSiteConfig.VCC_VistA_Environment__c
                );
                Assert.isNotNull(actualSiteConfig, 'Expected a value.');
            }
        } catch (Exception e) {
            Assert.fail('Unexpected exception: ' + e.getMessage() + e.getStackTraceString());
        }
        Test.stopTest();
    }
}