force-app/main/default/objects/VCC_Org_Settings__mdt/VCC_Org_Settings__mdt.object-meta.xml
<CustomObject>
    <description>This is used to map the various orgs to a specific Org Setting name. Used for mapping specific Sandbox to a particular API integration.</description>
    <label>VCC Org Settings</label>
    <pluralLabel>VCC Org Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/VCC_Org_Settings__mdt/fields/vccOrgId__c.field-meta.xml
<CustomField>
    <fullName>vccOrgId__c</fullName>
    <label>Org Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/VCC_Org_Settings__mdt/fields/vccType__c.field-meta.xml
<CustomField>
    <fullName>vccType__c</fullName>
    <inlineHelpText>DEV, QA, STAGING, PROD</inlineHelpText>
    <label>Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/vccEndpoint__mdt/vccEndpoint__mdt.object-meta.xml
<CustomObject>
    <description>This custom metadata type is used to store endpoints (ie. trailing path information) that, when combined with a Named Credential, will form a complete URL:
        {host}/{endpoint}</description>
    <label>Endpoint</label>
    <pluralLabel>Endpoints</pluralLabel>
</CustomObject>

sfdx-source/main/default/classes/VCC/VCC_EndpointUtility.cls
/**
 * @description An Apex Class which provides convenience operations for handling endpoints.
 * @author Unspecified
 * @since Unspecified
 * @group Helpers/Utilities
 */
public inherited sharing class VCC_EndpointUtility {
    /**
     * @description Generate map of field names to their Help Text value stored in custom metadata type.
     * @param appName Application Name
     * @param serviceName Service Name
     * @return A string representing the endpoint URL for the named credential.
     **/
    @SuppressWarnings('PMD.ApexCRUDViolation') // Suppress PMD warning for Organization query.
    public static String getEndpoint(String appName, String serviceName) {
        // Get Org Type from Custom Metadata. If test is running, bypass query and set orgType to DEV
        String orgType;

        // Scratch Org support
        Organization org = [
            SELECT IsSandbox, TrialExpirationDate
            FROM Organization
        ];
        Boolean isScratchOrg = org.IsSandbox && org.TrialExpirationDate != null;
        //Boolean isTrialOrg = !org.IsSandbox && org.TrialExpirationDate != null;

        if (Test.isRunningTest() || isScratchOrg) {
            orgType = 'QA';
        } else {
            orgType = [
                SELECT Id, vccType__c
                FROM VCC_Org_Settings__mdt
                WHERE vccOrgId__c = :UserInfo.getOrganizationId()
                WITH SECURITY_ENFORCED
            ]
            .vccType__c;
        }

        // Get Path from Custom Metadata
        String endpoint = [
            SELECT Id, DeveloperName, Path__c
            FROM vccEndpoint__mdt
            WHERE DeveloperName = :serviceName
            WITH SECURITY_ENFORCED
        ]
        .Path__c;

        // Construct Named Credential
        String namedCredential = constructNamedCredential(orgType, appName);

        // Test all Named Credential Org Types
        if (Test.isRunningTest()) {
            namedCredential = constructNamedCredential('SCRATCH', appName);
            namedCredential = constructNamedCredential('DEV', appName);
            namedCredential = constructNamedCredential('QA', appName);
            namedCredential = constructNamedCredential('STAGING', appName);
            namedCredential = constructNamedCredential('PRODUCTION', appName);
            namedCredential = constructNamedCredential('OTHER', appName);
        }

        // Construct URL
        return 'callout:' + namedCredential + '/' + endpoint;
    }

    /**
     * @description Generate map of field names to their Help Text value stored in custom metadata type
     * @param namedCred Named Credential
     * @return A string URL for given named credential
     **/
    public static String getUrlForNamedCredential(String namedCred) {
        String namedCredName = namedCred.substringAfter(':').substringBefore('/');
        String path = namedCred.substringAfter(':').substringAfter('/');
        return [
                SELECT Endpoint
                FROM NamedCredential
                WHERE DeveloperName = :namedCredName
                LIMIT 1
            ]
            .Endpoint +
            '/' +
            path;
    }

    /**
     * @description Generate map of field names to their Help Text value stored in custom metadata type
     * @param orgType Organization Type
     * @param appName Application Name
     * @return A string representing the constructed named credential for given org type and application name.
     **/
    public static String constructNamedCredential(String orgType, String appName) {
        if (orgType == 'DEV') {
            return 'vcc' + appName + '_dev';
        } else if (orgType == 'QA') {
            return 'vcc' + appName + '_qa';
        } else if (orgType == 'STAGING') {
            // not sure what to call this
            return 'vcc' + appName + '_staging';
        } else if (orgType == 'PRODUCTION') {
            return 'vcc' + appName + '_prod';
        } else if (orgType == 'SCRATCH') {
            return '';
        } else {
            return 'vcc' + appName + '_dev'; // Default to "DEV" if input param isn't recognized
        }
    }
}