force-app/main/default/objects/VCC_Org_Settings__mdt/VCC_Org_Settings__mdt.object-meta.xml
<CustomObject>
    <description>This is used to map the various orgs to a specific Org Setting name. Used for mapping specific Sandbox to a particular API integration.</description>
    <label>VCC Org Settings</label>
    <pluralLabel>VCC Org Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/VCC_Org_Settings__mdt/fields/vccOrgId__c.field-meta.xml
<CustomField>
    <fullName>vccOrgId__c</fullName>
    <label>Org Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sfdx-source/main/default/classes/VCR/VCR_SSOMockingRepo.cls
/**
 * @description This class provides methods to fetch organization settings.
 *              The metadata has a field that is a boolean indicating
 *              whether Enable SSO Mocking should be used.
 *
 */
public virtual inherited sharing class VCR_SSOMockingRepo {
    /**
     * @description
     * @param orgId
     * @return      `List<SObject>`
     */
    public List<VCC_Org_Settings__mdt> fetchByOrgId(Id orgId) {
        for (VCC_Org_Settings__mdt orgSetting : VCC_Org_Settings__mdt.getAll().values()) {
            if (orgSetting.vccOrgId__c == orgId) {
                return new List<VCC_Org_Settings__mdt>{ orgSetting };
            }
        }
        return new List<VCC_Org_Settings__mdt>();
    }
}