sfdx-source/main/default/objects/PC_User__c/PC_User__c.object-meta.xml
<CustomObject>
    <description>This object will hold information about the location of the FLPs and Specialists.</description>
    <label>PrC User</label>
    <nameField>
        <displayFormat>PCUser-{0000000000}</displayFormat>
        <label>PrC User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrC Users</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/PC_User__c/fields/Current_Location__c.field-meta.xml
<CustomField>
    <fullName>Current_Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Allows a user&apos;s location to be set.</description>
    <label>Current Location</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>PrC Users</relationshipLabel>
    <relationshipName>PrC_Users</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/objects/PC_User__c/fields/User_ID__c.field-meta.xml
<CustomField>
    <fullName>User_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Allows a user to be selected.</description>
    <label>User ID</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PrC_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/classes/PC/PC_PrcUserLocationSelectorController.cls
/**
 * @description Controller for the pcPrcUserLocationSelector LWC
 * @author      Booz Allen
 * @since       2024
 */
public with sharing class PC_PrcUserLocationSelectorController {
    @TestVisible
    private static PC_PrcUserRepo visiblePrcUserRepo;

    private static PC_PrcUserRepo prcUserRepo {
        get {
            if (visiblePrcUserRepo == null) {
                visiblePrcUserRepo = new PC_PrcUserRepo();
            }
            return visiblePrcUserRepo;
        }
    }

    /**
     * @description  fetches PC_User__c based on the supplied userId
     * @param userId the running user's Id
     * @return       `PC_User__c` running user's respective PC_User record
     * @exception    QueryException
     */
    @AuraEnabled(cacheable=true)
    public static PC_User__c getPrcUser(Id userId) {
        try {
            List<PC_User__c> fetchResultList = prcUserRepo.fetchPrcUserByUserId(userId);
            return fetchResultList.size() > 0 ? fetchResultList[0] : null;
        } catch (Exception e) {
            log_LogService.log(
                'PC_PrcUserLocationSelectorController.getPrcUser Exception',
                log_LogService.LogType.ERROR,
                e
            );
            log_LogService.publish();
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
     * @description   upserts the PC_User__c record (currently, only net new or update with changes to the Current_Location__c field)
     * @param prcUser current running user's PC_User__c record (matched via User_ID__c field)
     * @return        `PC_User__c` upserted record
     * @exception     DmlException
     */
    @AuraEnabled
    public static PC_User__c savePrcUser(PC_User__c prcUser) {
        try {
            return prcUserRepo.upsertPrcUser(prcUser);
        } catch (Exception e) {
            log_LogService.log(
                'PC_PrcUserLocationSelectorController.savePrcUser Exception',
                log_LogService.LogType.ERROR,
                e
            );
            log_LogService.publish();
            throw new AuraHandledException(e.getMessage());
        }
    }
}