force-app/main/default/objects/VCC_Endpoint_Status_Code_Range__mdt/VCC_Endpoint_Status_Code_Range__mdt.object-meta.xml
<CustomObject>
    <description>Defines the types of errors.</description>
    <label>Endpoint Status Code Range</label>
    <pluralLabel>Endpoint Status Code Ranges</pluralLabel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Endpoint_Status_Code_Range__mdt/fields/VCC_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>VCC_Endpoint__c</fullName>
    <label>Endpoint</label>
    <referenceTo>vccEndpoint__mdt</referenceTo>
    <relationshipLabel>Endpoint Status Code Ranges</relationshipLabel>
    <relationshipName>VCC_Endpoint_Status_Code_Ranges</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Endpoint_Status_Code_Range__mdt/fields/VCC_Status_Code_Range__c.field-meta.xml
<CustomField>
    <fullName>VCC_Status_Code_Range__c</fullName>
    <label>Status Code Range</label>
    <referenceTo>VCC_Status_Code_Range__mdt</referenceTo>
    <relationshipLabel>Endpoint Status Code Ranges</relationshipLabel>
    <relationshipName>VCC_Endpoint_Status_Code_Ranges</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Status_Code_Range__mdt/VCC_Status_Code_Range__mdt.object-meta.xml
<CustomObject>
    <label>Status Code Range</label>
    <pluralLabel>Status Code Ranges</pluralLabel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Status_Code_Range__mdt/fields/VCC_Status_Code_Lower_Bound__c.field-meta.xml
<CustomField>
    <fullName>VCC_Status_Code_Lower_Bound__c</fullName>
    <label>Status Code Lower Bound</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Status_Code_Range__mdt/fields/VCC_Status_Code_Upper_Bound__c.field-meta.xml
<CustomField>
    <fullName>VCC_Status_Code_Upper_Bound__c</fullName>
    <label>Status Code Upper Bound</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/main/default/classes/VCC/VCC_EndpointStatusCodeRangeSelectorTest.cls
@IsTest
public with sharing class VCC_EndpointStatusCodeRangeSelectorTest {
    @IsTest
    public static void instantiationTest() {
        Test.startTest();
        VCC_EndpointStatusCodeRangeSelector escrs = new VCC_EndpointStatusCodeRangeSelector();
        Test.stopTest();

        System.assert(escrs != null, 'Did not instantiate as expected.');
    }

    @IsTest
    public static void addSObjectFieldsTest() {
        VCC_EndpointStatusCodeRangeSelector escrs = new VCC_EndpointStatusCodeRangeSelector();

        System.assert(!escrs.getSObjectFieldList().contains(CodeSet.IsActive), 'Selector already contains the field to test.');

        Test.startTest();
        escrs.addSObjectFields(new List<SObjectField>{ CodeSet.IsActive });
        Test.stopTest();

        System.assert(escrs.getSObjectFieldList().contains(CodeSet.IsActive), 'Selector did not add SObject field correctly.');
    }

    @IsTest
    public static void selectByIdsTest() {
        VCC_EndpointStatusCodeRangeSelector escrs = new VCC_EndpointStatusCodeRangeSelector();
        VCC_Endpoint_Status_Code_Range__mdt escc = [
            SELECT Id
            FROM VCC_Endpoint_Status_Code_Range__mdt
            LIMIT 1
        ];
        Test.startTest();
        List<VCC_Endpoint_Status_Code_Range__mdt> esccList = escrs.selectById(new Set<Id>{ escc.Id });
        Test.stopTest();

        System.assert(esccList.size() == 1, 'Expected one record returned.');
    }

    @IsTest
    public static void selectByCodeAndEndpointTest() {
        VCC_EndpointStatusCodeRangeSelector escrs = new VCC_EndpointStatusCodeRangeSelector();
        Integer statusCode = 400;
        String endpointName = 'vccVdifIsValidEsig';
        List<VCC_Endpoint_Status_Code_Range__mdt> controlList = [
            SELECT Id
            FROM VCC_Endpoint_Status_Code_Range__mdt
            WHERE
                VCC_Endpoint__c = :endpointName
                AND VCC_App_Name__c = NULL
                AND VCC_Status_Code_Range__r.VCC_Status_Code_Lower_Bound__c <= :statusCode
                AND VCC_Status_Code_Range__r.VCC_Status_Code_Upper_Bound__c >= :statusCode
        ];
        List<VCC_Endpoint_Status_Code_Range__mdt> esccList = escrs.selectByCodeAndEndpoint(statusCode, endpointName);

        System.assert(controlList.size() == esccList.size(), 'Size mismatch.');
    }

    @IsTest
    public static void selectByCodeAndAppTest() {
        VCC_EndpointStatusCodeRangeSelector escrs = new VCC_EndpointStatusCodeRangeSelector();
        Integer statusCode = 400;
        String appName = 'Vdif';
        List<VCC_Endpoint_Status_Code_Range__mdt> controlList = [
            SELECT Id
            FROM VCC_Endpoint_Status_Code_Range__mdt
            WHERE
                VCC_Endpoint__c = NULL
                AND VCC_App_Name__c = :appName
                AND VCC_Status_Code_Range__r.VCC_Status_Code_Lower_Bound__c <= :statusCode
                AND VCC_Status_Code_Range__r.VCC_Status_Code_Upper_Bound__c >= :statusCode
        ];
        List<VCC_Endpoint_Status_Code_Range__mdt> esccList = escrs.selectByCodeAndApp(statusCode, appName);

        System.assert(controlList.size() == esccList.size(), 'Size mismatch.');
    }

    @IsTest
    public static void selectGlobalByCodeTest() {
        VCC_EndpointStatusCodeRangeSelector escrs = new VCC_EndpointStatusCodeRangeSelector();
        Integer statusCode = 400;
        List<VCC_Endpoint_Status_Code_Range__mdt> controlList = [
            SELECT Id
            FROM VCC_Endpoint_Status_Code_Range__mdt
            WHERE
                VCC_Endpoint__c = NULL
                AND VCC_App_Name__c = NULL
                AND VCC_Status_Code_Range__r.VCC_Status_Code_Lower_Bound__c <= :statusCode
                AND VCC_Status_Code_Range__r.VCC_Status_Code_Upper_Bound__c >= :statusCode
        ];
        List<VCC_Endpoint_Status_Code_Range__mdt> esccList = escrs.selectGlobalByCode(statusCode);

        System.assert(controlList.size() == esccList.size(), 'Size mismatch.');
    }

    @IsTest
    public static void selectEndpointNameTest() {
        VCC_EndpointStatusCodeRangeSelector escrs = new VCC_EndpointStatusCodeRangeSelector();
        String endpointName = 'vccVdifIsValidEsig';
        List<VCC_Endpoint_Status_Code_Range__mdt> controlList = [
            SELECT Id
            FROM VCC_Endpoint_Status_Code_Range__mdt
            WHERE VCC_Endpoint__c = :endpointName
        ];
        List<VCC_Endpoint_Status_Code_Range__mdt> esccList = escrs.selectByEndpointName(endpointName);

        System.assert(controlList.size() == esccList.size(), 'Size mismatch.');
    }
}