sfdx-source/main/default/objects/VCC_Heartbeat_Template__c/VCC_Heartbeat_Template__c.object-meta.xml
<CustomObject>
    <description>The object is used to store an api callout that will be preset by an API Heartbeat user to test the expected response of a VAHC API</description>
    <label>Heartbeat Template</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Heartbeat Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Heartbeat Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VCC_Heartbeat_Template__c/fields/AutoRun_Schedule__c.field-meta.xml
<CustomField>
    <fullName>AutoRun_Schedule__c</fullName>
    <description>The frequency this template will auto run.</description>
    <label>AutoRun Schedule</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Every Hour</fullName>
            </value>
            <value>
                <fullName>Every 3 Hours</fullName>
            </value>
            <value>
                <fullName>Every 6 Hours</fullName>
            </value>
            <value>
                <fullName>Every 12 Hours</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/VCC_Heartbeat_Template__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Endpoint</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCC_Heartbeat_Template__c/fields/Expected_Response__c.field-meta.xml
<CustomField>
    <fullName>Expected_Response__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Expected Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VCC_Heartbeat_Template__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/VCC_Heartbeat_Template_Parameter__c/VCC_Heartbeat_Template_Parameter__c.object-meta.xml
<CustomObject>
    <description>The object is used to set the parameters that will be used to build the body of the api callout</description>
    <label>Heartbeat Template Parameter</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Parameter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Heartbeat Template Parameters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Heartbeat_Template_Parameter__c/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <label>Data Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>String</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/VCC_Heartbeat_Template_Parameter__c/fields/Default_Value__c.field-meta.xml
<CustomField>
    <fullName>Default_Value__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Default Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Heartbeat_Template_Parameter__c/fields/Format__c.field-meta.xml
<CustomField>
    <fullName>Format__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Format</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Heartbeat_Template_Parameter__c/fields/Heartbeat_Template__c.field-meta.xml
<CustomField>
    <fullName>Heartbeat_Template__c</fullName>
    <label>Heartbeat Template</label>
    <referenceTo>VCC_Heartbeat_Template__c</referenceTo>
    <relationshipLabel>Heartbeat Template Parameters</relationshipLabel>
    <relationshipName>Heartbeat_Template_Parameters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/VCC/VCC_HeartbeatTemplate.cls
public class VCC_HeartbeatTemplate {
    public VCC_HeartbeatTemplate() {
        this.name = '';
        this.id = '';
        this.endpoint = '';
        this.description = '';
        this.method = 'POST';
        this.params = new List<Parameter>();
        this.path = '';
        this.schedule = 'None';
        this.expectedResponse = '';

        this.getDataTypes();
        this.getMethods();
        this.getSchedules();
    }

    public VCC_HeartbeatTemplate(VCC_Heartbeat_Template__c record) {
        this.id = record?.Id;
        this.name = record?.Name;
        this.endpoint = record?.Endpoint__c;
        this.description = record?.Description__c;
        this.method = record?.Method__c;
        this.params = new List<Parameter>();
        this.path = '';
        this.schedule = record?.AutoRun_Schedule__c;
        this.expectedResponse = record?.Expected_Response__c;

        Integer ctr = 0;
        for (VCC_Heartbeat_Template_Parameter__c item : record?.Heartbeat_Template_Parameters__r) {
            this.params.add(new Parameter(item, ctr));
            ctr++;
        }

        this.getDataTypes();
        this.getMethods();
        this.getSchedules();
    }

    public void getDataTypes() {
        this.dataTypes = new List<Option>();
        Schema.DescribeFieldResult fieldResult = VCC_Heartbeat_Template_Parameter__c.Data_Type__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry pickListVal : ple) {
            this.dataTypes.add(new Option(pickListVal.getLabel(), pickListVal.getValue()));
        }
    }

    public void getMethods() {
        this.methods = new List<Option>();
        Schema.DescribeFieldResult fieldResult = VCC_Heartbeat_Template__c.Method__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry pickListVal : ple) {
            this.methods.add(new Option(pickListVal.getLabel(), pickListVal.getValue()));
        }
    }

    public void getSchedules() {
        this.schedules = new List<Option>();
        Schema.DescribeFieldResult fieldResult = VCC_Heartbeat_Template__c.AutoRun_Schedule__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry pickListVal : ple) {
            this.schedules.add(new Option(pickListVal.getLabel(), pickListVal.getValue()));
        }
    }

    public List<Option> dataTypes { get; set; }
    public List<Option> methods { get; set; }
    public List<Option> schedules { get; set; }
    public string id { get; set; }
    public string name { get; set; }
    public string schedule { get; set; }
    public string path { get; set; }
    public string endpoint { get; set; }
    public string description { get; set; }
    public string method { get; set; }
    public List<Parameter> params { get; set; }
    public List<Option> headers { get; set; }
    public string passwordHeader { get; set; }
    public string expectedResponse { get; set; }

    public class Parameter {
        public string name { get; set; }
        public string dataType { get; set; }
        public string row { get; set; }
        public boolean isRequired { get; set; }
        public string format { get; set; }
        public string description { get; set; }
        public string value { get; set; }
        public string defaultValue { get; set; }
        public string type { get; set; }

        public Parameter() {
            this.name = '';
            this.dataType = 'String';
            this.row = 'PARAM-0';
            this.isRequired = false;
            this.format = '';
            this.description = '';
            this.value = '';
            this.type = 'body';
            this.defaultValue = '';
        }

        public Parameter(VCC_Heartbeat_Template_Parameter__c param, integer ctr) {
            this.name = param?.Name;
            this.dataType = param?.Data_Type__c;
            this.isRequired = param?.Is_Required__c;
            this.format = param?.Format__c;
            this.description = param?.Description__c;
            this.row = 'PARAM-' + ctr;
            this.value = param?.Default_Value__c;
        }
    }

    public class Option {
        public Option(string lbl, string val) {
            this.label = lbl;
            this.value = val;
        }

        public string label { get; set; }
        public string value { get; set; }
    }

    public class Param {
        public Param() {
            this.name = '';
            this.value = '';
            this.type = 'String';
            this.format = '';
        }

        public string name { get; set; }
        public string value { get; set; }
        public string type { get; set; }
        public string format { get; set; }
    }

    public class TestRunInfo {
        public TestRunInfo() {
            this.id = '';
            this.endpoint = '';
            this.method = 'POST';
            this.params = new List<Param>();
            this.schedule = 'None';
            this.expectedResponse = '';
        }

        public string id { get; set; }
        public string endpoint { get; set; }
        public string method { get; set; }
        public string schedule { get; set; }
        public string path { get; set; }
        public List<Param> params { get; set; }
        public string expectedResponse { get; set; }
    }

    public class TestResult {
        public TestResult() {
            this.success = false;
            this.message = '';
            this.status = 0;
        }

        public string message { get; set; }
        public boolean success { get; set; }
        public integer status { get; set; }
    }
}