sfdx-source/main/default/objects/VCC_Heartbeat_Template__c/VCC_Heartbeat_Template__c.object-meta.xml
<CustomObject>
    <description>The object is used to store an api callout that will be preset by an API Heartbeat user to test the expected response of a VAHC API</description>
    <label>Heartbeat Template</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Heartbeat Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Heartbeat Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VCC_Heartbeat_Template__c/fields/AutoRun_Schedule__c.field-meta.xml
<CustomField>
    <fullName>AutoRun_Schedule__c</fullName>
    <description>The frequency this template will auto run.</description>
    <label>AutoRun Schedule</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Every Hour</fullName>
            </value>
            <value>
                <fullName>Every 3 Hours</fullName>
            </value>
            <value>
                <fullName>Every 6 Hours</fullName>
            </value>
            <value>
                <fullName>Every 12 Hours</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/VCC_Heartbeat_Template__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Endpoint</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCC_Heartbeat_Template__c/fields/Expected_Response__c.field-meta.xml
<CustomField>
    <fullName>Expected_Response__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Expected Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VCC_Heartbeat_Template__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/VCC_Heartbeat_Template_Parameter__c/VCC_Heartbeat_Template_Parameter__c.object-meta.xml
<CustomObject>
    <description>The object is used to set the parameters that will be used to build the body of the api callout</description>
    <label>Heartbeat Template Parameter</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Parameter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Heartbeat Template Parameters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Heartbeat_Template_Parameter__c/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <label>Data Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>String</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/VCC_Heartbeat_Template_Parameter__c/fields/Default_Value__c.field-meta.xml
<CustomField>
    <fullName>Default_Value__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Default Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Heartbeat_Template_Parameter__c/fields/Format__c.field-meta.xml
<CustomField>
    <fullName>Format__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Format</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Heartbeat_Template_Parameter__c/fields/Heartbeat_Template__c.field-meta.xml
<CustomField>
    <fullName>Heartbeat_Template__c</fullName>
    <label>Heartbeat Template</label>
    <referenceTo>VCC_Heartbeat_Template__c</referenceTo>
    <relationshipLabel>Heartbeat Template Parameters</relationshipLabel>
    <relationshipName>Heartbeat_Template_Parameters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/VCC/VCC_HeartbeatUtility.cls
public without sharing class VCC_HeartbeatUtility {
    public static VCC_HeartbeatTemplate getTemplate(string recordId) {
        List<VCC_Heartbeat_Template__c> templates = [
            SELECT
                Id,
                Endpoint__c,
                Description__c,
                Name,
                Method__c,
                AutoRun_Schedule__c,
                Expected_Response__c,
                (
                    SELECT Id, Data_Type__c, Description__c, Format__c, Name, Heartbeat_Template__c, Is_Required__c, Default_Value__c
                    FROM Heartbeat_Template_Parameters__r
                )
            FROM VCC_Heartbeat_Template__c
            WHERE Id = :recordId
            WITH USER_MODE
        ];

        if (templates.size() == 0)
            return null;

        return new VCC_HeartbeatTemplate(templates[0]);
    }

    public static VCC_HeartbeatTemplate saveTemplate(VCC_HeartbeatTemplate template) {
        VCC_Heartbeat_Template__c data = new VCC_Heartbeat_Template__c();
        if (!string.isBlank(template.id))
            data.Id = template.id;
        data.Name = template.name;
        data.Description__c = template.description;
        data.Endpoint__c = template.endpoint;
        data.Method__c = template.method;
        data.Expected_Response__c = template.expectedResponse;
        data.AutoRun_Schedule__c = template.schedule;
        Database.upsertResult result;
        if (Schema.sObjectType.VCC_Heartbeat_Template__c.isCreateable() && Schema.sObjectType.VCC_Heartbeat_Template__c.isUpdateable()) {
            result = Database.upsert(data);
        }
        if (!result.isSuccess()) {
            template.id = '';
        } else {
            template.id = result.getId();
            List<VCC_Heartbeat_Template_Parameter__c> params;
            if (string.isNotBlank(template.id)) {
                params = [SELECT Id FROM VCC_Heartbeat_Template_Parameter__c WHERE Heartbeat_Template__c = :template.id WITH USER_MODE];
                if (params.size() > 0 && Schema.sObjectType.VCC_Heartbeat_Template_Parameter__c.isDeletable()) {
                    Database.delete(params, true);
                }
            }

            params = new List<VCC_Heartbeat_Template_Parameter__c>();
            VCC_Heartbeat_Template_Parameter__c item;
            for (VCC_HeartbeatTemplate.Parameter param : template.params) {
                item = new VCC_Heartbeat_Template_Parameter__c();
                item.Data_Type__c = param.dataType;
                item.Description__c = param.description;
                item.Format__c = param.format;
                item.Is_Required__c = param.isRequired;
                item.Name = param.name;
                item.Heartbeat_Template__c = result.getId();
                item.Default_Value__c = param.value;
                params.add(item);
            }
            if (params.size() > 0 && Schema.sObjectType.VCC_Heartbeat_Template_Parameter__c.isCreateable()) {
                Database.insert(params, true);
            }
            template = getTemplate(template.id);
        }

        return template;
    }
}