sfdx-source/main/default/objects/VCC_Appointment__c/VCC_Appointment__c.object-meta.xml
<CustomObject>
    <description>This represents the Appointment for a veteran patient. It is a mock object that mimics the fields of the api response.</description>
    <label>Appointment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VCC_Appointment_Batch_Delete_Config__mdt/VCC_Appointment_Batch_Delete_Config__mdt.object-meta.xml
<CustomObject>
    <description>Configuration used for Scheduled Batch Class to clean up stale Appointment and Appointment Request records.</description>
    <label>VCC Appointment Batch Delete Config</label>
    <pluralLabel>VCC Appointment Batch Delete Configs</pluralLabel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Appointment_Batch_Delete_Config__mdt/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <description>Variable to set the number of records per batch.</description>
    <label>Batch Size</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VCC_Appointment_Batch_Delete_Config__mdt/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>Class name passed as a string via callable.</description>
    <label>Class Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Appointment_Batch_Delete_Config__mdt/fields/Number_of_Days_for_Closed_Reqs__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Days_for_Closed_Reqs__c</fullName>
    <description>Used to calculate number of days in the past, to delete Closed Appointment Request records older than that.</description>
    <label>Number of Days for Closed Reqs</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VCC_Appointment_Batch_Delete_Config__mdt/fields/Number_of_Hours_for_Appts_and_Open_Reqs__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Hours_for_Appts_and_Open_Reqs__c</fullName>
    <description>Used to calculate number of hours in the past, to delete records older than that.
Value is used for query for and delete Appointment records and Appointment Request records that are not closed.</description>
    <label>Number of Hours for Appts and Open Reqs</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VCC_Appointment_Batch_Delete_Config__mdt/fields/Run_Batch__c.field-meta.xml
<CustomField>
    <fullName>Run_Batch__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Switch that can be used to run or not run batch class from Schedulable.
Job can remain scheduled, but this field can be set to false if you don&apos;t want it to run temporarily.</description>
    <label>Run Batch</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/VCC_AppointmentRequest__c/VCC_AppointmentRequest__c.object-meta.xml
<CustomObject>
    <description>The Appointment Request object represents a request to create an appointment by a patient. These are created via an integration with the DIP chronos API.</description>
    <label>Appointment Request</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Appointment Requests Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VCC_AppointmentRequest__c/fields/VCC_Appointment__c.field-meta.xml
<CustomField>
    <fullName>VCC_Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The appointment that the appointment request is linked with</description>
    <label>Appointment</label>
    <referenceTo>VCC_Appointment__c</referenceTo>
    <relationshipLabel>Appointment Requests</relationshipLabel>
    <relationshipName>Appointment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/classes/VCC_AppointmentDataSchedulable.cls
/**
 * @description This class is to be scheduled to run on a nightly basis.
 * It exists and uses Callable interface to remove any hard dependancies
 * to the repos and other classes referenced in the ApptDataBatchDelete class.
 * Since this class does not have any hard dependancies, we will not get any
 * conflicts when the job is scheduled, except in a rare case this class itself
 * needs to be modified.
 * @author Booz Allen Hamilton
 * @see VCC_AppointmentDataBatchDelete
 * @see VCC_AppointmentDataSchedulableTest
 */
public class VCC_AppointmentDataSchedulable implements Schedulable {
    @TestVisible
    /**
     * @description Metadata to store class name as string for callable.
     * Number of hours and days can be adjusted, such as lower values for testing.
     * Boolean Run_Batch__c switch to turn batch job off temporarily but keep schedulable job running.
     * Note: This needs to be set within the execute method so that
     * it reflects the current values of the Custom Metadata. If it gets the metadata values
     * as a class level variable, it will only have the values when the job was originally scheduled.
     */
    private VCC_Appointment_Batch_Delete_Config__mdt batchParameters;

    /**
     * @description Default value to use if Custom Metadata is null.
     */
    private final static Integer DEFAULT_HOURS_PAST = 24;

    /**
     * @description Default value to use if Custom Metadata is null.
     */
    private final static Integer DEFAULT_DAYS_PAST = 7;

    /**
     * @description Default value to use if Custom Metadata is null.
     */
    private final static Integer DEFAULT_BATCH_SIZE = 2000;

    @TestVisible
    /**
     * @description List of the appointment data object names that we want to delete in the batch class.
     */
    private final static List<String> APPOINTMENT_OBJECTS = new List<String>{
        'VCC_Appointment__c',
        'VCC_AppointmentRequest__c'
    };

    /**
     * @description Required execute method to implement Schedulable.
     * Exits if Run_Batch is false in metadata.
     * Otherwise it populates a Map with values from metadata.
     * Uses callable to execute batch class.
     * Logs job Id if successful; logs error message if not successful.
     * @param sc - Required SchedulableContext for scheduled async job.
     */
    public void execute(SchedulableContext sc) {
        batchParameters = VCC_Appointment_Batch_Delete_Config__mdt.getInstance('Batch_Config');
        if (batchParameters.Run_Batch__c) {
            try {
                Map<String, Object> batchParams = setParameters();
                Callable automationJob = (Callable) Type.forName(batchParameters.Class_Name__c).newInstance();
                Object responseObj = automationJob.call('executeNewBatchJob', batchParams);
                String executeBatchResponse = (String) responseObj;
                Logger.info('Execute batch job result: ' + executeBatchResponse);
            } catch (VCC_AppointmentDataBatchDelete.AppointmentDataBatchDeleteException batchDeleteException) {
                Logger.error(batchDeleteException.getMessage());
            } finally {
                Logger.saveLog();
            }
        }
    }

    /**
     * @description Populates a Map based on metadata.
     * If metadata fields are blank, it assigns default values.
     * @return `Map<String, Object>` Populates a Map which is required parameter for callable.
     */
    private Map<String, Object> setParameters() {
        // default values
        Integer hoursPast = DEFAULT_HOURS_PAST;
        Integer daysPast = DEFAULT_DAYS_PAST;
        Integer batchSize = DEFAULT_BATCH_SIZE;
        // update based on metadata
        if (batchParameters.Number_of_Hours_for_Appts_and_Open_Reqs__c != null) {
            hoursPast = (Integer) batchParameters.Number_of_Hours_for_Appts_and_Open_Reqs__c;
        }
        if (batchParameters.Number_of_Days_for_Closed_Reqs__c != null) {
            daysPast = (Integer) batchParameters.Number_of_Days_for_Closed_Reqs__c;
        }
        if (batchParameters.Batch_Size__c != null) {
            batchSize = (Integer) batchParameters.Batch_Size__c;
            if (batchSize > 2000) {
                batchSize = DEFAULT_BATCH_SIZE;
            }
        }
        return new Map<String, Object>{
            'objectNames' => APPOINTMENT_OBJECTS,
            'numberOfHours' => hoursPast,
            'numberOfDays' => daysPast,
            'batchSize' => batchSize
        };
    }
}