sfdx-source/main/default/objects/VCC_Addendum__c/VCC_Addendum__c.object-meta.xml
<CustomObject>
    <description>Contains the information regarding updates to a Progress Note</description>
    <label>Addendum</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Addendum Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addendums</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Addendum__c/fields/VCC_Addendum__c.field-meta.xml
<CustomField>
    <fullName>VCC_Addendum__c</fullName>
    <description>Addendum Description/Text</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Addendum Description/Text</inlineHelpText>
    <label>Addendum</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/VCC_Progress_Note__c.object-meta.xml
<CustomObject>
    <description>Progress Notes</description>
    <label>Progress Note</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>Progress Note</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VCC_Signers__c/VCC_Signers__c.object-meta.xml
<CustomObject>
    <description>Object use to Identify Signers of Notes or Addendums</description>
    <label>Signers</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Signer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Signers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Signers__c/fields/VCC_Addendum__c.field-meta.xml
<CustomField>
    <fullName>VCC_Addendum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Signers for the Addendums</description>
    <inlineHelpText>Signers for the Addendums</inlineHelpText>
    <label>Addendum</label>
    <referenceTo>VCC_Addendum__c</referenceTo>
    <relationshipLabel>Signers</relationshipLabel>
    <relationshipName>Signers</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Signers__c/fields/VCC_DUZ__c.field-meta.xml
<CustomField>
    <fullName>VCC_DUZ__c</fullName>
    <description>Signer&apos;s Unique Identifier</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Signer&apos;s Unique Identifier</inlineHelpText>
    <label>DUZ #</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCC_Signers__c/fields/VCC_Progress_Note__c.field-meta.xml
<CustomField>
    <fullName>VCC_Progress_Note__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Progress Note Signers</description>
    <inlineHelpText>Progress Note Signers</inlineHelpText>
    <label>Progress Note</label>
    <referenceTo>VCC_Progress_Note__c</referenceTo>
    <relationshipLabel>Signers</relationshipLabel>
    <relationshipName>Signers</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/classes/VCC/VCC_SignersService.cls
public with sharing class VCC_SignersService {
    public static VCC_SignersService instance {
        get {
            if (privateInstance != null) {
                return privateInstance;
            }
            privateInstance = new VCC_SignersService();
            return privateInstance;
        }
    }

    @TestVisible
    private static VCC_SignersService privateInstance;

    @TestVisible
    private static VCC_Stub stub() {
        VCC_Stub signersServiceStub = new VCC_Stub(VCC_SignersService.class);
        VCC_SignersService.privateInstance = (VCC_SignersService) signersServiceStub.instance;
        return signersServiceStub;
    }

    public List<VCC_Signers__c> getSignersForRecord(Id recordId) {
        if (String.isBlank((String) recordId)) {
            return new List<VCC_Signers__c>();
        }
        return getSignersForRecord(recordId, new VCC_SignersSelector());
    }

    @TestVisible
    private List<VCC_Signers__c> getSignersForRecord(Id recordId, VCC_SignersSelector signersSelector) {
        try {
            SObjectType sObjectType = recordId.getSobjectType();

            if (sObjectType === VCC_Progress_Note__c.SObjectType) {
                return signersSelector.selectSignersByProgressNoteId(recordId);
            } else if (sObjectType === VCC_Addendum__c.SObjectType) {
                return signersSelector.selectSignersByAddendumId(recordId);
            }
        } catch (Exception e) {
            Logger.error('VCC_SignersService.getSignersForRecord exception', e);
            Logger.saveLog();
        }

        return new List<VCC_Signers__c>();
    }

    public List<String> getSignerDuzListForCallout(Id recordId) {
        List<String> duzList = new List<String>();
        for (VCC_Signers__c signer : this.getSignersForRecord(recordId)) {
            duzList.add(signer.VCC_DUZ__c);
        }
        return duzList;
    }
}