sfdx-source/main/default/objects/VCC_Addendum__c/VCC_Addendum__c.object-meta.xml
<CustomObject>
    <description>Contains the information regarding updates to a Progress Note</description>
    <label>Addendum</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Addendum Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addendums</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Addendum__c/fields/VCC_Addendum__c.field-meta.xml
<CustomField>
    <fullName>VCC_Addendum__c</fullName>
    <description>Addendum Description/Text</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Addendum Description/Text</inlineHelpText>
    <label>Addendum</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/VCC_Progress_Note__c.object-meta.xml
<CustomObject>
    <description>Progress Notes</description>
    <label>Progress Note</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>Progress Note</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VCC_Progress_Note__c/fields/VCC_Emergency_Department_Payment_Discl__c.field-meta.xml
<CustomField>
    <fullName>VCC_Emergency_Department_Payment_Discl__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText
    >By checking this box, the following text will be written to the VistA progress note: “Patient advised that recommendation for care provided during the call does not
        constitute an approval for authorization for payment by the VA or its staff. Patient advised to report a community ED visit to the national Office of Community Care at
        1-844-724-7842 within 72 hours.”</inlineHelpText>
    <label>Emergency Department Payment Disclaimer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note__c/fields/VCC_Nurse_Summary__c.field-meta.xml
<CustomField>
    <fullName>VCC_Nurse_Summary__c</fullName>
    <description>Nurse&apos;s summary of the patient&apos;s call.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter your nurse&apos;s notes about the patient&apos;s call.</inlineHelpText>
    <label>Nurse Summary</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note__c/recordTypes/VCC_Clinical_Triage_Note_Progress_Note.recordType-meta.xml
<RecordType>
    <fullName>VCC_Clinical_Triage_Note_Progress_Note</fullName>
    <active>true</active>
    <description>Holds the fields for the Clinical Triage Progress Note</description>
    <label>Clinical Triage Progress Note</label>
</RecordType>

force-app/main/default/objects/VCC_Progress_Note_Configuration__mdt/VCC_Progress_Note_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>Used for identifying what Attributes belong to a particular Progress Note or Addendum Type.</description>
    <label>VCC Progress Note Configuration</label>
    <pluralLabel>Progress Note Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/VCC_Progress_Note_Custom_Section__mdt/VCC_Progress_Note_Custom_Section__mdt.object-meta.xml
<CustomObject>
    <description>Used for defining custom sections as part of Progress Notes</description>
    <label>VCC Progress Note Custom Section</label>
    <pluralLabel>VCC Progress Note Custom Sections</pluralLabel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Progress_Note_Custom_Section__mdt/fields/VCC_Display_Section_Name__c.field-meta.xml
<CustomField>
    <fullName>VCC_Display_Section_Name__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Display Section Name</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note_Custom_Section__mdt/fields/VCC_Fields__c.field-meta.xml
<CustomField>
    <fullName>VCC_Fields__c</fullName>
    <description>The API names of the fields to be added to the section, separated by commas.</description>
    <inlineHelpText>The API names of the fields to be added to the section, separated by commas.</inlineHelpText>
    <label>Fields</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/main/default/classes/VCC/VCC_JsonNoteParserTest.cls
@isTest
public with sharing class VCC_JsonNoteParserTest {
    @isTest
    public static void ctor() {
        VCC_JsonNoteParser emptyCtor;
        VCC_JsonNoteParser progressNoteCtor;
        VCC_JsonNoteParser addendumCtor;

        Test.startTest();
        emptyCtor = new VCC_JsonNoteParser();
        progressNoteCtor = new VCC_JsonNoteParser(new VCC_Progress_Note__c(), null);
        addendumCtor = new VCC_JsonNoteParser(new VCC_Addendum__c(), null);
        Test.stopTest();

        System.assert(emptyCtor != null, 'Expected VCC_JsonNoteParser, got null');
        System.assert(progressNoteCtor != null, 'Expected VCC_JsonNoteParser, got null');
        System.assert(addendumCtor != null, 'Expected VCC_JsonNoteParser, got null');
    }

    @isTest
    public static void initializeCustomSectionTest() {
        VCC_Progress_Note_Configuration__mdt config = new VCC_ProgressNoteConfigSelector().selectByRecordTypeApiName('VCC_Clinical_Triage_Note_Progress_Note');
        VCC_JsonNoteParser jsonNoteParser = new VCC_JsonNoteParser(new VCC_Progress_Note__c(), config);

        VCC_ProgressNoteJsonModel.ProgressNoteSection section;
        Test.startTest();
        section = jsonNoteParser.initializeSection(
            [
                SELECT Id, VCC_Display_Section_Name__c, MasterLabel
                FROM VCC_Progress_Note_Custom_Section__mdt
                LIMIT 1
            ]
        );
        Test.stopTest();

        System.assert(section != null, 'Expected VCC_ProgressNoteJsonModel.ProgressNoteSection, got null');
    }

    @isTest
    public static void initializeStandardLayoutSectionTest() {
        VCC_Progress_Note_Configuration__mdt config = new VCC_ProgressNoteConfigSelector().selectByRecordTypeApiName('VCC_Clinical_Triage_Note_Progress_Note');
        VCC_JsonNoteParser jsonNoteParser = new VCC_JsonNoteParser(new VCC_Progress_Note__c(), config);

        VCC_ProgressNoteJsonModel.ProgressNoteSection section;
        Test.startTest();
        section = jsonNoteParser.initializeSection(VCC_AdapterUtils_Note.getLayoutInfo(VCC_Progress_Note__c.SObjectType, config).sectionHashToSectionMap.values()[0]);
        Test.stopTest();

        System.assert(section != null, 'Expected VCC_ProgressNoteJsonModel.ProgressNoteSection, got null');
    }

    @isTest
    public static void createJsonFieldTest() {
        VCC_Progress_Note__c progressNote = new VCC_Progress_Note__c(VCC_Nurse_Summary__c = 'test');
        VCC_JsonNoteParser jsonNoteParser = new VCC_JsonNoteParser(progressNote, null);

        VCC_ProgressNoteJsonModel.ProgressNoteField jsonField;
        Test.startTest();
        jsonField = jsonNoteParser.createJsonField(VCC_Progress_Note__c.VCC_Nurse_Summary__c.getDescribe());
        Test.stopTest();

        System.assert(jsonField != null, 'Expected VCC_ProgressNoteJsonModel.ProgressNoteField, got null');
    }

    @isTest
    public static void createJsonFieldHelpTextTest() {
        VCC_Progress_Note__c progressNote = new VCC_Progress_Note__c(VCC_Emergency_Department_Payment_Discl__c = true);
        VCC_JsonNoteParser jsonNoteParser = new VCC_JsonNoteParser(progressNote, null);

        VCC_ProgressNoteJsonModel.ProgressNoteField jsonField;
        Test.startTest();
        jsonField = jsonNoteParser.createJsonField(VCC_Progress_Note__c.VCC_Emergency_Department_Payment_Discl__c.getDescribe());
        Test.stopTest();

        System.assert(jsonField != null, 'Expected VCC_ProgressNoteJsonModel.ProgressNoteField help text, got null');
    }

    @isTest
    public static void endToEnd() {
        VCC_Progress_Note__c progressNote = new VCC_Progress_Note__c(VCC_Nurse_Summary__c = 'test');
        VCC_Progress_Note_Configuration__mdt config = new VCC_ProgressNoteConfigSelector().selectByRecordTypeApiName('VCC_Clinical_Triage_Note_Progress_Note');
        VCC_JsonNoteParser jsonNoteParser = new VCC_JsonNoteParser(progressNote, config);
        VCC_LayoutService.LayoutInfo layoutInfo = VCC_AdapterUtils_Note.getLayoutInfo(VCC_Progress_Note__c.SObjectType, config);

        String jsonString;
        List<VCC_ProgressNoteJsonModel.ProgressNoteSection> sections;
        Test.startTest();
        jsonString = jsonNoteParser.parse(
            layoutInfo.sectionHashToSectionMap.values(),
            [
                SELECT Id, VCC_Display_Section_Name__c, VCC_Fields__c, MasterLabel
                FROM VCC_Progress_Note_Custom_Section__mdt
                LIMIT 1
            ]
        );
        sections = (List<VCC_ProgressNoteJsonModel.ProgressNoteSection>) JSON.deserialize(jsonString, List<VCC_ProgressNoteJsonModel.ProgressNoteSection>.class);
        Test.stopTest();

        System.assert(jsonString != null, 'Expected String output, got null');
        System.assert(sections != null, 'Expected List of VCC_ProgressNoteJsonModel.ProgressNoteSection, got null');
    }
}