sfdx-source/main/default/objects/VCC_Addendum__c/VCC_Addendum__c.object-meta.xml
<CustomObject>
    <description>Contains the information regarding updates to a Progress Note</description>
    <label>Addendum</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Addendum Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addendums</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Addendum__c/fields/VCC_Addendum__c.field-meta.xml
<CustomField>
    <fullName>VCC_Addendum__c</fullName>
    <description>Addendum Description/Text</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Addendum Description/Text</inlineHelpText>
    <label>Addendum</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VCC_Addendum__c/fields/VCC_CRM_System_Modified_Output_To_VistA__c.field-meta.xml
<CustomField>
    <fullName>VCC_CRM_System_Modified_Output_To_VistA__c</fullName>
    <defaultValue>false</defaultValue>
    <description
    >LEAF-299 / CCCM-20147 This checkbox is checked if user input was modified during the process of sending the note to VistA (via DIP/VDIF). For example, the backslash
        &quot;\&quot; is changed to a forward slash &quot;/&quot;.</description>
    <label>CRM System Modified Output To VistA</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/VCC_Progress_Note__c.object-meta.xml
<CustomObject>
    <description>Progress Notes</description>
    <label>Progress Note</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>Progress Note</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Relative_Type__c.field-meta.xml
<CustomField>
    <fullName>VCC_Relative_Type__c</fullName>
    <description>Relationship of Caller to Veteran. Populated from the Phone Call/Case via a Flow.</description>
    <inlineHelpText>Relationship of the Caller to the Veteran. This is populated from the Phone Call/Case, if captured.</inlineHelpText>
    <label>Caller/Recipient Relation to Patient</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Self</fullName>
            </value>
            <value>
                <fullName>Caregiver</fullName>
            </value>
            <value>
                <fullName>Power of Attorney</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Anonymous</fullName>
                <isActive>false</isActive>
                <label>Anonymous</label>
            </value>
            <value>
                <fullName>Aunt</fullName>
                <isActive>false</isActive>
                <label>Aunt</label>
            </value>
            <value>
                <fullName>Daughter</fullName>
                <isActive>false</isActive>
                <label>Daughter</label>
            </value>
            <value>
                <fullName>Father</fullName>
                <isActive>false</isActive>
                <label>Father</label>
            </value>
            <value>
                <fullName>Home Health</fullName>
                <isActive>false</isActive>
                <label>Home Health</label>
            </value>
            <value>
                <fullName>Mother</fullName>
                <isActive>false</isActive>
                <label>Mother</label>
            </value>
            <value>
                <fullName>Neighbor</fullName>
                <isActive>false</isActive>
                <label>Neighbor</label>
            </value>
            <value>
                <fullName>Sibling</fullName>
                <isActive>false</isActive>
                <label>Sibling</label>
            </value>
            <value>
                <fullName>Son</fullName>
                <isActive>false</isActive>
                <label>Son</label>
            </value>
            <value>
                <fullName>Spouse</fullName>
                <isActive>false</isActive>
                <label>Spouse</label>
            </value>
            <value>
                <fullName>Uncle</fullName>
                <isActive>false</isActive>
                <label>Uncle</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note_Configuration__mdt/VCC_Progress_Note_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>Used for identifying what Attributes belong to a particular Progress Note or Addendum Type.</description>
    <label>VCC Progress Note Configuration</label>
    <pluralLabel>Progress Note Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/VCC_Progress_Note_Custom_Section__mdt/VCC_Progress_Note_Custom_Section__mdt.object-meta.xml
<CustomObject>
    <description>Used for defining custom sections as part of Progress Notes</description>
    <label>VCC Progress Note Custom Section</label>
    <pluralLabel>VCC Progress Note Custom Sections</pluralLabel>
</CustomObject>

sfdx-source/main/default/classes/VCC/VCC_Adapter_NoteToVdif.cls
/**
 * @description This description is a stub and should be replaced, but I can't abide by suppressing all ApexDoc errors at a class level.
 */
public with sharing class VCC_Adapter_NoteToVdif {
    @InvocableMethod(Label='Write To VDIF' Category='Notes' Callout=true)
    public static List<String> writeNote(List<Parameters> paramsList) {
        List<String> returnStrings = new List<String>();
        List<VCC_Progress_Note__c> pnList = new List<VCC_Progress_Note__c>();
        for (Parameters params : paramsList) {
            if (params.noteSObject instanceof VCC_Addendum__c) {
                String returnString = VCC_NoteService.createAddendum(
                        parse(
                            params,
                            new VCC_ProgressNoteCustomSectionSelector()
                                .selectByParentConfigId(params.progressNoteConfig.Id)
                        ),
                        params.noteAndEncounterParams,
                        params.patientAndProviderParams,
                        params.noteSObject.Id
                    )
                    ?.text;
                returnStrings.add(returnString);
            } else if (params.noteSObject instanceof VCC_Progress_Note__c) {
                String returnString = VCC_NoteService.writeNote(
                        parse(
                                params,
                                new VCC_ProgressNoteCustomSectionSelector()
                                    .selectByParentConfigId(params.progressNoteConfig.Id)
                            )
                            .replace('<br>', ''),
                        params.noteAndEncounterParams,
                        params.patientAndProviderParams,
                        params.noteSObject.Id
                    )
                    ?.id;
                returnStrings.add(returnString);
                if (VCC_NoteParserService.didReplaceCharacters == true) {
                    VCC_Progress_Note__c vccProgressNote = new VCC_Progress_Note__c(
                        Id = params.noteSObject.Id,
                        VCC_CRM_System_Modified_Output_To_VistA__c = true,
                        VCC_Relative_Type__c = ((VCC_Progress_Note__c) params.noteSObject).VCC_Relative_Type__c
                    );
                    pnList.add(vccProgressNote);
                }
            }
        }

        if (!pnList.isEmpty()) {
            if (Schema.SObjectType.VCC_Progress_Note__c.isUpdateable()) {
                Database.update(pnList, true, System.AccessLevel.USER_MODE); //NOPMD
            }
        }
        return returnStrings;
    }

    @SuppressWarnings('PMD.ApexDoc')
    @AuraEnabled(Cacheable=false)
    public static List<String> parseLWC(String pnId, String pnRtId) {
        VCC_Progress_Note__c progressNote = new VCC_Progress_Note__c();
        progressNote.Id = pnId;
        progressNote.RecordTypeId = pnRtId;
        // Get Config
        VCC_Progress_Note_Configuration__mdt config = VCC_ProgressNoteService.getConfig(progressNote);
        // Prep our params
        Parameters params = new Parameters();
        params.progressNoteConfig = config;
        params.noteSObject = progressNote;
        params.noteAndEncounterParams = new VCC_Vdif_NoteAndEncounterParams();
        params.patientAndProviderParams = new VCC_Vdif_PatientAndProviderParams();

        //new
        List<String> nToVdiffList = new List<String>();
        nToVdiffList.add(
            VCC_Adapter_NoteToVdif.parse(
                    params,
                    new VCC_ProgressNoteCustomSectionSelector().selectByParentConfigId(params.progressNoteConfig.Id)
                )
                .replace('<br>', '')
        );
        // Parse
        return nToVdiffList;
    }

    @SuppressWarnings('PMD.ApexDoc')
    public static String parse(Parameters params, List<VCC_Progress_Note_Custom_Section__mdt> customSections) {
        //get layout info
        VCC_LayoutService.LayoutInfo layoutInfo = VCC_AdapterUtils_Note.getLayoutInfo(
            params.noteSObject.getSObjectType(),
            params.progressNoteConfig
        );

        //get missing data, if any
        params.noteSObject = VCC_AdapterUtils_Note.prepNote(
            params.noteSObject,
            VCC_AdapterUtils_Note.getAllFieldNames(layoutInfo, customSections)
        );

        String t2tDataVDIF = VCC_T2T_Adapter_Record2JSON.prepVDIFT2TData(params.noteSObject.Id);
        if (t2tDataVDIF != null) {
            return (new VCC_VdifNoteParser(params.noteSObject))
                    .parse(layoutInfo.sectionHashToSectionMap.values(), customSections) + t2tDataVDIF;
        }
        return (new VCC_VdifNoteParser(params.noteSObject))
            .parse(layoutInfo.sectionHashToSectionMap.values(), customSections);
    }

    //    /** adding for DAS */
    public static String parse(
        SObject noteSObject,
        VCC_Progress_Note_Configuration__mdt progressNoteConfig,
        List<VCC_Progress_Note_Custom_Section__mdt> customSections
    ) {
        Parameters params = new Parameters();
        params.noteSObject = noteSObject;
        params.progressNoteConfig = progressNoteConfig;
        return parse(params, customSections).replace('<br>', '');
    }

    @SuppressWarnings('PMD.ApexDoc')
    public class Parameters {
        @InvocableVariable
        public VCC_Progress_Note_Configuration__mdt progressNoteConfig;

        @InvocableVariable
        public SObject noteSObject;

        @InvocableVariable
        public VCC_Vdif_NoteAndEncounterParams noteAndEncounterParams;

        @InvocableVariable
        public VCC_Vdif_PatientAndProviderParams patientAndProviderParams;
    }
}