sfdx-source/main/default/objects/VCC_Addendum__c/VCC_Addendum__c.object-meta.xml
<CustomObject>
    <description>Contains the information regarding updates to a Progress Note</description>
    <label>Addendum</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Addendum Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addendums</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Addendum__c/fields/VCC_Addendum__c.field-meta.xml
<CustomField>
    <fullName>VCC_Addendum__c</fullName>
    <description>Addendum Description/Text</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Addendum Description/Text</inlineHelpText>
    <label>Addendum</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/VCC_Progress_Note__c.object-meta.xml
<CustomObject>
    <description>Progress Notes</description>
    <label>Progress Note</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>Progress Note</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VCC_Signers__c/VCC_Signers__c.object-meta.xml
<CustomObject>
    <description>Object use to Identify Signers of Notes or Addendums</description>
    <label>Signers</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Signer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Signers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Signers__c/fields/VCC_Addendum__c.field-meta.xml
<CustomField>
    <fullName>VCC_Addendum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Signers for the Addendums</description>
    <inlineHelpText>Signers for the Addendums</inlineHelpText>
    <label>Addendum</label>
    <referenceTo>VCC_Addendum__c</referenceTo>
    <relationshipLabel>Signers</relationshipLabel>
    <relationshipName>Signers</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Signers__c/fields/VCC_DUZ__c.field-meta.xml
<CustomField>
    <fullName>VCC_DUZ__c</fullName>
    <description>Signer&apos;s Unique Identifier</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Signer&apos;s Unique Identifier</inlineHelpText>
    <label>DUZ #</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Signers__c/fields/VCC_Location__c.field-meta.xml
<CustomField>
    <fullName>VCC_Location__c</fullName>
    <description>The location of Signer.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The location of Signer.</inlineHelpText>
    <label>Location</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCC_Signers__c/fields/VCC_Progress_Note__c.field-meta.xml
<CustomField>
    <fullName>VCC_Progress_Note__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Progress Note Signers</description>
    <inlineHelpText>Progress Note Signers</inlineHelpText>
    <label>Progress Note</label>
    <referenceTo>VCC_Progress_Note__c</referenceTo>
    <relationshipLabel>Signers</relationshipLabel>
    <relationshipName>Signers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCC_Signers__c/fields/VCC_Role__c.field-meta.xml
<CustomField>
    <fullName>VCC_Role__c</fullName>
    <description>Role of Signer</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Role of Signer</inlineHelpText>
    <label>Role</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCC_Signers__c/fields/VCC_Title__c.field-meta.xml
<CustomField>
    <fullName>VCC_Title__c</fullName>
    <description>Signer&apos;s job title</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Signer&apos;s job title</inlineHelpText>
    <label>Title</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/classes/VCC/VCC_SignersSelector.cls
public with sharing class VCC_SignersSelector extends fflib_SObjectSelector {
    private List<Schema.SObjectField> sObjectFields = new List<Schema.SObjectField>{
        VCC_Signers__c.Id,
        VCC_Signers__c.Name,
        VCC_Signers__c.VCC_Title__c,
        VCC_Signers__c.VCC_Role__c,
        VCC_Signers__c.VCC_Location__c,
        VCC_Signers__c.VCC_DUZ__c
    };

    public Schema.SObjectType getSObjectType() {
        return VCC_Signers__c.SObjectType;
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return this.sObjectFields;
    }

    public void addSObjectFields(List<Schema.SObjectField> sObjectFields) {
        if (sObjectFields != null && !sObjectFields.isEmpty()) {
            for (Schema.SObjectField field : sObjectFields) {
                if (!this.sObjectFields.contains(field)) {
                    this.sObjectFields.add(field);
                }
            }
        }
    }

    public List<VCC_Signers__c> selectSignersByAddendumId(Id addendumId) {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('VCC_Addendum__c =: addendumId');

        return Database.query(query.toSOQL());
    }

    public List<VCC_Signers__c> selectSignersByProgressNoteId(Id progressNoteId) {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('VCC_Progress_Note__c =: progressNoteId');

        return Database.query(query.toSOQL());
    }
}