force-app/main/default/objects/CodeCoverage__c/CodeCoverage__c.object-meta.xml
<CustomObject>
    <description>This object is part of the org management unlocked package. It is used to keep track code coverage for every class from each test run.</description>
    <label>Code Coverage</label>
    <nameField>
        <displayFormat>CC-{0000000000}</displayFormat>
        <label>Code Coverage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Code Coverages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CodeCoverage__c/fields/ApexClassOrTriggerName__c.field-meta.xml
<CustomField>
    <fullName>ApexClassOrTriggerName__c</fullName>
    <description>The apex class or trigger name.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The apex class or trigger name.</inlineHelpText>
    <label>ApexClass Or TriggerName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/classes/CodeCoverageTriggerHandler.cls
/**
 * Author:Jaren Yach
 *  Created Date 05/27/2022
 *  Purpose: Trigger handler class for CodeCoverage__c
 */
public without sharing class CodeCoverageTriggerHandler {
    /**
     * Before Insert handler
     *
     * @param newList - List<CodeCoverage__c
     */
    public static void beforeInsert(List<CodeCoverage__c> newList) {
        assignDTCModule(newList);
    }

    /**
     * Assigns the dtc module to the CodeCoverage__c record.
     *
     * @param newList - List<CodeCoverage__c>
     */
    private static void assignDTCModule(List<CodeCoverage__c> newList) {
        Set<String> classNames = new Set<String>();
        for (CodeCoverage__c rec : newList) {
            classNames.add(rec.ApexClassOrTriggerName__c);
        }

        List<ModuleClass__c> classes = [SELECT Name, DTCModule__r.Name FROM ModuleClass__c WHERE Name IN :classNames];

        Map<String, ModuleClass__c> moduleClassMap = new Map<String, ModuleClass__c>();
        for (ModuleClass__c moduleTestClass : classes) {
            moduleClassMap.put(moduleTestClass.Name.toLowerCase(), moduleTestClass);
        }

        for (CodeCoverage__c rec : newList) {
            String key = rec.ApexClassOrTriggerName__c?.toLowerCase();
            if (String.isNotBlank(key) && moduleClassMap.containsKey(key)) {
                rec.DTCModule__c = moduleClassMap.get(key).DTCModule__r.Id;
            }
        }
    }
}