force-app/main/default/objects/CodeCoverage__c/CodeCoverage__c.object-meta.xml
<CustomObject>
    <description>This object is part of the org management unlocked package. It is used to keep track code coverage for every class from each test run.</description>
    <label>Code Coverage</label>
    <nameField>
        <displayFormat>CC-{0000000000}</displayFormat>
        <label>Code Coverage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Code Coverages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/CodeCoverage__c/fields/ApexClassOrTriggerId__c.field-meta.xml
<CustomField>
    <fullName>ApexClassOrTriggerId__c</fullName>
    <description>The apex class or trigger Id</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The apex class or trigger Id</inlineHelpText>
    <label>ApexClass Or TriggerId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CodeCoverage__c/fields/ApexClassOrTriggerName__c.field-meta.xml
<CustomField>
    <fullName>ApexClassOrTriggerName__c</fullName>
    <description>The apex class or trigger name.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The apex class or trigger name.</inlineHelpText>
    <label>ApexClass Or TriggerName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/CodeCoverage__c/fields/LinesCovered__c.field-meta.xml
<CustomField>
    <fullName>LinesCovered__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The total number of lines covered by unit tests.</description>
    <inlineHelpText>The total number of lines covered by unit tests.</inlineHelpText>
    <label>Lines Covered</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CodeCoverage__c/fields/LinesNotCovered__c.field-meta.xml
<CustomField>
    <fullName>LinesNotCovered__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The total number of lines not covered by unit tests.</description>
    <inlineHelpText>The total number of lines not covered by unit tests.</inlineHelpText>
    <label>Lines Not Covered</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CodeCoverage__c/fields/TestRun__c.field-meta.xml
<CustomField>
    <fullName>TestRun__c</fullName>
    <description>The related test run that initiated the code coverage.</description>
    <inlineHelpText>The related test run that initiated the code coverage.</inlineHelpText>
    <label>Test Run</label>
    <referenceTo>Test_Run__c</referenceTo>
    <relationshipLabel>Code Coverages</relationshipLabel>
    <relationshipName>Code_Coverages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/main/default/classes/CodeCoverageWrapper.cls
/**
 * Author:Jaren Yach
 *  Created Date 05/27/2022
 *  Purpose: Wrapper class for Tooling Api Responses for ApexCodeCoverageAggregate object
 */
public with sharing class CodeCoverageWrapper {
    public List<Record> records { get; set; }
    public class Record {
        public String ApexClassorTriggerId { get; set; }
        public Integer NumLinesCovered { get; set; }
        public Integer NumLinesUncovered { get; set; }
        public ApexClassOrTrigger ApexClassOrTrigger { get; set; }

        /**
         * Overload method to convert class properties to CodeCoverage__c object
         *
         * @return CodeCoverage__c
         */
        public CodeCoverage__c toCodeCoverageSobject() {
            return toCodeCoverageSobject(null);
        }

        /**
         * Convert class properties to CodeCoverage__c object
         *
         * @param testRunId - Test run Id
         *
         * @return CodeCoverage__c
         */
        public CodeCoverage__c toCodeCoverageSobject(Id testRunId) {
            CodeCoverage__c cc = new CodeCoverage__c();
            cc.TestRun__c = testRunId;
            cc.ApexClassOrTriggerId__c = this.ApexClassorTriggerId;
            cc.ApexClassOrTriggerName__c = this.ApexClassOrTrigger.Name;
            cc.LinesCovered__c = this.NumLinesCovered;
            cc.LinesNotCovered__c = this.NumLinesUncovered;
            return cc;
        }
    }

    public class ApexClassOrTrigger {
        public String Name { get; set; }
    }

    /**
     * Easy way to deserialize json into object
     *
     * @param json - api response
     *
     * @return CodeCoverageWrapper
     */
    public static CodeCoverageWrapper parse(String json) {
        return (CodeCoverageWrapper) System.JSON.deserialize(json, CodeCoverageWrapper.class);
    }
}