force-app/main/default/objects/CodeCoverage__c/CodeCoverage__c.object-meta.xml
<CustomObject>
    <description>This object is part of the org management unlocked package. It is used to keep track code coverage for every class from each test run.</description>
    <label>Code Coverage</label>
    <nameField>
        <displayFormat>CC-{0000000000}</displayFormat>
        <label>Code Coverage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Code Coverages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CodeCoverage__c/fields/ApexClassOrTriggerName__c.field-meta.xml
<CustomField>
    <fullName>ApexClassOrTriggerName__c</fullName>
    <description>The apex class or trigger name.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The apex class or trigger name.</inlineHelpText>
    <label>ApexClass Or TriggerName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test_Run_Method_Result__c/Test_Run_Method_Result__c.object-meta.xml
<CustomObject>
    <description>Stores all the results of all the apex unit tests related to a Test_Run__c record.</description>
    <label>Test Run Method Result</label>
    <nameField>
        <displayFormat>TRMR-{0000000000}</displayFormat>
        <label>Test Run Method Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Run Method Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/Test_Run_Method_Result__c/fields/Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class__c</fullName>
    <description>The test apex class that was ran.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The test apex class that was ran.</inlineHelpText>
    <label>Apex Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ModuleClassTriggerHandler.cls
/**
 * Author:Jaren Yach
 *  Created Date 05/20/2022
 *  Purpose: Trigger handler class for ModuleClass__c
 */
public without sharing class ModuleClassTriggerHandler {
    /**
     * After Insert handler
     *
     * @param newList - List<ModuleClass__c
     * @param newMap Map<Id, ModuleClass__c>
     */
    public static void afterInsert(List<ModuleClass__c> newList, Map<Id, ModuleClass__c> newMap) {
        assignModules(newList);
    }

    /**
     * After Update handler
     *
     * @param newList - List<ModuleClass__c
     * @param oldList - List<ModuleClass__c
     * @param newMap - Map<Id, ModuleClass__c>
     * @param oldMap - Map<Id, ModuleClass__c>
     */
    public static void afterUpdate(List<ModuleClass__c> newList, List<ModuleClass__c> oldList, Map<Id, ModuleClass__c> newMap, Map<Id, ModuleClass__c> oldMap) {
        assignModules(newList);
    }

    /**
     * Assigns dtc module on Test_Run_Method_Result__c records that have the same apex class.
     *
     * @param newList - List<ModuleClass__c>
     */
    private static void assignModules(List<ModuleClass__c> newList) {
        Map<String, ModuleClass__c> classMap = new Map<String, ModuleClass__c>();
        for (ModuleClass__c mtc : newList) {
            classMap.put(mtc.Name.toLowerCase(), mtc);
        }

        List<Test_Run_Method_Result__c> testRunMethodResults = [
            SELECT Id, Apex_Class__c
            FROM Test_Run_Method_Result__c
            WHERE Apex_Class__c IN :classMap.keySet() AND DTCModule__c = NULL
        ];
        List<CodeCoverage__c> coverageRecs = [
            SELECT Id, ApexClassOrTriggerName__c
            FROM CodeCoverage__c
            WHERE ApexClassOrTriggerName__c IN :classMap.keySet() AND DTCModule__c = NULL
        ];

        List<SObject> updateList = new List<SObject>();
        for (Test_Run_Method_Result__c trmr : testRunMethodResults) {
            String key = trmr.Apex_Class__c?.toLowerCase();
            if (String.isNotBlank(key) && classMap.containsKey(key)) {
                trmr.DTCModule__c = classMap.get(key).DTCModule__c;
                updateList.add(trmr);
            }
        }

        for (CodeCoverage__c cc : coverageRecs) {
            String key = cc.ApexClassOrTriggerName__c?.toLowerCase();
            if (String.isNotBlank(key) && classMap.containsKey(key)) {
                cc.DTCModule__c = classMap.get(key).DTCModule__c;
                updateList.add(cc);
            }
        }

        if (updateList.size() > 0) {
            update updateList;
        }
    }
}