sfdx-source/main/default/objects/TUC_Supported_Location_By_VISN__mdt/TUC_Supported_Location_By_VISN__mdt.object-meta.xml
<CustomObject>
    <description>This custom metadata type is a configuration that stores the facilities (Location standard object) that the Tele-EC module currently support.</description>
    <label>TUC Supported Location By VISN</label>
    <pluralLabel>TUC Supported Locations By VISN</pluralLabel>
</CustomObject>

sfdx-source/main/default/objects/TUC_Supported_Location_By_VISN__mdt/fields/MPI_Facility_ID__c.field-meta.xml
<CustomField>
    <fullName>MPI_Facility_ID__c</fullName>
    <label>MPI Facility ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TUC_Supported_Location_By_VISN__mdt/fields/Salesforce_Facility_ID__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Facility_ID__c</fullName>
    <description>Facility (Location) Id.</description>
    <inlineHelpText>Facility (Location) Id.</inlineHelpText>
    <label>Salesforce Facility ID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TUC_Supported_Location_By_VISN__mdt/fields/VISN__c.field-meta.xml
<CustomField>
    <fullName>VISN__c</fullName>
    <description>The VISN number for this Tele-EC solution</description>
    <inlineHelpText>The VISN number for this Tele-EC solution</inlineHelpText>
    <label>VISN</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VISN__c/VISN__c.object-meta.xml
<CustomObject>
    <label>VISN</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>VISN Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VISNs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/main/default/classes/TUC/TUC_SupportedLocationByVISNMdtRepo.cls
/**
 * @description This repository is for the TUC_Supported_Location_By_VISN__mdt Metadata. Meant to be used in test classes that retrieve and compare to make sure all VISNs have data
 * @author Booz Allen
 */
public virtual with sharing class TUC_SupportedLocationByVISNMdtRepo extends VTC_BaseRepo {
    /**
     * @description Constructor function for TUC_SupportedLocationByVISNMdtRepo. Calls super constructor which sets this.sObjectType to
     * TUC_Supported_Location_By_VISN__mdt
     */
    public TUC_SupportedLocationByVISNMdtRepo() {
        super(TUC_Supported_Location_By_VISN__mdt.sObjectType);
    }

    /**
     * @description retrieves all metadata in the org
     * @return `List<TUC_Supported_Location_By_VISN__mdt>` - list of the Tuc Supported Location metadata
     */
    public List<TUC_Supported_Location_By_VISN__mdt> getAllTUCSupportedLocationByVISNmdtRecords() {
        String selectClause = 'SELECT Id, MPI_Facility_ID__c, Salesforce_Facility_ID__c, VISN__c ';
        String fromClause = 'FROM TUC_Supported_Location_By_VISN__mdt';
        String query = selectClause + fromClause;

        return this.fetch(query);
    }
}