sfdx-source/main/default/objects/PC_Case_Feedback_Answer__c/PC_Case_Feedback_Answer__c.object-meta.xml
<CustomObject>
    <label>PrC Case Feedback Answer</label>
    <nameField>
        <displayFormat>PCCFA-{00000}</displayFormat>
        <label>PC Case Feedback Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrC Case Feedback Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/PC_Case_Feedback_Answer__c/fields/PC_Question__c.field-meta.xml
<CustomField>
    <fullName>PC_Question__c</fullName>
    <label>Question</label>
    <referenceTo>PC_Case_Feedback_Question__c</referenceTo>
    <relationshipName>PC_Survey_Question_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/main/default/objects/PC_Case_Feedback_Answer__c/fields/Provider_Connect_Case__c.field-meta.xml
<CustomField>
    <fullName>Provider_Connect_Case__c</fullName>
    <description>Provider Connect Case to which this feedback answer relates</description>
    <label>Provider Connect Case</label>
    <referenceTo>PC_Case__c</referenceTo>
    <relationshipLabel>PC Case Feedback Answers</relationshipLabel>
    <relationshipName>PC_Case_Feedback_Answers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PC_Case_Feedback_Question__c/PC_Case_Feedback_Question__c.object-meta.xml
<CustomObject>
    <description>Questions for the case feedback.</description>
    <label>PrC Case Feedback Question</label>
    <nameField>
        <displayFormat>PCCFQ-{00000}</displayFormat>
        <label>PC Case Feedback Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrC Case Feedback Questions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PC_Case_Feedback_Question__c/fields/PC_Active__c.field-meta.xml
<CustomField>
    <fullName>PC_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Determines if the question is available to use.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/PC_Case_Feedback_Question__c/fields/PC_Question__c.field-meta.xml
<CustomField>
    <fullName>PC_Question__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Question</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

sfdx-source/main/default/classes/PC/PC_CaseFeedbackAnswerRepo.cls
/**
 * @description Repository class for the Case Feedback Answer object to hold its respective query and DML logic
 * @author Booz Allen
 * @since  2024
 */
public with sharing class PC_CaseFeedbackAnswerRepo extends VTC_BaseRepo {
    /**
     * @description Constructor function for PC_CaseFeedbackAnswerRepo. Calls super constructor which sets this.sObjectType to 'PC_Case_Feedback_Answer__c'
     */
    public PC_CaseFeedbackAnswerRepo() {
        super(PC_Case_Feedback_Answer__c.sObjectType);
    }

    /**
     * @description     gets a list of Case Feedback that need to action for a specific Case
     * @param caseIds Set of Ids for the Cases to verify
     * @return 'List<PC_Case_Feedback_Answer__c>' list of Case Feedback Answers
     */
    public List<PC_Case_Feedback_Answer__c> getFeedbackAnswersFromPrcCases(Set<Id> caseIds) {
        String selectClause = 'SELECT Id,Provider_Connect_Case__c';
        String fromClause = this.calculateFromClause();
        String whereClause = 'WHERE Provider_Connect_Case__c IN :caseIds AND PC_Question__r.PC_Active__c = TRUE';
        String query = selectClause + ' ' + fromClause + ' ' + whereClause;
        return (List<PC_Case_Feedback_Answer__c>) this.fetch(query, new Map<String, Object>{ 'caseIds' => caseIds });
    }
}