force-app/main/default/objects/VCC_Callout_Data__c/VCC_Callout_Data__c.object-meta.xml
<CustomObject>
    <description>Used for the Integration Test Utility, holding info about the vdif/mpi callouts that are a part of the note-signing-process.</description>
    <label>Callout Data</label>
    <nameField>
        <displayFormat>COD-{0000}</displayFormat>
        <label>Callout Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Callout Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Test_Run__c/VCC_Test_Run__c.object-meta.xml
<CustomObject>
    <description>Used by the &quot;Integration Test Utility&quot;</description>
    <label>Test Run</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>Test Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Runs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VCC_Test_Run_Callout__c/VCC_Test_Run_Callout__c.object-meta.xml
<CustomObject>
    <description>The junction object between VCC_Callout_Data__c and VCC_Test_Run__c for the &apos;Integration Test Utility&apos;</description>
    <label>Test Run Callout</label>
    <nameField>
        <displayFormat>TRCO-{0000}</displayFormat>
        <label>Test Run Callout Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Run Callouts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VCC_Test_Run_Callout__c/fields/VCC_Callout__c.field-meta.xml
<CustomField>
    <fullName>VCC_Callout__c</fullName>
    <description>Relationship to parent Callout Data</description>
    <label>Callout Data</label>
    <referenceTo>VCC_Callout_Data__c</referenceTo>
    <relationshipLabel>Test Run Callouts</relationshipLabel>
    <relationshipName>Test_Run_Callouts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VCC_Test_Run_Callout__c/fields/VCC_Test_Run__c.field-meta.xml
<CustomField>
    <fullName>VCC_Test_Run__c</fullName>
    <description>Relationship to parent Test Run</description>
    <label>Test Run</label>
    <referenceTo>VCC_Test_Run__c</referenceTo>
    <relationshipLabel>Test Run Callouts</relationshipLabel>
    <relationshipName>Test_Run_Callouts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/VCC/VCC_TestRunCalloutService.cls
public with sharing class VCC_TestRunCalloutService {
    public static VCC_TestRunCalloutService instance {
        get {
            if (privateInstance != null) {
                return privateInstance;
            }
            privateInstance = new VCC_TestRunCalloutService();
            return privateInstance;
        }
    }

    @TestVisible
    private static VCC_TestRunCalloutService privateInstance;

    @TestVisible
    private static VCC_Stub stub() {
        VCC_Stub testRunCalloutServiceStub = new VCC_Stub(VCC_TestRunCalloutService.class);
        VCC_TestRunCalloutService.privateInstance = (VCC_TestRunCalloutService) testRunCalloutServiceStub.instance;
        return testRunCalloutServiceStub;
    }

    public VCC_Test_Run_Callout__c insertNewTestRunCallout(VCC_Test_Run__c testRun, VCC_Callout_Data__c calloutData) {
        VCC_Test_Run_Callout__c testRunCallout = new VCC_Test_Run_Callout__c(VCC_Callout__c = calloutData?.Id, VCC_Test_Run__c = testRun?.Id);

        fflib_ISObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(new List<Schema.SObjectType>{ VCC_Test_Run_Callout__c.SObjectType });
        uow.registerNew(testRunCallout);
        uow.commitWork();
        return testRunCallout;
    }
}