force-app/main/default/objects/VCC_Callout_Data__c/VCC_Callout_Data__c.object-meta.xml
<CustomObject>
    <description>Used for the Integration Test Utility, holding info about the vdif/mpi callouts that are a part of the note-signing-process.</description>
    <label>Callout Data</label>
    <nameField>
        <displayFormat>COD-{0000}</displayFormat>
        <label>Callout Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Callout Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VCC_Callout_Data__c/fields/VCC_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>VCC_Endpoint__c</fullName>
    <description>The endpoint that is used for the callout when using the Integration Test Utility Tool</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Endpoint</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCC_Callout_Data__c/fields/VCC_Request_Body__c.field-meta.xml
<CustomField>
    <fullName>VCC_Request_Body__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>The body of the HTTP request that is used for the callout when using the Integration Test Utility Tool</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Request Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Callout_Data__c/fields/VCC_Request_Time__c.field-meta.xml
<CustomField>
    <fullName>VCC_Request_Time__c</fullName>
    <description>Timestamp for when the request is sent</description>
    <label>Request Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Callout_Data__c/fields/VCC_Response_Body__c.field-meta.xml
<CustomField>
    <fullName>VCC_Response_Body__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>The body of the response that is received after the request has been sent to the endpoint</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Response Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VCC_Callout_Data__c/fields/VCC_Response_Time__c.field-meta.xml
<CustomField>
    <fullName>VCC_Response_Time__c</fullName>
    <description>Timestamp for when the response is received</description>
    <label>Response Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Callout_Data__c/fields/VCC_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>VCC_Status_Code__c</fullName>
    <description>The response code that is received after the callout is completed</description>
    <label>Status Code</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/main/default/objects/vccEndpoint__mdt/vccEndpoint__mdt.object-meta.xml
<CustomObject>
    <description>This custom metadata type is used to store endpoints (ie. trailing path information) that, when combined with a Named Credential, will form a complete URL:
        {host}/{endpoint}</description>
    <label>Endpoint</label>
    <pluralLabel>Endpoints</pluralLabel>
</CustomObject>

sfdx-source/main/default/classes/VCC/VCC_CalloutDataDomainTest.cls
@IsTest
public with sharing class VCC_CalloutDataDomainTest {
    private static String username = 'coddomain';

    @TestSetup
    public static void makeData() {
        User testUser = VCC_TestDataFactory.insertUser('VAVET Base Profile');
        VCC_TestDataFactory.assignPermissionSetByName(testUser, 'VCC_Integration_Test_Utility_Base');
        testUser.Username = username + testUser.Username;
        update testUser;
    }

    public static User getTestUser() {
        return [SELECT Id FROM User WHERE Username LIKE :username + '%' LIMIT 1];
    }

    @IsTest
    static void convertHttpDataToCalloutDataTestHappy() {
        VCC_HttpIntercept_Observer.HttpData httpData = new VCC_HttpIntercept_Observer.HttpData();
        httpData.requestEndpoint = VCC_EndpointUtility.getEndpoint('Vdif', 'vccVDIFGetAdditionalSigners');
        httpData.requestMethod = 'GET';
        httpData.requestIsCompressed = false;
        httpData.requestBody = 'test';
        httpData.responseStatusCode = 200;
        httpData.responseStatus = 'idk';
        httpData.responseBody = 'some text';
        httpData.timeSent = 23;
        httpData.timeReceived = 34;

        String path = [SELECT Id, DeveloperName, Path__c FROM vccEndpoint__mdt WHERE DeveloperName = 'vccVDIFGetAdditionalSigners'].Path__c;

        Test.startTest();
        System.runAs(getTestUser()) {
            VCC_Callout_Data__c calloutData = new VCC_CalloutDataDomain().convertHttpDataToCalloutData(httpData);

            System.assert(calloutData.VCC_Endpoint__c.contains(path), 'Expected path in endpoint.');
            System.assert(calloutData.VCC_Request_Time__c == httpData.timeSent, 'Expected values to match.');
            System.assert(calloutData.VCC_Request_Body__c == httpData.requestBody, 'Expected values to match.');
            System.assert(calloutData.VCC_Response_Time__c == httpData.timeReceived, 'Expected values to match.');
            System.assert(calloutData.VCC_Response_Body__c == httpData.responseBody, 'Expected null.');
            System.assert(calloutData.VCC_Status_Code__c == httpData.responseStatusCode, 'Expected values to match.');
        }
        Test.stopTest();
    }

    @IsTest
    static void convertHttpDataToCalloutDataTestNulls() {
        Test.startTest();
        System.runAs(getTestUser()) {
            VCC_HttpIntercept_Observer.HttpData httpData = new VCC_HttpIntercept_Observer.HttpData();
            httpData.requestEndpoint = null;
            httpData.requestMethod = null;
            httpData.requestIsCompressed = null;
            httpData.requestBody = null;
            httpData.responseStatusCode = null;
            httpData.responseStatus = null;
            httpData.responseBody = null;
            httpData.timeSent = null;
            httpData.timeReceived = null;

            VCC_Callout_Data__c calloutData = new VCC_CalloutDataDomain().convertHttpDataToCalloutData(httpData);

            System.assert(calloutData.VCC_Endpoint__c == null, 'Expected null.');
            System.assert(calloutData.VCC_Request_Time__c == null, 'Expected null.');
            System.assert(calloutData.VCC_Request_Body__c == null, 'Expected null.');
            System.assert(calloutData.VCC_Response_Time__c == null, 'Expected null.');
            System.assert(calloutData.VCC_Response_Body__c == null, 'Expected null.');
            System.assert(calloutData.VCC_Status_Code__c == null, 'Expected null.');
        }
        Test.stopTest();
    }

    @IsTest
    static void convertHttpDataToCalloutDataTestSad() {
        Test.startTest();
        System.runAs(getTestUser()) {
            VCC_Callout_Data__c calloutData = new VCC_CalloutDataDomain().convertHttpDataToCalloutData(null);
        }
        Test.stopTest();
    }
}