force-app/main/default/objects/VCC_Callout_Data__c/VCC_Callout_Data__c.object-meta.xml
<CustomObject>
    <description>Used for the Integration Test Utility, holding info about the vdif/mpi callouts that are a part of the note-signing-process.</description>
    <label>Callout Data</label>
    <nameField>
        <displayFormat>COD-{0000}</displayFormat>
        <label>Callout Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Callout Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VCC_Callout_Data__c/fields/VCC_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>VCC_Endpoint__c</fullName>
    <description>The endpoint that is used for the callout when using the Integration Test Utility Tool</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Endpoint</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCC_Callout_Data__c/fields/VCC_Request_Body__c.field-meta.xml
<CustomField>
    <fullName>VCC_Request_Body__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>The body of the HTTP request that is used for the callout when using the Integration Test Utility Tool</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Request Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Callout_Data__c/fields/VCC_Request_Time__c.field-meta.xml
<CustomField>
    <fullName>VCC_Request_Time__c</fullName>
    <description>Timestamp for when the request is sent</description>
    <label>Request Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Callout_Data__c/fields/VCC_Response_Body__c.field-meta.xml
<CustomField>
    <fullName>VCC_Response_Body__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>The body of the response that is received after the request has been sent to the endpoint</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Response Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VCC_Callout_Data__c/fields/VCC_Response_Time__c.field-meta.xml
<CustomField>
    <fullName>VCC_Response_Time__c</fullName>
    <description>Timestamp for when the response is received</description>
    <label>Response Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Callout_Data__c/fields/VCC_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>VCC_Status_Code__c</fullName>
    <description>The response code that is received after the callout is completed</description>
    <label>Status Code</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/main/default/classes/VCC/VCC_CalloutDataDomain.cls
public with sharing class VCC_CalloutDataDomain {
    public VCC_Callout_Data__c convertHttpDataToCalloutData(VCC_HttpIntercept_Observer.HttpData httpData) {
        if (httpData == null) {
            return new VCC_Callout_Data__c();
        }
        VCC_Callout_Data__c calloutData = new VCC_Callout_Data__c(
            VCC_Request_Time__c = httpData.timeSent,
            VCC_Request_Body__c = VCC_String_Utilities.truncateStringForField(httpData.requestBody, VCC_Callout_Data__c.VCC_Request_Body__c),
            VCC_Endpoint__c = (!String.isBlank(httpData.requestEndpoint)) ? VCC_EndpointUtility.getUrlForNamedCredential(httpData.requestEndpoint) : null,
            VCC_Response_Time__c = httpData.timeReceived,
            VCC_Response_Body__c = VCC_String_Utilities.truncateStringForField(httpData.responseBody, VCC_Callout_Data__c.VCC_Response_Body__c),
            VCC_Status_Code__c = httpData.responseStatusCode
        );
        return calloutData;
    }
}