force-app/main/default/objects/VCC_Callout_Data__c/VCC_Callout_Data__c.object-meta.xml
<CustomObject>
    <description>Used for the Integration Test Utility, holding info about the vdif/mpi callouts that are a part of the note-signing-process.</description>
    <label>Callout Data</label>
    <nameField>
        <displayFormat>COD-{0000}</displayFormat>
        <label>Callout Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Callout Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VCC_Callout_Data__c/fields/VCC_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>VCC_Endpoint__c</fullName>
    <description>The endpoint that is used for the callout when using the Integration Test Utility Tool</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Endpoint</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VCC/VCC_CalloutDataServiceTest.cls
@IsTest
public with sharing class VCC_CalloutDataServiceTest {
    private static String username = 'calloutdata';

    @TestSetup
    public static void makeData() {
        User testUser = VCC_TestDataFactory.insertUser('VAVET Base Profile');
        VCC_TestDataFactory.assignPermissionSetByName(testUser, 'VCC_Integration_Test_Utility_Base');
        testUser.Username = username + testUser.Username;
        update testUser;
    }

    public static User getTestUser() {
        return [SELECT Id FROM User WHERE Username LIKE :username + '%' LIMIT 1];
    }

    @IsTest
    static void stubTest() {
        Test.startTest();
        VCC_Stub stub = VCC_CalloutDataService.stub();
        System.assert(VCC_CalloutDataService.instance === stub.instance, 'Expected privateInstance to be stub.');
        Test.stopTest();
    }

    @IsTest
    static void insertNewCalloutDataHappy() {
        VCC_Stub calloutDataDomainStub = new VCC_Stub(VCC_CalloutDataDomain.class);
        VCC_CalloutDataDomain calloutDataDomain = (VCC_CalloutDataDomain) calloutDataDomainStub.instance;
        calloutDataDomainStub.setReturnValue('convertHttpDataToCalloutData', new VCC_Callout_Data__c(VCC_Endpoint__c = 'test'));

        Exception unexpectedException;

        Test.startTest();
        System.runAs(getTestUser()) {
            VCC_Callout_Data__c calloutData;

            try {
                calloutData = VCC_CalloutDataService.instance.insertNewCalloutData(null, calloutDataDomain);
            } catch (Exception e) {
                unexpectedException = e;
            }

            System.assert(calloutData != null, 'Unexpected null.');
            System.assert(unexpectedException == null, 'Unexpected exception.');
        }
        Test.stopTest();
    }
}