force-app/main/default/objects/PC_Exception__c/PC_Exception__c.object-meta.xml
<CustomObject>
    <description>Object to display Exceptions to a Schedule</description>
    <label>PrC Exception</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Exception</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PrC Exceptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/PC_Exception__c/fields/Day_of_Week_fmla__c.field-meta.xml
<CustomField>
    <fullName>Day_of_Week_fmla__c</fullName>
    <description>Converts selected Date to the corresponding day of the week.</description>
    <formula
    >CASE(WEEKDAY(PC_Date__c), 1, &quot;Sunday&quot;, 2, &quot;Monday&quot;, 3, &quot;Tuesday&quot;, 4, &quot;Wednesday&quot;, 5, &quot;Thursday&quot;, 6, &quot;Friday&quot;,
        7, &quot;Saturday&quot;, &quot;N/A&quot;)</formula>
    <label>Day of Week</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PC_Exception__c/fields/PC_Date__c.field-meta.xml
<CustomField>
    <fullName>PC_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date</label>
    <type>Date</type>
</CustomField>

sfdx-source/main/default/objects/PC_Exception__c/fields/PC_Day_of_Week__c.field-meta.xml
<CustomField>
    <fullName>PC_Day_of_Week__c</fullName>
    <label>Day of Week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
            <value>
                <fullName>Sunday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PC_Exception__c/fields/PC_End_Time__c.field-meta.xml
<CustomField>
    <fullName>PC_End_Time__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/PC_Exception__c/fields/PC_Operating_Hours__c.field-meta.xml
<CustomField>
    <fullName>PC_Operating_Hours__c</fullName>
    <label>Operating Hours</label>
    <referenceTo>PC_Operating_Hours__c</referenceTo>
    <relationshipName>PC_Exceptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

sfdx-source/main/default/objects/PC_Exception__c/fields/PC_Service__c.field-meta.xml
<CustomField>
    <fullName>PC_Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>PC_Service__c</referenceTo>
    <relationshipName>Exceptions</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/objects/PC_Operating_Hours__c/PC_Operating_Hours__c.object-meta.xml
<CustomObject>
    <description>Object to display operating hours of a service and to hold time slots</description>
    <label>PrC Operating Hours</label>
    <nameField>
        <displayFormat>OH - {00000}</displayFormat>
        <label>Operating Hours</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrC Operating Hours</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/PC_Service__c/PC_Service__c.object-meta.xml
<CustomObject>
    <description>Object to display related VISNs, Territories, and Locations</description>
    <label>PrC Service</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Service Name (e.g. Eastern Cardio Group)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PrC Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PC_Service__c/fields/PC_Operating_Hours__c.field-meta.xml
<CustomField>
    <fullName>PC_Operating_Hours__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Standard OperatingHours object. Likely not needed, can be removed later as we have a lookup field to the PC Operating Hours object</description>
    <label>Operating Hours Standard</label>
    <referenceTo>OperatingHours</referenceTo>
    <relationshipName>Services_Standard</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/objects/PC_Service__c/fields/PC_Operating_Hours_Lookup__c.field-meta.xml
<CustomField>
    <fullName>PC_Operating_Hours_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to PC Operating Hours</description>
    <label>Operating Hours</label>
    <referenceTo>PC_Operating_Hours__c</referenceTo>
    <relationshipName>OperatingHours</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PC_Service__c/fields/PC_Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>PC_Time_Zone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Eastern Standard Time</fullName>
            </value>
            <value>
                <fullName>Central Standard Time</fullName>
            </value>
            <value>
                <fullName>Mountain Standard Time</fullName>
            </value>
            <value>
                <fullName>Pacific Standard Time</fullName>
            </value>
            <value>
                <fullName>Alaska Standard Time</fullName>
            </value>
            <value>
                <fullName>Hawaii-Aleutian Standard Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PC_Time_Slot__c/PC_Time_Slot__c.object-meta.xml
<CustomObject>
    <description>Object to collect specific information for coverage hours and exceptions.</description>
    <label>PrC Time Slot</label>
    <nameField>
        <displayFormat>TS-{00000}</displayFormat>
        <label>Time Slot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrC Time Slots</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PC_Time_Slot__c/fields/PC_Date__c.field-meta.xml
<CustomField>
    <fullName>PC_Date__c</fullName>
    <defaultValue>Now()</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PC_Time_Slot__c/fields/PC_End__c.field-meta.xml
<CustomField>
    <fullName>PC_End__c</fullName>
    <defaultValue>TIMEVALUE(&quot;17:00:00.000&quot;)</defaultValue>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/PC_Time_Slot__c/fields/PC_Operating_Hours__c.field-meta.xml
<CustomField>
    <fullName>PC_Operating_Hours__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Operating Hours</label>
    <referenceTo>PC_Operating_Hours__c</referenceTo>
    <relationshipLabel>PC_Time Slots</relationshipLabel>
    <relationshipName>Time_Slot</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PC_Time_Slot__c/fields/PC_Start__c.field-meta.xml
<CustomField>
    <fullName>PC_Start__c</fullName>
    <defaultValue>TIMEVALUE(&quot;08:00:00.000&quot;)</defaultValue>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

sfdx-source/main/default/classes/PC/pcServiceOperatingHoursController.cls
/**
 * @description       : controller for Service's Operating Hours component
 * @author            : BAH
 * @group             :
 * @last modified on  : 09-07-2023
 * @last modified by  : BAH
 **/
@SuppressWarnings(
    'PMD.ApexDoc, PMD.ClassNamingConventions, PMD.ExcessivePublicCount, PMD.VariableNamingConventions, PMD.LocalVariableNamingConventions, PMD.FieldDeclarationsShouldBeAtStart, PMD.PropertyNamingConventions'
)
public with sharing class pcServiceOperatingHoursController {
    /**
     * @description
     * @author BAH | 09-07-2023
     * @param String serviceId
     * @return DataTableResponse
     **/
    @AuraEnabled
    public static DataTableResponse getOperatingHours(String serviceId) {
        DataTableResponse res = new DataTableResponse();
        List<PC_Service__c> serviceList = [SELECT Id, PC_Time_Zone__c, PC_Operating_Hours_Lookup__r.Id FROM PC_Service__c WHERE Id = :serviceId WITH SECURITY_ENFORCED];

        if (serviceList == null || serviceList.isEmpty()) {
            return res;
        } else {
            PC_Service__c service = serviceList[0];
            String opHourId = service.PC_Operating_Hours_Lookup__r.Id;
            List<PC_Operating_Hours__c> opHoursList = [
                SELECT
                    Id,
                    (SELECT Id, Name, PC_Day_of_Week__c, PC_Start__c, PC_End__c FROM Time_Slot__r),
                    (SELECT Id, Name, PC_Date__c, Day_of_Week_fmla__c, PC_End_Time__c, PC_Start_Time__c FROM PC_Exceptions__r)
                FROM PC_Operating_Hours__c
                WHERE Id = :opHourId
                WITH SECURITY_ENFORCED
            ];

            if (opHoursList == null || opHoursList.isEmpty()) {
                return res;
            } else {
                PC_Operating_Hours__c operatingHours = opHoursList[0];

                res.Id = service.Id;
                res.Timezone = service.PC_Time_Zone__c;
                res.opHoursId = operatingHours.Id;
                List<HourTableWrapper> timeslots = new List<HourTableWrapper>();
                for (PC_Time_Slot__c ts : operatingHours.Time_Slot__r) {
                    HourTableWrapper timeslotWrap = new HourTableWrapper();
                    timeslotWrap.Id = ts.Id;
                    timeslotWrap.DayOfWeek = ts.PC_Day_of_Week__c;
                    DateTime dtStart = DateTime.newInstance(Date.today(), ts.PC_Start__c);
                    DateTime dtEnd = DateTime.newInstance(Date.today(), ts.PC_End__c);
                    timeslotWrap.Timeslot = '' + dtStart.format('hh:mm a') + '-' + dtEnd.format('hh:mm a');
                    timeslots.add(timeslotWrap);
                }
                timeslots.sort();
                res.TimeSlots = timeslots;
                List<ExceptionTableWrapper> exceptionslots = new List<ExceptionTableWrapper>();
                for (PC_Exception__c ex : operatingHours.PC_Exceptions__r) {
                    ExceptionTableWrapper exceptionWrap = new ExceptionTableWrapper();
                    exceptionWrap.Id = ex.Id;
                    exceptionWrap.Name = ex.Name;
                    exceptionWrap.DateOf = ex.PC_Date__c.format();
                    exceptionWrap.DateHold = ex.PC_Date__c;
                    exceptionWrap.DayOfWeek = ex.Day_of_Week_fmla__c;
                    DateTime dtStart = DateTime.newInstance(ex.PC_Date__c, ex.PC_Start_Time__c);
                    DateTime dtEnd = DateTime.newInstance(ex.PC_Date__c, ex.PC_End_Time__c);
                    exceptionWrap.StartTime = dtStart.format('hh:mm a');
                    exceptionWrap.EndTime = dtEnd.format('hh:mm a');
                    exceptionslots.add(exceptionWrap);
                }
                exceptionslots.sort();
                res.Exceptions = exceptionslots;
            }
        }
        return res;
    }

    /**
     * @description       : DataTable Response wrapper
     * @author            : BAH
     **/
    public class DataTableResponse {
        @AuraEnabled
        public String Id { get; set; }
        @AuraEnabled
        public String Timezone { get; set; }
        @AuraEnabled
        public String opHoursId { get; set; }
        @AuraEnabled
        public List<HourTableWrapper> TimeSlots { get; set; }
        @AuraEnabled
        public List<ExceptionTableWrapper> Exceptions { get; set; }
    }

    /**
     * @description       : HourTable wrapper
     * @author            : BAH
     **/
    public class HourTableWrapper implements Comparable {
        @AuraEnabled
        public String Id { get; set; }
        @AuraEnabled
        public String DayOfWeek { get; set; }
        @AuraEnabled
        public String Timeslot { get; set; }

        private List<String> dayOrder = new List<String>{ 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday' };

        /**
         * @description
         * @author BAH | 09-07-2023
         * @param Object compareTo
         * @return Integer
         **/
        public Integer compareTo(Object compareTo) {
            //this sorts the returned list by day order
            HourTableWrapper compareToSlot = (HourTableWrapper) compareTo;
            Integer positionOf = dayOrder.indexOf(DayOfWeek);
            Integer positionOfCompare = dayOrder.indexOf(compareToSlot.DayOfWeek);
            if (positionOf == positionOfCompare) {
                return 0;
            }
            if (positionOf > positionOfCompare) {
                return 1;
            }
            return -1;
        }
    }

    /**
     * @description       : ExceptionTable wrapper
     * @author            : BAH
     **/
    public class ExceptionTableWrapper implements Comparable {
        @AuraEnabled
        public String Id { get; set; }
        @AuraEnabled
        public String Name { get; set; }
        @AuraEnabled
        public String DateOf { get; set; }
        @AuraEnabled
        public Date DateHold { get; set; }
        @AuraEnabled
        public String DayOfWeek { get; set; }
        @AuraEnabled
        public String StartTime { get; set; }
        @AuraEnabled
        public String EndTime { get; set; }

        /**
         * @description
         * @author BAH | 09-07-2023
         * @param Object compareTo
         * @return Integer
         **/
        public Integer compareTo(Object compareTo) {
            //this sorts the returned list by date
            ExceptionTableWrapper compareToSlot = (ExceptionTableWrapper) compareTo;
            Date DateHoldCompare = compareToSlot.DateHold;
            if (DateHold == DateHoldCompare) {
                return 0;
            }
            if (DateHold > DateHoldCompare) {
                return 1;
            }
            return -1;
        }
    }
}