sfdx-source/main/default/objects/VCC_Update_UI__e/VCC_Update_UI__e.object-meta.xml
<CustomObject>
    <description>Platform event that informs the current UI to refresh itself.</description>
    <label>VCC Update UI</label>
    <pluralLabel>VCC Update UI</pluralLabel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Update_UI__e/fields/isMeds__c.field-meta.xml
<CustomField>
    <fullName>isMeds__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isMeds</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/VCC/VCC_UpdateMeds_Invocable.cls
/**
 * VCC_UpdateMeds_Invocable
 * @description Invocable class LWC
 * @author Liberty
 * @date 01/16/2024
 * @version 1.0.0
 */
public with sharing class VCC_UpdateMeds_Invocable {
    @InvocableMethod(Label='Update Meds W/O refresh' Description='Updates the Meds LWC on this page' category='UI')
    public static void updateMeds() {
        EventBus.publish(new VCC_Update_UI__e(isMeds__c = true));
    }
}