force-app/main/default/objects/Contact/fields/FQ_Contact__c.field-meta.xml
<CustomField>
    <fullName>FQ_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Functional Queue CF</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/Contact/fields/User_ID__c.field-meta.xml
<CustomField>
    <fullName>User_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Finds USER ID from Users Standard object, can be used later in formulas.</description>
    <label>User ID</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/objects/Functional_Queue__c/Functional_Queue__c.object-meta.xml
<CustomObject>
    <description>Record used to represent a group and a queue in the backend when functional queue members are related to it.</description>
    <label>Functional Queue</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Functional Queue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functional Queues</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Functional_Queue__c/fields/Associated_Application__c.field-meta.xml
<CustomField>
    <fullName>Associated_Application__c</fullName>
    <label>Associated Application</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PSIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/Functional_Queue__c/fields/Public_Group_ID__c.field-meta.xml
<CustomField>
    <fullName>Public_Group_ID__c</fullName>
    <description>ID of the corresponding public group. This is autopopulated when a member is added to the functional queue.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Public Group ID will auto-populate after members are added to the functional queue.</inlineHelpText>
    <label>Public Group ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Functional_Queue__c/fields/Queue_ID__c.field-meta.xml
<CustomField>
    <fullName>Queue_ID__c</fullName>
    <description>Id of the corresponding Queue. This is autopopulated when a member is added to the functional queue.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Queue ID will auto-populate after members are added to the functional queue.</inlineHelpText>
    <label>Queue ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/Functional_Queue_Member__c/Functional_Queue_Member__c.object-meta.xml
<CustomObject>
    <description>Junction object to connect contacts to functional queues.</description>
    <label>Functional Queue Member</label>
    <nameField>
        <displayFormat>FQM-{0000}</displayFormat>
        <label>Functional Queue Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Functional Queue Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/Functional_Queue_Member__c/fields/Contact_Member__c.field-meta.xml
<CustomField>
    <fullName>Contact_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Member</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.User_ID__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Functional Queue Membership</relationshipLabel>
    <relationshipName>Functional_Queue_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/objects/Functional_Queue_Member__c/fields/Functional_Queue__c.field-meta.xml
<CustomField>
    <fullName>Functional_Queue__c</fullName>
    <label>Functional Queue</label>
    <referenceTo>Functional_Queue__c</referenceTo>
    <relationshipLabel>Functional Queue Members</relationshipLabel>
    <relationshipName>Functional_Queue_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/main/default/objects/Functional_Queue_Member__c/fields/User_ID__c.field-meta.xml
<CustomField>
    <fullName>User_ID__c</fullName>
    <formula>Contact_Member__r.User_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>User ID</label>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/classes/FunctionalQueueMemberHandlerTest.cls
/**
 * @description       :
 * @author            : jonathon.schleicher@b3groupinc.com
 * @group             :
 * @last modified on  : 12-15-2021
 * @last modified by  : jonathon.schleicher@b3groupinc.com
 **/
@IsTest
public with sharing class FunctionalQueueMemberHandlerTest {
    @IsTest
    private static void addNewMembersToCorrespondingGroups_givenNewFunctionalQueueMember_shouldAddUserToCorrespondingPublicGroup() {
        User testUser = createStandardTestUser('testUser');
        Account testAccount = createTestAccount('testAccount');
        Contact testContact = createTestContact(testUser.Id, 'testUser', testAccount.Id);
        Functional_Queue__c testFunctionalQueue = createTestFunctionalQueue('Test Functional Queue');

        Test.startTest();
        createTestFunctionalQueueMember(testFunctionalQueue.Id, testContact.Id);
        Test.stopTest();

        testFunctionalQueue = [SELECT Queue_ID__c, Public_Group_ID__c FROM Functional_Queue__c WHERE Id = :testFunctionalQueue.Id];
        System.assertNotEquals(null, testFunctionalQueue.Queue_ID__c);
        System.assertNotEquals(null, testFunctionalQueue.Public_Group_ID__c);

        // Check that the user was successfully added to group
        GroupMember functionalQueueMember = [SELECT Id FROM GroupMember WHERE GroupId = :testFunctionalQueue.Public_Group_ID__c AND UserOrGroupId = :testUser.Id];
        System.assertNotEquals(null, functionalQueueMember);
    }

    @IsTest
    private static void deleteFunctionalQueueGroupMembers_givenDeletedFunctionalQueueMember_shouldRemoveUserFromCorrespondingPublicGroup() {
        User testUser = createStandardTestUser('testUser');
        Account testAccount = createTestAccount('testAccount');
        Contact testContact = createTestContact(testUser.Id, 'testUser', testAccount.Id);
        Functional_Queue__c testFunctionalQueue = createTestFunctionalQueue('Test Functional Queue');

        Functional_Queue_Member__c testQueueMember = createTestFunctionalQueueMember(testFunctionalQueue.Id, testContact.Id);

        Test.startTest();
        delete testQueueMember;
        Test.stopTest();

        testFunctionalQueue = [SELECT Queue_ID__c, Public_Group_ID__c FROM Functional_Queue__c WHERE Id = :testFunctionalQueue.Id];
        List<GroupMember> functionalQueueMembers = [SELECT Id FROM GroupMember WHERE GroupId = :testFunctionalQueue.Public_Group_ID__c];
        System.assertEquals(0, functionalQueueMembers.size());
    }

    private static User createStandardTestUser(String lastName) {
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
        User u = new User(
            Alias = lastName,
            Email = lastName + '@testorg.com',
            EmailEncodingKey = 'UTF-8',
            LastName = lastName,
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = p.Id,
            FederationIdentifier = lastName,
            TimeZoneSidKey = 'America/New_York',
            UserName = lastName + '@testorg.com' + UserInfo.getOrganizationId() + String.valueof(Datetime.now()).replace(' ', '').replace(':', '').replace('-', '')
        );
        insert u;
        return u;
    }

    private static Functional_Queue__c createTestFunctionalQueue(String functionalQueueName) {
        Functional_Queue__c testFunctionalQueue = new Functional_Queue__c();
        testFunctionalQueue.Name = functionalQueueName;
        testFunctionalQueue.Associated_Application__c = 'PSIP';
        insert testFunctionalQueue;
        return testFunctionalQueue;
    }

    private static Functional_Queue_Member__c createTestFunctionalQueueMember(Id functionalQueueId, Id contactId) {
        Functional_Queue_Member__c testFunctionalQueueMember = new Functional_Queue_Member__c();
        testFunctionalQueueMember.Functional_Queue__c = functionalQueueId;
        testFunctionalQueueMember.Contact_Member__c = contactId;
        insert testFunctionalQueueMember;
        return testFunctionalQueueMember;
    }

    private static Account createTestAccount(String accountName) {
        Account testAccount = new Account();
        testAccount.Name = accountName;
        insert testAccount;
        return testAccount;
    }

    private static Contact createTestContact(Id userId, String lastName, Id accountId) {
        Contact testContact = new Contact();
        testContact.LastName = lastName;
        testContact.User_ID__c = userId;
        testContact.AccountId = accountId;
        testContact.FQ_Contact__c = true;
        testContact.Email = 'test@va.gov.test';
        insert testContact;
        return testContact;
    }
}