sfdx-source/main/default/objects/Case/recordTypes/VCC_Administrative.recordType-meta.xml
<RecordType>
    <fullName>VCC_Administrative</fullName>
    <active>true</active>
    <businessProcess>VCC Support Process</businessProcess>
    <description>--VA Health Connect scheduling, medication refills, enrollment, and other administrative cases</description>
    <label>Administrative and Scheduling Case</label>
</RecordType>

sfdx-source/main/default/objects/Case/recordTypes/VCC_Clinical_Triage.recordType-meta.xml
<RecordType>
    <fullName>VCC_Clinical_Triage</fullName>
    <active>true</active>
    <businessProcess>VCC Support Process</businessProcess>
    <description>--VA Health Connect nursing and symptom cases</description>
    <label>Clinical Triage Case</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/VCC_Vitrual_Clinic_Visit.recordType-meta.xml
<RecordType>
    <fullName>VCC_Vitrual_Clinic_Visit</fullName>
    <active>true</active>
    <businessProcess>VCC Support Process</businessProcess>
    <description>--VA Health Connect virtual visits with medical providers</description>
    <label>Virtual Clinic Visit Case</label>
</RecordType>

force-app/main/default/objects/VCC_Case_Metrics__c/VCC_Case_Metrics__c.object-meta.xml
<CustomObject>
    <description>An extension of the Case object to track metrics for reporting purposes.</description>
    <label>Case Metrics</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>Case Metrics Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VCC_Case_Metrics__c/fields/VCC_Case__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case__c</fullName>
    <description>The parent case of the Case Metrics record.</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Metrics</relationshipLabel>
    <relationshipName>Case_Metrics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Case_Metrics__c/fields/VCC_Child_Case__c.field-meta.xml
<CustomField>
    <fullName>VCC_Child_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Child Case from the Parent Case.</description>
    <label>Child Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Metrics (Child Case)</relationshipLabel>
    <relationshipName>Case_Metrics_Child_Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCC_Case_Metrics__c/fields/VCC_VISN__c.field-meta.xml
<CustomField>
    <fullName>VCC_VISN__c</fullName>
    <description>This field holds the VISN of the parent Case whether the Case owner is a User or a Queue. This is assigned in the following flows: VCC_Assign_Case_to_Me, VCC_Case_Subflow_Follow_Up, VCC_Create_Related_Case</description>
    <encryptionScheme>None</encryptionScheme>
    <label>VISN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Case_Metrics__c/recordTypes/VCC_Reporting.recordType-meta.xml
<RecordType>
    <fullName>VCC_Reporting</fullName>
    <active>true</active>
    <description>Record type for reporting purposes.</description>
    <label>Reporting</label>
</RecordType>

force-app/main/default/objects/VCC_Queue_Mapping__mdt/VCC_Queue_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>This will be used by VAHC to reference queues when logic is needed to determine which queue a case should be routed to.</description>
    <label>VCC Queue Mapping</label>
    <pluralLabel>VCC Queue Mappings</pluralLabel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Queue_Mapping__mdt/fields/VCC_VISN_Name__c.field-meta.xml
<CustomField>
    <fullName>VCC_VISN_Name__c</fullName>
    <description>Maps to Owner.Division (.e.g VISN 9)</description>
    <label>VISN Name</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_VISN__c/VCC_VISN__c.object-meta.xml
<CustomObject>
    <description>Tracks the VISNs for the Service Onboarding Tracker App</description>
    <label>VISN</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>VISN Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VISNs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/VCC/VCC_CaseMetricLogic.cls
/**
 * @description this is the logic class for manipulating that houses the business logic for the Case Metric object.
 * @author BAH
 * @see VCR_CaseMetricRepo
 * @see VCC_GenericBatch
 */
public without sharing class VCC_CaseMetricLogic extends ABS_BatchExecutioner {
    private static final String VCC_REPORTING = 'VCC_Reporting';
    private static final List<String> DEVELOPER_NAMES = new List<String>{
        'VCC_Administrative',
        'VCC_Clinical_Triage',
        'VCC_Vitrual_Clinic_Visit'
    };
    private static final String EXECUTIONER_NAME = 'VCC_CaseMetricLogic';

    private final String queryLocator;
    @TestVisible
    private Map<String, VCC_Queue_Mapping__mdt> devNameToQueueMapping;
    private final Map<String, Object> bindParams;
    private final String recordTypeId;
    private List<VCC_Case_Metrics__c> upsertMetricCases;
    private List<Case> inputCaseList;

    /**
     * @description property for the caseMetricRepo object
     * provides access to the methods in the VCR_CaseMetricRepo class
     * static so that it can be accessed from the test class
     * @see VCR_CaseMetricRepo
     */
    @TestVisible
    private static VCR_CaseMetricRepo caseMetricRepo {
        get {
            return caseMetricRepo = caseMetricRepo ?? new VCR_CaseMetricRepo();
        }
        set;
    }

    /**
     * @description property for the caseRepo object
     * provides access to the methods in the VCR_CaseRepo class
     * static so that it can be accessed from the test class
     * @see VCR_CaseRepo
     */
    @TestVisible
    private static VCR_CaseRepo caseRepo {
        get {
            return caseRepo ?? new VCR_CaseRepo();
        }
        set;
    }

    /**
     * @description This is the constructor for the VCC_CaseMetricLogic class.
     * It initializes the object by querying and locating the necessary data.
     */
    public VCC_CaseMetricLogic() {
        queryLocator = getQueryLocatorString();
        devNameToQueueMapping = VCC_Queue_Mapping__mdt.getAll();
        bindParams = getBindVariables();
        recordTypeId = getRecordTypeId();
        super.executionerName = EXECUTIONER_NAME;
    }

    /**
     * @description This method fetches and returns the query string from the caseRepo.
     * @return String Returns the query string.
     */
    public override String getQueryLocatorString() {
        return caseRepo.getQueryLocatorString();
    }
    /**
     * @description This method fetches and returns the query locator from the caseRepo.
     * @param query The query string to process
     * @return Database.QueryLocator Returns the query locator.
     */
    public override Database.QueryLocator getQueryLocator(String query) {
        if (String.isBlank(query)) {
            return null;
        }
        return caseRepo.getQueryLocator(query, this.bindParams);
    }

    /**
     * @description This method fetches and returns the bind variables from the caseRepo.
     * @return Map<String, Object> Returns the bind variables.
     */
    public override Map<String, Object> getBindVariables() {
        return new Map<String, Object>{ 'developerNames' => DEVELOPER_NAMES };
    }

    /**
     * @description This method processes a list of Case records. It collects important information from the given Case records
     * including their Id, ParentId if any, and associated metrics. Then, it retrieves related childCase records.
     * If an associated metric record doesn't exist for a Case and it is not a child Case, a new metric record is created with detailed properties.
     * @param inputList List of Case records to process
     */
    public override void execute(List<SObject> inputList) {
        this.inputCaseList = (List<Case>) inputList;
        upsertMetricCases = new List<VCC_Case_Metrics__c>();
        for (Case currentCase : inputCaseList) {
            upsertMetricCases.add(generateCaseMetrics(currentCase));
        }

        caseMetricRepo.upsertCaseMetrics(upsertMetricCases);
    }
    /**
     * @description This method generates a VCC_Case_Metrics__c record for the given Case record.
     * It sets the VCC_Case__c, VCC_Child_Case__c, VCC_VISN__c, and RecordTypeId fields of the VCC_Case_Metrics__c record.
     * @param currentCase The Case record to process
     * @return VCC_Case_Metrics__c Returns the generated VCC_Case_Metrics__c record.
     */
    @TestVisible
    private VCC_Case_Metrics__c generateCaseMetrics(Case currentCase) {
        VCC_Case_Metrics__c caseMetrics = currentCase?.Case_Metrics__r != null && !currentCase.Case_Metrics__r.isEmpty()
            ? currentCase.Case_Metrics__r[0]
            : new VCC_Case_Metrics__c();
        if (currentCase?.Cases != null && !currentCase.Cases.isEmpty()) {
            caseMetrics.VCC_Child_Case__c = currentCase.Cases[0].Id;
        }
        if (caseMetrics?.Id == null) {
            caseMetrics.VCC_Case__c = currentCase?.Id; //If the caseMetrics is new, set the VCC_Case__c field
        }
        caseMetrics.VCC_VISN__c = getRecordVISNName(currentCase);
        caseMetrics.RecordTypeId = recordTypeId;

        return caseMetrics;
    }
    /**
     * @description This method fetches and returns the VISN Name of the record.
     * @param inputCase The Case record to process
     * @return String Returns the VISN Name of the record.
     */
    @TestVisible
    private String getRecordVISNName(Case inputCase) {
        String recordVISNName;
        if (inputCase.Owner instanceof User) {
            User tempUser = inputCase.Owner;
            recordVISNName = tempUser.Division;
        } else if (inputCase.Owner instanceof Group && inputCase.OwnerId != null) {
            Group tempGroup = inputCase.Owner;
            String developerName = tempGroup.DeveloperName;
            if (devNameToQueueMapping.containsKey(developerName)) {
                recordVISNName = devNameToQueueMapping.get(developerName).VCC_VISN_Name__c;
            }
        } else {
            recordVISNName = '';
        }
        return recordVISNName;
    }
    /**
     * @description This method fetches and returns the RecordTypeId of the VCC_Reporting record type.
     * @return String Returns the RecordTypeId of the VCC_Reporting record type.
     */
    @TestVisible
    private static String getRecordTypeId() {
        return VCC_Case_Metrics__c.SObjectType.getDescribe(SObjectDescribeOptions.DEFERRED)
            .getRecordTypeInfosByDeveloperName()
            .get(VCC_REPORTING)
            .getRecordTypeId();
    }
}