sfdx-source/main/default/objects/NTSP_Case__c/NTSP_Case__c.object-meta.xml
<CustomObject>
    <label>NTSP Case</label>
    <nameField>
        <displayFormat>NTSP-{0000}</displayFormat>
        <label>NTSP Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NTSP Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NTSP_Case__c/fields/Consult_Date__c.field-meta.xml
<CustomField>
    <fullName>Consult_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Consult Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NTSP_Case__c/fields/Consult_Time_Local_Time_24_hrs__c.field-meta.xml
<CustomField>
    <fullName>Consult_Time_Local_Time_24_hrs__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Patient&apos;s local time</inlineHelpText>
    <label>Consult Time (Local Time 24 hrs)</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NTSP_Case__c/fields/LKW_Date__c.field-meta.xml
<CustomField>
    <fullName>LKW_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>LKW Date</label>
    <type>Date</type>
</CustomField>

sfdx-source/main/default/objects/NTSP_Case__c/fields/LKW_Time_24_hr__c.field-meta.xml
<CustomField>
    <fullName>LKW_Time_24_hr__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>LKW Time 24 hr</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NTSP_Case__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inpatient</fullName>
            </value>
            <value>
                <fullName>ED</fullName>
            </value>
            <value>
                <fullName>ICU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NTSP_Case__c/fields/NTSP_Facility__c.field-meta.xml
<CustomField>
    <fullName>NTSP_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NTSP Facility</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This facility is not registered as a NTSP site.</errorMessage>
        <filterItems>
            <field>NTSP_Facility__c.NTSP_Registered_Site__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>NTSP_Facility__c</referenceTo>
    <relationshipLabel>NTSP Cases</relationshipLabel>
    <relationshipName>NTSP_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NTSP_Case__c/fields/Telestroke_Consultant__c.field-meta.xml
<CustomField>
    <fullName>Telestroke_Consultant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Telestroke Consultant</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>User.Role_Type__c</field>
            <operation>equals</operation>
            <value>NTSP Consultant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>NTSP_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NTSP_Facility__c/NTSP_Facility__c.object-meta.xml
<CustomObject>
    <label>NTSP Facility</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>NTSP Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NTSP Facilities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NTSP_Facility__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>NTSP Facilities</relationshipLabel>
    <relationshipName>NTSP_Facilities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/objects/NTSP_Nurse_Note__c/NTSP_Nurse_Note__c.object-meta.xml
<CustomObject>
    <label>NTSP Nurse Note</label>
    <nameField>
        <displayFormat>NN-{0000}</displayFormat>
        <label>NTSP Nurse Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NTSP Nurse Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NTSP_Nurse_Note__c/fields/BEFAST_Arm_Leg_Numbness__c.field-meta.xml
<CustomField>
    <fullName>BEFAST_Arm_Leg_Numbness__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Arm/Leg Numbness</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/NTSP_Nurse_Note__c/fields/BEFAST_Arm_Leg_Weakness__c.field-meta.xml
<CustomField>
    <fullName>BEFAST_Arm_Leg_Weakness__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Arm/Leg Weakness</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/NTSP_Nurse_Note__c/fields/BEFAST_Balance_Difficulty__c.field-meta.xml
<CustomField>
    <fullName>BEFAST_Balance_Difficulty__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Balance Difficulty</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NTSP_Nurse_Note__c/fields/BEFAST_Blurred_Vision__c.field-meta.xml
<CustomField>
    <fullName>BEFAST_Blurred_Vision__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Blurred Vision</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NTSP_Nurse_Note__c/fields/BEFAST_Double_Vision__c.field-meta.xml
<CustomField>
    <fullName>BEFAST_Double_Vision__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Double Vision</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/NTSP_Nurse_Note__c/fields/BEFAST_Eyes_Vision_Changes__c.field-meta.xml
<CustomField>
    <fullName>BEFAST_Eyes_Vision_Changes__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Eyes/Vision Changes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NTSP_Nurse_Note__c/fields/BEFAST_Facial_Weakness__c.field-meta.xml
<CustomField>
    <fullName>BEFAST_Facial_Weakness__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Facial Weakness</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NTSP_Nurse_Note__c/fields/BEFAST_Incoordination__c.field-meta.xml
<CustomField>
    <fullName>BEFAST_Incoordination__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Incoordination</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NTSP_Nurse_Note__c/fields/BEFAST_Left_Droop__c.field-meta.xml
<CustomField>
    <fullName>BEFAST_Left_Droop__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Left Droop</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NTSP_Nurse_Note__c/fields/BEFAST_Left_Lower_Extremity_Numbness__c.field-meta.xml
<CustomField>
    <fullName>BEFAST_Left_Lower_Extremity_Numbness__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Left Lower Extremity</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/NTSP_Nurse_Note__c/fields/BEFAST_Left_Lower_Extremity_Weakness__c.field-meta.xml
<CustomField>
    <fullName>BEFAST_Left_Lower_Extremity_Weakness__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Left Lower Extremity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NTSP_Nurse_Note__c/fields/BEFAST_Left_Numbness__c.field-meta.xml
<CustomField>
    <fullName>BEFAST_Left_Numbness__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Left Numbness</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NTSP_Nurse_Note__c/fields/BEFAST_Left_Upper_Extremity_Numbness__c.field-meta.xml
<CustomField>
    <fullName>BEFAST_Left_Upper_Extremity_Numbness__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Left Upper Extremity</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/NTSP_Nurse_Note__c/fields/BEFAST_Left_Upper_Extremity_Weakness__c.field-meta.xml
<CustomField>
    <fullName>BEFAST_Left_Upper_Extremity_Weakness__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Left Upper Extremity</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/NTSP_Nurse_Note__c/fields/BEFAST_Loss_of_Vision__c.field-meta.xml
<CustomField>
    <fullName>BEFAST_Loss_of_Vision__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Loss of Vision</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/NTSP_Nurse_Note__c/fields/BEFAST_Right_Droop__c.field-meta.xml
<CustomField>
    <fullName>BEFAST_Right_Droop__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Right Droop</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NTSP_Nurse_Note__c/fields/BEFAST_Right_Lower_Extremity_Numbness__c.field-meta.xml
<CustomField>
    <fullName>BEFAST_Right_Lower_Extremity_Numbness__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Right Lower Extremity</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/NTSP_Nurse_Note__c/fields/BEFAST_Right_Lower_Extremity_Weakness__c.field-meta.xml
<CustomField>
    <fullName>BEFAST_Right_Lower_Extremity_Weakness__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Right Lower Extremity</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/NTSP_Nurse_Note__c/fields/BEFAST_Right_Numbness__c.field-meta.xml
<CustomField>
    <fullName>BEFAST_Right_Numbness__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Right Numbness</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NTSP_Nurse_Note__c/fields/BEFAST_Right_Upper_Extremity_Weakness__c.field-meta.xml
<CustomField>
    <fullName>BEFAST_Right_Upper_Extremity_Weakness__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Right Upper Extremity</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/NTSP_Nurse_Note__c/fields/BEFAST_Symptoms__c.field-meta.xml
<CustomField>
    <fullName>BEFAST_Symptoms__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BEFAST Symptoms</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NTSP_Nurse_Note__c/fields/BEFAST_Walking_Difficulty__c.field-meta.xml
<CustomField>
    <fullName>BEFAST_Walking_Difficulty__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Walking Difficulty</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NTSP_Nurse_Note__c/fields/Criteria_Met__c.field-meta.xml
<CustomField>
    <fullName>Criteria_Met__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Criteria Met</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NTSP_Nurse_Note__c/fields/Direct_Telephone_Number_of_Caller__c.field-meta.xml
<CustomField>
    <fullName>Direct_Telephone_Number_of_Caller__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Direct Telephone Number of Caller</label>
    <type>Phone</type>
</CustomField>

sfdx-source/main/default/objects/NTSP_Nurse_Note__c/fields/Extension_of_Caller__c.field-meta.xml
<CustomField>
    <fullName>Extension_of_Caller__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Extension of Caller</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/NTSP_Nurse_Note__c/fields/Handoff_Date__c.field-meta.xml
<CustomField>
    <fullName>Handoff_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Handoff Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NTSP_Nurse_Note__c/fields/Handoff_Time__c.field-meta.xml
<CustomField>
    <fullName>Handoff_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Handoff Time</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/NTSP_Nurse_Note__c/fields/LVO_Symptoms__c.field-meta.xml
<CustomField>
    <fullName>LVO_Symptoms__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LVO Symptoms</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NTSP_Nurse_Note__c/fields/Name_of_Caller__c.field-meta.xml
<CustomField>
    <fullName>Name_of_Caller__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Name of Caller</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NTSP_Nurse_Note__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Notes</label>
    <type>TextArea</type>
</CustomField>

sfdx-source/main/default/objects/NTSP_Nurse_Note__c/fields/NTSP_Case__c.field-meta.xml
<CustomField>
    <fullName>NTSP_Case__c</fullName>
    <label>NTSP Case</label>
    <referenceTo>NTSP_Case__c</referenceTo>
    <relationshipLabel>NTSP Nurse Notes</relationshipLabel>
    <relationshipName>NTSP_Nurse_Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/main/default/objects/NTSP_Nurse_Note__c/fields/Other_Description__c.field-meta.xml
<CustomField>
    <fullName>Other_Description__c</fullName>
    <description>Used to gather additional information from user when &quot;Other&quot; radio option is selected from Position of Caller field.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Other Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NTSP_Nurse_Note__c/fields/Physician_Caring_for_Patient__c.field-meta.xml
<CustomField>
    <fullName>Physician_Caring_for_Patient__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Physician Caring for Patient</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/NTSP_Nurse_Note__c/fields/Position_of_Caller__c.field-meta.xml
<CustomField>
    <fullName>Position_of_Caller__c</fullName>
    <label>Position of Caller</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Provider</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/NTSP_Nurse_Note__c/fields/Site_Requesting_Consultation__c.field-meta.xml
<CustomField>
    <fullName>Site_Requesting_Consultation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Site Requesting Consultation</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/classes/NTSP/NTSP_NurseNoteController.cls
/**
 * @description       : Class used as the controller for the ntsp_nurseNote and ntsp_caseSummary Lightning Web Component
 * @author            : George Elias
 * @group             : Liberty IT Solutions
 * @last modified on  : 02-16-2022
 * @last modified by  : George Elias
 * Modifications Log
 * Ver   Date         Author                               Modification
 * 1.0   02-16-2022   George Elias                          Initial Version
 **/
public with sharing class NTSP_NurseNoteController {
    /**
     * @description Method to fetch and return the case and note records
     * @author George Elias | 02-16-2022
     * @return  Map<String, Object> - Map containing 'case' and 'note' values
     **/
    @AuraEnabled(Cacheable=true)
    public static Map<String, Object> fetchCaseSummary(String caseId) {
        try {
            final Map<String, Object> returnMap = new Map<String, Object>();

            returnMap.put(
                'case',
                [
                    SELECT Id, Consult_Date__c, Consult_Time_Local_Time_24_hrs__c, LKW_Date__c, LKW_Time_24_hr__c, Telestroke_Consultant__r.Name, Location__c, NTSP_Facility__r.Name
                    FROM NTSP_Case__c
                    WHERE Id = :caseId
                    LIMIT 1
                ]
            );

            returnMap.put(
                'note',
                [
                    SELECT
                        Id,
                        Name_of_Caller__c,
                        Position_of_Caller__c,
                        Other_Description__c,
                        Direct_Telephone_Number_of_Caller__c,
                        Extension_of_Caller__c,
                        Physician_Caring_for_Patient__c,
                        BEFAST_Symptoms__c,
                        LVO_Symptoms__c,
                        Criteria_Met__c,
                        Handoff_Date__c,
                        Handoff_Time__c,
                        Site_Requesting_Consultation__c,
                        Notes__c,
                        BEFAST_Balance_Difficulty__c,
                        BEFAST_Incoordination__c,
                        BEFAST_Walking_Difficulty__c,
                        BEFAST_Eyes_Vision_Changes__c,
                        BEFAST_Blurred_Vision__c,
                        BEFAST_Double_Vision__c,
                        BEFAST_Loss_of_Vision__c,
                        BEFAST_Facial_Weakness__c,
                        BEFAST_Left_Droop__c,
                        BEFAST_Right_Droop__c,
                        BEFAST_Left_Numbness__c,
                        BEFAST_Right_Numbness__c,
                        BEFAST_Arm_Leg_Weakness__c,
                        BEFAST_Left_Lower_Extremity_Weakness__c,
                        BEFAST_Right_Lower_Extremity_Weakness__c,
                        BEFAST_Left_Upper_Extremity_Weakness__c,
                        BEFAST_Right_Upper_Extremity_Weakness__c,
                        BEFAST_Arm_Leg_Numbness__c,
                        BEFAST_Left_Lower_Extremity_Numbness__c,
                        BEFAST_Right_Lower_Extremity_Numbness__c,
                        BEFAST_Left_Upper_Extremity_Numbness__c,
                        BEFAST_Right_Upper_Extremity_Numbness__c,
                        BEFAST_Speech_Changes__c,
                        BEFAST_Difficulty_Comprehending_Words__c,
                        BEFAST_Difficulty_Finding_Words__c,
                        BEFAST_Slurred_Garbled_Speech__c,
                        BEFAST_LKW__c,
                        LVO_Hemiparesis__c,
                        LVO_Right_or_Left_Hemiparesis__c,
                        LVO_Arm_Leg_Weakness__c,
                        LVO_Left_Lower_Extremity_Weakness__c,
                        LVO_Right_Lower_Extremity_Weakness__c,
                        LVO_Left_Upper_Extremity_Weakness__c,
                        LVO_Right_Upper_Extremity_Weakness__c,
                        LVO_Arm_Leg_Numbness__c,
                        LVO_Left_Lower_Extremity_Numbness__c,
                        LVO_Right_Lower_Extremity_Numbness__c,
                        LVO_Left_Upper_Extremity_Numbness__c,
                        LVO_Right_Upper_Extremity_Numbness__c,
                        LVO_Vision_Loss__c,
                        LVO_Aphasia__c,
                        LVO_Neglect__c,
                        LVO_Gaze_Deviation__c,
                        LVO_LKW__c,
                        Consult_Type__c,
                        CreatedById
                    FROM NTSP_Nurse_Note__c
                    WHERE NTSP_Case__c = :caseId
                    LIMIT 1
                ]
            );

            final Boolean isNurse = FeatureManagement.checkPermission('NTSP_Triage_Nurse');
            returnMap.put('isNurse', isNurse);

            return returnMap;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}