sfdx-source/main/default/objects/NTSP_Case__c/NTSP_Case__c.object-meta.xml
<CustomObject>
    <label>NTSP Case</label>
    <nameField>
        <displayFormat>NTSP-{0000}</displayFormat>
        <label>NTSP Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NTSP Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NTSP_Case__c/fields/Consult_Date__c.field-meta.xml
<CustomField>
    <fullName>Consult_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Consult Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NTSP_Case__c/fields/Consult_Time_Local_Time_24_hrs__c.field-meta.xml
<CustomField>
    <fullName>Consult_Time_Local_Time_24_hrs__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Patient&apos;s local time</inlineHelpText>
    <label>Consult Time (Local Time 24 hrs)</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NTSP_Case__c/fields/Last_Four__c.field-meta.xml
<CustomField>
    <fullName>Last_Four__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Four</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/NTSP_Case__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NTSP_Case__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inpatient</fullName>
            </value>
            <value>
                <fullName>ED</fullName>
            </value>
            <value>
                <fullName>ICU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NTSP_Case__c/fields/NTSP_Facility__c.field-meta.xml
<CustomField>
    <fullName>NTSP_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NTSP Facility</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This facility is not registered as a NTSP site.</errorMessage>
        <filterItems>
            <field>NTSP_Facility__c.NTSP_Registered_Site__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>NTSP_Facility__c</referenceTo>
    <relationshipLabel>NTSP Cases</relationshipLabel>
    <relationshipName>NTSP_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NTSP_Case__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <defaultValue
    >IF(( $Permission.NTSP_Triage_Nurse = TRUE || $Permission.NTSP_Triage_Nurse_Manager = TRUE || $Permission.NTSP_Triage_Nurse_Peer_Reviewer = TRUE), &apos;Triaged&apos;,
        &apos;Consultant Created&apos;)</defaultValue>
    <label>Outcome</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Triaged</fullName>
            </value>
            <value>
                <fullName>Consultant Created</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Telephone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NTSP_Facility__c/NTSP_Facility__c.object-meta.xml
<CustomObject>
    <label>NTSP Facility</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>NTSP Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NTSP Facilities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NTSP_Facility__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>NTSP Facilities</relationshipLabel>
    <relationshipName>NTSP_Facilities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NTSP_Facility__c/fields/NTSP_Registered_Site__c.field-meta.xml
<CustomField>
    <fullName>NTSP_Registered_Site__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NTSP Registered Site</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NTSP_Facility__c/fields/Station_Code__c.field-meta.xml
<CustomField>
    <fullName>Station_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Site Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/NTSP_Nurse_Note__c/NTSP_Nurse_Note__c.object-meta.xml
<CustomObject>
    <label>NTSP Nurse Note</label>
    <nameField>
        <displayFormat>NN-{0000}</displayFormat>
        <label>NTSP Nurse Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NTSP Nurse Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/NTSP_Nurse_Note__c/fields/NTSP_Case__c.field-meta.xml
<CustomField>
    <fullName>NTSP_Case__c</fullName>
    <label>NTSP Case</label>
    <referenceTo>NTSP_Case__c</referenceTo>
    <relationshipLabel>NTSP Nurse Notes</relationshipLabel>
    <relationshipName>NTSP_Nurse_Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/main/default/classes/NTSP/NTSP_NurseNoteController_Test.cls
/**
 * @description       : Class used to test the NTSP_NurseNoteController Apex class
 * @author            : George Elias
 * @group             : Liberty IT Solutions
 * @last modified on  : 02-16-2022
 * @last modified by  : George Elias
 * Modifications Log
 * Ver   Date         Author                               Modification
 * 1.0   02-16-2022   George Elias                          Initial Version
 **/
@isTest
public class NTSP_NurseNoteController_Test {
    /**
     * @description Method to create test data for unit tests
     * @author George Elias | 02-16-2022
     * @return  void
     **/
    @TestSetup
    static void makeData() {
        final User testUser = [SELECT Id FROM User WHERE Profile.Name = 'System Administrator' AND isActive = TRUE LIMIT 1];

        System.runAs(testUser) {
            final Profile baseProfile = [SELECT Id FROM Profile WHERE Name = 'VAVET Base Profile'];

            Integer randomInt = Integer.valueOf(math.rint(math.random() * 1000000));

            final User nurse = new User(
                Email = 'test@test.com',
                EmailEncodingKey = 'UTF-8',
                LastName = 'NTSP Nurse',
                Alias = 'Nurse',
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US',
                ProfileId = baseProfile.Id,
                TimeZoneSidKey = 'America/Los_Angeles',
                UserName = 'nurse' + randomInt + '@ntsp.com'
            );

            insert nurse;

            final Id nursePM = [SELECT Id, MasterLabel FROM PermissionSetGroup WHERE MasterLabel = 'NTSP Triage Nurse'].Id;

            // PermissionSetAssignment psa = new PermissionSetAssignment(AssigneeId = nurse.Id, PermissionSetGroupId = nursePM);

            // insert psa;

            NTSP_TestDataFactory.mockPermGroupAssignment(nurse.Id, nursePM);
        }

        final Schema.Location loc = new Schema.Location(Name = 'Test', LocationType = 'Test', VAF_Facility_ID__c = '1234');
        insert loc;

        final NTSP_Facility__c ntspFacility = new NTSP_Facility__c(Name = 'Test', Station_Code__c = '12345', Location__c = loc.Id, NTSP_Registered_Site__c = true);
        insert ntspFacility;

        final NTSP_Case__c ntspCase = new NTSP_Case__c(
            Consult_Date__c = Date.today(),
            Consult_Time_Local_Time_24_hrs__c = '1122',
            Last_Name__c = 'Test',
            Last_Four__c = '1234',
            NTSP_Facility__c = ntspFacility.Id,
            Location__c = 'ED',
            outcome__c = 'Cancelled'
        );

        insert ntspCase;

        final NTSP_Nurse_Note__c note = new NTSP_Nurse_Note__c(NTSP_Case__c = ntspCase.Id);

        insert note;
    }

    /**
     * @description Method to test the fetchCaseSummary method in the NTSP_NurseNoteController class
     * @author George Elias | 02-16-2022
     * @return  void
     **/
    @isTest
    static void fetchCaseSummaryTest() {
        NTSP_Case__c ntspCase = [SELECT Id FROM NTSP_Case__c LIMIT 1];

        Map<String, Object> returnMap = NTSP_NurseNoteController.fetchCaseSummary(ntspCase.Id);

        List<NTSP_Case__c> caseList = (List<NTSP_Case__c>) returnMap.get('case');
        Boolean valueCheck = caseList[0].Id == ntspCase.Id;

        List<NTSP_Nurse_Note__c> noteList = (List<NTSP_Nurse_Note__c>) returnMap.get('note');
        valueCheck = valueCheck && noteList.size() == 1;
        System.assertEquals(valueCheck, true, 'valueCheck was determined to be false, excpected return values are incorrect');
    }
}