sfdx-source/main/default/objects/Tele_EC_Escalation_Status__c/Tele_EC_Escalation_Status__c.object-meta.xml
<CustomObject>
    <label>Tele-EC Escalation Status</label>
    <nameField>
        <displayFormat>tuces-{000000}</displayFormat>
        <label>Tele-EC Escalation Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tele-EC Escalation Statuses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Tele_EC_Escalation_Status__c/fields/TUC_Is_Current_Status__c.field-meta.xml
<CustomField>
    <fullName>TUC_Is_Current_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox for the current status.</description>
    <label>Is Current Status</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/Tele_EC_Escalation_Status__c/fields/TUC_Original_Pause_Record__c.field-meta.xml
<CustomField>
    <fullName>TUC_Original_Pause_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Self lookup to Tele-EC Escalation Status</description>
    <label>Original Pause Record</label>
    <referenceTo>Tele_EC_Escalation_Status__c</referenceTo>
    <relationshipLabel>Tele-EC Escalation Statuses</relationshipLabel>
    <relationshipName>TUC_Original_Pause_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/objects/Tele_EC_Escalation_Status__c/fields/TUC_Pause_Reason__c.field-meta.xml
<CustomField>
    <fullName>TUC_Pause_Reason__c</fullName>
    <description>This field is meant to help understand reasons the Tele-EC is placed on pause and realize any underlying trends.</description>
    <inlineHelpText>This field is meant to help understand reasons the Tele-EC is placed on pause and realize any underlying trends.</inlineHelpText>
    <label>Pause Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Provider unavailable- service at capacity</fullName>
            </value>
            <value>
                <fullName>Provider unavailable- on break</fullName>
            </value>
            <value>
                <fullName>Tele-EC closed (after hours)</fullName>
            </value>
            <value>
                <fullName>Technical issue (i.e, power outage, wifi)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/Tele_EC_Escalation_Status__c/fields/TUC_Queue_Type__c.field-meta.xml
<CustomField>
    <fullName>TUC_Queue_Type__c</fullName>
    <description>Used in TUC_CommonUtils apex class. Determines which type of queue the status record is being created for.</description>
    <label>Queue Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High Acuity</fullName>
            </value>
            <value>
                <fullName>Intermediate Acuity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/Tele_EC_Escalation_Status__c/fields/TUC_Status_Datetime__c.field-meta.xml
<CustomField>
    <fullName>TUC_Status_Datetime__c</fullName>
    <description>Used in tucCommonUtils apex class. Used to capture the status date/time</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Status Datetime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

sfdx-source/main/default/objects/Tele_EC_Escalation_Status__c/fields/TUC_Status_Type__c.field-meta.xml
<CustomField>
    <fullName>TUC_Status_Type__c</fullName>
    <description>Used in tucCommonUtils apex class. Determines if the status is paused or resumed</description>
    <label>Status Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Resumed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/Tele_EC_Escalation_Status__c/fields/TUC_VISN__c.field-meta.xml
<CustomField>
    <fullName>TUC_VISN__c</fullName>
    <description>Used in tucCommonUtils apex class. Used to capture the VISN</description>
    <encryptionScheme>None</encryptionScheme>
    <label>VISN</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/classes/TUC/TUC_EscalatePauseButtonControllerTest.cls
/**
 * @description       : Test Class for TUC_EscalatePauseButtonController
 * @author            : Booz Allen
 **/
@isTest
public with sharing class TUC_EscalatePauseButtonControllerTest {
    static final String TEST_QUEUE_TYPE = 'High Acuity'; //must match a Tele-EC Queue Type, defined in the TUC_Queue_Type__c field
    static final String TEST_PAUSE_REASON = 'Provider unavailable- service at capacity'; //must match a Tele-EC Pause Reason, defined in the TUC_Pause_Reason__c field

    /**
     * @description - Simple test for the get visn data
     */
    @isTest
    public static void unitTestGetVISNData() {
        User minimumAccessMolly = VATEST_UserFactory.createMinAccessPersonaUser(false);
        minimumAccessMolly.Division = 'VISN 0';
        System.runAs(minimumAccessMolly) {
            Test.startTest();
            String visn = TUC_EscalatePauseButtonController.getVISNData();
            Assert.areEqual('0', visn, 'Expected 0 but was ' + visn);
            Test.stopTest();
        }
    }

    /**
     * @description - Functional test for the status record creation. Builds out a mock record, stubs the create repo call, and then runs the function and tests.
     */
    @isTest
    public static void funcTestCreateStatus() {
        String providedVisn = '0';
        String queueType = TEST_QUEUE_TYPE;
        Tele_EC_Escalation_Status__c escalationStatusPrototype = new Tele_EC_Escalation_Status__c();
        DateTime sys = System.now();
        escalationStatusPrototype.TUC_Status_Datetime__c = DateTime.newInstance(
            sys.year(),
            sys.month(),
            sys.day(),
            sys.hour(),
            sys.minute(),
            0
        );
        escalationStatusPrototype.TUC_VISN__c = providedVisn;
        escalationStatusPrototype.TUC_Is_Current_Status__c = true;
        escalationStatusPrototype.TUC_Queue_Type__c = queueType;
        escalationStatusPrototype.TUC_Pause_Reason__c = TEST_PAUSE_REASON;
        escalationStatusPrototype.TUC_Status_Type__c = 'Paused';
        Tele_EC_Escalation_Status__c escalationStatusPrototypeResumed = new Tele_EC_Escalation_Status__c();
        escalationStatusPrototypeResumed.TUC_Status_Datetime__c = DateTime.newInstance(
            sys.year(),
            sys.month(),
            sys.day(),
            sys.hour(),
            sys.minute(),
            0
        );
        escalationStatusPrototypeResumed.TUC_VISN__c = providedVisn;
        escalationStatusPrototypeResumed.TUC_Is_Current_Status__c = true;
        escalationStatusPrototypeResumed.TUC_Queue_Type__c = queueType;
        escalationStatusPrototypeResumed.TUC_Pause_Reason__c = TEST_PAUSE_REASON;
        escalationStatusPrototypeResumed.TUC_Original_Pause_Record__c = null;
        escalationStatusPrototypeResumed.TUC_Status_Type__c = 'Resumed';
        List<Tele_EC_Escalation_Status__c> recordList = new List<Tele_EC_Escalation_Status__c>{
            escalationStatusPrototype
        };

        TUC_TeleEcEscalationStatusRepo stubRepo = (TUC_TeleEcEscalationStatusRepo) new VATEST_StubBuilder(
                TUC_TeleEcEscalationStatusRepo.class
            )
            .mockingMethodCall('getEscalationStatusWithVisnAndQueueType')
            .withParameterTypes(String.class, String.class)
            .withParameterValues(providedVisn, queueType)
            .returning(recordList)
            .mockingMethodCall('doUpdate')
            .withParameterTypes(sObject.class)
            .withParameterValues(escalationStatusPrototype)
            .returning()
            .mockingMethodCall('doCreate')
            .withParameterTypes(sObject.class)
            .withParameterValues(escalationStatusPrototypeResumed)
            .returning()
            .defineStub();
        TUC_EscalatePauseButtonController.memoizedEscalationRepo = stubRepo; // dependency injected a fake implementation of the repo.

        String fieldsJSON =
            '{"providedVISN":"0","queueType":"' +
            TEST_QUEUE_TYPE +
            '","pauseReason":"' +
            TEST_PAUSE_REASON +
            '"}';

        VATEST_UserBuilder builder = new VATEST_UserBuilder();
        User doctorUser = builder.withPermissionSet('TED_Medical_Provider_Group')
            .withUserProfile('VAVET Base Profile')
            .withStandardData()
            .build(false);

        System.runAs(doctorUser) {
            Test.startTest();
            String statusRet = TUC_EscalatePauseButtonController.createTeleEcStatusRecord(fieldsJSON);
            Assert.areEqual('Success', statusRet, 'Expected Success but was ' + statusRet);
            Test.stopTest();
        }
    }

    /**
     * @description - Functional test for the get escalation status. Mocks and creates an escalation record, stubs the query method on the repo, then tests that record is queried correctly
     */
    @isTest
    public static void funcTestGetStatus() {
        String providedVisn = '0';
        String queueType = TEST_QUEUE_TYPE;
        Tele_EC_Escalation_Status__c escalationStatusPrototype = new Tele_EC_Escalation_Status__c();
        DateTime sys = System.now();
        escalationStatusPrototype.TUC_Status_Datetime__c = DateTime.newInstance(
            sys.year(),
            sys.month(),
            sys.day(),
            sys.hour(),
            sys.minute(),
            0
        );
        escalationStatusPrototype.TUC_VISN__c = providedVisn;
        escalationStatusPrototype.TUC_Is_Current_Status__c = true;
        escalationStatusPrototype.TUC_Queue_Type__c = queueType;
        escalationStatusPrototype.TUC_Pause_Reason__c = TEST_PAUSE_REASON;
        escalationStatusPrototype.TUC_Status_Type__c = 'Paused';
        Tele_EC_Escalation_Status__c mockRecord = ((Tele_EC_Escalation_Status__c) VATEST_SObjectFactory.createSObject(
            escalationStatusPrototype,
            true
        ));
        List<Tele_EC_Escalation_Status__c> recordList = new List<Tele_EC_Escalation_Status__c>{ mockRecord };

        TUC_TeleEcEscalationStatusRepo stubRepo = (TUC_TeleEcEscalationStatusRepo) new VATEST_StubBuilder(
                TUC_TeleEcEscalationStatusRepo.class
            )
            .mockingMethodCall('getEscalationStatusWithVisnAndQueueType')
            .withParameterTypes(String.class, String.class)
            .withParameterValues(providedVisn, queueType)
            .returning(recordList)
            .defineStub();
        TUC_EscalatePauseButtonController.memoizedEscalationRepo = stubRepo; // dependency injected a fake implementation of the repo.

        VATEST_UserBuilder builder = new VATEST_UserBuilder();
        User doctorUser = builder.withPermissionSet('TED_Medical_Provider_Group')
            .withUserProfile('VAVET Base Profile')
            .withStandardData()
            .build(false);

        System.runAs(doctorUser) {
            Test.startTest();
            Tele_EC_Escalation_Status__c statusRecord = TUC_EscalatePauseButtonController.getCurrentStatusRecord(
                providedVisn,
                queueType
            );
            String statusString = statusRecord.TUC_Status_Type__c;
            Assert.areEqual('Paused', statusString, 'Expected Paused but was ' + statusString);
            Test.stopTest();
        }
    }

    /**
     * @description - Tests the parse method, providing a bad json to the create function, testing for a negative result.
     */
    @isTest
    public static void unitTestDeserializeJSONParseNegative() {
        Boolean exceptionThrown = false;
        String testJSON = '{"Statu$\';"Close@"}}';
        VATEST_UserBuilder builder = new VATEST_UserBuilder();
        User doctorUser = builder.withPermissionSet('TED_Medical_Provider_Group')
            .withUserProfile('VAVET Base Profile')
            .withStandardData()
            .build(false);

        System.runAs(doctorUser) {
            Test.startTest();
            try {
                TUC_EscalatePauseButtonController.createTeleEcStatusRecord(testJSON);
            } catch (AuraHandledException e) {
                if (e.getMessage().contains('JSON is malformed')) {
                    exceptionThrown = true;
                }
            }
            Test.stopTest();
            Assert.isTrue(exceptionThrown, 'Aura exception occurred, expected result');
        }
    }
}