sfdx-source/main/default/objects/Tele_EC_Escalation_Status__c/Tele_EC_Escalation_Status__c.object-meta.xml
<CustomObject>
    <label>Tele-EC Escalation Status</label>
    <nameField>
        <displayFormat>tuces-{000000}</displayFormat>
        <label>Tele-EC Escalation Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tele-EC Escalation Statuses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Tele_EC_Escalation_Status__c/fields/TUC_Is_Current_Status__c.field-meta.xml
<CustomField>
    <fullName>TUC_Is_Current_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox for the current status.</description>
    <label>Is Current Status</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/Tele_EC_Escalation_Status__c/fields/TUC_Pause_Reason__c.field-meta.xml
<CustomField>
    <fullName>TUC_Pause_Reason__c</fullName>
    <description>This field is meant to help understand reasons the Tele-EC is placed on pause and realize any underlying trends.</description>
    <inlineHelpText>This field is meant to help understand reasons the Tele-EC is placed on pause and realize any underlying trends.</inlineHelpText>
    <label>Pause Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Provider unavailable- service at capacity</fullName>
            </value>
            <value>
                <fullName>Provider unavailable- on break</fullName>
            </value>
            <value>
                <fullName>Tele-EC closed (after hours)</fullName>
            </value>
            <value>
                <fullName>Technical issue (i.e, power outage, wifi)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/Tele_EC_Escalation_Status__c/fields/TUC_Queue_Type__c.field-meta.xml
<CustomField>
    <fullName>TUC_Queue_Type__c</fullName>
    <description>Used in TUC_CommonUtils apex class. Determines which type of queue the status record is being created for.</description>
    <label>Queue Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High Acuity</fullName>
            </value>
            <value>
                <fullName>Intermediate Acuity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/Tele_EC_Escalation_Status__c/fields/TUC_Status_Datetime__c.field-meta.xml
<CustomField>
    <fullName>TUC_Status_Datetime__c</fullName>
    <description>Used in tucCommonUtils apex class. Used to capture the status date/time</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Status Datetime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

sfdx-source/main/default/objects/Tele_EC_Escalation_Status__c/fields/TUC_Status_Type__c.field-meta.xml
<CustomField>
    <fullName>TUC_Status_Type__c</fullName>
    <description>Used in tucCommonUtils apex class. Determines if the status is paused or resumed</description>
    <label>Status Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Resumed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/Tele_EC_Escalation_Status__c/fields/TUC_VISN__c.field-meta.xml
<CustomField>
    <fullName>TUC_VISN__c</fullName>
    <description>Used in tucCommonUtils apex class. Used to capture the VISN</description>
    <encryptionScheme>None</encryptionScheme>
    <label>VISN</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TUC/TUC_TeleEcEscalationStatusRepoTest.cls
/**
 * @description Tests the TUC_TeleEcEscalationStatusRepo class
 * @author Booz Allen
 *
 * @see TUC_TeleEcEscalationStatusRepo for class being tested
 *
 */
@isTest
public with sharing class TUC_TeleEcEscalationStatusRepoTest {
    /**
     * @description Test fetching Tele EC Escalation object for positive result
     */
    @IsTest
    private static void unitTestgetEscalationStatusWithVisnAndQueueTypePositive() {
        VATEST_UserBuilder builder = new VATEST_UserBuilder();
        User doctorUser = builder.withPermissionSet('TED_Medical_Provider')
            .withUserProfile('VAVET Base Profile')
            .withStandardData()
            .build(true);

        System.runAs(doctorUser) {
            String providedVisn = '0';
            String queueType = 'High Acuity';
            Tele_EC_Escalation_Status__c escalationStatusPrototype = new Tele_EC_Escalation_Status__c();
            escalationStatusPrototype.TUC_Status_Datetime__c = System.now();
            escalationStatusPrototype.TUC_VISN__c = providedVisn;
            escalationStatusPrototype.TUC_Is_Current_Status__c = true;
            escalationStatusPrototype.TUC_Queue_Type__c = queueType;
            escalationStatusPrototype.TUC_Pause_Reason__c = 'Provider unavailable- service at capacity';
            escalationStatusPrototype.TUC_Status_Type__c = 'Paused';
            VATEST_SObjectFactory.createSObject(escalationStatusPrototype, true);

            TUC_TeleEcEscalationStatusRepo testRepo = new TUC_TeleEcEscalationStatusRepo();
            List<Tele_EC_Escalation_Status__c> results = testRepo.getEscalationStatusWithVisnAndQueueType(
                providedVisn,
                queueType
            );

            Assert.areEqual(
                results.size(),
                1,
                'Expected single record to be returned but ' + results.size() + ' were returned'
            );
        }
    }

    /**
     * @description Test fetching Tele EC Escalation object for negative result
     */
    @IsTest
    private static void unitTestgetEscalationStatusWithVisnAndQueueTypeNegative() {
        VATEST_UserBuilder builder = new VATEST_UserBuilder();
        User doctorUser = builder.withPermissionSet('TED_Medical_Provider')
            .withUserProfile('VAVET Base Profile')
            .withStandardData()
            .build(true);

        System.runAs(doctorUser) {
            TUC_TeleEcEscalationStatusRepo testRepo = new TUC_TeleEcEscalationStatusRepo();
            List<Tele_EC_Escalation_Status__c> results = testRepo.getEscalationStatusWithVisnAndQueueType(
                '1',
                'Intermediate Acuity'
            );

            Assert.areEqual(
                results.size(),
                0,
                'Expected no records to be returned but ' + results.size() + ' were returned'
            );
        }
    }
}