sfdx-source/main/default/objects/Tele_EC_Escalation_Status__c/Tele_EC_Escalation_Status__c.object-meta.xml
<CustomObject>
    <label>Tele-EC Escalation Status</label>
    <nameField>
        <displayFormat>tuces-{000000}</displayFormat>
        <label>Tele-EC Escalation Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tele-EC Escalation Statuses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Tele_EC_Escalation_Status__c/fields/TUC_Is_Current_Status__c.field-meta.xml
<CustomField>
    <fullName>TUC_Is_Current_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox for the current status.</description>
    <label>Is Current Status</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/Tele_EC_Escalation_Status__c/fields/TUC_Pause_Reason__c.field-meta.xml
<CustomField>
    <fullName>TUC_Pause_Reason__c</fullName>
    <description>This field is meant to help understand reasons the Tele-EC is placed on pause and realize any underlying trends.</description>
    <inlineHelpText>This field is meant to help understand reasons the Tele-EC is placed on pause and realize any underlying trends.</inlineHelpText>
    <label>Pause Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Provider unavailable- service at capacity</fullName>
            </value>
            <value>
                <fullName>Provider unavailable- on break</fullName>
            </value>
            <value>
                <fullName>Tele-EC closed (after hours)</fullName>
            </value>
            <value>
                <fullName>Technical issue (i.e, power outage, wifi)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/Tele_EC_Escalation_Status__c/fields/TUC_Queue_Type__c.field-meta.xml
<CustomField>
    <fullName>TUC_Queue_Type__c</fullName>
    <description>Used in TUC_CommonUtils apex class. Determines which type of queue the status record is being created for.</description>
    <label>Queue Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High Acuity</fullName>
            </value>
            <value>
                <fullName>Intermediate Acuity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/Tele_EC_Escalation_Status__c/fields/TUC_Status_Datetime__c.field-meta.xml
<CustomField>
    <fullName>TUC_Status_Datetime__c</fullName>
    <description>Used in tucCommonUtils apex class. Used to capture the status date/time</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Status Datetime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

sfdx-source/main/default/objects/Tele_EC_Escalation_Status__c/fields/TUC_Status_Type__c.field-meta.xml
<CustomField>
    <fullName>TUC_Status_Type__c</fullName>
    <description>Used in tucCommonUtils apex class. Determines if the status is paused or resumed</description>
    <label>Status Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Resumed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/Tele_EC_Escalation_Status__c/fields/TUC_VISN__c.field-meta.xml
<CustomField>
    <fullName>TUC_VISN__c</fullName>
    <description>Used in tucCommonUtils apex class. Used to capture the VISN</description>
    <encryptionScheme>None</encryptionScheme>
    <label>VISN</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TUC/TUC_TeleEcEscalationStatusRepo.cls
/**
 * @author Booz Allen
 * @description This repository is for the Tele_EC_Escalation_Status__c object database operations
 */
public with sharing class TUC_TeleEcEscalationStatusRepo extends VTC_BaseRepo {
    /**
     * @description Constructor method for the E911 Repo
     */
    public TUC_TeleEcEscalationStatusRepo() {
        super(Tele_EC_Escalation_Status__c.sObjectType);
    }

    /**
     * @description Retrieves a list of Tele Ec Escalation Statuses with a specified query
     * @param providedVISN - the visn being queried
     * @param queueType - the type of queue being queried
     * @return  `List<Tele_EC_Escalation_Status__c>` - list of Escalation Statuses
     */
    public List<Tele_EC_Escalation_Status__c> getEscalationStatusWithVisnAndQueueType(
        String providedVISN,
        String queueType
    ) {
        String selectClause = 'Select Id,TUC_Status_Type__c,TUC_Status_Datetime__c,TUC_VISN__c,TUC_Is_Current_Status__c,TUC_Queue_Type__c,TUC_Pause_Reason__c';
        String fromClause = 'From Tele_EC_Escalation_Status__c';
        String whereClause =
            'Where TUC_Is_Current_Status__c = True AND TUC_VISN__c = \'' +
            providedVISN +
            '\' AND TUC_Queue_Type__c = \'' +
            queueType +
            '\'';
        String queryString = selectClause + ' ' + fromClause + ' ' + whereClause;
        return this.fetch(
            queryString,
            new Map<String, Object>{ 'providedVISN' => providedVISN, 'queueType' => queueType }
        );
    }
}