force-app/main/default/objects/VCC_Recent_View__c/VCC_Recent_View__c.object-meta.xml
<CustomObject>
    <label>VCC Recent View</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>VCC Recent View Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VCC Recent View</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VCC_Recent_View__c/fields/VCC_Account__c.field-meta.xml
<CustomField>
    <fullName>VCC_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VCC Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>VCC Recent View</relationshipLabel>
    <relationshipName>VCC_Recent_View</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Recent_View__c/fields/VCC_Is_Acknowledged__c.field-meta.xml
<CustomField>
    <fullName>VCC_Is_Acknowledged__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VCC Is Acknowledged</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Recent_View__c/fields/VCC_Pharmacy_Verify_Addresses__c.field-meta.xml
<CustomField>
    <fullName>VCC_Pharmacy_Verify_Addresses__c</fullName>
    <description>Track Pharmacy user&apos;s selection during Verify Caller if they&apos;ve verified the Patients Mailing and Temporary Address.</description>
    <label>Pharmacy Verified Address?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Verified Address</fullName>
            </value>
            <value>
                <fullName>Updated Address</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/VCC_Recent_View__c/fields/VCC_Type_Facility_Access__c.field-meta.xml
<CustomField>
    <fullName>VCC_Type_Facility_Access__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that the recent view is of type Facility Access.</description>
    <label>VCC Type - Facility Access</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VCC_Recent_View__c/fields/VCC_Type_Flags__c.field-meta.xml
<CustomField>
    <fullName>VCC_Type_Flags__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates a flag that the recent view is of type Flags</description>
    <label>VCC Type - Flags</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VCC_Recent_View__c/fields/VCC_Type_In_Patient__c.field-meta.xml
<CustomField>
    <fullName>VCC_Type_In_Patient__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates the recent view is of type In Patient.</description>
    <label>VCC Type - In Patient</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Recent_View__c/fields/VCC_Type_Sensitive_Patient__c.field-meta.xml
<CustomField>
    <fullName>VCC_Type_Sensitive_Patient__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that the recent view is of type Sensitive Patient.</description>
    <label>VCC Type - Sensitive Patient</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Recent_View__c/fields/VCC_Type_Verify_Patient__c.field-meta.xml
<CustomField>
    <fullName>VCC_Type_Verify_Patient__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that the recent view is of type Verify Patient.</description>
    <label>VCC Type - Verify Patient</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Recent_View__c/fields/VCC_User__c.field-meta.xml
<CustomField>
    <fullName>VCC_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VCC User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>VCC_Recent_View</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/classes/VCC/VCC_RecentViewHelper.cls
/**
 * @author VAHC Liberty IT
 * @since 08/2023
 * @description class to create, retrive and acknowlege recent view records
 * @group
 */
public with sharing class VCC_RecentViewHelper {
    public static final string TYPE_FLAGS = 'Flags';
    public static final string TYPE_SENSITIVE_PATIENT = 'SensitivePatient';
    public static final string TYPE_VERIFY_PATIENT = 'VerifyPatient';
    public static final string TYPE_IN_PATIENT = 'InPatient';
    public static final string TYPE_FACILITY_ACCESS = 'FacilityAccess';

    /**
     * @description call to generate or get the latest recent view record for the current user.
     * @param recordId
     *
     * @return VCC_Recent_View__c
     */
    public static VCC_Recent_View__c getRecentView(string recordId) {
        VCC_Recent_View__c recentView;
        List<VCC_Recent_View__c> recentViewList = [
            SELECT
                Id,
                VCC_Account__c,
                VCC_User__c,
                VCC_Type_Facility_Access__c,
                VCC_Type_Flags__c,
                VCC_Type_In_Patient__c,
                VCC_Type_Sensitive_Patient__c,
                VCC_Type_Verify_Patient__c,
                VCC_Is_Acknowledged__c,
                VCC_Pharmacy_Verify_Addresses__c,
                CreatedDate,
                LastModifiedDate,
                UserRecordAccess.HasEditAccess
            FROM VCC_Recent_View__c
            WHERE VCC_User__c = :UserInfo.getUserId()
            WITH USER_MODE
            ORDER BY LastModifiedDate DESC
            LIMIT 1
        ];

        if (!recentViewList.isEmpty() && recentViewList[0].VCC_Account__c == recordId) {
            recentView = recentViewList[0];
        }

        if (recentView == null) {
            recentView = new VCC_Recent_View__c();
            recentView.VCC_User__c = UserInfo.getUserId();
            recentView.VCC_Account__c = recordId;
            recentView.VCC_Type_Facility_Access__c = false;
            recentView.VCC_Type_Flags__c = false;
            recentView.VCC_Type_In_Patient__c = false;
            recentView.VCC_Type_Sensitive_Patient__c = false;
            recentView.VCC_Type_Verify_Patient__c = false;
            recentView.VCC_Is_Acknowledged__c = false;

            if (Schema.sObjectType.VCC_Recent_View__c.isCreateable()) {
                Database.insert(recentView, AccessLevel.USER_MODE);
            }
        }

        return recentView;
    }

    /**
     * @description call to acknowledge a recent view type.
     * @param recordId
     * @param type
     *
     * @return Boolean
     */
    public static boolean acknowledge(string recordId, string vccType) {
        VCC_Recent_View__c recentView = getRecentView(recordId);

        if (vccType == TYPE_FLAGS)
            recentView.VCC_Type_Flags__c = true;
        if (vccType == TYPE_SENSITIVE_PATIENT)
            recentView.VCC_Type_Sensitive_Patient__c = true;
        if (vccType == TYPE_VERIFY_PATIENT)
            recentView.VCC_Type_In_Patient__c = true;
        if (vccType == TYPE_FACILITY_ACCESS)
            recentView.VCC_Type_Facility_Access__c = true;
        if (vccType == TYPE_IN_PATIENT)
            recentView.VCC_Type_In_Patient__c = true;

        recentView.VCC_Is_Acknowledged__c = (recentView.VCC_Type_Facility_Access__c &&
        recentView.VCC_Type_Flags__c &&
        recentView.VCC_Type_In_Patient__c &&
        recentView.VCC_Type_Sensitive_Patient__c &&
        recentView.VCC_Type_Verify_Patient__c);

        if (recentView.UserRecordAccess.HasEditAccess && Schema.sObjectType.VCC_Recent_View__c.isUpdateable()) {
            Database.SaveResult result = Database.update(recentView);
            return result.isSuccess();
        }

        return false;
    }

    /**
     * @description call to generate or get the latest recent view record for the current user for use in Flow.
     * @param recordId
     * @param type
     *
     * @return VCC_Recent_View__c
     */
    @InvocableMethod(Label='Get Recent View Record' Description='Get the recent view record for this account.')
    public static List<VCC_Recent_View__c> getRecentView(List<String> recordIds) {
        VCC_Recent_View__c recentView = VCC_RecentViewHelper.getRecentView(recordIds[0]);
        return new List<VCC_Recent_View__c>{ recentView };
    }
}