sfdx-source/main/default/objects/VCC_Log__c/VCC_Log__c.object-meta.xml
<CustomObject>
    <description>Records the request and responses when calling MPI.</description>
    <label>VCC Log</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VCC Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VCC_Log__c/fields/Correlation_Id__c.field-meta.xml
<CustomField>
    <fullName>Correlation_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Correlation Id</label>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Log__c/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Log Type</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCC_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VCC_Log__c/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Timestamp</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/VCC/VCC_LogManagerTest.cls
@IsTest
public with sharing class VCC_LogManagerTest {
    @TestSetup
    private static void setup() {
        VCC_Log__c log = new VCC_Log__c(
            Correlation_Id__c = 'ABC123',
            Timestamp__c = Datetime.now(),
            Name = 'Unit Test',
            Log_Type__c = 'INFO',
            Message__c = 'Unit Test log entry.',
            Username__c = UserInfo.getUserName()
        );
        insert log;
    }

    @IsTest
    public static void batch_Test() {
        Database.executeBatch(new VCC_LogManager());
    }

    @IsTest
    public static void execute_Test() {
        List<VCC_Log__c> logs = [SELECT Id FROM VCC_Log__c];
        new VCC_LogManager().deleteLogs(logs);
    }

    @IsTest
    public static void execute_Schedulable_Test() {
        Test.startTest();
        VCC_LogManager batchLogManager = new VCC_LogManager();
        String schedule = '0 0 23 * * ?';
        System.schedule('Test check', schedule, batchLogManager);
        Test.stopTest();
    }

    @IsTest
    public static void executeoverride_Schedulable_Test() {
        Test.startTest();
        VCC_LogManager logManager = new VCC_LogManager();
        logManager.execute(null, new List<VCC_Log__c>());
        Test.stopTest();
    }
}