sfdx-source/main/default/objects/VCC_Test_Configuration_Data__c/VCC_Test_Configuration_Data__c.object-meta.xml
<CustomObject>
    <description>Used by the &quot;Integration Test Utility&quot;. Data here is used as input parameters for test runs.</description>
    <label>Test Configuration Data</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Test Configuration Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Configuration Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Test_Configuration_Data__c/fields/VCC_Note_Title_IEN__c.field-meta.xml
<CustomField>
    <fullName>VCC_Note_Title_IEN__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Note Title IEN</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCC_Test_Configuration_Data__c/fields/VCC_Note_Title_IEN_For_Encounter__c.field-meta.xml
<CustomField>
    <fullName>VCC_Note_Title_IEN_For_Encounter__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Note Title IEN For Encounter</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Test_Configuration_Data__c/recordTypes/VCC_Vdif_Test_Patient.recordType-meta.xml
<RecordType>
    <fullName>VCC_Vdif_Test_Patient</fullName>
    <active>true</active>
    <label>VCC Vdif Test Patient</label>
</RecordType>

sfdx-source/main/default/objects/VCC_Test_Run__c/VCC_Test_Run__c.object-meta.xml
<CustomObject>
    <description>Used by the &quot;Integration Test Utility&quot;</description>
    <label>Test Run</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>Test Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Runs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VCC_Test_Run__c/fields/VCC_Category__c.field-meta.xml
<CustomField>
    <fullName>VCC_Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vdif</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/VCC_Test_Run__c/fields/VCC_Site_Code__c.field-meta.xml
<CustomField>
    <fullName>VCC_Site_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Site Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCC_Test_Run__c/fields/VCC_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>VCC_Sub_Category__c</fullName>
    <label>Sub-Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>VCC_Category__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Create encounter, note, and sign</fullName>
            </value>
            <value>
                <fullName>Create note, addendum, and sign</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VCC_Test_Run__c/fields/VCC_Test_Configuration_Data__c.field-meta.xml
<CustomField>
    <fullName>VCC_Test_Configuration_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Configuration Data</label>
    <referenceTo>VCC_Test_Configuration_Data__c</referenceTo>
    <relationshipLabel>Test Runs</relationshipLabel>
    <relationshipName>Test_Runs</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Test_Run__c/recordTypes/VCC_Vdif_Test_Run.recordType-meta.xml
<RecordType>
    <fullName>VCC_Vdif_Test_Run</fullName>
    <active>true</active>
    <label>VCC Vdif Test Run</label>
</RecordType>

sfdx-source/main/default/classes/VCC/VCC_TestRunDomain.cls
public with sharing class VCC_TestRunDomain {
    public void initializeTestRun(VCC_Test_Run__c testRun, VCC_Test_Configuration_Data__C testConfigurationData) {
        if (String.isBlank((String) testConfigurationData.RecordTypeId)) {
            return;
        }

        testRun.VCC_Test_Configuration_Data__c = testConfigurationData.Id;

        switch on VCC_Test_Configuration_Data__c.getSObjectType().getDescribe().getRecordTypeInfosById().get(testConfigurationData.RecordTypeId).getDeveloperName() {
            when 'VCC_Vdif_Test_Patient' {
                this.initializeVdifTestRun(testRun, testConfigurationData);
            }
        }
    }

    @TestVisible
    private void initializeVdifTestRun(VCC_Test_Run__c testRun, VCC_Test_Configuration_Data__C testConfigurationData) {
        testRun.VCC_Category__c = 'Vdif';
        testRun.VCC_Site_Code__c = testConfigurationData.VCC_Site_Code__c;
        testRun.RecordTypeId = VCC_Test_Run__c.getSObjectType().getDescribe().getRecordTypeInfosByDeveloperName().get('VCC_Vdif_Test_Run').getRecordTypeId();

        if (!String.isBlank(testConfigurationData.VCC_Note_Title_IEN__c) && !String.isBlank(testConfigurationData.VCC_Note_Title_IEN_For_Encounter__c)) {
            return;
        }

        if (!String.isBlank(testConfigurationData.VCC_Note_Title_IEN__c)) {
            testRun.VCC_Sub_Category__c = 'Create note, addendum, and sign';
        }

        if (!String.isBlank(testConfigurationData.VCC_Note_Title_IEN_For_Encounter__c)) {
            testRun.VCC_Sub_Category__c = 'Create encounter, note, and sign';
        }
    }
}