sfdx-source/main/default/objects/VCC_Test_Configuration_Data__c/VCC_Test_Configuration_Data__c.object-meta.xml
<CustomObject>
    <description>Used by the &quot;Integration Test Utility&quot;. Data here is used as input parameters for test runs.</description>
    <label>Test Configuration Data</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Test Configuration Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Configuration Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Test_Configuration_Data__c/fields/VCC_ICN__c.field-meta.xml
<CustomField>
    <fullName>VCC_ICN__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ICN</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Test_Configuration_Data__c/fields/VCC_Note_Title_IEN__c.field-meta.xml
<CustomField>
    <fullName>VCC_Note_Title_IEN__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Note Title IEN</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Test_Configuration_Data__c/fields/VCC_Org_Type__c.field-meta.xml
<CustomField>
    <fullName>VCC_Org_Type__c</fullName>
    <label>Org Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEV</fullName>
                <default>true</default>
                <label>DEV</label>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
            <value>
                <fullName>STAGING</fullName>
            </value>
            <value>
                <fullName>PRODUCTION</fullName>
            </value>
            <value>
                <fullName>SCRATCH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/VCC_Test_Configuration_Data__c/fields/VCC_Service__c.field-meta.xml
<CustomField>
    <fullName>VCC_Service__c</fullName>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PharmacyI</fullName>
                <label>Pharmacy I</label>
            </value>
            <value>
                <fullName>PharmacyII</fullName>
                <label>Pharmacy II</label>
            </value>
            <value>
                <fullName>TeleEC</fullName>
                <label>Tele-EC</label>
            </value>
            <value>
                <fullName>Admin</fullName>
                <label>Admin &amp; Scheduling</label>
            </value>
            <value>
                <fullName>CT</fullName>
                <label>Clinical Triage</label>
            </value>
            <value>
                <fullName>VCV</fullName>
                <label>Virtual Clinic Visit</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/VCC_Test_Configuration_Data__c/recordTypes/VCC_Vdif_Test_Patient.recordType-meta.xml
<RecordType>
    <fullName>VCC_Vdif_Test_Patient</fullName>
    <active>true</active>
    <label>VCC Vdif Test Patient</label>
</RecordType>

force-app/main/default/classes/VCC/VCC_TestConfigurationDataSelectorTest.cls
@isTest
public with sharing class VCC_TestConfigurationDataSelectorTest {
    @isTest
    public static void instantiationTest() {
        Test.startTest();
        VCC_TestConfigurationDataSelector testConfigurationDataSelector = new VCC_TestConfigurationDataSelector();
        Test.stopTest();

        System.assert(testConfigurationDataSelector != null, 'Did not instantiate as expected.');
    }

    @isTest
    public static void addSObjectFieldsTest() {
        VCC_TestConfigurationDataSelector testConfigurationDataSelector = new VCC_TestConfigurationDataSelector();

        System.assert(!testConfigurationDataSelector.getSObjectFieldList().contains(VCC_Test_Configuration_Data__c.SystemModstamp), 'Selector already contains the field to test.');

        Test.startTest();
        testConfigurationDataSelector.addSObjectFields(new List<SObjectField>{ VCC_Test_Configuration_Data__c.SystemModstamp });
        Test.stopTest();

        System.assert(testConfigurationDataSelector.getSObjectFieldList().contains(VCC_Test_Configuration_Data__c.SystemModstamp), 'Selector did not add SObject field correctly.');
    }

    @IsTest
    static void selectVdifTestPatientDataTest() {
        VCC_Test_Configuration_Data__c config = new VCC_Test_Configuration_Data__c(
            RecordTypeId = VCC_Test_Configuration_Data__c.getSObjectType().getDescribe().getRecordTypeInfosByDeveloperName().get('VCC_Vdif_Test_Patient').getRecordTypeId(),
            VCC_Service__c = 'Admin',
            VCC_Site_Code__c = '984',
            VCC_Org_Type__c = (new VCC_OrgSettingsSelector()).selectByOrgId(UserInfo.getOrganizationId()).vccType__c,
            VCC_Note_Title_IEN__c = 'test',
            VCC_ICN__c = 'test'
        );

        VCC_Test_Configuration_Data__c config2 = new VCC_Test_Configuration_Data__c(
            RecordTypeId = VCC_Test_Configuration_Data__c.getSObjectType().getDescribe().getRecordTypeInfosByDeveloperName().get('VCC_Vdif_Test_Patient').getRecordTypeId(),
            VCC_Service__c = 'PharmacyI',
            VCC_Site_Code__c = '984',
            VCC_Org_Type__c = (new VCC_OrgSettingsSelector()).selectByOrgId(UserInfo.getOrganizationId()).vccType__c,
            VCC_Note_Title_IEN__c = 'test',
            VCC_ICN__c = 'test'
        );

        VCC_Test_Configuration_Data__c config3 = new VCC_Test_Configuration_Data__c(
            RecordTypeId = VCC_Test_Configuration_Data__c.getSObjectType().getDescribe().getRecordTypeInfosByDeveloperName().get('VCC_Vdif_Test_Patient').getRecordTypeId(),
            VCC_Service__c = 'PharmacyI',
            VCC_Site_Code__c = '983',
            VCC_Org_Type__c = (new VCC_OrgSettingsSelector()).selectByOrgId(UserInfo.getOrganizationId()).vccType__c,
            VCC_Note_Title_IEN__c = 'test',
            VCC_ICN__c = 'test'
        );

        insert new List<VCC_Test_Configuration_Data__c>{ config, config2, config3 };

        Test.startTest();
        VCC_TestConfigurationDataSelector testConfigurationDataSelector = new VCC_TestConfigurationDataSelector();
        List<VCC_Test_Configuration_Data__c> testConfigDataList = testConfigurationDataSelector.selectVdifTestPatientData(new List<String>{ '984' });
        System.assert(testConfigDataList[0].Id == config.Id, 'Expected matching Id\'s');
        System.assert(testConfigDataList[1].Id == config2.Id, 'Expected matching Id\'s');
        System.assert(testConfigDataList.size() == 2, 'Expected list of size 2.');
        Test.stopTest();
    }

    @IsTest
    static void selectVdifTestPatientDataByServiceAndSiteTest() {
        VCC_Test_Configuration_Data__c config2 = new VCC_Test_Configuration_Data__c(
            RecordTypeId = VCC_Test_Configuration_Data__c.getSObjectType().getDescribe().getRecordTypeInfosByDeveloperName().get('VCC_Vdif_Test_Patient').getRecordTypeId(),
            VCC_Service__c = 'PharmacyI',
            VCC_Site_Code__c = '985',
            VCC_Org_Type__c = (new VCC_OrgSettingsSelector()).selectByOrgId(UserInfo.getOrganizationId()).vccType__c,
            VCC_Note_Title_IEN__c = 'test',
            VCC_ICN__c = 'test'
        );
        insert config2;

        Test.startTest();
        System.assert((new VCC_TestConfigurationDataSelector()).selectVdifTestPatientDataByServiceAndSite('985', 'PharmacyI')[0].Id == config2.Id, 'Expected Id\'s to match.');
        Test.stopTest();
    }
}