sfdx-source/main/default/objects/VCC_Test_Configuration_Data__c/VCC_Test_Configuration_Data__c.object-meta.xml
<CustomObject>
    <description>Used by the &quot;Integration Test Utility&quot;. Data here is used as input parameters for test runs.</description>
    <label>Test Configuration Data</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Test Configuration Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Configuration Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VCC_Test_Configuration_Data__c/fields/VCC_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>VCC_Account_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Account Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCC_Test_Configuration_Data__c/fields/VCC_Addendum_IEN__c.field-meta.xml
<CustomField>
    <fullName>VCC_Addendum_IEN__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Addendum IEN</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCC_Test_Configuration_Data__c/fields/VCC_Additional_Signer_IEN__c.field-meta.xml
<CustomField>
    <fullName>VCC_Additional_Signer_IEN__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Additional Signer IEN</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Test_Configuration_Data__c/fields/VCC_Diagnosis_Codes__c.field-meta.xml
<CustomField>
    <fullName>VCC_Diagnosis_Codes__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Diagnosis Codes</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Test_Configuration_Data__c/fields/VCC_ICN__c.field-meta.xml
<CustomField>
    <fullName>VCC_ICN__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ICN</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCC_Test_Configuration_Data__c/fields/VCC_Location_IEN__c.field-meta.xml
<CustomField>
    <fullName>VCC_Location_IEN__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Location IEN</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Test_Configuration_Data__c/fields/VCC_Note_Text__c.field-meta.xml
<CustomField>
    <fullName>VCC_Note_Text__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Note Text</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Test_Configuration_Data__c/fields/VCC_Note_Title_IEN__c.field-meta.xml
<CustomField>
    <fullName>VCC_Note_Title_IEN__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Note Title IEN</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCC_Test_Configuration_Data__c/fields/VCC_Note_Title_IEN_For_Encounter__c.field-meta.xml
<CustomField>
    <fullName>VCC_Note_Title_IEN_For_Encounter__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Note Title IEN For Encounter</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Test_Configuration_Data__c/fields/VCC_Org_Type__c.field-meta.xml
<CustomField>
    <fullName>VCC_Org_Type__c</fullName>
    <label>Org Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEV</fullName>
                <default>true</default>
                <label>DEV</label>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
            <value>
                <fullName>STAGING</fullName>
            </value>
            <value>
                <fullName>PRODUCTION</fullName>
            </value>
            <value>
                <fullName>SCRATCH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/VCC_Test_Configuration_Data__c/fields/VCC_Procedure_Codes__c.field-meta.xml
<CustomField>
    <fullName>VCC_Procedure_Codes__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Procedure Codes</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Test_Configuration_Data__c/fields/VCC_Service__c.field-meta.xml
<CustomField>
    <fullName>VCC_Service__c</fullName>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PharmacyI</fullName>
                <label>Pharmacy I</label>
            </value>
            <value>
                <fullName>PharmacyII</fullName>
                <label>Pharmacy II</label>
            </value>
            <value>
                <fullName>TeleEC</fullName>
                <label>Tele-EC</label>
            </value>
            <value>
                <fullName>Admin</fullName>
                <label>Admin &amp; Scheduling</label>
            </value>
            <value>
                <fullName>CT</fullName>
                <label>Clinical Triage</label>
            </value>
            <value>
                <fullName>VCV</fullName>
                <label>Virtual Clinic Visit</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VCC_Test_Configuration_Data__c/fields/VCC_Visit_Related_Tos__c.field-meta.xml
<CustomField>
    <fullName>VCC_Visit_Related_Tos__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Visit Related Tos</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCC_Test_Configuration_Data__c/fields/VCC_VISN__c.field-meta.xml
<CustomField>
    <fullName>VCC_VISN__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>VISN</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Test_Configuration_Data__c/recordTypes/VCC_Vdif_Test_Patient.recordType-meta.xml
<RecordType>
    <fullName>VCC_Vdif_Test_Patient</fullName>
    <active>true</active>
    <label>VCC Vdif Test Patient</label>
</RecordType>

sfdx-source/main/default/objects/VCC_VISN__c/VCC_VISN__c.object-meta.xml
<CustomObject>
    <description>Tracks the VISNs for the Service Onboarding Tracker App</description>
    <label>VISN</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>VISN Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VISNs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/VCC/VCC_TestConfigurationDataSelector.cls
public with sharing class VCC_TestConfigurationDataSelector extends fflib_SObjectSelector {
    private List<Schema.SObjectField> sObjectFields = new List<Schema.SObjectField>{
        VCC_Test_Configuration_Data__c.Id,
        VCC_Test_Configuration_Data__c.RecordTypeId,
        VCC_Test_Configuration_Data__c.VCC_Account_Id__c,
        VCC_Test_Configuration_Data__c.VCC_Addendum_IEN__c,
        VCC_Test_Configuration_Data__c.VCC_Additional_Signer_IEN__c,
        VCC_Test_Configuration_Data__c.VCC_Diagnosis_Codes__c,
        VCC_Test_Configuration_Data__c.VCC_ICN__c,
        VCC_Test_Configuration_Data__c.VCC_Location_IEN__c,
        VCC_Test_Configuration_Data__c.VCC_Note_Text__c,
        VCC_Test_Configuration_Data__c.VCC_Note_Title_IEN__c,
        VCC_Test_Configuration_Data__c.VCC_Note_Title_IEN_For_Encounter__c,
        VCC_Test_Configuration_Data__c.VCC_Org_Type__c,
        VCC_Test_Configuration_Data__c.VCC_Procedure_Codes__c,
        VCC_Test_Configuration_Data__c.VCC_Service__c,
        VCC_Test_Configuration_Data__c.VCC_Site_Code__c,
        VCC_Test_Configuration_Data__c.VCC_Visit_Related_Tos__c,
        VCC_Test_Configuration_Data__c.VCC_VISN__c
    };

    public Schema.SObjectType getSObjectType() {
        return VCC_Test_Configuration_Data__c.SObjectType;
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return this.sObjectFields;
    }

    public void addSObjectFields(List<Schema.SObjectField> sObjectFields) {
        if (sObjectFields != null && !sObjectFields.isEmpty()) {
            for (Schema.SObjectField field : sObjectFields) {
                if (!this.sObjectFields.contains(field)) {
                    this.sObjectFields.add(field);
                }
            }
        }
    }

    public List<VCC_Test_Configuration_Data__c> selectVdifTestPatientData(List<String> sites) {
        Id recordTypeId = VCC_Test_Configuration_Data__c.getSObjectType().getDescribe().getRecordTypeInfosByDeveloperName().get('VCC_Vdif_Test_Patient').getRecordTypeId();
        String orgType = (new VCC_OrgSettingsSelector()).selectByOrgId(UserInfo.getOrganizationId()).vccType__c;

        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('VCC_Site_Code__c IN :sites AND RecordTypeId = :recordTypeId AND VCC_Org_Type__c = :orgType');
        query.setOrdering('VCC_Service__c', fflib_QueryFactory.SortOrder.DESCENDING);

        return Database.query(query.toSOQL());
    }

    public List<VCC_Test_Configuration_Data__c> selectVdifTestPatientDataByServiceAndSite(String site, String service) {
        Id recordTypeId = VCC_Test_Configuration_Data__c.getSObjectType().getDescribe().getRecordTypeInfosByDeveloperName().get('VCC_Vdif_Test_Patient').getRecordTypeId();
        String orgType = (new VCC_OrgSettingsSelector()).selectByOrgId(UserInfo.getOrganizationId()).vccType__c;

        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('VCC_Site_Code__c = :site AND RecordTypeId =:recordTypeId AND VCC_Org_Type__c =:orgType AND VCC_Service__c = :service');

        return Database.query(query.toSOQL());
    }
}