sfdx-source/main/default/objects/VCC_Progress_Note__c/VCC_Progress_Note__c.object-meta.xml
<CustomObject>
    <description>Progress Notes</description>
    <label>Progress Note</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>Progress Note</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Chief_Complaint__c.field-meta.xml
<CustomField>
    <fullName>VCC_Chief_Complaint__c</fullName>
    <description>Primary reason for patient’s call.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Primary reason for patient’s call.</inlineHelpText>
    <label>Chief Complaint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>VCC_Date_of_Birth__c</fullName>
    <description>Patient&apos;s date of birth</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Patient&apos;s date of birth</inlineHelpText>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note__c/fields/VCC_Diastolic_Blood_Pressure__c.field-meta.xml
<CustomField>
    <fullName>VCC_Diastolic_Blood_Pressure__c</fullName>
    <description>Used for Vitals intake. Patient&apos;s diastolic blood pressure within 50 - 140 mmHg</description>
    <inlineHelpText>Patient&apos;s diastolic blood pressure within 50 - 140 mmHg</inlineHelpText>
    <label>Diastolic Blood Pressure</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Gender__c.field-meta.xml
<CustomField>
    <fullName>VCC_Gender__c</fullName>
    <description>Used for Vitals intake. Patient&apos;s birth sex.</description>
    <inlineHelpText>Patient&apos;s birth sex</inlineHelpText>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note__c/fields/VCC_Height__c.field-meta.xml
<CustomField>
    <fullName>VCC_Height__c</fullName>
    <description>Used for Vitals intake. Patient&apos;s height within 4&apos;0&quot; - 7&apos;4&quot; feet/inches</description>
    <inlineHelpText>Patient&apos;s height within 4&apos;0&quot; - 7&apos;4&quot; feet/inches</inlineHelpText>
    <label>Height</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>4&apos;0&quot;</fullName>
            </value>
            <value>
                <fullName>4&apos;1&quot;</fullName>
            </value>
            <value>
                <fullName>4&apos;2&quot;</fullName>
            </value>
            <value>
                <fullName>4&apos;3&quot;</fullName>
            </value>
            <value>
                <fullName>4&apos;4&quot;</fullName>
            </value>
            <value>
                <fullName>4&apos;5&quot;</fullName>
            </value>
            <value>
                <fullName>4&apos;6&quot;</fullName>
            </value>
            <value>
                <fullName>4&apos;7&quot;</fullName>
            </value>
            <value>
                <fullName>4&apos;8&quot;</fullName>
            </value>
            <value>
                <fullName>4&apos;9&quot;</fullName>
            </value>
            <value>
                <fullName>4&apos;10&quot;</fullName>
            </value>
            <value>
                <fullName>4&apos;11&quot;</fullName>
            </value>
            <value>
                <fullName>5&apos;0&quot;</fullName>
            </value>
            <value>
                <fullName>5&apos;1&quot;</fullName>
            </value>
            <value>
                <fullName>5&apos;2&quot;</fullName>
            </value>
            <value>
                <fullName>5&apos;3&quot;</fullName>
            </value>
            <value>
                <fullName>5&apos;4&quot;</fullName>
            </value>
            <value>
                <fullName>5&apos;5&quot;</fullName>
            </value>
            <value>
                <fullName>5&apos;6&quot;</fullName>
            </value>
            <value>
                <fullName>5&apos;7&quot;</fullName>
            </value>
            <value>
                <fullName>5&apos;8&quot;</fullName>
            </value>
            <value>
                <fullName>5&apos;9&quot;</fullName>
            </value>
            <value>
                <fullName>5&apos;10&quot;</fullName>
            </value>
            <value>
                <fullName>5&apos;11&quot;</fullName>
            </value>
            <value>
                <fullName>6&apos;0&quot;</fullName>
            </value>
            <value>
                <fullName>6&apos;1&quot;</fullName>
            </value>
            <value>
                <fullName>6&apos;2&quot;</fullName>
            </value>
            <value>
                <fullName>6&apos;3&quot;</fullName>
            </value>
            <value>
                <fullName>6&apos;4&quot;</fullName>
            </value>
            <value>
                <fullName>6&apos;5&quot;</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note__c/fields/VCC_Logistical_Recommendation_WHEN__c.field-meta.xml
<CustomField>
    <fullName>VCC_Logistical_Recommendation_WHEN__c</fullName>
    <description>Explain recommendation based on clinical or logistical factors.</description>
    <inlineHelpText>Explain recommendation based on clinical or logistical factors.</inlineHelpText>
    <label>Nurse&apos;s Recommendation / WHEN</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>911</fullName>
            </value>
            <value>
                <fullName>Now</fullName>
            </value>
            <value>
                <fullName>Within 8 Hours</fullName>
            </value>
            <value>
                <fullName>Within 24 Hours</fullName>
            </value>
            <value>
                <fullName>Within 3 Days</fullName>
            </value>
            <value>
                <fullName>Within 2 Weeks</fullName>
            </value>
            <value>
                <fullName>Selfcare</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Logistical_Recommendation_WHERE__c.field-meta.xml
<CustomField>
    <fullName>VCC_Logistical_Recommendation_WHERE__c</fullName>
    <description>Explain recommendation based on clinical or logistical factors.</description>
    <inlineHelpText>Explain recommendation based on clinical or logistical factors.</inlineHelpText>
    <label>Nurse&apos;s Recommendation / WHERE</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>911</fullName>
            </value>
            <value>
                <fullName>Appointment</fullName>
            </value>
            <value>
                <fullName>Clinic/VAMC</fullName>
            </value>
            <value>
                <fullName>Dentist</fullName>
            </value>
            <value>
                <fullName>ED Other</fullName>
            </value>
            <value>
                <fullName>ED VA</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Refused</fullName>
            </value>
            <value>
                <fullName>Tele-EC</fullName>
            </value>
            <value>
                <fullName>Telephone Visit</fullName>
            </value>
            <value>
                <fullName>Urgent Non-VA</fullName>
            </value>
            <value>
                <fullName>Urgent VA</fullName>
            </value>
            <value>
                <fullName>Virtual Video Visit</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note__c/fields/VCC_Pulse__c.field-meta.xml
<CustomField>
    <fullName>VCC_Pulse__c</fullName>
    <description>Used for Vitals intake. Patient&apos;s pulse within 40 - 220 bpm</description>
    <inlineHelpText>Patient&apos;s pulse within 40 - 220 bpm</inlineHelpText>
    <label>Pulse</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note__c/fields/VCC_Pulse_Oximetry__c.field-meta.xml
<CustomField>
    <fullName>VCC_Pulse_Oximetry__c</fullName>
    <description>Used for Vitals intake. Patient&apos;s O2 Saturation (Pulse Oximetry) within 70 - 100%</description>
    <inlineHelpText>Patient&apos;s O2 Saturation (Pulse Oximetry) within 70 - 100%</inlineHelpText>
    <label>Pulse Oximetry</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note__c/fields/VCC_Respiratory_Rate__c.field-meta.xml
<CustomField>
    <fullName>VCC_Respiratory_Rate__c</fullName>
    <description>Used for Vitals intake. Patient&apos;s respiratory rate within 10 - 80 bpm</description>
    <inlineHelpText>Patient&apos;s respiratory rate within 10 - 80 bpm</inlineHelpText>
    <label>Respiratory rate per min</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Serum_Glucose__c.field-meta.xml
<CustomField>
    <fullName>VCC_Serum_Glucose__c</fullName>
    <description>Used for Vitals intake. Patient&apos;s serum glucose level within 20 - 600 mg/dl</description>
    <inlineHelpText>You must enter a value between 20-600. Values outside this range should be treated as a medical emergency. If the home glucometer reads: &quot; HI&quot; or
        &quot;high&quot; enter 600 into the numeric field. If the home glucometer reads: &quot;low&quot; enter 20 into the numeric field.</inlineHelpText>
    <label>Serum Glucose</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Signed__c.field-meta.xml
<CustomField>
    <fullName>VCC_Signed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Progress Note has been electronically signed.</description>
    <inlineHelpText>Progress Note has been electronically signed.</inlineHelpText>
    <label>Signed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note__c/fields/VCC_System_RFI__c.field-meta.xml
<CustomField>
    <fullName>VCC_System_RFI__c</fullName>
    <description>System suggested follow up interval</description>
    <encryptionScheme>None</encryptionScheme>
    <label>System WHEN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_System_RFL__c.field-meta.xml
<CustomField>
    <fullName>VCC_System_RFL__c</fullName>
    <description>System suggested follow up location</description>
    <encryptionScheme>None</encryptionScheme>
    <label>System WHERE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Systolic_Blood_Pressure__c.field-meta.xml
<CustomField>
    <fullName>VCC_Systolic_Blood_Pressure__c</fullName>
    <description>Used for Vitals intake. Patient&apos;s systolic blood pressure within 70 - 250 mmHg</description>
    <inlineHelpText>Patient&apos;s systolic blood pressure within 70 - 250 mmHg</inlineHelpText>
    <label>Systolic Blood Pressure</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note__c/fields/VCC_Temperature__c.field-meta.xml
<CustomField>
    <fullName>VCC_Temperature__c</fullName>
    <description>Used for Vitals Intake. Patient&apos;s temperature within 95.0 and 105.7 F</description>
    <inlineHelpText>Patient&apos;s temperature within 95.0 and 105.7 F</inlineHelpText>
    <label>Temperature *F</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Triage_Complete__c.field-meta.xml
<CustomField>
    <fullName>VCC_Triage_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the TXCC process has been completed.</description>
    <inlineHelpText>Checked if the TXCC process has been completed.</inlineHelpText>
    <label>Triage Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note__c/fields/VCC_Triage_Note__c.field-meta.xml
<CustomField>
    <fullName>VCC_Triage_Note__c</fullName>
    <description>Textual triage note from TXCC disposition object</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Triage Note</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VCC_Progress_Note__c/fields/VCC_Weight__c.field-meta.xml
<CustomField>
    <fullName>VCC_Weight__c</fullName>
    <description>Used for Vitals intake. Patient&apos;s weight within 60 - 600 lbs</description>
    <inlineHelpText>Patient&apos;s weight within 60 - 600 lbs</inlineHelpText>
    <label>Weight (lbs)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/VCC/VCC_TriageController.cls
public with sharing class VCC_TriageController {
    @AuraEnabled
    public static List<VCC_Progress_Note__c> getVitals(Id recordId) {
        VCC_ProgressNoteSelector progressNoteSelector = new VCC_ProgressNoteSelector();
        progressNoteSelector.addSObjectFields(
            new List<Schema.SObjectField>{
                VCC_Progress_Note__c.VCC_Gender__c,
                VCC_Progress_Note__c.VCC_Date_of_Birth__c,
                VCC_Progress_Note__c.VCC_Height__c,
                VCC_Progress_Note__c.VCC_Weight__c,
                VCC_Progress_Note__c.VCC_Systolic_Blood_Pressure__c,
                VCC_Progress_Note__c.VCC_Diastolic_Blood_Pressure__c,
                VCC_Progress_Note__c.VCC_Temperature__c,
                VCC_Progress_Note__c.VCC_Serum_Glucose__c,
                VCC_Progress_Note__c.VCC_Respiratory_Rate__c,
                VCC_Progress_Note__c.VCC_Pulse_Oximetry__c,
                VCC_Progress_Note__c.VCC_Pulse__c,
                VCC_Progress_Note__c.VCC_Triage_Complete__c,
                VCC_Progress_Note__c.VCC_Triage_Note__c,
                VCC_Progress_Note__c.VCC_Chief_Complaint__c,
                VCC_Progress_Note__c.VCC_Logistical_Recommendation_WHEN__c,
                VCC_Progress_Note__c.VCC_Logistical_Recommendation_WHERE__c,
                VCC_Progress_Note__c.VCC_System_RFI__c,
                VCC_Progress_Note__c.VCC_System_RFL__c
            }
        );
        return progressNoteSelector.selectByIds(new Set<Id>{ recordId });
    }

    @AuraEnabled
    public static TriageStatus getTriageStatus(Id recordId) {
        return new TriageStatus(recordId);
    }

    @TestVisible
    private class TriageStatus {
        @AuraEnabled
        public Boolean isStartable = false;

        @AuraEnabled
        public String isNotStartableReason = 'VCC_TriageController.cls: Unhandled Exception';

        private VCC_Progress_Note__c getProgressNote(Id recordId) {
            VCC_ProgressNoteSelector progressNoteSelector = new VCC_ProgressNoteSelector();
            progressNoteSelector.addSObjectFields(
                new List<Schema.SObjectField>{
                    VCC_Progress_Note__c.VCC_Triage_Complete__c,
                    VCC_Progress_Note__c.CreatedById,
                    VCC_Progress_Note__c.VCC_Signed__c,
                    VCC_Progress_Note__c.VCC_Date_of_Birth__c
                }
            );
            List<VCC_Progress_Note__c> progressNoteList = progressNoteSelector.selectByIds(new Set<Id>{ recordId });
            return (progressNoteList.size() > 0) ? progressNoteList[0] : null;
        }

        private void doIsStartableConditions(VCC_Progress_Note__c progressNoteRecord) {
            if (progressNoteRecord.CreatedById != UserInfo.getUserId()) {
                this.isNotStartableReason = System.Label.VCC_TriageController_isNotStartableReason_must_be_creator;
                return;
            }
            if (progressNoteRecord.VCC_Triage_Complete__c == true) {
                this.isNotStartableReason = System.Label.VCC_TriageController_isNotStartableReason_triage_complete;
                return;
            }
            if (progressNoteRecord.VCC_Signed__c == true) {
                this.isNotStartableReason = System.Label.VCC_TriageController_isNotStartableReason_progress_note_signed;
                return;
            }
            if (String.isBlank(String.valueOf(progressNoteRecord.VCC_Date_of_Birth__c))) {
                this.isNotStartableReason = System.Label.VCC_TriageController_isNotStartableReason_no_dob;
                return;
            }
            this.isNotStartableReason = '';
            this.isStartable = true;
        }

        public TriageStatus(Id recordId) {
            try {
                VCC_Progress_Note__c progressNoteRecord = this.getProgressNote(recordId);
                this.doIsStartableConditions(progressNoteRecord);
            } catch (Exception e) {
                this.isNotStartableReason = 'VCC_TriageController.cls: ' + e.getMessage();
            }
        }
    }
}