sfdx-source/main/default/objects/VCC_Progress_Note__c/VCC_Progress_Note__c.object-meta.xml
<CustomObject>
    <description>Progress Notes</description>
    <label>Progress Note</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>Progress Note</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VCC_Progress_Note__c/fields/VCC_Caller_Name_Text__c.field-meta.xml
<CustomField>
    <fullName>VCC_Caller_Name_Text__c</fullName>
    <description>Caller Name is populated from the Phone Call/Case, if different from the Veteran.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Caller Name is populated from the Phone Call/Case, if different from the Veteran.</inlineHelpText>
    <label>Caller Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Caregiver_Name__c.field-meta.xml
<CustomField>
    <fullName>VCC_Caregiver_Name__c</fullName>
    <description>Name of caregiver speaking on behalf of the patient</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Name of caregiver speaking on behalf of the patient</inlineHelpText>
    <label>Caller/Recipient Name</label>
    <type>TextArea</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Relative_Type__c.field-meta.xml
<CustomField>
    <fullName>VCC_Relative_Type__c</fullName>
    <description>Relationship of Caller to Veteran. Populated from the Phone Call/Case via a Flow.</description>
    <inlineHelpText>Relationship of the Caller to the Veteran. This is populated from the Phone Call/Case, if captured.</inlineHelpText>
    <label>Caller/Recipient Relation to Patient</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Self</fullName>
            </value>
            <value>
                <fullName>Caregiver</fullName>
            </value>
            <value>
                <fullName>Power of Attorney</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Anonymous</fullName>
                <isActive>false</isActive>
                <label>Anonymous</label>
            </value>
            <value>
                <fullName>Aunt</fullName>
                <isActive>false</isActive>
                <label>Aunt</label>
            </value>
            <value>
                <fullName>Daughter</fullName>
                <isActive>false</isActive>
                <label>Daughter</label>
            </value>
            <value>
                <fullName>Father</fullName>
                <isActive>false</isActive>
                <label>Father</label>
            </value>
            <value>
                <fullName>Home Health</fullName>
                <isActive>false</isActive>
                <label>Home Health</label>
            </value>
            <value>
                <fullName>Mother</fullName>
                <isActive>false</isActive>
                <label>Mother</label>
            </value>
            <value>
                <fullName>Neighbor</fullName>
                <isActive>false</isActive>
                <label>Neighbor</label>
            </value>
            <value>
                <fullName>Sibling</fullName>
                <isActive>false</isActive>
                <label>Sibling</label>
            </value>
            <value>
                <fullName>Son</fullName>
                <isActive>false</isActive>
                <label>Son</label>
            </value>
            <value>
                <fullName>Spouse</fullName>
                <isActive>false</isActive>
                <label>Spouse</label>
            </value>
            <value>
                <fullName>Uncle</fullName>
                <isActive>false</isActive>
                <label>Uncle</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Signed__c.field-meta.xml
<CustomField>
    <fullName>VCC_Signed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Progress Note has been electronically signed.</description>
    <inlineHelpText>Progress Note has been electronically signed.</inlineHelpText>
    <label>Signed</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_T2T_Assessment_Completed__c.field-meta.xml
<CustomField>
    <fullName>VCC_T2T_Assessment_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description
    >Field that is used to track if a T2T Assessment has been completed for a given progress note, displaying this field in the record is a visual confirmation for the user,
        and the T2T flow checks this field to decide if another T2T Assessment can be launched.</description>
    <inlineHelpText>Indicates if a Test to Treat assessment has been completed for this patient.</inlineHelpText>
    <label>T2T Assessment Completed</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note_Detail__c/VCC_Progress_Note_Detail__c.object-meta.xml
<CustomObject>
    <description>Stores details from the progress note</description>
    <label>Progress Note Detail</label>
    <nameField>
        <displayFormat>PND-{00000}</displayFormat>
        <label>Progress Note Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Progress_Note_Detail__c/fields/VCC_Progress_Note__c.field-meta.xml
<CustomField>
    <fullName>VCC_Progress_Note__c</fullName>
    <description>This is the master-detail relationship to the parent Progress Note custom object which is a one to one relationship.</description>
    <label>Progress Note</label>
    <referenceTo>VCC_Progress_Note__c</referenceTo>
    <relationshipLabel>Progress Notes Detail</relationshipLabel>
    <relationshipName>Progress_Notes_Detail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note_Detail__c/fields/VCC_T2T_Data__c.field-meta.xml
<CustomField>
    <fullName>VCC_T2T_Data__c</fullName>
    <description>This field stores the data for the Test to Treat data when Medical Provider does an assessment.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>T2T Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/main/default/classes/VCC/VCC_InterviewsByRecordController.cls
@SuppressWarnings('PMD.ApexDoc, PMD.ApexCrudViolation')
public with sharing class VCC_InterviewsByRecordController {
    @InvocableMethod(label='Get T2T Interviews')
    public static List<String> retrieveInterviews(List<String> recordId) {
        String thisRecord = recordId[0];
        String concat = '%';
        thisRecord = concat + thisRecord + concat;
        List<String> isInterview = new List<String>();
        for (FlowInterview flows : [
            SELECT InterviewLabel
            FROM FlowInterview
            WHERE InterviewLabel LIKE :thisRecord
            WITH SECURITY_ENFORCED
            LIMIT 1
        ])
            isInterview.add(flows.InterviewLabel);

        if (isInterview == null || isInterview.isEmpty()) {
            return null;
        }

        return isInterview;
    }

    @AuraEnabled
    public static String getPausedId(String recordId) {
        String thisRecord = '%' + recordId + '%';
        List<FlowInterview> interviews = [
            SELECT Id
            FROM FlowInterview
            WHERE InterviewLabel LIKE :thisRecord
            WITH SECURITY_ENFORCED
            ORDER BY LastModifiedDate ASC NULLS LAST
        ];
        if (interviews == null || interviews.isEmpty()) {
            return null;
        }
        return interviews.get(0).Id;
    }

    @AuraEnabled
    public static Boolean removeInterview(Id rowId) {
        List<FlowInterview> interviews = [
            SELECT Id
            FROM FlowInterview
            WHERE Id = :rowId
            WITH SECURITY_ENFORCED
            ORDER BY LastModifiedDate ASC NULLS LAST
        ];
        if (interviews == null || interviews.isEmpty()) {
            return false;
        }
        delete interviews;
        return true;
    }

    @AuraEnabled
    public static void resetT2TData(String recordId) {
        List<VCC_Progress_Note_Detail__c> dNotes = [
            SELECT Id, Name, VCC_Progress_Note__c, VCC_T2T_Data__c
            FROM VCC_Progress_Note_Detail__c
            WHERE VCC_Progress_Note__c = :recordId
            WITH SECURITY_ENFORCED
            LIMIT 1
        ];

        if (!dNotes.isEmpty()) {
            VCC_Progress_Note_Detail__c dNote = dNotes[0];
            dNote.VCC_T2T_Data__c = null;
            update dNote;
        }

        List<VCC_Progress_Note__c> pNotes = [
            SELECT Id, Name, LastModifiedDate, VCC_Signed__c, VCC_Relative_Type__c, VCC_Caller_Name_Text__c, VCC_Caregiver_Name__c, VCC_T2T_Assessment_Completed__c
            FROM VCC_Progress_Note__c
            WHERE Id = :recordId
            WITH SECURITY_ENFORCED
            LIMIT 1
        ];

        if (!pNotes.isEmpty()) {
            VCC_Progress_Note__c pNote = pNotes[0];
            pNote.VCC_T2T_Assessment_Completed__c = false;
            update pNote;
        }
    }
    @AuraEnabled
    public static Boolean getFieldValue(Id recordId) {
        List<VCC_Progress_Note__c> record = [
            SELECT Id, VCC_T2T_Assessment_Completed__c
            FROM VCC_Progress_Note__c
            WHERE Id = :recordId
            WITH SECURITY_ENFORCED
            LIMIT 1
        ];
        return record[0].VCC_T2T_Assessment_Completed__c;
    }
}