sfdx-source/main/default/objects/VCC_Progress_Note__c/VCC_Progress_Note__c.object-meta.xml
<CustomObject>
    <description>Progress Notes</description>
    <label>Progress Note</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>Progress Note</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Case__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case__c</fullName>
    <description>Parent Case for Progress Note</description>
    <inlineHelpText>Case related to Progress Note on the patient record.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Progress Notes</relationshipLabel>
    <relationshipName>Progress_Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Patient_ICN__c.field-meta.xml
<CustomField>
    <fullName>VCC_Patient_ICN__c</fullName>
    <description>Patient integration control number (icn). Also known as MPI/MVI External Id</description>
    <formula>VCC_Case__r.Account.MVI_External_Id__pc</formula>
    <label>VCC Patient ICN</label>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/classes/VCC/VCC_ProgressNoteSelector.cls
public with sharing class VCC_ProgressNoteSelector extends fflib_SObjectSelector {
    private List<Schema.SObjectField> sObjectFields = new List<Schema.SObjectField>{
        VCC_Progress_Note__c.Id,
        VCC_Progress_Note__c.VCC_Patient_ICN__c,
        VCC_Progress_Note__c.RecordTypeId,
        VCC_Progress_Note__c.VCC_Case__c
    };

    public Schema.SObjectType getSObjectType() {
        return VCC_Progress_Note__c.SObjectType;
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return this.sObjectFields;
    }

    public void addSObjectFields(List<Schema.SObjectField> sObjectFields) {
        if (sObjectFields != null && !sObjectFields.isEmpty()) {
            for (Schema.SObjectField field : sObjectFields) {
                if (!this.sObjectFields.contains(field)) {
                    this.sObjectFields.add(field);
                }
            }
        }
    }

    public List<VCC_Progress_Note__c> selectByIds(Set<Id> ids) {
        return (List<VCC_Progress_Note__c>) selectSObjectsById(ids);
    }
}