sfdx-source/main/default/objects/VCC_Progress_Note__c/VCC_Progress_Note__c.object-meta.xml
<CustomObject>
    <description>Progress Notes</description>
    <label>Progress Note</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>Progress Note</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VCC_Progress_Note__c/fields/VCC_CS_Checked_FDA_Authorized_Test_Kit__c.field-meta.xml
<CustomField>
    <fullName>VCC_CS_Checked_FDA_Authorized_Test_Kit__c</fullName>
    <description
    >If patient had a home test done, the RN user needs to choose from the options whether patient used FDA or non FDA authorized test kit or if RN did not check.</description>
    <inlineHelpText>If patient had a home test done, please choose from these options.</inlineHelpText>
    <label>Checked for FDA Authorized Test Kit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FDA authorized test kit used</fullName>
            </value>
            <value>
                <fullName>Non-FDA authorized test kit used</fullName>
            </value>
            <value>
                <fullName>Did not check</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_CS_FDA_authorized_test_kit__c.field-meta.xml
<CustomField>
    <fullName>VCC_CS_FDA_authorized_test_kit__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox indicates if the test kit is FDA authorized.</description>
    <label>FDA authorized test kit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/VCC/VCC_TransferFDACheckToPicklistValues.cls
@SuppressWarnings('PMD.ApexDoc')
public with sharing class VCC_TransferFDACheckToPicklistValues implements Database.Batchable<sObject> {
    @SuppressWarnings('PMD.ApexDoc,PMD.ApexCRUDViolation,PMD.AvoidSoqlWithoutLimits')
    public Database.QueryLocator start(Database.BatchableContext batchableContext) {
        return Database.getQueryLocator([SELECT Id, VCC_CS_FDA_authorized_test_kit__c, VCC_CS_Checked_FDA_Authorized_Test_Kit__c FROM VCC_Progress_Note__c]);
    }

    @SuppressWarnings('PMD.ApexDoc')
    public void execute(Database.BatchableContext batchableContext, List<VCC_Progress_Note__c> scope) {
        List<VCC_Progress_Note__c> updateProgressNote = new List<VCC_Progress_Note__c>(); // not needed
        for (VCC_Progress_Note__c pn : scope) {
            Boolean isChecked = pn.VCC_CS_FDA_authorized_test_kit__c;

            if (!isChecked) {
                pn.VCC_CS_Checked_FDA_Authorized_Test_Kit__c = 'Non-FDA authorized test kit used'; // should be a custom label or at the very least a static final string
            } else {
                pn.VCC_CS_Checked_FDA_Authorized_Test_Kit__c = 'FDA authorized test kit used'; // should be a custom label or at the very least a static final string
            }
            updateProgressNote.add(pn); // not needed
        }
        update updateProgressNote; // could just perform an update on 'scope'
    }

    @SuppressWarnings('PMD.ApexDoc')
    public void finish(Database.BatchableContext batchableContext) {
        return;
    }
}