force-app/main/default/objects/Activity/fields/VCC_Case__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Case related to task</description>
    <inlineHelpText>Case related to task</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/VCC_Caller_Name__c.field-meta.xml
<CustomField>
    <fullName>VCC_Caller_Name__c</fullName>
    <description>The name of the caller if the the Caller Relation to Veteran is not &quot;Self&quot;. Populated via the Verify Caller process.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The name of the caller if the the Caller Relation to Veteran is not &quot;Self&quot;. Populated via the Verify Caller process.</inlineHelpText>
    <label>Caller Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/Case/fields/VCC_Caller_Relation__c.field-meta.xml
<CustomField>
    <fullName>VCC_Caller_Relation__c</fullName>
    <description>Identifies the relationship of the Caller to the Patient</description>
    <inlineHelpText>Identifies the relationship of the Caller to the Patient. Populated via the Verify Patient process.</inlineHelpText>
    <label>Caller/Recipient Relation to Patient</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Self</fullName>
            </value>
            <value>
                <fullName>Caregiver</fullName>
            </value>
            <value>
                <fullName>Power of Attorney</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Anonymous</fullName>
                <isActive>false</isActive>
                <label>Anonymous</label>
            </value>
            <value>
                <fullName>Aunt</fullName>
                <isActive>false</isActive>
                <label>Aunt</label>
            </value>
            <value>
                <fullName>Daughter</fullName>
                <isActive>false</isActive>
                <label>Daughter</label>
            </value>
            <value>
                <fullName>Father</fullName>
                <isActive>false</isActive>
                <label>Father</label>
            </value>
            <value>
                <fullName>Home Health</fullName>
                <isActive>false</isActive>
                <label>Home Health</label>
            </value>
            <value>
                <fullName>Internal Review Only</fullName>
                <isActive>false</isActive>
                <label>Internal Review Only</label>
            </value>
            <value>
                <fullName>Mother</fullName>
                <isActive>false</isActive>
                <label>Mother</label>
            </value>
            <value>
                <fullName>Neighbor</fullName>
                <isActive>false</isActive>
                <label>Neighbor</label>
            </value>
            <value>
                <fullName>Psychiatrist</fullName>
                <isActive>false</isActive>
                <label>Psychiatrist</label>
            </value>
            <value>
                <fullName>Relative</fullName>
                <isActive>false</isActive>
                <label>Relative</label>
            </value>
            <value>
                <fullName>Sibling</fullName>
                <isActive>false</isActive>
                <label>Sibling</label>
            </value>
            <value>
                <fullName>Son</fullName>
                <isActive>false</isActive>
                <label>Son</label>
            </value>
            <value>
                <fullName>Spouse</fullName>
                <isActive>false</isActive>
                <label>Spouse</label>
            </value>
            <value>
                <fullName>Uncle</fullName>
                <isActive>false</isActive>
                <label>Uncle</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/Case/fields/VCC_Case_Outcome_Multi__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case_Outcome_Multi__c</fullName>
    <description>Case outcome field used on the Administrative and Scheduling Case that allows MSAs to select multiple outcomes for why the case was created</description>
    <inlineHelpText>Action Completed for the Veteran</inlineHelpText>
    <label>Case Outcome</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processed Medication Refill</fullName>
            </value>
            <value>
                <fullName>Entered Progress Note</fullName>
            </value>
            <value>
                <fullName>Entered Unsigned Order</fullName>
            </value>
            <value>
                <fullName>Provided Medication Extension</fullName>
            </value>
            <value>
                <fullName>Provided Status of Rx</fullName>
            </value>
            <value>
                <fullName>Provided Medication Counseling</fullName>
            </value>
            <value>
                <fullName>Provided Requested Information</fullName>
            </value>
            <value>
                <fullName>Provided Bridge Supply</fullName>
            </value>
            <value>
                <fullName>Provider Care Coordination</fullName>
            </value>
            <value>
                <fullName>Adjudicated Retail Billing</fullName>
            </value>
            <value>
                <fullName>Processed Pending Order</fullName>
            </value>
            <value>
                <fullName>Processed Early Fill</fullName>
            </value>
            <value>
                <fullName>Notified Local Site</fullName>
            </value>
            <value>
                <fullName>Transferred to CCC Nurse</fullName>
            </value>
            <value>
                <fullName>Transferred to CCC Scheduling</fullName>
            </value>
            <value>
                <fullName>Transferred to Veterans Crisis Line</fullName>
            </value>
            <value>
                <fullName>Contacted Emergency Services</fullName>
            </value>
            <value>
                <fullName>Call Dropped - Could not Reconnect</fullName>
            </value>
            <value>
                <fullName>Caller Terminated</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Cannot Complete Scheduling Action</fullName>
            </value>
            <value>
                <fullName>Completed Scheduling Action</fullName>
            </value>
            <value>
                <fullName>Progress Note to PACT</fullName>
            </value>
            <value>
                <fullName>Refilled Medication</fullName>
            </value>
            <value>
                <fullName>Requested Medication Renewal</fullName>
            </value>
            <value>
                <fullName>Transferred Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/VCC_Case_Reason_Multi__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case_Reason_Multi__c</fullName>
    <description>Reason why patient is calling-Multiselect</description>
    <inlineHelpText>Reason why patient is calling</inlineHelpText>
    <label>Case Reason</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>VCC_Case_Sub_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Schedule Appointment</fullName>
            </value>
            <value>
                <fullName>Cancel Appointment</fullName>
            </value>
            <value>
                <fullName>Verify Appointment</fullName>
            </value>
            <value>
                <fullName>Request Call Back</fullName>
            </value>
            <value>
                <fullName>Benefits &amp; Enrollment</fullName>
            </value>
            <value>
                <fullName>Community Care/ Mission Act</fullName>
            </value>
            <value>
                <fullName>Consult Request</fullName>
            </value>
            <value>
                <fullName>Death Notification</fullName>
            </value>
            <value>
                <fullName>Home Health/Nursing Home</fullName>
            </value>
            <value>
                <fullName>Lab/ Imaging Result</fullName>
            </value>
            <value>
                <fullName>Medical Equipment Request</fullName>
            </value>
            <value>
                <fullName>Medication Refill/Renewal</fullName>
            </value>
            <value>
                <fullName>Outside Care Performed</fullName>
            </value>
            <value>
                <fullName>Paperwork Request</fullName>
            </value>
            <value>
                <fullName>Update Demographic</fullName>
            </value>
            <value>
                <fullName>Dropped Call</fullName>
            </value>
            <value>
                <fullName>Returned Call</fullName>
            </value>
            <value>
                <fullName>Medication Refill</fullName>
            </value>
            <value>
                <fullName>Medication Renewal</fullName>
            </value>
            <value>
                <fullName>Prescription Status</fullName>
            </value>
            <value>
                <fullName>Prescription Tracking</fullName>
            </value>
            <value>
                <fullName>Facility Information</fullName>
            </value>
            <value>
                <fullName>Community Care Information</fullName>
            </value>
            <value>
                <fullName>Urgent First Fill Issues</fullName>
            </value>
            <value>
                <fullName>Med List Reconciliation</fullName>
            </value>
            <value>
                <fullName>Mission Act Information</fullName>
            </value>
            <value>
                <fullName>Clinical Question(s)</fullName>
            </value>
            <value>
                <fullName>Medication Recall</fullName>
            </value>
            <value>
                <fullName>Side Effect/ADR</fullName>
            </value>
            <value>
                <fullName>Crisis Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/VCC_Case_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>VCC_Case_Sub_Type__c</fullName>
    <description>Categorize the Case for reporting purposes.</description>
    <inlineHelpText>Categorize the Case for reporting purposes.</inlineHelpText>
    <label>Case Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>VCC_Case_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrative</fullName>
            </value>
            <value>
                <fullName>Community Care</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Emergent</fullName>
            </value>
            <value>
                <fullName>Medication Status</fullName>
            </value>
            <value>
                <fullName>Non-Emergent</fullName>
            </value>
            <value>
                <fullName>Telephone Virtual Visit</fullName>
                <label>Phone</label>
            </value>
            <value>
                <fullName>Refill Medication</fullName>
            </value>
            <value>
                <fullName>Renew Medication</fullName>
            </value>
            <value>
                <fullName>Scheduling</fullName>
            </value>
            <value>
                <fullName>Triage</fullName>
            </value>
            <value>
                <fullName>Urgent</fullName>
            </value>
            <value>
                <fullName>Urgent First Fill</fullName>
            </value>
            <value>
                <fullName>Video Virtual Visit</fullName>
                <label>Video</label>
            </value>
            <value>
                <fullName>PHR VCV</fullName>
            </value>
            <value>
                <fullName>Administrative and Scheduling</fullName>
                <label>Scheduling and Administrative</label>
            </value>
            <value>
                <fullName>Pharmacy</fullName>
            </value>
            <value>
                <fullName>Pharmacy Quality Assurance Issue</fullName>
            </value>
            <value>
                <fullName>Medication Error</fullName>
                <isActive>false</isActive>
                <label>Medication Error</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/Case/fields/VCC_Progress_Note__c.field-meta.xml
<CustomField>
    <fullName>VCC_Progress_Note__c</fullName>
    <description>Check true if there are any Progress Notes, related to the case.</description>
    <formula>IF( VCC_Progress_Notes_Count__c &gt; 0, TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Check true if there are any Progress Notes, related to the case.</inlineHelpText>
    <label>Progress Note</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/VCC_Pharmacy.recordType-meta.xml
<RecordType>
    <fullName>VCC_Pharmacy</fullName>
    <active>true</active>
    <businessProcess>VCC Support Process</businessProcess>
    <description>--VA Health Connect medication and prescription cases</description>
    <label>Pharmacy Case</label>
</RecordType>

sfdx-source/main/default/objects/VCC_Progress_Note__c/VCC_Progress_Note__c.object-meta.xml
<CustomObject>
    <description>Progress Notes</description>
    <label>Progress Note</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>Progress Note</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_Progress_Note__c/fields/VCC_Caller_Name__c.field-meta.xml
<CustomField>
    <fullName>VCC_Caller_Name__c</fullName>
    <description>If caller is not veteran, name of caller, populated from case.</description>
    <formula>VCC_Case__r.VCC_Caller_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>If caller is not veteran, name of caller, populated from case.</inlineHelpText>
    <label>Caller Name</label>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/classes/VCC/VCC_MedsServiceTest.cls
/**
 * @description       : Test class for VCC_MedsService
 * @author            : Booz Allen Hamilton
 * @date              : 12/2024
 **/
@IsTest
private with sharing class VCC_MedsServiceTest {
    /**
     * @description creates test Pharm user
     */
    @TestSetup
    static void makeData() {
        new VATEST_UserBuilder()
            .withUserProfile('VAVET Base Profile')
            .withPermissionSets(new Set<String>{ 'VAHC_Standard_VCC_User', 'VCC_Pharmacy_I', 'HealthCloudFoundation' })
            .withStandardData()
            .build(true);
    }

    /**
     * @description gets test user generated in makedata
     * @return A test user
     */
    public static User getTestUser() {
        return [
            SELECT Id, Title
            FROM User
            WHERE Email LIKE 'Testuser@test.example.com%'
            LIMIT 1
        ];
    }

    /**
     * @description tests the constructor of MedRefillRequest positive
     */
    @IsTest
    private static void unitMedRefillRequestConstructPositive() {
        System.runAs(getTestUser()) {
            Test.startTest();
            VCC_MedsService.MedRefillRequest medRefillRequest = new VCC_MedsService.MedRefillRequest();
            Assert.isNotNull(medRefillRequest, 'Expected medRefillRequest class to be initialized.');
            Assert.isNull(medRefillRequest.facilityId, 'Expected facility id to not be initialized.');
            Assert.isNull(medRefillRequest.prescriptionId, 'Expected prescription id to not be initialized.');
            Assert.isNull(medRefillRequest.icn, 'Expected icn to not be initialized.');
            Assert.isNull(medRefillRequest.prescriptionName, 'Expected prescriptionName to not be initialized.');
            Test.stopTest();
        }
    }

    /**
     * @description tests the construction of MedRefillResponse positive
     */
    @IsTest
    private static void unitRefillMedicationsResponsePositive() {
        System.runAs(getTestUser()) {
            Test.startTest();
            VCC_MedsService.MedRefillResponse medRefillResponse = new VCC_MedsService.MedRefillResponse();
            Assert.isNotNull(medRefillResponse, 'Expected MedRefillResponse class to be initialized.');
            Assert.isFalse(medRefillResponse.allSuccessful, 'Expected allSuccessful value to be false but was not');
            Assert.isNull(medRefillResponse.caseObject, 'Expected caseObject to be null but was not');

            VCC_DivaClient.RefillMedicationsRS refillMedicationsRS = new VCC_DivaClient.RefillMedicationsRS();
            VCC_DivaClient.ResponseJSON responseJSON = new VCC_DivaClient.ResponseJSON();
            responseJSON.prescriptionId = 'fakeId';
            responseJSON.success = false;
            responseJSON.message = 'Force unit test failure.';
            refillMedicationsRS.responseJSON.add(responseJSON);
            medRefillResponse = new VCC_MedsService.MedRefillResponse(refillMedicationsRS, new Case());

            Assert.isNotNull(medRefillResponse.allSuccessful, 'Expected allSuccessful value to not be null');
            Assert.isNotNull(medRefillResponse.caseObject, 'Expected caseObject to not be null');
            Test.stopTest();
        }
    }

    /**
     * @description tests refilling medications by case positive
     */
    @IsTest
    private static void funcRefillMedicationsByCasePositive() {
        System.runAs(getTestUser()) {
            Account testAccount = (Account) VATEST_SObjectFactory.createSObject(
                new Account(
                    RecordTypeId = new VCR_AccountRepo().recordTypeConstant.fromDeveloperName('PersonAccount').Id
                ),
                true
            );
            Case testCase = (Case) VATEST_SObjectFactory.createSObject(
                new Case(
                    RecordTypeId = new VCR_CaseRepo().recordTypeConstant.fromDeveloperName('VCC_Pharmacy').Id,
                    Subject = 'VCC_MedsServiceTest',
                    AccountId = testAccount.Id,
                    VCC_Caller_Relation__c = 'Self',
                    VCC_Caller_Name__c = 'Unit Test'
                ),
                true
            );
            VCC_MedsService.MedRefillResponse medRefillResponse;

            Test.startTest();
            medRefillResponse = VCC_MedsService.refillMedications(
                testCase,
                new List<VCC_MedsService.MedRefillRequest>()
            );
            Test.stopTest();

            Assert.isTrue(medRefillResponse.allSuccessful, 'Expected allSuccessful to be true but was not');
            Assert.areEqual(
                testCase.Id,
                medRefillResponse.caseObject.Id,
                'Expected caseObject from med refill to be equal to the original case from this test'
            );
        }
    }

    /**
     * @description tests refilling medications by case to result in expcetion when case is not found, negative
     */
    @IsTest
    private static void untiRefillMedicationsByCaseNegative() {
        System.runAs(getTestUser()) {
            Test.startTest();
            try {
                VCC_MedsService.refillMedications(new Case(), new List<VCC_MedsService.MedRefillRequest>());
            } catch (VCC_MedsService.VCC_MedsServiceException e) {
                Assert.areEqual('Case Id is required', e.getMessage(), 'Expected exception messages to match.');
            }
            Test.stopTest();
        }
    }

    /**
     * @description tests the refill medications by account positive
     */
    @IsTest
    private static void funcRfillMedicationsByAccountPositive() {
        System.runAs(getTestUser()) {
            StaticResourceCalloutMock staticResourceMock = new StaticResourceCalloutMock();
            staticResourceMock.setStaticResource('VCC_DivaClient_RefillMedicationsRS');
            staticResourceMock.setHeader('Content-Type', 'application/json');
            staticResourceMock.setStatusCode(200);
            Test.setMock(HttpCalloutMock.class, staticResourceMock);

            Account testAccount = (Account) VATEST_SObjectFactory.createSObject(
                new Account(
                    RecordTypeId = new VCR_AccountRepo().recordTypeConstant.fromDeveloperName('PersonAccount').Id
                ),
                true
            );

            List<VCC_MedsService.MedRefillRequest> medRefillRequests = new List<VCC_MedsService.MedRefillRequest>();
            medRefillRequests.add(new VCC_MedsService.MedRefillRequest());
            VCC_MedsService.MedRefillResponse medRefillResponse;
            Test.startTest();
            medRefillResponse = VCC_MedsService.refillMedications(testAccount, medRefillRequests);
            Test.stopTest();

            Assert.isTrue(medRefillResponse.allSuccessful, 'Expected allSuccessful to be true but was not');
            Assert.areEqual(
                'Pharmacy',
                medRefillResponse.caseObject.VCC_Case_Sub_Type__c,
                'Expected caseObject from med refill to be of sub type Pharmacy but was not'
            );
            Assert.areEqual(
                'Processed Medication Refill',
                medRefillResponse.caseObject.VCC_Case_Outcome_Multi__c,
                'Expected caseObject from med refill to have Processed Medication Refill as case outcome but did not'
            );
            Assert.areEqual(
                'Medication Refill',
                medRefillResponse.caseObject.VCC_Case_Reason_Multi__c,
                'Expected caseObject from med refill to have Medication Refill as case reason but did not'
            );
        }
    }

    /**
     * @description tests the refill medications by account negative when account id is null
     */
    @IsTest
    private static void unitRefillMedicationsByAccountMissingIdNegative() {
        System.runAs(getTestUser()) {
            Test.startTest();
            try {
                VCC_MedsService.refillMedications(new Account(), new List<VCC_MedsService.MedRefillRequest>());
            } catch (VCC_MedsService.VCC_MedsServiceException e) {
                Assert.areEqual('Account Id is required', e.getMessage(), 'Expected exception messages to match.');
            }
            Test.stopTest();
        }
    }

    /**
     * @description tests the refill medications by account negative when account is not found
     */
    @IsTest
    private static void unitRefillMedicationsByAccountMissingAccountNegative() {
        System.runAs(getTestUser()) {
            Test.startTest();
            try {
                Id fakAccountId = VATEST_IdFactory.get(Account.sObjectType);
                VCC_MedsService.refillMedications(
                    new Account(id = fakAccountId),
                    new List<VCC_MedsService.MedRefillRequest>()
                );
            } catch (VCC_MedsService.VCC_MedsServiceException e) {
                Assert.areEqual('Account not found', e.getMessage(), 'Expected exception messages to match.');
            }
            Test.stopTest();
        }
    }

    /**
     * @description tests refill medications by progress note positive
     */
    @IsTest
    private static void funcRefillMedicationsByProgressNotePositive() {
        System.runAs(getTestUser()) {
            Account testAccount = (Account) VATEST_SObjectFactory.createSObject(
                new Account(
                    RecordTypeId = new VCR_AccountRepo().recordTypeConstant.fromDeveloperName('PersonAccount').Id
                ),
                true
            );
            Case testCase = (Case) VATEST_SObjectFactory.createSObject(
                new Case(
                    RecordTypeId = new VCR_CaseRepo().recordTypeConstant.fromDeveloperName('VCC_Pharmacy').Id,
                    Subject = 'VCC_MedsServiceTest',
                    AccountId = testAccount.Id,
                    VCC_Caller_Relation__c = 'Self',
                    VCC_Caller_Name__c = 'Unit Test'
                ),
                true
            );
            VCC_Progress_Note__c progressNote = (VCC_Progress_Note__c) VATEST_SObjectFactory.createSObject(
                new VCC_Progress_Note__c(
                    VCC_Case__c = testCase.Id,
                    VCC_Relative_Type__c = 'Self',
                    VCC_Caller_Name_Text__c = 'Test',
                    VCC_Case__r = testCase
                ),
                true
            );

            VCC_MedsService.MedRefillResponse medRefillResponse;

            Test.startTest();
            medRefillResponse = VCC_MedsService.refillMedications(
                progressNote,
                new List<VCC_MedsService.MedRefillRequest>()
            );
            Test.stopTest();

            Assert.isTrue(medRefillResponse.allSuccessful, 'Expected allSuccessful to be true but was not');
            Assert.areEqual(
                testCase.Id,
                medRefillResponse.caseObject.Id,
                'Expected caseObject from med refill to be equal to the original case from this test'
            );
        }
    }

    /**
     * @description tests refill medications when flag is passed as true, positive
     */
    @IsTest
    private static void untiRefillMedicationWithBooleanPassedPositive() {
        System.runAs(getTestUser()) {
            Test.startTest();
            VCC_MedsService.MedRefillResponse medRefillResponse = new VCC_MedsService.MedRefillResponse(true);
            Assert.isNotNull(medRefillResponse.caseObject, 'Expected med refill case object to not be null');
            Assert.isNotNull(medRefillResponse, 'Expected class to be initialized.');
            Assert.isTrue(medRefillResponse.allSuccessful, 'Expected med response to be all successfull but was not');
            Test.stopTest();
        }
    }

    /**
     * @description tests refill medications by progress note when id is null, negative
     */
    @IsTest
    private static void refillMedicationsByProgressNoteException1() {
        System.runAs(getTestUser()) {
            Test.startTest();
            try {
                VCC_MedsService.refillMedications(
                    new VCC_Progress_Note__c(),
                    new List<VCC_MedsService.MedRefillRequest>()
                );
            } catch (VCC_MedsService.VCC_MedsServiceException e) {
                Assert.areEqual(
                    'Progress Note Id is required',
                    e.getMessage(),
                    'Expected exception messages to match.'
                );
            }
            Test.stopTest();
        }
    }

    /**
     * @description tests refill medications by progress note when it doesnt exist, negative
     */
    @IsTest
    private static void refillMedicationsByProgressNoteException2() {
        System.runAs(getTestUser()) {
            Test.startTest();
            try {
                Id fakeProgressNoteId = VATEST_IdFactory.get(VCC_Progress_Note__c.sObjectType);
                VCC_MedsService.refillMedications(
                    new VCC_Progress_Note__c(id = fakeProgressNoteId),
                    new List<VCC_MedsService.MedRefillRequest>()
                );
            } catch (VCC_MedsService.VCC_MedsServiceException e) {
                Assert.areEqual('Progress Note not found', e.getMessage(), 'Expected exception messages to match.');
            }
            Test.stopTest();
        }
    }

    /**
     * @description tests the getPharmacyLog method when bad data is passed in expecting exception, negative
     */
    @isTest
    private static void unitGetPharmacyLogNegative() {
        System.runAs(getTestUser()) {
            VCC_DivaClient.bypassCallout = true;

            Test.startTest();
            VCC_DivaResponse phamacyLog = VCC_MedsService.getPharmacyLog(
                VCC_Enum.VCC_PharmacyLogType.ACTIVITY,
                new VCC_PharmacyLogRQ('123', '99')
            );
            VCC_MedsService.getPharmacyLog(VCC_Enum.VCC_PharmacyLogType.ERX, new VCC_PharmacyLogRQ('123', '99'));
            VCC_MedsService.getPharmacyLog(VCC_Enum.VCC_PharmacyLogType.ECME, new VCC_PharmacyLogRQ('123', '99'));
            VCC_MedsService.getPharmacyLog(VCC_Enum.VCC_PharmacyLogType.CMOP, new VCC_PharmacyLogRQ('123', '99'));
            VCC_MedsService.getPharmacyLog(VCC_Enum.VCC_PharmacyLogType.COPAY, new VCC_PharmacyLogRQ('123', '99'));
            VCC_MedsService.getPharmacyLog(VCC_Enum.VCC_PharmacyLogType.LABEL, new VCC_PharmacyLogRQ('123', '99'));
            VCC_MedsService.getPharmacyLog(VCC_Enum.VCC_PharmacyLogType.REFILL, new VCC_PharmacyLogRQ('123', '99'));
            VCC_MedsService.getPharmacyLog(VCC_Enum.VCC_PharmacyLogType.PARTIAL, new VCC_PharmacyLogRQ('123', '99'));
            VCC_MedsService.getPharmacyLog(VCC_Enum.VCC_PharmacyLogType.CMOPLOTLOG, new VCC_PharmacyLogRQ('123', '99'));

            Assert.isNull(phamacyLog, 'expected bypass flag to make service return null');

            try {
                VCC_MedsService.getPharmacyLog(null, new VCC_PharmacyLogRQ('123', '99'));
            } catch (Exception ex) {
                Assert.areEqual(
                    'VCC_MedsService.VCC_MedsServiceException',
                    ex.getTypeName(),
                    'Expected meds service exception to be thrown'
                );
            }

            Test.stopTest();
        }
    }
}