sfdx-source/main/default/objects/OperatingHours/fields/VCC_Operating_Hours_Type__c.field-meta.xml
<CustomField>
    <fullName>VCC_Operating_Hours_Type__c</fullName>
    <description>Contains values to help delineate which type of offices and teams use this Operating Hours record entry.</description>
    <label>Operating Hours Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>VCC_VAHC_Application_Team_Name</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/OperatingHours/fields/VCC_VISN__c.field-meta.xml
<CustomField>
    <fullName>VCC_VISN__c</fullName>
    <defaultValue>$User.Division</defaultValue>
    <description>Used in Validation rules to validate the user&apos;s division against the operating hours they are entering</description>
    <label>VISN</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VISN 1</fullName>
            </value>
            <value>
                <fullName>VISN 2</fullName>
            </value>
            <value>
                <fullName>VISN 4</fullName>
            </value>
            <value>
                <fullName>VISN 5</fullName>
            </value>
            <value>
                <fullName>VISN 6</fullName>
            </value>
            <value>
                <fullName>VISN 7</fullName>
            </value>
            <value>
                <fullName>VISN 8</fullName>
            </value>
            <value>
                <fullName>VISN 9</fullName>
            </value>
            <value>
                <fullName>VISN 10</fullName>
            </value>
            <value>
                <fullName>VISN 12</fullName>
            </value>
            <value>
                <fullName>VISN 15</fullName>
            </value>
            <value>
                <fullName>VISN 16</fullName>
            </value>
            <value>
                <fullName>VISN 17</fullName>
            </value>
            <value>
                <fullName>VISN 19</fullName>
            </value>
            <value>
                <fullName>VISN 20</fullName>
            </value>
            <value>
                <fullName>VISN 21</fullName>
            </value>
            <value>
                <fullName>VISN 22</fullName>
            </value>
            <value>
                <fullName>VISN 23</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/VCC_VISN__c/VCC_VISN__c.object-meta.xml
<CustomObject>
    <description>Tracks the VISNs for the Service Onboarding Tracker App</description>
    <label>VISN</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>VISN Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VISNs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/VCC_VAHC_Application_Team_Name.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CRM</fullName>
    </customValue>
    <customValue>
        <fullName>Provider Connect</fullName>
    </customValue>
    <customValue>
        <fullName>Tele-EC</fullName>
    </customValue>
    <description>Global picklist that represents the different applications for VAHC by team name</description>
    <masterLabel>VAHC Application Team Name</masterLabel>
</GlobalValueSet>

sfdx-source/main/default/classes/VCR/VCR_OperatingHoursRepo.cls
/**
 * @author Booz Allen Hamilton
 * @since 5/14/24
 * @description Repository for all CRUD operations for the OperatingHours object
 *
 * @see VCC_OperatingHoursHolidayService
 */
public inherited sharing class VCR_OperatingHoursRepo extends VTC_BaseRepo {
    /**
     * @description Create an instance of a Repository for handling CRUD calls for OperatingHours object
     */
    public VCR_OperatingHoursRepo() {
        super(OperatingHours.SObjectType);
        this.defaultSelectFields.addAll(new Set<String>{ 'VCC_VISN__c', 'TimeZone', 'Name' });
    }

    /**
     * @description Fetch all OperatingHours records along with the relevant Timeslots for the given Provider VISN
     *
     * @param providerVisn String representing the Provider VISN to retrieve Operating Hours

     * @return
     */
    public List<OperatingHours> fetchOperatingHoursWithTimeSlots(String providerVisn) {
        String queryString = this.calculateSelectClause(this.defaultSelectFields);
        queryString += ', (SELECT Id, DayOfWeek, StartTime, EndTime, VCC_VISN__c, TUC_Schedule_Settings__c, Type FROM TimeSlots WHERE VCC_VISN__c=:timeSlotProviderVisn)';
        queryString += ' ' + this.calculateFromClause();
        queryString += ' WHERE VCC_VISN__c=:providerVisn';
        queryString += ' ORDER BY VCC_VISN__c';
        return (List<OperatingHours>) this.fetch(
            queryString,
            new Map<String, Object>{ 'timeSlotProviderVisn' => providerVisn, 'providerVisn' => providerVisn }
        );
    }

    /**
     * @description Fetch all OperatingHours records along with the relevant Timeslots for the given Provider VISN List
     *
     * @param providerVisnList List<String> A list of Strings representing the Provider VISNs to retrieve Operating Hours
     * @param opHourType String that corresponds to VCC_Operating_Hours_Type__c, indicating which subset of Operating Hours to retrieve
     * @return List<OperatingHours> all Operating Hours that are applicable to the provided list of VISNs
     */
    public List<OperatingHours> fetchMultipleOperatingHoursWithTimeSlotsByType(
        List<String> providerVisnList,
        String opHourType
    ) {
        if (providerVisnList == null || providerVisnList.isEmpty()) {
            return new List<OperatingHours>();
        }

        String queryString = this.calculateSelectClause(this.defaultSelectFields);
        queryString += ', (SELECT Id, DayOfWeek, StartTime, EndTime, VCC_VISN__c, TUC_Schedule_Settings__c, Type FROM TimeSlots WHERE VCC_VISN__c IN: timeSlotProviderVisns)';
        queryString += ' ' + this.calculateFromClause();
        queryString += ' WHERE VCC_VISN__c IN: providerVisns AND VCC_Operating_Hours_Type__c =: opHourType';
        queryString += ' ORDER BY VCC_VISN__c';
        return (List<OperatingHours>) this.fetch(
            queryString,
            new Map<String, Object>{
                'timeSlotProviderVisns' => providerVisnList,
                'providerVisns' => providerVisnList,
                'opHourType' => opHourType
            }
        );
    }
}