force-app/main/default/objects/VCC_e911_Metrics__c/VCC_e911_Metrics__c.object-meta.xml
<CustomObject>
    <description>A place to store data related to e911 functionality that can be used to supply metrics data</description>
    <label>e911 Metrics</label>
    <nameField>
        <displayFormat>e-{0000}</displayFormat>
        <label>e911 Metrics Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>e911 Metrics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/main/default/objects/VCC_e911_Metrics__c/fields/VCC_Patient_Account__c.field-meta.xml
<CustomField>
    <fullName>VCC_Patient_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>e911 Patient Account lookup to Contact</description>
    <label>Patient Account</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>e911 Metrics</relationshipLabel>
    <relationshipName>e911_Metrics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VCR/Tests/VCR_E911MetricsRepoTest.cls
/**
 * @description Tests the VCR_E911MetricsRepo class
 * @author Booz Allen
 *
 * @see VCR_E911MetricsRepo for class being tested
 *
 * NOTE: Suppressing warning for PMD.ApexUnitTestClassShouldHaveRunAs as there is no need to use System.RunAs for the
 *  Repository functional tests.
 */
@SuppressWarnings('PMD.ApexUnitTestClassShouldHaveRunAs')
@isTest
public class VCR_E911MetricsRepoTest {
    /**
     * @description Test to ensure init of repo is not null
     */
    @IsTest
    private static void funcInitTestPositive() {
        Test.startTest();
        VCR_E911MetricsRepo metricRepo = new VCR_E911MetricsRepo();
        Test.stopTest();

        Assert.isTrue(metricRepo != null, 'Expected repo to be initialized but was not.');
    }

    /**
     * @description Test fetching E911 Metric Record with correspondiong contact id for success path
     */
    @IsTest
    private static void unitTestGetE911MetricsByContactIdPositive() {
        Id contactId = ((Contact) VATEST_SObjectFactory.createSObject(new Contact(), true)).Id;
        VATEST_SObjectFactory.createSObject(new VCC_e911_Metrics__C(VCC_Patient_Account__c = contactId), true);
        Test.startTest();
        VCR_E911MetricsRepo metricsRepo = new VCR_E911MetricsRepo();
        List<VCC_e911_Metrics__c> results = metricsRepo.getE911MetricsByContactId(contactId);
        Test.stopTest();

        Assert.areEqual(
            results.size(),
            1,
            'Expected single record to be returned but ' + results.size() + ' were returned'
        );
    }

    /**
     * @description Test fetching E911 Metric Record when non exist that meet the criteria
     */
    @IsTest
    private static void unitTestGetE911MetricsByContactIdNegative() {
        Id fakeContactId = VATEST_IdFactory.get(Contact.sObjectType);
        Test.startTest();
        VCR_E911MetricsRepo metricsRepo = new VCR_E911MetricsRepo();
        List<VCC_e911_Metrics__c> results = metricsRepo.getE911MetricsByContactId(fakeContactId);
        Test.stopTest();

        Assert.areEqual(
            results.size(),
            0,
            'Expected no records to be returned but ' + results.size() + ' were returned'
        );
    }
}