force-app/main/default/objects/VCC_e911_Metrics__c/VCC_e911_Metrics__c.object-meta.xml
<CustomObject>
    <description>A place to store data related to e911 functionality that can be used to supply metrics data</description>
    <label>e911 Metrics</label>
    <nameField>
        <displayFormat>e-{0000}</displayFormat>
        <label>e911 Metrics Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>e911 Metrics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VCC_e911_Metrics__c/fields/VCC_Activated_From__c.field-meta.xml
<CustomField>
    <fullName>VCC_Activated_From__c</fullName>
    <description>The context in which the e911 was activated</description>
    <label>Activated From</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Progress Note</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/VCC_e911_Metrics__c/fields/VCC_Active__c.field-meta.xml
<CustomField>
    <fullName>VCC_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field will be needed to check if there is an active e911 call</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/main/default/objects/VCC_e911_Metrics__c/fields/VCC_Call_Back_Number__c.field-meta.xml
<CustomField>
    <fullName>VCC_Call_Back_Number__c</fullName>
    <description>User&apos;s current phone number so that the system can provide a temporary, local e911 phone number for a validated patient current location address</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Call-Back Number</label>
    <type>Phone</type>
</CustomField>

sfdx-source/main/default/objects/VCC_e911_Metrics__c/fields/VCC_City__c.field-meta.xml
<CustomField>
    <fullName>VCC_City__c</fullName>
    <description>Patient&apos;s current location (City)when e911 activated</description>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCC_e911_Metrics__c/fields/VCC_Country__c.field-meta.xml
<CustomField>
    <fullName>VCC_Country__c</fullName>
    <description>Patient current location(Country) when e911 activated</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HealthCloudGA__Countries</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/VCC_e911_Metrics__c/fields/VCC_Date_Activated__c.field-meta.xml
<CustomField>
    <fullName>VCC_Date_Activated__c</fullName>
    <description>Date/Time of e911 activation</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Date Activated</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/VCC_e911_Metrics__c/fields/VCC_e911_Case__c.field-meta.xml
<CustomField>
    <fullName>VCC_e911_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>e911 Case Lookup field for associate Case to an e911 record upon closure</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>e911 Metrics</relationshipLabel>
    <relationshipName>e911_Metrics</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/objects/VCC_e911_Metrics__c/fields/VCC_e911_Progress_Note__c.field-meta.xml
<CustomField>
    <fullName>VCC_e911_Progress_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>e911 Progress Note lookup field for associate  Progress Note to an e911 record upon closure</description>
    <label>Progress Note</label>
    <referenceTo>VCC_Progress_Note__c</referenceTo>
    <relationshipLabel>e911 Metrics</relationshipLabel>
    <relationshipName>e911_Metrics</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/objects/VCC_e911_Metrics__c/fields/VCC_Modality__c.field-meta.xml
<CustomField>
    <fullName>VCC_Modality__c</fullName>
    <description>Modality (phone or video) of the patient visit when e911 activated</description>
    <label>Modality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VCC_e911_Metrics__c/fields/VCC_Non_Address__c.field-meta.xml
<CustomField>
    <fullName>VCC_Non_Address__c</fullName>
    <description>Patient&apos;s non-address when e911 activated</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Non-Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_e911_Metrics__c/fields/VCC_Patient_Account__c.field-meta.xml
<CustomField>
    <fullName>VCC_Patient_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>e911 Patient Account lookup to Contact</description>
    <label>Patient Account</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>e911 Metrics</relationshipLabel>
    <relationshipName>e911_Metrics</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/main/default/objects/VCC_e911_Metrics__c/fields/VCC_Service__c.field-meta.xml
<CustomField>
    <fullName>VCC_Service__c</fullName>
    <description>Service (Tele-EC Triage, Tele EC MP Visit, CT Triage, VCV, Pharmacy) of user who activated e911</description>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tele-EC Triage</fullName>
            </value>
            <value>
                <fullName>Tele EC MP Visit</fullName>
            </value>
            <value>
                <fullName>CT Triage</fullName>
            </value>
            <value>
                <fullName>VCV</fullName>
            </value>
            <value>
                <fullName>Pharmacy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/default/objects/VCC_e911_Metrics__c/fields/VCC_State__c.field-meta.xml
<CustomField>
    <fullName>VCC_State__c</fullName>
    <description>Patient current location(State) when e911 activated</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VCC_e911_Metrics__c/fields/VCC_Street__c.field-meta.xml
<CustomField>
    <fullName>VCC_Street__c</fullName>
    <description>Patient&apos;s current location(Street) when e911 activated</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_e911_Metrics__c/fields/VCC_Temporary_e911_Number__c.field-meta.xml
<CustomField>
    <fullName>VCC_Temporary_e911_Number__c</fullName>
    <description>Temporary 911 phone number or ECRC phone number provided to user</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Temporary e911 Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/VCC_e911_Metrics__c/fields/VCC_User_Name_Activated__c.field-meta.xml
<CustomField>
    <fullName>VCC_User_Name_Activated__c</fullName>
    <description>Name of user who activated e911</description>
    <encryptionScheme>None</encryptionScheme>
    <label>User Name Activated</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_e911_Metrics__c/fields/VCC_User_VISN__c.field-meta.xml
<CustomField>
    <fullName>VCC_User_VISN__c</fullName>
    <description>VISN of user who activated e911</description>
    <encryptionScheme>None</encryptionScheme>
    <label>User VISN</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/default/objects/VCC_e911_Metrics__c/fields/VCC_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>VCC_Zip_Code__c</fullName>
    <description>Patient current location(Zip Code) when e911 activated</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VCR/VCR_E911MetricsRepo.cls
/**
 * @description This repository is for the E911 Metrics object database operations
 * @author Booz Allen
 * @date 04/2024
 */

public virtual inherited sharing class VCR_E911MetricsRepo extends VTC_BaseRepo {
    /**
     * @description Constructor function for VCR_E911MetricsRepo. Calls super constructor which sets this.sObjectType to 'VCC_e911_Metrics__c'
     *
     */
    public VCR_E911MetricsRepo() {
        super(VCC_e911_Metrics__c.sObjectType);
        this.defaultSelectFields.addAll(
            new Set<String>{
                'VCC_Street__c',
                'VCC_City__c',
                'VCC_State__c',
                'VCC_Country__c',
                'VCC_Zip_Code__c',
                'VCC_Call_Back_Number__c',
                'VCC_Temporary_e911_Number__c'
            }
        );
    }
    /**
     * @description Retrieves a list of E911 Metric records that share the same contact id
     * @param contactId - contact id
     * @return List<VCC_e911_Metrics__c> - list of E911 Metric records that match the contact id
     */
    public List<VCC_e911_Metrics__c> getE911MetricsByContactId(String contactId) {
        String selectClause = 'SELECT VCC_Street__c,VCC_City__c,VCC_State__c,VCC_Country__c,VCC_Zip_Code__c,VCC_Non_Address__c,VCC_Date_Activated__c,VCC_User_Name_Activated__c,VCC_User_VISN__c,VCC_Service__c,VCC_Temporary_e911_Number__c,VCC_Modality__c,VCC_e911_Case__c,VCC_Call_Back_Number__c,VCC_e911_Progress_Note__c,VCC_Patient_Account__c,VCC_Activated_From__c,VCC_Active__c ';
        String fromClause = 'FROM VCC_e911_Metrics__c ';
        String whereClause = 'WHERE VCC_Date_Activated__c = null AND VCC_Patient_Account__c = \'' + contactId + '\'';
        String limitClause = ' LIMIT 1';
        String query = selectClause + fromClause + whereClause + limitClause;
        return this.fetch(query);
    }
}